<div class="slide-content" id="khai-thue-hai-quan">
			<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_native_toolbox"></div>
        <div class="item-page">

            <p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: justify; line-height: 27pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><b><span style="font-size:18.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#333333">Khai thuế hải quan<o:p></o:p></span></b></p>

<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: justify; line-height: 27pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><b><span style="font-size:18.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#333333">&nbsp;</span></b><span style="font-size: 10pt; line-height: 150%; font-family: Wingdings;">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><span style="font-size: 10pt; line-height: 150%; font-family: Arial, sans-serif;">Đối với hàng hoá xuất – nhập khẩu,
khai báo hải quan là một trong những khâu quan trọng không thể tách rời của một
quá trình. Trong quá trình làm thủ tục hải quan, nhiều vấn đề phát sinh có thể
nằm ngoài dự kiến của doanh nghiệp, khi đó đòi hỏi phải có sự linh hoạt để giải
quyết các vấn đề một cách ưu việt nhất. Công ty CMG cung cấp cho các doanh
nghiệp một dịch vụ có chất lượng tốt nhất từ việc tư vấn đến việc thực hiện để
có thể đảm bảo thông quan một cách nhanh nhất.</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-bottom: 0.0001pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span><span style="font-size: 10pt; line-height: 150%; font-family: Wingdings;">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><span style="font-size: 10pt; line-height: 150%; font-family: Arial, sans-serif;">Các dịch vụ tư vấn hải quan của CMG:</span></p>

<p class="MsoNormal" style="margin: 0in 0in 0.0001pt 0.5in; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Làm bộ chứng
từ, khai báo hải quan (bao gồm: hàng tàu, hàng nguyên container, hàng lẻ, hàng
rời với tất cả các loại hình: kinh doanh, đầu tư, đầu tư nộp , tạm nhập - tái
xuất, gia công, sxxk, hàng mẫu, hàng phi mậu dịch, hàng kho ngoại quan…vv).<o:p></o:p></span></p>

<p class="MsoNormal" style="margin: 0in 0in 0.0001pt 0.5in; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Làm dịch vụ
hải quan đối với hàng Gia công (từ khâu lập hợp đồng gia công, lập danh mục máy
móc thiết bị nhập khẩu, lập danh mục nguyên phụ liệu nhập khẩu, lập bộ hồ sơ tờ
khai nhập khẩu, lập định mức, lập bộ hồ sơ tờ khai xuất khẩu, lập hồ sơ thanh
khoản hợp đồng gia công và thực hiện khai báo dữ liệu điện tử đến cơ quan hải quan).<o:p></o:p></span></p>

<p class="MsoNormal" style="margin: 0in 0in 0.0001pt 0.5in; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Làm thủ tục
xuất nhập khẩu trọn gói cho các doanh nghiệp sản xuất thuộc khu công nghiệp,
khu chế xuất.<o:p></o:p></span></p>

<p class="MsoNormal" style="margin: 0in 0in 0.0001pt 0.5in; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Làm thủ tục
thông quan đối với tất cả các loại hình hàng hoá xuất nhập khẩu: hàng kinh
doanh, hàng viện trợ, hàng dự án, hàng triển lãm, hàng quá cảnh, hàng tạm
nhập-tái xuất, hàng tạm xuất-tái nhập, và hàng phi mậu dịch.<o:p></o:p></span></p>

<p class="MsoNormal" style="margin: 0in 0in 0.0001pt 0.5in; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Tư vấn về
khai hải quan, tính thuế, áp mã, áp giá hải quan và các chính sách thuế khác có
liên quan.<o:p></o:p></span></p>

<p class="MsoNormal" style="margin: 0in 0in 0.0001pt 0.5in; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Tư vấn các
vấn đề liên quan về xuất nhập khẩu và thủ tục hải quan của các nước khác nơi có
hàng Việt Nam xuất khẩu đến.<o:p></o:p></span></p>

    
        </div>
    </div>

<script type="text/javascript">
    closeSidepage('#khai-thue-hai-quan');
   openSidepage('#khai-thue-hai-quan');
</script>