<?php
$url_order = 'ASC';
if ($order_by == 'tire_excess_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_excess_type_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_excess_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_excess')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_excess_vat')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> CHI PHÍ PHÁT SINH CODE <?php echo $code ?></h1></center>
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm chi phí</a>
</div>
    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Search">
        <input type="button" name="" id="search-submit" class="button-search" value="Search" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
       
    </div>
    <div class="tablenav top">

        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Select</option>
                
                <option value="delete">Delete</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Apply" onclick="action();">
        </div>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
            <option  value="18446744073709">All</option>
            <option value="15">15 items</option>
            <option value="20">20 items</option>
            <option value="50">50 items</option>
            <option selected="selected" value="100">100 items</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Apply" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                              
        </div>

        
      </div>

</div>

<table class="table_data">
<thead>
    <tr>
        <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_excess_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'tire_excess_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','code','<?php echo $url_order ?>')">Code <?php if ($order_by == 'code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_brand_name','<?php echo $url_order ?>')">Thương hiệu <?php if ($order_by == 'tire_brand_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_size_number','<?php echo $url_order ?>')">Size <?php if ($order_by == 'tire_size_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_excess_pattern','<?php echo $url_order ?>')">Mã gai <?php if ($order_by == 'tire_excess_pattern'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_excess_type_name','<?php echo $url_order ?>')">Loại chi phí <?php if ($order_by == 'tire_excess_type_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_excess_name','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'tire_excess_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_excess','<?php echo $url_order ?>')">0 VAT <?php if ($order_by == 'tire_excess'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_excess_vat','<?php echo $url_order ?>')">VAT <?php if ($order_by == 'tire_excess_vat'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_excess','<?php echo $url_order ?>')">Tổng cộng <?php if ($order_by == 'tire_excess'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        
        <th class="fix"></th>
    </tr>
    
   </thead>
   <tbody>
    <?php $tong=0; ?>
    <?php foreach ($tire_costs as $tire_excess) : ?>
    
        <?php $tong += $tire_excess->tire_excess+$tire_excess->tire_excess_vat; ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $tire_excess->tire_excess_id ?>" class="edit_tr">
            
            <td>
                <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $tire_excess->tire_excess_id ?>">
            </td>
            
            <td  class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="code_<?php echo $tire_excess->tire_excess_id; ?>"><?php echo $tire_excess->code; ?></td>
            <td class="fix" id="tire_excess_brand_<?php echo $tire_excess->tire_excess_id; ?>"><?php echo $tire_excess->tire_brand_name; ?></td>
            <td class="fix" id="tire_excess_size_<?php echo $tire_excess->tire_excess_id; ?>"><?php echo $tire_excess->tire_size_number; ?></td>
            <td class="fix" data="<?php echo $tire_excess->tire_pattern; ?>" id="tire_excess_pattern_<?php echo $tire_excess->tire_excess_id; ?>"><?php echo $tire_excess->tire_pattern_name; ?></td>
            <td class="fix" id="tire_excess_type_<?php echo $tire_excess->tire_excess_id; ?>"><?php echo $tire_excess->tire_excess_type_name; ?></td>
            <td class="fix" id="tire_excess_name_<?php echo $tire_excess->tire_excess_id; ?>"><?php echo $tire_excess->tire_excess_name; ?></td>
            <td class="fix" id="tire_excess_<?php echo $tire_excess->tire_excess_id; ?>"><?php echo $lib->formatMoney($tire_excess->tire_excess); ?></td>
            <td class="fix" id="tire_excess_vat_<?php echo $tire_excess->tire_excess_id; ?>"><?php echo $lib->formatMoney($tire_excess->tire_excess_vat); ?></td>
            <td class="fix" id="total_<?php echo $tire_excess->tire_excess_id; ?>"><?php echo $lib->formatMoney($tire_excess->tire_excess+$tire_excess->tire_excess_vat); ?></td>
            <td style="display:none" class="fix" data="<?php echo $tire_excess->customer ?>" id="customer_<?php echo $tire_excess->tire_excess_id; ?>"><?php echo isset($customer[$tire_excess->customer]['name'])?$customer[$tire_excess->customer]['name']:null; ?></td>
            <td>
                <button class="error del" data="<?php echo $tire_excess->tire_excess_id ?>" >Xóa</button>
                
               
            </td>
        </tr>


    <?php endforeach; ?>
    <tr style="text-align:center; font-weight: bold; color: red;">
        <td class="fix" colspan="10" >Tổng cộng</td>
        <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
        <td class="fix" ></td>
    </tr>
     
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('tiresale') ?>">&larr;</a></div>
<div style="display:none" id="lasted"></div>
<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Chi phí </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_tire" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            <td>Code</td>
                            <td>
                                <input style="width:80px" disabled class="number" type="text" id="code"  name="code" tabindex="1"  required="required" value="<?php echo $code ?>" >
                                
                            </td>
                            <td>Loại</td>
                            <td>
                                <select name="tire_excess_type" id="tire_excess_type" tabindex="2"  required="required">
                                    <?php foreach ($tire_excess_types as $tire_excess_type) { ?>
                                        <option value="<?php echo $tire_excess_type->tire_excess_type_id ?>"><?php echo $tire_excess_type->tire_excess_type_name ?></option>
                                    <?php } ?>
                                    
                                </select>
                                
                            </td>
                            <td>Nội dung</td>
                            <td>
                                <textarea id="tire_excess_name" id="tire_excess_name" tabindex="3"></textarea>
                                
                            </td>
                            
                        </tr>
                        <tr>
                            <td>Thương hiệu</td>
                            <td>
                                <select name="tire_excess_brand" id="tire_excess_brand" tabindex="4"  required="required">
                                    <?php foreach ($tire_brands as $tire_brand) { ?>
                                        <option value="<?php echo $tire_brand->tire_brand_id ?>"><?php echo $tire_brand->tire_brand_name ?></option>
                                    <?php } ?>
                                    
                                </select>
                                
                            </td>
                            <td>0 VAT</td>
                            <td>
                                <input style="width:80px" class="numbers" type="text" id="tire_excess"  name="tire_excess" tabindex="5"  >
                                
                            </td>
                            <td>VAT</td>
                            <td>
                                <input style="width:80px" class="numbers" type="text" id="tire_excess_vat"  name="tire_excess_vat" tabindex="6"  >
                                
                            </td>
                        </tr>
                        <tr>
                            
                            <td>Size</td>
                            <td>
                                <select name="tire_excess_size" id="tire_excess_size" tabindex="7"  required="required">
                                    <?php foreach ($tire_sizes as $tire_size) { ?>
                                        <option value="<?php echo $tire_size->tire_size_id ?>"><?php echo $tire_size->tire_size_number ?></option>
                                    <?php } ?>
                                    
                                </select>
                                
                            </td>
                            <td>
                                Mã gai
                            </td>
                            <td>
                                <input disabled style="width:80px" type="text" class="tire_pattern" id="tire_excess_pattern" name="tire_excess_pattern" required="required" value="<?php echo $tire_pattern_name ?>" data="<?php echo $tire_pattern ?>" tabindex="8"> 
                            </td>
                            <td>Khách hàng </td>
                            <td><input type="text"  id="customer" name="customer" tabindex="9"  autocomplete="off" placeholder="Nhập tên hoặc * để chọn" >
                                <ul id="customer_list_id"></ul>
                            </td>
                        </tr>
                                               
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td></td>
                            <td></td>
                            <td></td>

                            <td>
                                <input type="submit" name="submit" value="Submit" tabindex="10">
                                
                            </td>
                            <td>
                                <input type="reset" name="reset" value="Reset" tabindex="11">
                            </td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>


<script type="text/javascript">


  
$('.add-field').hide();  


$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);     
        
    }
    $('#customer_list_id').slideUp(200); 
});



    $('.edit_tr').click(function(e){
        if(e.target != '[object HTMLButtonElement]' && e.target != '[object HTMLSpanElement]' && !$('.checkbox').is(':focus')) { 
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            var code = $(this).find("#code_"+$(this).attr('id')).text();
            var tire_excess_type = $(this).find("#tire_excess_type_"+$(this).attr('id')).text();
            var tire_excess_name = $(this).find("#tire_excess_name_"+$(this).attr('id')).text();
            var tire_excess = $(this).find("#tire_excess_"+$(this).attr('id')).text();
            var tire_excess_vat = $(this).find("#tire_excess_vat_"+$(this).attr('id')).text();
            var tire_excess_brand = $(this).find("#tire_excess_brand_"+$(this).attr('id')).text();
            var tire_excess_size = $(this).find("#tire_excess_size_"+$(this).attr('id')).text();
            var customer_name = $(this).find("#customer_"+$(this).attr('id')).text();
            var customer = $(this).find("#customer_"+$(this).attr('id')).attr('data');
            var tire_pattern_name = $(this).find("#tire_excess_pattern_"+$(this).attr('id')).text();
            var tire_pattern = $(this).find("#tire_excess_pattern_"+$(this).attr('id')).attr('data');

            //alert(cost_code);
            $('#yes').val($(this).attr('id'));
            
            $('#code').val(code);
            $("#tire_excess_type option:contains(" + tire_excess_type + ")").attr('selected', 'selected');
            $('#tire_excess_name').val(tire_excess_name);
            $('#tire_excess').val(tire_excess);
            $('#tire_excess_vat').val(tire_excess_vat);
            $("#tire_excess_brand option:contains(" + tire_excess_brand + ")").attr('selected', 'selected');
            $("#tire_excess_size option:contains(" + tire_excess_size + ")").attr('selected', 'selected');

            $('#customer').val(customer_name);
            $('#customer').attr('data',customer);
            $('#tire_excess_pattern').val(tire_pattern_name);
            $('#tire_excess_pattern').attr('data',tire_pattern);
            $('#tire_excess_pattern').attr('disabled',true);

            $( ".add-field" ).dialog( "open" );
        }

        
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
     
        $('#tire_excess_name').val("");
        $('#tire_excess').val(0);
        $('#tire_excess_vat').val(0);
        $('#customer').val("");
        $('#customer').attr('data',"");
                
        $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

    $( ".add-field" ).dialog( "open" );
}


$(document).ready(function(){
            // Validate form
            $("#add_tire").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var code = $('#code').attr('value');
                    var tire_excess_name = $('#tire_excess_name').attr('value');
                    var tire_excess_type = $('#tire_excess_type').attr('value');
                    var tire_excess = $('#tire_excess').attr('value');
                    var tire_excess_vat = $('#tire_excess_vat').attr('value');
                    var tire_excess_brand = $('#tire_excess_brand').attr('value');
                    var tire_excess_size = $('#tire_excess_size').attr('value');
                    var customer = $('#customer').attr('data');
                    var tire_excess_pattern = $('#tire_excess_pattern').attr('data');
                    var tire_pattern_name = $('#tire_excess_pattern').attr('value');
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/tiresale/addcost", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            code: code,
                            tire_excess_name: tire_excess_name,
                            tire_excess_type: tire_excess_type,
                            tire_excess: tire_excess,
                            tire_excess_vat: tire_excess_vat,
                            tire_excess_brand: tire_excess_brand,
                            tire_excess_size: tire_excess_size,
                            customer: customer,
                            tire_excess_pattern: tire_excess_pattern,
                            tire_pattern_name: tire_pattern_name,

                            yes: yes,

                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

                                    $('#expect_date_'+yes).text(expect_date);
                                    $('#comment_'+yes).text(comment);
                                    $('#money_'+yes).text(money);
                                    $('#source_'+yes).text($("#source option:selected").text());
                                    $('#source_in_'+yes).text($("#source_in option:selected").text());
                            }
                            else{
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="vendor_'+parseInt(lastID+1)+'">'+vendor+'</td><td class="fix" id="money_'+parseInt(lastID+1)+'">'+money+'</td><td class="fix" id="expect_date_'+parseInt(lastID+1)+'">'+expect_date+'</td><td class="fix" id="week_'+parseInt(lastID+1)+'"></td><td class="fix" id="code_'+parseInt(lastID+1)+'">'+code+'</td><td class="fix" id="source_'+parseInt(lastID+1)+'">'+$("#source option:selected").text()+'</td><td class="fix" id="comment_'+parseInt(lastID+1)+'">'+comment+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                
                            }
                        }
                    });
                    return false;
                     
                 }
            });


$('#customer').keyup(function(){
      
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/salereport/getcustomer',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                $('#customer_list_id').slideDown(200);
                $('#customer_list_id').html(data);
            }
        });
        if ($('#customer').val() == "" || $('#customer').attr('data') == "") {
            
            $('#customer').attr('data',"");
        }
      
      
   });  
$('#customer').on('keydown', function() {
        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('#customer').attr('data',"");
        }
            
      });  

   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-]/g, "")
        ;
      });
    });
    

});

function get_number(id){
    return $(id).val().replace(/\,/g,'');
}
function set_item(item,value,phone,address,email,ngay) {
    // change input value
    $('#customer').val(item);
    $("#customer").attr("data",value);
    $('#customer_list_id').hide();
    $('#customer').focus();

}

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });


 
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');


</script>
</div>

<script type="text/javascript">


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Lô hàng",
    hide: 'fold',
    show: 'blind'
});

$('.del').click(function(){
    var data = $(this).attr('data');
    var r = confirm("Bạn có chắc chắn không?");
    if (r == true){
         $.post("<?php echo BASE_URL ?>/tiresale/deletecost", {data: data},
           function(data){
                setTimeout(function() {
                    sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                  }, 200);
           }); 
    }
});
</script>

