
<div class="main-content-box">



    <h2>Chính sách bảo hành & Đổi trả</h2>



    <div class="items-list-prod">


        <div class="wrap_detail">
            
                <p> <strong>Chính sách bảo hành</strong></p>
                <p>Việt Trade cam kết cung cấp cho khách hàng các sản phẩm đúng theo tiêu chuẩn chất lượng của Nhà sản xuất đã đăng ký với cơ quan quản lý chất lượng Nhà nước. Hàng mới 100%, chưa qua sử dụng.</p>
                <p>- Bảo hành chung: Bảo hành khi lỗi do nhà sản xuất và gai lốp xe còn 30% trong trường hợp xe chạy đúng tải trọng và mục đích cho phép.</p>
                <p>- Bảo hành riêng: Việt Trade bảo hành riêng biệt cho từng sản phẩm cung cấp cho khách hàng trong trường hợp khách hàng tiến hành việc tồn trữ, vận chuyển, hướng dẫn sử dụng và giám sát, nghiệm thu đúng với nội dung đã huấn luyện và phổ biến của Việt Trade.</p>
                <p>- Khách hàng sẽ được bảo hành 1 đổi 1 tương ứng với quy cách và chất lượng của sản phẩm mà khách hàng đã mua tại Việt Trade nếu đúng với điều kiện được bảo hành.</p>
                <p>- Quy trình:</p>
                <ul>
                    <li>Khách hàng thông báo tới bộ phận hỗ trợ khách hàng của Việt Trade</li>
                    <li>Việt Trade tiếp nhận thông tin của khách hàng: Hình ảnh, chủng loại, số lượng, tình trạng,...</li>
                    <li>Khách hàng gửi sản phẩm tới Việt Trade</li>
                    <li>Việt Trade xác nhận và tiến hành kiểm tra và xác minh</li>
                    <li>Thông báo kết quả và đổi sản phẩm nếu đủ điều kiện bảo hành</li>
                </ul>
                <p> <strong>Chính sách đổi trả</strong></p>
                <p>- Trong trường hợp sản phẩm quý khách nhận được không đúng như những gì Việt Trade đã mô tả trong phần thông tin sản phẩm, quý khách vui lòng thông tin đến bộ phận Hỗ trợ khách hàng trong thời gian sớm nhất kể từ khi nhận hàng đồng thời đảm bảo sản phẩm trong tình trạng chưa qua sử dụng để được hỗ trợ đổi trả.</p>
                <p>- Trong mọi trường hợp, khách hàng đều có quyền chấm dứt giao dịch nếu đã thực hiện các biện pháp sau đây:</p>
                <ul>
                    <li>Thông báo cho Việt Trade về việc hủy giao dịch qua đường dây nóng 083 500 9000 hoặc nhân viên phụ trách</li>
                    <li>Trả lại hàng hoá đã nhận nhưng chưa sử dụng hoặc hưởng bất kỳ lợi ích nào từ hàng hóa đó</li>
                </ul>
                <p><i>Bất kỳ tranh cãi, khiếu nại hoặc tranh chấp phát sinh từ hoặc liên quan đến giao dịch tại Việt Trade sẽ được giải quyết bằng hình thức thương lượng, hòa giải, trọng tài và/hoặc Tòa án theo Luật bảo vệ Người tiêu dùng Chương 4 về Giải quyết tranh chấp giữa người tiêu dùng và tổ chức, cá nhân kinh doanh hàng hóa, dịch vụ.</i></p>
        </div>
        
    </div>



</div>

<style type="text/css">
.wrap_detail{
    color: white;
}
</style>