
<div class="main-content-box">



    <h2>Chính sách giao hàng</h2>



    <div class="items-list-prod">


        <div class="wrap_detail">
            <table class="table table-bordered" id="table_4">
                <thead>
                    <tr>
                        <th>Hình thức</th>
                        <th>Nội dung áp dụng</th>
                        <th>Thời gian</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Giao hàng tận nơi
                        </td>
                        <td>
                            Miễn phí giao hàng cho những đơn hàng số lượng từ 10 lốp trở lên tại các khu vực sau: TP. Hồ Chí Minh, Đồng Nai, Bình Dương, Bà Rịa - Vũng Tàu.
                        </td>
                        <td>
                            (*)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Lấy hàng tại kho
                        </td>
                        <td>
                            Giảm 100.000VNĐ/1 bộ cho khách hàng lấy hàng tại kho công ty.
                        </td>
                        <td>
                            Từ 7:00 - 22:00 Tất cả các ngày trong tuần
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Giao hàng qua chành xe hoặc đơn vị vận chuyển
                        </td>
                        <td>
                            Chi phí do 2 bên thỏa thuận.
                        </td>
                        <td>
                            (*)
                        </td>
                    </tr>
                </tbody>
            </table>
            <p>
                <i>(*) Thời gian phụ thuộc vào tùy tình hình thực tế.</i>
            </p>    
        </div>
    </div>



</div>

<style type="text/css">
.wrap_detail{
    color: white;
}
</style>