
<div class="main-content-box">



    <h2>Liên hệ</h2>



    <div class="items-list-prod">


        <div class="wrap_detail">
            <p>
                <strong>CÔNG TY TNHH VIỆT TRA DE</strong>
            </p>
            <p><span class="lh">Mã số thuế:</span> 3603295302</p>
            <P><span class="lh">Trụ sở chính:</span> Số 545, Tổ 10, Ấp Hương Phước, Xã Phước Tân, TP. Biên Hòa, Tỉnh Đồng Nai</P>
            <P><span class="lh">Văn phòng:</span> Số 29, QL 51, Xã Phước Tân, TP. Biên Hòa, Tỉnh Đồng Nai</P>
            <p><span class="lh">Số điện thoại:</span> 0613 937 677 - 0613 937 747 - 0613 937 607</p>
            <P><span class="lh">Fax:</span> 0613 937 677</P>
            <P><span class="lh">Hotline:</span> 083 500 9000</P>
            <p><span class="lh">Email:</span> it@viet-trade.org</p>
            <p><span class="lh">Website:</span> www.viet-trade.org</p>
            <div class="items-list-prod">

                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3917.9855316469148!2d106.8948135143375!3d10.888703760089754!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174dfc25c447b5f%3A0xc91b336a3f9bdcd5!2zVmnhu4d0IFRyYWRl!5e0!3m2!1svi!2s!4v1471573615604" width="100%" height="650" frameborder="0" style="border:0" allowfullscreen></iframe>

            </div>
        </div>
        
    </div>



</div>

<style type="text/css">
.wrap_detail{
    color: white;
}
.lh{
    color: #337ab7;
}
</style>