
<div class="main-content-box">



    <h2><i class="fa fa-credit-card"></i> Chuyển khoản</h2>



    <div class="items-list-prod">


        <div class="wrap_detail">
                    <p>Quý khách vui lòng chuyển khoản cho chúng tôi theo thông tin sau: </p>

                    <div class="wrap-div-thong-tin-ngan-hang">
                        <div class=" thong-tin-ngan-hang">
                            <div class="col-md-2">
                                Ngân hàng
                            </div>
                            <div class="col-md-10">
                                : <b>BIDV - Chi nhánh Nam Đồng Nai</b>
                            </div>
                        </div>
                        <div class=" thong-tin-ngan-hang">
                            <div class="col-md-2">
                                Tên tài khoản
                            </div>
                            <div class="col-md-10">
                                : <b>Công Ty TNHH Việt Tra de</b>
                            </div>
                        </div>
                        <div class=" thong-tin-ngan-hang">
                            <div class="col-md-2">
                                Số TK
                            </div>
                            <div class="col-md-10">
                                : 6721.0000.476.025
                            </div>
                        </div>
                    </div>
                    <div>&nbsp;</div>
                    <div class="wrap-div-thong-tin-ngan-hang">
                        <div class=" thong-tin-ngan-hang">
                            <div class="col-md-2">
                                Ngân hàng
                            </div>
                            <div class="col-md-10">
                                : <b>ACB - PGD  Long Bình Tân - Biên Hòa - Đồng Nai</b>
                            </div>
                        </div>
                        <div class=" thong-tin-ngan-hang">
                            <div class="col-md-2">
                                Tên tài khoản
                            </div>
                            <div class="col-md-10">
                                : <b>Công Ty TNHH Việt Tra de</b>
                            </div>
                        </div>
                        <div class=" thong-tin-ngan-hang">
                            <div class="col-md-2">
                                Số TK
                            </div>
                            <div class="col-md-10">
                                : 200.970.509
                            </div>
                        </div>
                    </div>
                    


                    <p>Để đảm bảo quyền lợi khách hàng, khách hàng cần lưu ý</p>
                    <span>Quý khách vui lòng chuyển khoản qua ngân hàng trong phần “Nội dung thanh toán”, Quý khách ghi rõ mã đơn hàng cần thanh toán.</span> 
                    
                
        </div>
    </div>



</div>

<div class="main-content-box">



    <h2><i class="fa fa-home"></i> Tại văn phòng</h2>



    <div class="items-list-prod">


        <div class="wrap_detail">
                    
                    <p>Quý khách có thể đến trực tiếp văn phòng để giao dịch </p>
                    <ul>
                        <li>
                            Số 29, QL 51, X. Phước Tân, TP. Biên Hòa, T. Đồng Nai. <br>
                            ĐT: (061) 3 937 677   -  Fax: (061) 3 937 677   -  Hotline: 083 500 9000
                        </li>
                        <li>
                            Giờ làm việc (từ thứ 2 đến thứ 6, thứ 7 làm việc buổi sáng)
                        </li>

                    </ul>
                    <p>Để đảm bảo quyền lợi khách hàng, khách hàng cần lưu ý</p>
                    <ul>
                        <li>
                            Giao dịch tại các địa điểm được quy định.
                        </li>
                        <li>
                            Kiểm tra cẩn thận các giao dịch trước khi rời nơi giao dịch.
                        </li>
                        <li>
                            Khách hàng phải ký vào biên bản, phiếu thu và các giấy tờ khác.
                        </li>
                    </ul>
                
                
        </div>
    </div>



</div>

<style type="text/css">
.wrap_detail{
    color: white;
}
</style>