<div class="slide-content" id="huong-dan-nhanh">
        <div class="item-page">
            <h2>Hướng dẫn</h2>
            <p>1. Khách hàng làm công văn nêu rõ lý do có dấu và chữ ký của Chủ doanh nghiệp trình Hãng tàu, Hải quan và Cảng, .
            <p>2. Khách hàng xin xác nhận đồng ý của Hãng tàu (chủ khai thác container).
            <p>3. Khách hàng liên hệ  Bộ phận quản lý container (Ter/Khu hàng) để xác nhận vị trí và số lượng container đảo chuyển thực tế.
            <p>4. Khách hàng xin xác nhận container chưa vào sổ tàu hoặc xoá khỏi sổ tàu tại Bộ phận Đăng ký tàu xuất.
            <p>5. Khách hàng xin xác nhận đồng ý cho lấy hàng ra khỏi Cảng của cơ quan Hải quan:
            <p>- Hải quan xin xác nhận gồm – Customs departments  to get approval include:
               <p>+ Hải quan Giám sát
               <p>+ Chỉ huy đội Hải quan Giám sát
                <p>+ Lãnh đạo chi cục Hải quan Cảng Sài Gòn - Khu vực I - Cát lái
            <p>6. Khách hàng xin xác nhận của Trực ban Sản xuất Cảng Cát Lái:
               <p>+ Đối với số lượng dưới 03 container, Trực ban Sản xuất xác nhận giải quyết.
               <p>+ Đối với số lượng trên 03 container, Trực ban Sản xuất báo cáo Ban Giám Đốc Trung tâm xin ý kiến giải quyết.
            <p>7. Khách hàng hoàn tất thủ tục tại phòng Phát hành chứng từ, nhận phiếu Xuất nhập bãi để lấy container.
            <p>8. Khách hàng đưa phương tiện vào lấy container ra khỏi Cảng trước khi thời hạn Phiếu Xuất nhập bãi hết giá trị.

        </div>
    </div> 

<script type="text/javascript">
    closeSidepage('#huong-dan-nhanh');
   openSidepage('#huong-dan-nhanh');
</script>