<div class="slide-content" id="giam-dinh-sua-chua-container">
            <!-- Go to www.addthis.com/dashboard to customize your tools -->
        <div class="addthis_native_toolbox"></div>
        <div class="item-page">
            <h2>Dịch vụ giám định - Sửa chữa container</h2>
            <p>
                Với kinh nghiệm sản xuất container nhiều năm, đội ngũ nhân viên lành nghề công ty chúng tôi cung cấp cho thị trường dịch vụ sửa chữa container chuyên nghiệp theo tiêu chuẩn ISO Container, IICL.
            </p>
            <img src="public/images/cont8.jpg">
        </div>
    </div>
<script type="text/javascript">
    closeSidepage('#giam-dinh-sua-chua-container');
   openSidepage('#giam-dinh-sua-chua-container');
</script>