<link href="<?php echo BASE_URL ?>/public/css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo BASE_URL ?>/public/css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
<script src="<?php echo BASE_URL ?>/public/js/tag-it.js" type="text/javascript" charset="utf-8"></script>
<?php
$url_order = 'ASC';
if ($order_by == 'e_cart_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'e_cart_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'e_customer_contact')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'e_total')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'e_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> DANH SÁCH ĐƠN HÀNG </h1></center>
<div class="add-box">
    <?php if($_SESSION['role_logined'] ==1 ){ ?>
    <a class="add_button" id="btnExport" >Export Excel</a>
    <?php } ?>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
        <div >
            <select id="sl_tha" name="sl_tha" style="width:90px; margin-left:5px;">
             <?php 
                for ($i=1; $i < 13; $i++) { 
                    echo '<option value="'.$i.'">Tháng '.$i.'</option>';
                }
             ?>
            </select>
            <select id="sl_na" name="sl_na" style="width:100px">
             <?php 
                $nam = date('Y');
                for ($i=($nam-5); $i < ($nam+5); $i++) { 
                    echo '<option value="'.$i.'">Năm '.$i.'</option>';
                }
             ?>
            </select>
            <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        </div>
        <div >
    
            Từ  <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:100px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');"> 
                                    
        </div>
        
        <div class="add-box">
            <select id="sl_status" name="sl_status" style="width:200px">
                <option value="">Khách hàng</option>
                <?php foreach ($customers as $customer) { ?>
                    <option value="<?php echo $customer->e_customer_id ?>"><?php echo $customer->e_customer_contact ?></option>
                <?php } ?>
            </select>
            <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        </div>
        <div class="add-box">
            <select id="sl_nv" name="sl_nv" style="width:150px">
                <option value="">Trạng thái</option>
                <option value="0">Chưa giao hàng</option>
                <option value="1">Đã giao hàng</option>
            </select>
            <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        </div>
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action2();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
            <option selected="selected" value="10">Hiển thị 10 giá trị</option>
			<option value="20">Hiển thị 20 giá trị</option>
            <option value="30">Hiển thị 30 giá trị</option>
            <option value="50">Hiển thị 50 giá trị</option>
            
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>
    

</div>

<table id="tblExport" class="table_data">
<thead>
    <tr>
    	<th rowspan="2" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_cart_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'e_cart_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_cart_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'e_cart_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_customer_contact','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'e_customer_contact'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_customer_phone','<?php echo $url_order ?>')">SĐT <?php if ($order_by == 'e_customer_phone'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_customer_email','<?php echo $url_order ?>')">Email <?php if ($order_by == 'e_customer_email'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_number','<?php echo $url_order ?>')">Số lượng <?php if ($order_by == 'e_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_total','<?php echo $url_order ?>')">Thu <?php if ($order_by == 'e_total'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_discount','<?php echo $url_order ?>')">Trừ giảm <?php if ($order_by == 'e_discount'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_total','<?php echo $url_order ?>')">KH phải trả <?php if ($order_by == 'e_total'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_comment','<?php echo $url_order ?>')">Ghi chú <?php if ($order_by == 'e_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_status','<?php echo $url_order ?>')">Trạng thái <?php if ($order_by == 'e_status'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','e_staff','<?php echo $url_order ?>')">Nhân viên <?php if ($order_by == 'e_staff'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
    </tr>
    
   </thead>
   <tbody>
    <?php $j=1; $tongsl = 0; $tongthu=0; $tongthue=0; $tonggiam=0; $tongtra=0; ?>
    <?php foreach ($e_carts as $e_cart) : ?>
    <?php
        $tongsl += $e_cart->e_number; 
        $tongthu += $e_cart->e_total+$e_cart->e_discount; 
        $tonggiam += $e_cart->e_discount; 
        $tongtra += $e_cart->e_total;
    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $e_cart->e_cart_id ?>" class="edit_tr" >
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $e_cart->e_cart_id ?>"></td>
            <td class="fix"><?php echo $j++; ?></td>
            <td class="fix"  id="e_cart_date_<?php echo $e_cart->e_cart_id; ?>"><?php echo $lib->hien_thi_ngay_thang($e_cart->e_cart_date); ?></td>
            <td class="fix" data="<?php echo $e_cart->e_customer; ?>"  id="e_customer_<?php echo $e_cart->e_cart_id; ?>"><?php echo $e_cart->e_customer_contact; ?></td>
            <td class="fix" data="<?php echo $e_cart->e_customer; ?>"  id="e_customer_phone_<?php echo $e_cart->e_cart_id; ?>"><?php echo $e_cart->e_customer_phone; ?></td>
            <td class="fix" data="<?php echo $e_cart->e_customer; ?>"  id="e_customer_email_<?php echo $e_cart->e_cart_id; ?>"><?php echo $e_cart->e_customer_email; ?></td>
            <td class="fix"  id="e_number_<?php echo $e_cart->e_cart_id; ?>"><a style="font-weight:bold;text-decoration:underline" class="order_list" href="<?php echo $this->url('ecart/listtire/'.$e_cart->e_cart_id); ?>"><?php echo $e_cart->e_number; ?></a></td>
            <td class="fix" id="thu_<?php echo $e_cart->e_cart_id; ?>"><?php echo $lib->formatMoney($e_cart->e_total+$e_cart->e_discount); ?></td> 
            <td class="fix"  id="e_discount_<?php echo $e_cart->e_cart_id; ?>"><?php echo $lib->formatMoney($e_cart->e_discount); ?></td>
            <td class="fix"  id="e_total_<?php echo $e_cart->e_cart_id; ?>"><?php echo $lib->formatMoney($e_cart->e_total); ?></td>
            <td class="fix" id="e_comment_<?php echo $e_cart->e_cart_id; ?>"><?php echo $e_cart->e_comment; ?></td> 
            <td class="fix" id="e_status_<?php echo $e_cart->e_cart_id; ?>" data="<?php echo $e_cart->e_status ?>">
                <?php echo $e_cart->e_status==1?"Đã giao hàng":"Chưa xuất hàng" ?>
            </td> 
            <td class="fix" id="e_staff_<?php echo $e_cart->e_cart_id; ?>" data="<?php echo $e_cart->e_staff ?>">
                <?php
                if ($e_cart->e_staff > 0) {
                    echo $users['name'][$e_cart->e_staff];
                }
                else{
                ?>
                <button id="ex_stock_<?php echo $e_cart->e_cart_id; ?>" style="display:none" class="ex_stock" data="<?php echo $e_cart->e_cart_id; ?>">Nhận</button>
                <?php } ?>
            </td> 
        </tr>
    <?php endforeach; ?>
        <tr style="text-align:center; font-weight: bold; color: red;">
            <td class="fix" colspan="6" >Tổng cộng</td>
            <td class="fix"><?php echo $lib->formatMoney($tongsl); ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongthu); ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tonggiam); ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongtra); ?></td>
            <td class="fix" colspan="3" ></td>
        </tr>

   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('ecart') ?>">&larr;</a></div>



<script type="text/javascript">
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');

var c = "<?php echo $trangthai ?>";
$('#sl_status option[value='+c+']').attr('selected','selected');

var s = "<?php echo $nv ?>";
$('#sl_nv option[value='+s+']').attr('selected','selected');

var th = "<?php echo $thang ?>";
$('#sl_tha option[value='+th+']').attr('selected','selected');

var n = "<?php echo $nam ?>";
$('#sl_na option[value='+n+']').attr('selected','selected');



$(".order_list").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:500,
            width:600,
            resizable: false,
            title:'Thông tin',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });



$('.edit_tr').hover(function(){
    var e_status = $(this).find("#e_status_"+$(this).attr('id')).attr('data');
    if (e_status != 1) {
        $('#ex_stock_'+$(this).attr('id')).show();
    }
    else{
        $('#ex_stock_'+$(this).attr('id')).hide();
    }
},function(){
    $('#ex_stock_'+$(this).attr('id')).hide();
});

$('.ex_stock').click(function(){
    var id = $(this).attr("data");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/ecart/approve", {data: id},
           function(data){
            //alert(data);

            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});


function get_number(id){
    return $(id).val().replace(/[^0-9\.-]+/g,"");
}

$('.numbers').focus(function(){
        if ( $(this).val() == '0') {
           $(this).val(""); 
        };
        
    });
    $('.numbers').blur(function(){
        if ( $(this).val() == "") {
            $(this).val(0);
        };
        
    });

     $('.numbers').keyup(function(event) {

      // skip for arrow keys
  if(event.which >= 37 && event.which <= 40) return;

  // format number
  $(this).val(function(index, value) {
    return value
      .replace(/[^0-9-.]/g, "")
      .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
    ;
  });
});



</script>
<script type="text/javascript">
    
    $('#sl_tha').change(function(){
        var m = $(this).val();
        var y = $('#sl_na').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

    $('#sl_na').change(function(){
        var y = $(this).val();
        var m = $('#sl_tha').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });


    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showWeek: true,
        weekHeader: 'Tuần',
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showWeek: true,
        weekHeader: 'Tuần',
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
  $('.del').click(function(){
    var data = $(this).attr('data');
    var r = confirm("Bạn có chắc chắn không?");
    if (r == true){
         $.post("<?php echo BASE_URL ?>/ecart/delete", {data: data},
           function(data){
                setTimeout(function() {
                    sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                  }, 200);
           }); 
    }
});

function action2(){
  
    var action       = $('#action').attr('value');
    if(action != -1)
    {
      if($('.add-field') !== null)
        {
          $('.add-field').fadeOut();
        }
      var del = [];
      ids = $('input:checkbox.checkbox:checked').map(function() { return del.push(this.value); });
      
       if(action=='delete'){
         var r = confirm("Bạn có chắc chắn muốn xóa không?");
        if (r == true){
          $('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
           $.ajax({
            url: "<?php echo $this->url('ecart/delete') ?>",   
            type: 'POST',   
            data: "xoa="+del,   
            success:function(answer){ 
              for(var i=0; i<del.length; i++)
                 $('tr#'+del[i]).remove();
              $('#loading').fadeOut(500); 
              $("html, body").animate({ scrollTop: 0 }, 100);
            }
          });
        }
       }
       else if(action=='phathanh'){
         $.ajax({
          url: window.location.href+"/update", 
          type: 'POST',   
          data: "phathanh="+del,   
          success:function(answer){ 
            for(var i=0; i<del.length; i++)
               $('#trangthai_'+del[i]).html('Hiá»ƒn thá»‹');
            $('#loading').fadeOut(500); 
          }
        });
       }
       else if(action=='an'){
         $.ajax({
          url: window.location.href+"/update",   
          type: 'POST',   
          data: "an="+del,   
          success:function(answer){ 
            for(var i=0; i<del.length; i++)
               $('#trangthai_'+del[i]).html('áº¨n');
            $('#loading').fadeOut(500); 
          }
        });
       }
       else if(action=='noibat'){
         $.ajax({
          url: window.location.href+"/update",  
          type: 'POST',   
          data: "noibat="+del,   
          success:function(answer){ 
            for(var i=0; i<del.length; i++)
               $('#tinnoibat_'+del[i]).html('Ná»•i báº­t');
            $('#loading').fadeOut(500); 
          }
        });
       }
       else if(action=='binhthuong'){
         $.ajax({
          url: window.location.href+"/update",   
          type: 'POST',   
          data: "binhthuong="+del,   
          success:function(answer){ 
            for(var i=0; i<del.length; i++)
               $('#tinnoibat_'+del[i]).html('BĂ¬nh thÆ°á»ng');
            $('#loading').fadeOut(500); 
          }
        });
       }
    }
  
}
</script>