<?php 
foreach ($accounts as $account) {
  $nodauky = isset($data_additional[$account->account_id]['no']['dauky'])?$data_additional[$account->account_id]['no']['dauky']:0;
  $codauky = isset($data_additional[$account->account_id]['co']['dauky'])?$data_additional[$account->account_id]['co']['dauky']:0;
  
 $no_dauky[$account->account_number] = isset($no_dauky[$account->account_number])?$no_dauky[$account->account_number]+max(0,$nodauky-$codauky):max(0,$nodauky-$codauky);
 $co_dauky[$account->account_number] = isset($co_dauky[$account->account_number])?$co_dauky[$account->account_number]+max(0,$codauky-$nodauky):max(0,$codauky-$nodauky);
     
  switch ($account->account_number) {
    case '5111':
      $acc_5111 = $account->account_id;
      break;
    case '3331':
      $acc_3331 = $account->account_id;
      break;
    case '515':
      $acc_515 = $account->account_id;
      break;
    case '6321':
      $acc_6321 = $account->account_id;
      break;
    case '635':
      $acc_635 = $account->account_id;
      break;
    case '6411':
      $acc_6411 = $account->account_id;
      break;
    case '6412':
      $acc_6412 = $account->account_id;
      break;
    case '6413':
      $acc_6413 = $account->account_id;
      break;
    case '6414':
      $acc_6414 = $account->account_id;
      break;
    case '6418':
      $acc_6418 = $account->account_id;
      break;
    case '6421':
      $acc_6421 = $account->account_id;
      break;
    case '6422':
      $acc_6422 = $account->account_id;
      break;
    case '6423':
      $acc_6423 = $account->account_id;
      break;
    case '6425':
      $acc_6425 = $account->account_id;
      break;
    case '6426':
      $acc_6426 = $account->account_id;
      break;
    case '6427':
      $acc_6427 = $account->account_id;
      break;
    case '6428':
      $acc_6428 = $account->account_id;
      break;
    case '711':
      $acc_711 = $account->account_id;
      break;
    case '811':
      $acc_811 = $account->account_id;
      break;
    case '911':
      $acc_911 = $account->account_id;
      break;
    case '4111':
      $acc_4111 = $account->account_id;
      break;
    default:
      # code...
      break;
  }
  
 }


$no_dauky['515'] = max(0,$no_dauky['515']-$co_dauky['515']);
$co_dauky['515'] = max(0,$co_dauky['515']-$no_dauky['515']);
$no_dauky['635'] = max(0,$no_dauky['635']-$co_dauky['635']);
$co_dauky['635'] = max(0,$co_dauky['635']-$no_dauky['635']);

$co_dauky['911'] += $co_dauky['5111'];
$co_dauky['911'] += $co_dauky['3331'];
$co_dauky['911'] += $co_dauky['515'];
$no_dauky['911'] += $no_dauky['6321'];
$no_dauky['911'] += $no_dauky['635'];
$no_dauky['911'] += $no_dauky['6411'];
$no_dauky['911'] += $no_dauky['6412'];
$no_dauky['911'] += $no_dauky['6413'];
$no_dauky['911'] += $no_dauky['6414'];
$no_dauky['911'] += $no_dauky['6418'];
$no_dauky['911'] += $no_dauky['6421'];
$no_dauky['911'] += $no_dauky['6422'];
$no_dauky['911'] += $no_dauky['6423'];
$no_dauky['911'] += $no_dauky['6425'];
$no_dauky['911'] += $no_dauky['6426'];
$no_dauky['911'] += $no_dauky['6427'];
$no_dauky['911'] += $no_dauky['6428'];
$co_dauky['911'] += $co_dauky['711'];
$no_dauky['911'] += $no_dauky['811'];

if ($co_dauky['911']>$no_dauky['911']) {
  $co_dauky['911'] = $co_dauky['911']-$no_dauky['911'];
  $no_dauky['911'] = 0;
}
else{
  $no_dauky['911'] = $no_dauky['911']-$co_dauky['911'];
  $co_dauky['911'] = 0;
}
?>
<center>
  <select id="sl_round" name="sl_round" style="width:90px; margin-left:5px;">
   <?php 
      for ($i=1; $i < 13; $i++) { 
          echo '<option value="'.$i.'">Tháng '.$i.'</option>';
      }
   ?>
  </select>
  <select id="sl_trangthai" name="sl_trangthai" style="width:100px">
   <?php 
      $nam = date('Y');
      for ($i=($nam-5); $i < ($nam+5); $i++) { 
          echo '<option value="'.$i.'">Năm '.$i.'</option>';
      }
   ?>
  </select>
  <button type="button" id="show" class="btn">Lấy dữ liệu</button>
</center>


<form id="add" name="add" action="" method="post">
  Ngày chứng từ: <input type="date" id="document_date"  name="document_date" tabindex="1" required="required" autocomplete="off" >
  Ngày hạch toán: <input type="date" id="additional_date"  name="additional_date" tabindex="2" required="required" autocomplete="off" >
  Số chứng từ: <input type="text" id="document_number"  name="document_number" tabindex="3" required="required" autocomplete="off" >
  <button type="submit" class="btn"><i class="fa fa-check"></i> Kết chuyển</button>
  <button type="button" id="remove" class="btn"><i class="fa fa-times"></i> Xóa</button>
  <table class="table_data">
    <thead>
      <tr>
        <th class="fix">Thứ tự</th>
        <th class="fix">Kết chuyển từ</th>
        <th class="fix">Kết chuyển đến</th>
        <th class="fix">Diễn giải</th>
        <th class="fix">Số tiền</th>
        <th class="fix">Kết quả</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="fix text-center">1</td>
        <td class="fix text-center">5111</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_5111_911"  name="comment_5111_911" required="required" autocomplete="off" value="Doanh thu lốp xe" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_5111_911"  name="money_5111_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($co_dauky['5111']) ?>" ></td>
        <td class="fix"><span id="result_5111_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">2</td>
        <td class="fix text-center">3331</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_3331_911"  name="comment_3331_911" required="required" autocomplete="off" value="Thuế GTGT lốp xe" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_3331_911"  name="money_3331_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($co_dauky['3331']) ?>" ></td>
        <td class="fix"><span id="result_3331_911"></span></td>
      </tr>
      <tr>
        <td class="fix text-center">3</td>
        <td class="fix text-center">515</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_515_911"  name="comment_515_911" required="required" autocomplete="off" value="Lãi tiền gửi" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_515_911"  name="money_515_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($co_dauky['515']) ?>" ></td>
        <td class="fix"><span id="result_515_911"></span></td>
      </tr>
      <tr>
        <td class="fix text-center">4</td>
        <td class="fix text-center">6321</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6321_911"  name="comment_6321_911" required="required" autocomplete="off" value="Chi phí vốn hàng lốp xe" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6321_911"  name="money_6321_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6321']) ?>" ></td>
        <td class="fix"><span id="result_6321_911"></span></td>
      </tr>
      <tr>
        <td class="fix text-center">5</td>
        <td class="fix text-center">635</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_635_911"  name="comment_635_911" required="required" autocomplete="off" value="Trả lãi vay" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_635_911"  name="money_635_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['635']) ?>" ></td>
        <td class="fix"><span id="result_635_911"></span></td>
      </tr>
      <tr>
        <td class="fix text-center">6</td>
        <td class="fix text-center">6411</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6411_911"  name="comment_6411_911" required="required" autocomplete="off" value="Chi phí logistics" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6411_911"  name="money_6411_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6411']) ?>" ></td>
        <td class="fix"><span id="result_6411_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">7</td>
        <td class="fix text-center">6412</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6412_911"  name="comment_6412_911" required="required" autocomplete="off" value="Chi phí xăng, công tác" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6412_911"  name="money_6412_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6412']) ?>" ></td>
        <td class="fix"><span id="result_6412_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">8</td>
        <td class="fix text-center">6413</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6413_911"  name="comment_6413_911" required="required" autocomplete="off" value="Chi phí bảo hành" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6413_911"  name="money_6413_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6413']) ?>" ></td>
        <td class="fix"><span id="result_6413_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">9</td>
        <td class="fix text-center">6414</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6414_911"  name="comment_6414_911" required="required" autocomplete="off" value="Chi phí hoa hồng cho khách hàng" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6414_911"  name="money_6414_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6414']) ?>" ></td>
        <td class="fix"><span id="result_6414_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">10</td>
        <td class="fix text-center">6418</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6418_911"  name="comment_6418_911" required="required" autocomplete="off" value="Chi phí VC + BX" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6418_911"  name="money_6418_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6418']) ?>" ></td>
        <td class="fix"><span id="result_6418_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">11</td>
        <td class="fix text-center">6421</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6421_911"  name="comment_6421_911" required="required" autocomplete="off" value="Tiền lương & Phụ cấp + Bảo hiểm" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6421_911"  name="money_6421_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6421']) ?>" ></td>
        <td class="fix"><span id="result_6421_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">12</td>
        <td class="fix text-center">6422</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6422_911"  name="comment_6422_911" required="required" autocomplete="off" value="Chi phí vật liệu quản lý (VPP, …)" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6422_911"  name="money_6422_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6422']) ?>" ></td>
        <td class="fix"><span id="result_6422_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">13</td>
        <td class="fix text-center">6423</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6423_911"  name="comment_6423_911" required="required" autocomplete="off" value="Phí chuyển khoản + quản lý tk" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6423_911"  name="money_6423_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6423']) ?>" ></td>
        <td class="fix"><span id="result_6423_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">14</td>
        <td class="fix text-center">6425</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6425_911"  name="comment_6425_911" required="required" autocomplete="off" value="Thuế, phí & lệ phí" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6425_911"  name="money_6425_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6425']) ?>" ></td>
        <td class="fix"><span id="result_6425_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">15</td>
        <td class="fix text-center">6426</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6426_911"  name="comment_6426_911" required="required" autocomplete="off" value="Thuê kho bãi + Xây dựng kho" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6426_911"  name="money_6426_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6426']) ?>" ></td>
        <td class="fix"><span id="result_6426_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">16</td>
        <td class="fix text-center">6427</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6427_911"  name="comment_6427_911" required="required" autocomplete="off" value="Dịch vụ mua ngoài (EMS, …)" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6427_911"  name="money_6427_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6427']) ?>" ></td>
        <td class="fix"><span id="result_6427_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">17</td>
        <td class="fix text-center">6428</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_6428_911"  name="comment_6428_911" required="required" autocomplete="off" value="Chi phí khác (tiếp khách, hội nghị)" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_6428_911"  name="money_6428_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['6428']) ?>" ></td>
        <td class="fix"><span id="result_6428_911"></span></td>
        
      </tr>
      <tr>
        <td class="fix text-center">18</td>
        <td class="fix text-center">711</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_711_911"  name="comment_711_911" required="required" autocomplete="off" value="Kết chuyển thu nhập khác" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_711_911"  name="money_711_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($co_dauky['711']) ?>" ></td>
        <td class="fix"><span id="result_711_911"></span></td>
      </tr>
      <tr>
        <td class="fix text-center">19</td>
        <td class="fix text-center">811</td>
        <td class="fix text-center">911</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_811_911"  name="comment_811_911" required="required" autocomplete="off" value="Kết chuyển chi phí khác" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right" id="money_811_911"  name="money_811_911" required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['811']) ?>" ></td>
        <td class="fix"><span id="result_811_911"></span></td>
      </tr>
      <tr>
        <td class="fix text-center">20</td>
        <td class="fix text-center">911</td>
        <td class="fix text-center">4111</td>
        <td class="fix"><input style="width:100%" type="text" id="comment_911_4111"  name="comment_911_4111" required="required" autocomplete="off" value="Kết chuyển kết quả hoạt động kinh doanh" ></td>
        <td class="fix" style="width:10%"><input type="text" class="numbers text-right"  required="required" autocomplete="off" value="<?php echo $lib->formatMoney($no_dauky['911']+$co_dauky['911']) ?>" ></td>
        <td class="fix"><span id="result_911_4111"></span></td>
      </tr>
    </tbody>
  </table>
  <input type="hidden" id="money_911_4111" value="<?php echo $lib->formatMoney($no_dauky['911']) ?>">
  <input type="hidden" id="money_4111_911" value="<?php echo $lib->formatMoney($co_dauky['911']) ?>">
</form>


<script type="text/javascript">
var month = "<?php echo (int)date('m',strtotime($ketthuc)) ?>";
var year = "<?php echo date('Y',strtotime($ketthuc)) ?>";

$('#sl_round option[value="'+month+'"]').attr('selected','selected');
$('#sl_trangthai option[value="'+year+'"]').attr('selected','selected');
$('#document_date').val("<?php echo date('Y-m-t',strtotime($ketthuc)) ?>");
$('#additional_date').val("<?php echo date('Y-m-t',strtotime($ketthuc)) ?>");

$("#add").validate({
  errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
  rules: {

  },
  submitHandler: function(form) {
    var document_date = $('#document_date').val();
    var additional_date = $('#additional_date').val();
    var document_number = $('#document_number').val();
    var comment_5111_911 = $('#comment_5111_911').val();
    var money_5111_911 = $('#money_5111_911').val();
    var comment_3331_911 = $('#comment_3331_911').val();
    var money_3331_911 = $('#money_3331_911').val();
    var comment_515_911 = $('#comment_515_911').val();
    var money_515_911 = $('#money_515_911').val();
    var comment_6321_911 = $('#comment_6321_911').val();
    var money_6321_911 = $('#money_6321_911').val();
    var comment_635_911 = $('#comment_635_911').val();
    var money_635_911 = $('#money_635_911').val();
    var comment_6411_911 = $('#comment_6411_911').val();
    var money_6411_911 = $('#money_6411_911').val();
    var comment_6412_911 = $('#comment_6412_911').val();
    var money_6412_911 = $('#money_6412_911').val();
    var comment_6413_911 = $('#comment_6413_911').val();
    var money_6413_911 = $('#money_6413_911').val();
    var comment_6414_911 = $('#comment_6414_911').val();
    var money_6414_911 = $('#money_6414_911').val();
    var comment_6418_911 = $('#comment_6418_911').val();
    var money_6418_911 = $('#money_6418_911').val();
    var comment_6421_911 = $('#comment_6421_911').val();
    var money_6421_911 = $('#money_6421_911').val();
    var comment_6422_911 = $('#comment_6422_911').val();
    var money_6422_911 = $('#money_6422_911').val();
    var comment_6423_911 = $('#comment_6423_911').val();
    var money_6423_911 = $('#money_6423_911').val();
    var comment_6425_911 = $('#comment_6425_911').val();
    var money_6425_911 = $('#money_6425_911').val();
    var comment_6426_911 = $('#comment_6426_911').val();
    var money_6426_911 = $('#money_6426_911').val();
    var comment_6427_911 = $('#comment_6427_911').val();
    var money_6427_911 = $('#money_6427_911').val();
    var comment_6428_911 = $('#comment_6428_911').val();
    var money_6428_911 = $('#money_6428_911').val();
    var comment_711_911 = $('#comment_711_911').val();
    var money_711_911 = $('#money_711_911').val();
    var comment_811_911 = $('#comment_811_911').val();
    var money_811_911 = $('#money_811_911').val();
    
    var comment_911_4111 = $('#comment_911_4111').val();
    var money_911_4111 = $('#money_911_4111').val();
    var money_4111_911 = $('#money_4111_911').val();

    $.ajax({
      url: '<?php echo BASE_URL ?>/forward/complete',
      type: 'POST',
      data: {
        document_date: document_date,
        additional_date: additional_date,
        document_number: document_number,
        comment_5111_911: comment_5111_911,
        money_5111_911: money_5111_911,
        comment_3331_911: comment_3331_911,
        money_3331_911: money_3331_911,
        comment_515_911: comment_515_911,
        money_515_911: money_515_911,
        comment_6321_911: comment_6321_911,
        money_6321_911: money_6321_911,
        comment_635_911: comment_635_911,
        money_635_911: money_635_911,
        comment_6411_911: comment_6411_911,
        money_6411_911: money_6411_911,
        comment_6412_911: comment_6412_911,
        money_6412_911: money_6412_911,
        comment_6413_911: comment_6413_911,
        money_6413_911: money_6413_911,
        comment_6414_911: comment_6414_911,
        money_6414_911: money_6414_911,
        comment_6418_911: comment_6418_911,
        money_6418_911: money_6418_911,
        comment_6421_911: comment_6421_911,
        money_6421_911: money_6421_911,
        comment_6422_911: comment_6422_911,
        money_6422_911: money_6422_911,
        comment_6423_911: comment_6423_911,
        money_6423_911: money_6423_911,
        comment_6425_911: comment_6425_911,
        money_6425_911: money_6425_911,
        comment_6426_911: comment_6426_911,
        money_6426_911: money_6426_911,
        comment_6427_911: comment_6427_911,
        money_6427_911: money_6427_911,
        comment_6428_911: comment_6428_911,
        money_6428_911: money_6428_911,
        comment_711_911: comment_711_911,
        money_711_911: money_711_911,
        comment_811_911: comment_811_911,
        money_811_911: money_811_911,
        comment_911_4111: comment_911_4111,
        money_911_4111: money_911_4111,
        money_4111_911: money_4111_911,
        acc_5111: "<?php echo $acc_5111 ?>",
        acc_3331: "<?php echo $acc_3331 ?>",
        acc_515: "<?php echo $acc_515 ?>",
        acc_6321: "<?php echo $acc_6321 ?>",
        acc_635: "<?php echo $acc_635 ?>",
        acc_6411: "<?php echo $acc_6411 ?>",
        acc_6412: "<?php echo $acc_6412 ?>",
        acc_6413: "<?php echo $acc_6413 ?>",
        acc_6414: "<?php echo $acc_6414 ?>",
        acc_6418: "<?php echo $acc_6418 ?>",
        acc_6421: "<?php echo $acc_6421 ?>",
        acc_6422: "<?php echo $acc_6422 ?>",
        acc_6423: "<?php echo $acc_6423 ?>",
        acc_6425: "<?php echo $acc_6425 ?>",
        acc_6426: "<?php echo $acc_6426 ?>",
        acc_6427: "<?php echo $acc_6427 ?>",
        acc_6428: "<?php echo $acc_6428 ?>",
        acc_711: "<?php echo $acc_711 ?>",
        acc_811: "<?php echo $acc_811 ?>",
        acc_911: "<?php echo $acc_911 ?>",
        acc_4111: "<?php echo $acc_4111 ?>",
      },
      success:function(answer){
        var data = JSON.parse(answer);
        $('#result_5111_911').html(data.result_5111_911);
        $('#result_3331_911').html(data.result_3331_911);
        $('#result_515_911').html(data.result_515_911);
        $('#result_6321_911').html(data.result_6321_911);
        $('#result_635_911').html(data.result_635_911);
        $('#result_6411_911').html(data.result_6411_911);
        $('#result_6412_911').html(data.result_6412_911);
        $('#result_6413_911').html(data.result_6413_911);
        $('#result_6414_911').html(data.result_6414_911);
        $('#result_6418_911').html(data.result_6418_911);
        $('#result_6421_911').html(data.result_6421_911);
        $('#result_6422_911').html(data.result_6422_911);
        $('#result_6423_911').html(data.result_6423_911);
        $('#result_6425_911').html(data.result_6425_911);
        $('#result_6426_911').html(data.result_6426_911);
        $('#result_6427_911').html(data.result_6427_911);
        $('#result_6428_911').html(data.result_6428_911);
        $('#result_711_911').html(data.result_711_911);
        $('#result_811_911').html(data.result_811_911);
        $('#result_911_4111').html(data.result_911_4111);
      }
    });
  }
});

$('.numbers').keyup(function(event) {
    // skip for arrow keys
  if(event.which >= 37 && event.which <= 40) return;
  // format number
  $(this).val(function(index, value) {
    return value
      .replace(/[^0-9-.]/g, "")
      .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
    ;
  });
});
$('.numbers').focus(function(){
    if ( $(this).val() == '0') {
       $(this).val(""); 
    };
    
});
$('.numbers').blur(function(){
    if ( $(this).val() == "") {
        $(this).val(0);
    };
    
});
$('#sl_round').change(function(){
      var m = $(this).val();
      var y = $('#sl_trangthai').val();
      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, m, 1).toISOString().slice(0,10);

      $('#document_date').val(lastDay );
      $('#additional_date').val(lastDay );

  });

  $('#sl_trangthai').change(function(){
      var y = $(this).val();
      var m = $('#sl_round').val();
      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, m, 1).toISOString().slice(0,10);

      $('#document_date').val(lastDay );
      $('#additional_date').val(lastDay );

  });

  $('#remove').click(function(){
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        var additional_date = $('#additional_date').val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/forward/delete',
            type: 'POST',
            data: {
              additional_date:additional_date,
              acc_5111: "<?php echo $acc_5111 ?>",
              acc_3331: "<?php echo $acc_3331 ?>",
              acc_515: "<?php echo $acc_515 ?>",
              acc_6321: "<?php echo $acc_6321 ?>",
              acc_635: "<?php echo $acc_635 ?>",
              acc_6411: "<?php echo $acc_6411 ?>",
              acc_6412: "<?php echo $acc_6412 ?>",
              acc_6413: "<?php echo $acc_6413 ?>",
              acc_6414: "<?php echo $acc_6414 ?>",
              acc_6418: "<?php echo $acc_6418 ?>",
              acc_6421: "<?php echo $acc_6421 ?>",
              acc_6422: "<?php echo $acc_6422 ?>",
              acc_6423: "<?php echo $acc_6423 ?>",
              acc_6425: "<?php echo $acc_6425 ?>",
              acc_6426: "<?php echo $acc_6426 ?>",
              acc_6427: "<?php echo $acc_6427 ?>",
              acc_6428: "<?php echo $acc_6428 ?>",
              acc_711: "<?php echo $acc_711 ?>",
              acc_811: "<?php echo $acc_811 ?>",
              acc_911: "<?php echo $acc_911 ?>",
              acc_4111: "<?php echo $acc_4111 ?>",
            },
            success:function(data){
              alert(data);
                window.location.reload();
            }
        });
      }
  });

$('#show').click(function(){
  var additional_date = $('#additional_date').val();
  $.ajax({
      url: '<?php echo BASE_URL ?>/forward/index',
      type: 'POST',
      data: {
        additional_date:additional_date,
      },
      success:function(answer){
        $('body').html(answer); // đặt kết quả trả về từ test.php vào thẻ div success
              

        //Enable sidebar toggle
          $(document).on('click', "[data-toggle='offcanvas']", function (e) {
            e.preventDefault();

            //Enable sidebar push menu
            if ($(window).width() > (768 - 1)) {
              if ($("body").hasClass('sidebar-collapse')) {
                $("body").removeClass('sidebar-collapse').trigger('expanded.pushMenu');
              } else {
                $("body").addClass('sidebar-collapse').trigger('collapsed.pushMenu');
              }
            }
            //Handle sidebar push menu for small screens
            else {
              if ($("body").hasClass('sidebar-open')) {
                $("body").removeClass('sidebar-open').removeClass('sidebar-collapse').trigger('collapsed.pushMenu');
              } else {
                $("body").addClass('sidebar-open').trigger('expanded.pushMenu');
              }
            }
          });
      }
  });
});

</script>