<div class="slide-content" id="cung-ung-dau">
			<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_native_toolbox"></div>
        <div class="item-page">

            <h2>Cung ứng dầu        </h2>


        <p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--> Chúng tôi là đại lý xăng dầu của Petrolimex, PVN, chuyên cung ứng cho tàu đi tuyến trong nước và quốc tế ở mọi hình thức cũng như tư vấn cho khách hàng phương thức thanh toàn phù hợp nhất.</p>
        <p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--> Nhận thức tầm quan trọng của tốc độ và thời gian trong thế giới tàu thuyền, phương châm của chúng tôi là tin tưởng và giao hàng nhanh chóng, tạo điều kiện cho tàu của quý vị có thể ra khơi càng sớm càng tốt</p> 
        </div>
    </div>

<script type="text/javascript">
    closeSidepage('#cung-ung-dau');
   openSidepage('#cung-ung-dau');
</script>