<div class="slide-content" id="giam-dinh-bao-hiem-tau">
			<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_native_toolbox"></div>
        <div class="item-page">

            <h2>Giám định - Bảo hiểm tàu        </h2>

            <p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Giám định thuê tàu/ Giám định trả
tàu là giám định tình trạng cấu trúc phương tiện vận tải biển, hàng hải giao
tàu cho người thuê tàu hoặc trả tàu cho chủ tàu. Báo cáo giám định bao gồm một
mô tả chi tiết không gian chở hàng của tàu/ khu vực trên boon, điều kiện cấu
trúc, không gian chứa hàng hóa sạch sẽ, tính toán số lượng nhiên liệu còn lại
trên tàu, chứng chỉ của tàu, an toàn thiết bị di động...<o:p></o:p></span><br></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Khi sự khác biệt phát sinh trong
hoạt đông giao trả nhiên liệu, đội ngũ giám định viên giàu kinh nghiệm của
chúng tôi có khả năng để tìm lỗi, nếu có, hoặc để đưa ra các con số phù hợp với
thỏa thuận bên thứ ba.<o:p></o:p></span><br></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Mục đích của giám định thuê tàu/
Giám định trả tàu là chủ yếu để xác định tình trạng hiện hữu của kết cấu phần
chuyên chở( như hầmm hàng) mức độ thiệt hại, hao mòn tực tế theo thời gian, có
thể đã xảy ra với tàu biển giữa hai lần giao hàng - trả tàu. Đó là:<o:p></o:p></span><br></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Việc kiểm tra
chứng từ tài liệu và chứng nhận của tàu.<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Giám định và
tính toán số lượng nhiên liệu còn lại của tàu<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Giám định
sạch sẽ của không gian hầm chứa hàng.<o:p></o:p></span></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Dịch vụ giám định này là một loại
hình tổng hợp dùng cho tất cả các loại đối tượng, sử dụng tất cả các phương
pháp giám định theo yêu cầu của các chủ tầu/đại lý, người chuyên chở, bảo hiểm,
các doanh nghiệp <o:p></o:p></span><br></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Ngoài những dịch vụ giám định
số/khối lượng, chất lượng, tình trạng/tổn thất, chúng tôi có thể phục vụ khách
hàng những dịch vụ đặc thù sau:<o:p></o:p></span><br></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Giám định
thuê /container /trả tầu (từng phần hoặc toàn phần).<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Giám định
tình trạng phương tiện/vật chứa trước khi xếp hàng về sạch sẽ, kín chắc,
máy/thiết bị, nhiệt độ…<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Giám sát
xếp/dỡ hàng vào/ra khỏi phương tiện /container về số lượng (nếu được yêu cầu
đếm hàng), tình trạng bao bì, tiến độ, nhiệt độ của phương tiện/vật chứa, của
vật được xếp.<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Tính hệ số
xếp hàng của hàng và của tàu<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Đo thể tích
hầm hàng/vật chứa làm cơ sở tính cước<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Lập sơ đồ hầm
hàng<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Giám định
nhiên liệu<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Giám định
trước và sau khi sửa chữa tầu/container<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Giám định
chằng buộc, giám định lai dắt<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Giám định về
rò rỉ khí độc<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Giám định
P&amp;I, PTI<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Niêm chì/phá
niêm chì hầm tầu/container<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Tư vấn/cung
cấp thông tin cho thuyền trường<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Điều tra,
theo dõi việc điều trị của thuyền viên tại các bệnh viện Việt Nam<o:p></o:p></span></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Việc kinh doanh khai thác tàu thủy
luôn phải đương đầu với rủi ro trên sông hồ và biển cả, nhưng bạn có thể yên
tâm vì chúng tôi luôn sẵn sàng tư vấn, phục vụ, luôn là người bạn đồng hành tin
cậy ở mọi lúc mọi nơi cho con tàu của bạn. &nbsp;Chúng tôi đáp ứng đầy đủ các
yêu cầu của khách hàng về bảo hiểm cho tàu thủy với các Quy tắc, điều khoản Bảo
hiểm theo tiêu chuẩn Quốc tế. Chúng tôi sẽ đem lại chất lượng dịch vụ tốt nhất
với những sản phẩm bảo hiểm tàu thủy đa dạng:<o:p></o:p></span><br></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Bảo hiểm thân
tàu định hạn - ITC1995<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Bảo hiểm thân
tàu định hạn - tổn thất toàn bộ ITC 1995<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Bảo hiểm thân
tàu chuyến - ITC 1995<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Bảo hiểm mọi
rủi ro nhà thầu đóng tàu<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Bảo hiểm thân
tàu sông, tàu ven biển<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Bảo hiểm TNDS
chủ tàu sông, tàu ven biển<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Bảo hiểm thân
tàu cá<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Bảo hiểm TNDS
chủ tàu cá<o:p></o:p></span></p><p>
</p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt 56.7pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">- Bảo hiểm tai
nạn thuyền viên<o:p></o:p></span></p>
        </div>
    </div>
<script type="text/javascript">
    closeSidepage('#giam-dinh-bao-hiem-tau');
   openSidepage('#giam-dinh-bao-hiem-tau');
</script>