<div class="slide-content" id="trinh-do-chuyen-mon">
			<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_native_toolbox"></div>
        <div class="item-page">

            <p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: justify; line-height: 27pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><b><span style="font-size:18.0pt;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;">TRÌNH ĐỘ CHUYÊN MÔN<o:p></o:p></span></b></p>



<p class="MsoListParagraphCxSpFirst" style="margin-bottom: 6.75pt; text-align: justify; text-indent: -0.25in; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;
font-family:Wingdings;mso-fareast-font-family:Wingdings;mso-bidi-font-family:
Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;
</span></span><!--[endif]--><span style="font-size:10.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;"> - Với phương châm nhân lực là tài sản
quý giá nhất của công ty, CMG luôn dành một sự quan tâm lớn nhất đến đội ngũ
nhân viên của mình.<o:p></o:p></span></p>



<p class="MsoListParagraphCxSpMiddle" style="margin-bottom: 6.75pt; text-align: justify; text-indent: -0.25in; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;
font-family:Wingdings;mso-fareast-font-family:Wingdings;mso-bidi-font-family:
Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;
</span></span><!--[endif]--><span style="font-size:10.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;"> - Hiện nay, Công ty CMG đang sở hữu
một đội ngũ nhân viên đông đảo với trình độ chuyên môn vững vàng, phần lớn nhân
viên của chúng tôi đã được hoặc đang được đào tạo bài bản về Logistics, Giao
Thông Vận Tải, Thương Mại Quốc Tế, Kinh Tế Quốc Tế, Ngoại Thương từ những trường
đại học hàng đầu Việt Nam và nước ngoài. Hàng năm chúng tôi còn tuyển chọn
những nhân viên xuất sắc để cử sang nước ngoài học tập.<o:p></o:p></span></p>



<p class="MsoListParagraphCxSpMiddle" style="margin-bottom: 6.75pt; text-align: justify; text-indent: -0.25in; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;
font-family:Wingdings;mso-fareast-font-family:Wingdings;mso-bidi-font-family:
Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;
</span></span><!--[endif]--><span style="font-size:10.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;"> - Nhân viên Công ty CMG là những con
người năng động sáng tạo, nhiệt tình trong công việc, có khả năng làm việc độc
lập cũng như làm việc nhóm rất hiệu quả. Nhân viên của chúng tôi luôn không
ngừng học tập, nâng cao hiểu biết, đóng góp sức mình vào sự phát triển lớn mạnh
của công ty.<o:p></o:p></span></p>



<p class="MsoListParagraphCxSpMiddle" style="margin-bottom: 6.75pt; text-align: justify; text-indent: -0.25in; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;
font-family:Wingdings;mso-fareast-font-family:Wingdings;mso-bidi-font-family:
Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;
</span></span><!--[endif]--><span style="font-size:10.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;"> - Tập thể nhân viên của Công ty CMG là
một tập thể đoàn kết, vững mạnh, gắn bó.<o:p></o:p></span></p>
<p><center><img src="public/images/gtcl.jpg" ></center></p>
         
    </div>

  </div>

<script type="text/javascript">
    closeSidepage('#trinh-do-chuyen-mon');
   openSidepage('#trinh-do-chuyen-mon');
</script>