<div class="slide-content" id="trang-thiet-bi">
      <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <div class="addthis_native_toolbox"></div>
      <div class="item-page">

        <p style="margin: 0in 0in 6.75pt; text-align: justify; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><b><span style="font-size:18.0pt;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:Calibri;mso-fareast-theme-font:
minor-latin">TRANG THIẾT BỊ<o:p></o:p></span></b></p>

<p style="margin: 0in 0in 6.75pt; text-align: justify; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:14.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
Calibri;mso-fareast-theme-font:minor-latin;color:red">&nbsp;</span></p>

<p style="margin: 0in 0in 6.75pt; text-align: justify; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:14.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
Calibri;mso-fareast-theme-font:minor-latin;color:red">Phương tiện vận chuyển<o:p></o:p></span></p>

<p style="margin: 0in 0in 0.0001pt 35.7pt; text-align: justify; text-indent: -17.85pt; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings;color:#333333">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
color:#333333">Để cung cấp dịch vụ vận tải “door to door” cho khách hàng của
mình, Công ty CMG sở hữu&nbsp;hàng trăm <b>phương
tiện vận tải ôtô các hạng từ 0,5 tấn đến những xe tải lớn, xe đầu
kéo container, xe chuyên dụng, xe lạnh dùng vận chuyển lon, chai nước
giải khát, thực phẩm, đồ uống, xe bồn, stec chở hóa chất… </b>đem
đến cho khách hàng dịch vụ vận tải với thời gian, chất lượng cao và
giá cả hợp lý.<o:p></o:p></span></p>
<p><center><img src="public/images/xe.jpg"></center></p>
<p style="margin: 0in 0in 0.0001pt 35.7pt; text-indent: -17.85pt; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;
line-height:150%;font-family:Wingdings;mso-fareast-font-family:Wingdings;
mso-bidi-font-family:Wingdings;color:#333333">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
color:#333333">Bên cạnh đó, Công ty CMG còn sở hữa các loại container khác nhau
như container 20”, 40”, container lạnh, container cho hàng quá khổ, quá tải,
v.v…<o:p></o:p></span></p>
<p><center><img src="public/images/containers.jpg"></center></p>
<p style="margin: 0in 0in 6.75pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:14.0pt;
font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:Calibri;mso-fareast-theme-font:
minor-latin;color:red">Hệ thống Kho, Bãi: <o:p></o:p></span></p>

<p style="margin: 0in 0in 0.0001pt 35.7pt; text-align: justify; text-indent: -17.85pt; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings;color:#333333">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
color:#333333">Dịch vụ Kho, Bãi, phân phối hàng hóa là một trong những mắt
xích quan trọng của chuỗi cung ứng logistics 3PL, 5PL,…<o:p></o:p></span></p>

<p style="margin: 0in 0in 0.0001pt 35.7pt; text-align: justify; text-indent: -17.85pt; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings;color:#333333">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
color:#333333">Hiện nay CMG đang khai thác, sử dụng hàng trăm ngàn mét vuông
Kho, Bãi hiện đại tại các trung tâm kinh tế miền Đông Nam Bộ, Đà Nẵng, Hải
Phòng. Phần mềm quản lý kho, các tiêu chuẩn kỹ thuật về an toàn, an
ninh, môi trường nghiêm ngặt, luôn làm hài lòng và đáp ứng mọi nhu
cầu của khách hàng tại các vùng, miền trong cả nước về Kho, Bãi và
phân phối.<o:p></o:p></span></p>
<p><center><img src="public/images/kho.jpg"></center></p>
<p style="margin: 0in 0in 6.75pt 0.5in; text-align: justify; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"> 
<p><table cellpadding="0" cellspacing="0" width="100%">
   <tbody><tr>
    <td><!--[endif]-->
    <div>
    <p class="MsoNormal" align="center" style="text-align:center"><i><span style="font-size:10.0pt;
    line-height:107%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Kho đạt tiêu chuẩn về vệ
    sinh và an toàn<o:p></o:p></span></i></p>
    </div>
    <!--[if !mso]--></td>
   </tr>
  </tbody></table>
  <!--[endif]-->
 <w:wrap type="square" anchorx="margin">
<span style="font-size:10.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
color:#333333"><o:p></o:p></span><p></p>

<p style="margin: 0in 0in 6.75pt 0.5in; text-align: justify; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;color:#333333"><o:p>&nbsp;</o:p></span></p>

<p style="margin: 0in 0in 0.0001pt 35.7pt; text-align: justify; text-indent: -17.85pt; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings;color:#333333">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
color:#333333">Sử dụng dịch vụ kho, bãi,&nbsp; khách hàng luôn yên tâm và tin
tưởng vì Công ty CMG quản lý hàng hóa khoa học, hợp lý, an toàn, tối ưu
hóa diện tích sử dụng, thuận tiện trong giám sát, kiểm đếm xuất nhập hàng hóa
nhờ hệ thống giá kệ nhiều tầng hiện đại, phần mềm quản lý kho cho phép quản lý
từng ký mã hiệu hàng hóa, thông số xuất- nhập- tồn kho, vị trí hàng hóa. Các
thiết bị xe nâng hạ hiện đại giúp việc luân chuyển hàng hóa, xuất nhập kho được
thuận tiện và nhanh chóng. Ngoài ra, tại các kho, bãi của CMG, khách hàng
còn được đáp ứng có yêu cầu dịch vụ đóng gói, chia hàng, dịch vụ
tiếp nhận đơn đặt hàng theo các chuẩn mực cao của CMG hoặc các yêu cầu của
khách hàng.<o:p></o:p></span></p>
<p><center><img src="public/images/bai.jpg"></center></p>
<p style="margin: 0in 0in 0.0001pt 35.7pt; text-align: justify; text-indent: -17.85pt; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings;color:#333333">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
color:#333333">Ngoài ra, Công ty CMG còn điều hành một đội ngũ lái xe kinh
nghiệm, nhân viên kỹ thuật sửa chữa phương tiện có tay nghề cao, đội sà lan và
thuyền viên chuyên nghiệp. Cùng với việc tiếp tục đầu tư phương tiện, nâng cao
năng lực vận tải, áp dụng các phần mềm quản lý, hệ thống định vị GPS trên toàn
bộ các phương tiện, Công ty CMG đã và đang thực sự trở thành một trong những
thương hiệu mạnh của ngành vận tải biển nội địa Việt Nam.<o:p></o:p></span></p>


       </div>
    </div>

<script type="text/javascript">
    closeSidepage('#trang-thiet-bi');
   openSidepage('#trang-thiet-bi');
</script>