<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>/public/css/jquery.cslider.css" />
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>/public/css/jquery.bxslider.css" />
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>/public/css/animate.css" />
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>/public/css/style2.css" />

<!-- Start home section -->
        <div id="home">
            <!-- Start cSlider -->
            <div id="da-slider" class="da-slider">
                <div class="triangle"></div>
                <!-- mask elemet use for masking background image -->
                <div class="mask"></div>
                <!-- All slides centred in container element -->
                <div class="container">
                    <!-- Start first slide -->
                    <div class="da-slide">
                        <h2 class="fittext2">Dịch vụ Giao nhận và Vận chuyển</h2>
                        <h4>Logistics</h4>
                        <p>Chúng tôi luôn tự hào về cung cấp dịch vụ vận tải đa phương thức là 1 trong những điểm mạnh. Nhờ mạng lưới tổ chức tốt chúng tôi có thể thực hiện được các dịch vụ sau: <br>
                        -       Giao nhận hàng hóa <br>
                        -       Dịch vụ vận chuyển nội địa và quốc tế <br>
                        -       Dịch vụ vận chuyển đa phương thức <br>
                        -       Dịch vụ vận chuyển hàng hóa bằng đường bộ/ đường biển/ đường hàng không/ đường sắt <br>
                        -       Dịch vụ vận tải hàng hóa <br>

                        <br>
                        Chúng tôi cam kết cung cấp dịch vụ giao nhận vận chuyển đa dạng với chất lượng tốt nhất. Với 1 hệ thống đại lý mạnh và rộng khắp, các loại dịch vụ của chúng tôi không ngừng phát triển và cải tiến.
                         </p>
                        <a href="<?php echo $this->url('van-tai-duong-bo') ?>" class="da-link button">Chi tiết</a>
                        <div class="da-img">
                            <img src="<?php echo BASE_URL ?>/public/images/container.png" alt="image01" >
                        </div>
                    </div>
                    <!-- End first slide -->
                    <!-- Start second slide -->
                    <div class="da-slide">
                        <h2>Đại lý tàu</h2>
                        <h4>Boarding Agent</h4>
                        <p>Công ty CMG tự hào với mạng lưới chi nhánh cung cấp dịch vụ đại lý trải khắp các cảng lớn  trong nước từ Hải Phòng, Đà Nẵng, đến Qui Nhơn và Hồ Chí Minh. <br><br>

                            Dịch vụ đại lý của chúng tôi bao gồm: <br>
                            - Đại lý xếp, dỡ hàng. <br>
                            - Đại lý độc quyền cho các tàu chạy chuyên tuyến. <br>
                            - Hoàn tất thủ tục nhập, xuất cho tàu (với Cảng vụ, Hải Quan, Biên Phòng, Kiểm dịch…) <br>
                            - Cung cấp dầu, nước ngọt. <br>
                            - Xếp dỡ và chuyển tải hàng hoá tại tất cả các cảng. <br>
                            - Lên đà, sửa chữa và dịch vụ kèm theo  <br>
                            - Cung cấp nhu yếu phẩm cho tàu. <br>

                        </p>
                        <a href="<?php echo $this->url('dai-ly-tau') ?>" class="da-link button">Chi tiết</a>
                        <div class="da-img">
                            <img src="<?php echo BASE_URL ?>/public/images/shipping.png" alt="image02" >
                        </div>
                    </div>
                    <!-- End second slide -->
                    <!-- Start third slide -->
                    <div class="da-slide">
                        <h2>Dịch vụ mua bán, cho thuê và sửa chữa container</h2>
                        <h4>Container</h4>
                        <p>
                        -  Với nhiều năm kinh nghiệm trong lĩnh vực mua bán và cho thuê container, công ty chúng tôi cung cấp đủ các chủng loại container cho thị trường và đặc biệt chúng tôi còn sản xuất và cung cấp loại conatiner văn phòng. <br>

                        -  Ngoài ra công ty còn sản xuất các loại container theo yêu cầu, thiết kế của khách hàng như kích thước mẫu mã container riêng biệt, container có gắn thêm thiết bị chuyên dụng… <br>

                        -  Đáp ứng nhu cầu thị trường hiện nay, công ty linh hoạt cho thuê container với nhiều hình thức như cho thuê dài hạn, cho thuê ngắn hạn, cho thuê theo chuyến… <br><br>
                        CMG luôn tư vấn cho khách hàng những phương án tối ưu nhất với giá cả cạnh tranh nhất. 
                        </p>
                        <a href="<?php echo $this->url('mua-ban-cho-thue-container') ?>" class="da-link button">Chi tiết</a>
                        <div class="da-img">
                            <img src="<?php echo BASE_URL ?>/public/images/cont.png" alt="image03" >
                        </div>
                    </div>
                    <!-- Start third slide -->
                    <div class="da-slide">
                        <h2>Dịch vụ kho bãi</h2>
                        <h4>Warehouse</h4>
                        <p>
                        -  Kho bãi của chúng tôi cung cấp cho khách hàng khả năng tiếp cận nhanh chóng đến tất cả các cảng và nhà máy. Chúng tôi cung cấp dịch vụ thuê kho cho tất cả các loại hàng hóa thông thường. Các dịch vụ hỗ trợ hiện có như: đóng gói, dán nhãn, đóng kiện và kiểm đếm hàng hóa … <br><br>

                        -  Cung cấp dịch vụ kho bãi và đóng hàng xuất nhập theo yêu cầu của tất cả các khách hàng trong và ngoài nước. Dịch vụ của chúng tôi gồm sắp xếp và đóng rút hàng vào ra cho các loại Container, kể cả Container khung và Container phẳng. Đảm bảo an toàn cho hàng hoá với nhiều chủng loại khác nhau <br><br>

                        -  Depot và dịch vụ depot <br>
                        </p>
                        <a href="<?php echo $this->url('luu-kho-va-bao-quan-hang-hoa') ?>" class="da-link button">Chi tiết</a>
                        <div class="da-img">
                            <img src="<?php echo BASE_URL ?>/public/images/warehouse.png" alt="image04" >
                        </div>
                    </div>
                    <!-- Start third slide -->
                    <!-- Start third slide -->
                    <div class="da-slide">
                        <h2>Xuất nhập khẩu</h2>
                        <h4>Import - Export</h4>
                        <p>
                            CMG chuyên xuất nhập khẩu các loại mặt hàng: sắn lát, ớt bột, bột nhang, viên nén mùn cưa, hạt cà phê, trà xanh.. <br>
                        -  Sắn lát <br>
                        &nbsp;&nbsp;&nbsp;&nbsp;TAPIOCA CHIPS/POWDER International export <br>
                        -  Ớt bột <br>
                        &nbsp;&nbsp;&nbsp;&nbsp;CHILI POWDER International export <br>

                        -  Bột nhang <br>
                        &nbsp;&nbsp;&nbsp;&nbsp;INCENSE POWDER International export <br>
                        -  Đường <br>
                        &nbsp;&nbsp;&nbsp;&nbsp;WHITE SUGAR <br>

                        -  Viên nén mùn cưa <br>
                        &nbsp;&nbsp;&nbsp;&nbsp;WOOD PELLETS <br>
                        </p>
                        <a href="<?php echo $this->url('tapioca-chips') ?>" class="da-link button">Chi tiết</a>
                        <div class="da-img">
                            <img src="<?php echo BASE_URL ?>/public/images/global.png" alt="image04" >
                        </div>
                    </div>
                    <!-- Start third slide -->
                    <!-- Start cSlide navigation arrows -->
                    <div class="da-arrows">
                        <span class="da-arrows-prev"></span>
                        <span class="da-arrows-next"></span>
                    </div>
                    <!-- End cSlide navigation arrows -->
                </div>
            </div>
        </div>
        <!-- End home section -->
        <!-- Service section start -->
        <div class="section primary-section" id="service">
            <div class="container">
                <!-- Start title section -->
                <div class="title">
                    <h1>Hãy đến với dịch vụ của chúng tôi !</h1>
                    <!-- Section's title goes here -->
                    <p>CMG cam kết mang đến Quý khách hàng chất lượng dịch vụ uy tín và ổn định cũng như những giải pháp, tư vấn tối ưu cho các Doanh nghiệp trong và ngoài nước nhằm tiết kiệm chi phí tới mức tối thiểu nhưng vẫn đạt hiệu quả tối đa</p>
                    <!--Simple description for section goes here. -->
                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle" src="<?php echo BASE_URL ?>/public/images/fast.png" alt="service 1">
                            </div>
                            <h3>Nhanh chóng</h3>
                            <p>Với đội ngũ nhân viên chuyên nghiệp cùng cơ sở vật chất hiện đại, chúng tôi luôn mang đến những dịch vụ tốt nhất.</p>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle" src="<?php echo BASE_URL ?>/public/images/safety.png" alt="service 2" />
                            </div>
                            <h3>An toàn</h3>
                            <p>Chất lượng dịch vụ là yếu tố quan trọng trong phương châm hoạt động của chúng tôi.</p>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle" src="<?php echo BASE_URL ?>/public/images/save.png" alt="service 3">
                            </div>
                            <h3>Tiết kiệm</h3>
                            <p>Luôn mang tới khách hàng những dịch vụ với giá cả rẻ nhất.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Service section end -->
        

<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/jquery.mixitup.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/bootstrap.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/modernizr.custom.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/jquery.bxslider.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/jquery.cslider.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/jquery.placeholder.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/jquery.inview.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/app.js"></script>