
<?php
$url_order = 'ASC';
if ($order_by == 'customer_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'expect_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'money')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'week')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'staff')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bank_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'vendor')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> CÔNG NỢ KHÁCH HÀNG </h1></center>

	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        
    </div>
    <div class="add-box">
    
        Đến ngày <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >   
         <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');"> 
                                
    </div>
    <div class="tablenav top">
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="20">Hiển thị 20 giá trị</option>
            <option value="30">Hiển thị 30 giá trị</option>
            <option value="50">Hiển thị 50 giá trị</option>
            <option value="100">Hiển thị 100 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

        <div class="add-box">
            <a class="add_button" id="btnExport" >Export Excel</a>
        </div>


      </div>

</div>

<table id="tblExport" class="table_data">
<thead>
    <tr>
    	<th  class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'customer_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>

        <th class="fix" >
            <a >Tổng cộng </a>
        </th>   
          
        <th class="fix" >
            <a >Đã thu </a>
        </th>
        <th  class="fix" >Còn lại</th> 
         
    
   </thead>
   <tbody>
    <?php $tong = 0; $tongthu= 0; $tongcon = 0; ?>
    <?php foreach ($customers as $customer) : ?>
    <?php $tong += isset($obtain_data['total'][$customer->customer_id])?$obtain_data['total'][$customer->customer_id]:0; ?>
    <?php $tongthu += isset($obtain_data['down'][$customer->customer_id])?str_replace('-', "", $obtain_data['down'][$customer->customer_id]):0; ?>
    <?php $tongcon += (isset($obtain_data['total'][$customer->customer_id])?$obtain_data['total'][$customer->customer_id]:0-(isset($obtain_data['down'][$customer->customer_id])?$obtain_data['down'][$customer->customer_id]:0)); ?>
    
    
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $customer->customer_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $customer->customer_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="customer_<?php echo $customer->customer_id; ?>"><a href="<?php echo $this->url('customer/index/'.$customer->customer_id) ?>" ><?php echo $customer->customer_name; ?> &rarr;</a></td>
            <td class="fix" id="total_<?php echo $customer->customer_id; ?>"><?php echo $lib->formatMoney(isset($obtain_data['total'][$customer->customer_id])?$obtain_data['total'][$customer->customer_id]:0); ?></td>
            <td class="fix"  id="down_<?php echo $customer->customer_id; ?>"><?php echo $lib->formatMoney(isset($obtain_data['down'][$customer->customer_id])?str_replace('-', "", $obtain_data['down'][$customer->customer_id]):0) ?></td>
            <td class="fix" id="conlai_<?php echo $customer->customer_id; ?>"><?php echo $lib->formatMoney((isset($obtain_data['total'][$customer->customer_id])?$obtain_data['total'][$customer->customer_id]:0)-(isset($obtain_data['down'][$customer->customer_id])?str_replace('-', "", $obtain_data['down'][$customer->customer_id]):0)); ?></td>
            
            
        </tr>
        
    <?php endforeach; ?>
    <tr style="text-align:center; font-weight: bold; color: red;">
        <td class="fix" colspan="3" >Tổng cộng</td>
        <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
        <td class="fix"><?php echo $lib->formatMoney($tongthu); ?></td>
        <td class="fix"><?php echo $lib->formatMoney($tong-$tongthu); ?></td>
    </tr>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('cusdebts') ?>">&larr;</a></div>

<script type="text/javascript">
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');

var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $("#batdau").datepicker(pickerOpay2);
</script>