<style type="text/css">
    .ui-datepicker-calendar {
        display: none;
    }​
</style>
<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        changeMonth: true,
        changeYear: true,
        dateFormat: 'MM yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function() {
                $("#chonngaytao").change();
         },
         
    };  
    $("#chonngaytao").datepicker(pickerOpts);
              
            
    $("#chonngaytao").change(function(){
        var month = parseInt($("#ui-datepicker-div .ui-datepicker-month :selected").val());
        var year = parseInt($("#ui-datepicker-div .ui-datepicker-year :selected").val());
        if (month<9) {
            var ngay = "0"+(month+1)+"-"+year;
        }
        else
            var ngay = (month+1)+"-"+year;

        var page = "<?php echo $page; ?>";
        var cot = "<?php echo $order_by; ?>";
        var sapxep = "<?php echo $order; ?>";
        var keyword = "<?php echo $keyword; ?>";
        var loc =    $('#chonloc').val();
          if($('#sl_status') != null)
          {
            var trangthai = $('#sl_status').val();
          }
          if($('#sl_nv') != null)
          {
            var nv = $('#sl_nv').val();
          }
          if($('#sl_tha') != null)
          {
            var tha = $('#sl_tha').val();
          }
          if($('#sl_na') != null)
          {
            var na = $('#sl_na').val();
          }
          if($('#tu') != null)
          {
            var tu = $('#tu').val();
          }
          if($('#den') != null)
          {
            var den = $('#den').val();
          }
        
        
        var dataString = 'keyword='+ keyword+"&limit="+loc+"&ngaytao="+ngay+"&page="+ page +"&order_by="+ cot +"&order="+ sapxep+"&trangthai="+ trangthai+"&nv="+nv+"&tha="+tha+"&na="+na+"&tu="+tu+"&den="+den;  
        
        $('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
        
            $.ajax({
                type: "POST",                            // Phương thức gọi là GET
                url: "#",                 // File xử lý
                data: dataString,                       // Dữ liệu truyền vào
                beforeSend:  function() {               // add class "loading" cho khung nhập
                    $('input#search-input').addClass('loading');
                },
                success: function(server_response)      // Khi xử lý thành công sẽ chạy hàm này
                {
                    $('body').html(server_response);    // Hiển thị dữ liệu vào thẻ div #searchresultdata
                    
                     
                    if ($('input#search-input').hasClass("loading")) {      // Kiểm tra class "loading"
                        $("input#search-input").removeClass("loading");     // Remove class "loading"
                    }
                    $('#loading').fadeOut(500); 
                }
            });
        
        
    });
});
</script>
<?php
$url_order = 'ASC';
if ($order_by == 'staff_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'staff_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> CHI PHÍ NHÂN SỰ </h1></center>
<div class="add-box">
    <a class="add_button" id="btnExport" href="#">Export Excel</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
        <div class="add-box">
            THÁNG
        	<input type="search" name="chonngaytao" id="chonngaytao" placeholder="Chọn ngày" <?php if(isset($thang)) echo 'value="'.date('m-Y',$thang).'"'; else if(isset($ngaytao)) echo "value='$ngaytao'"; ?>>  
                                        
        </div>
        
      </div>


</div>

<?php if( $_SESSION['role_logined'] == 1 || $_SESSION['role_logined'] == 9){ ?>
<div class="add-box">
    <a class="add_button approve" data="<?php echo '01-'.$ngaytao ?>" >Duyệt</a>
</div>
<?php } ?>

<table class="table_data" id="tblExport">
<thead>
    <tr style="display:none">
        <th colspan="17"><center>BẢNG LƯƠNG THÁNG <?php echo isset($thang)?date('m/Y',$thang):(isset($ngaytao)?$ngaytao:"") ?></center></th>
    </tr>
    <tr style="display:none">
        <th colspan="17"></th>
    </tr>
    <tr>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','staff_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'staff_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','staff_name','<?php echo $url_order ?>')">Họ và tên <?php if ($order_by == 'staff_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','position','<?php echo $url_order ?>')">Chức vụ <?php if ($order_by == 'position'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">Lương <br> chức vụ</th>
        <th rowspan="2" class="fix">Lương <br> doanh thu</th>
        <th rowspan="2" class="fix">Lương <br> lợi nhuận</th>
        <th rowspan="2" class="fix">Xăng xe <br> công tác</th>
        <th rowspan="2" class="fix">Phụ cấp ĐT</th>
        <th rowspan="2" class="fix">Phụ cấp <br> cơm</th>
        <th rowspan="2" class="fix">Bảo hiểm</th>
        <th rowspan="2" class="fix">Trừ BH + Cơm</th>
        <th rowspan="2" class="fix">Cộng lương</th>
        <th colspan="4" class="fix">Hệ số</th>
        <th rowspan="2" class="fix">Thực lĩnh</th>
            
    </tr>
    <tr>
        <th class="fix">Đánh giá</th>
        <th class="fix">Hiệu quả</th>
        <th class="fix">Thời gian</th>
        <th class="fix">Kỷ luật</th>
    </tr>
   </thead>
   <tbody>
    <?php 
    $tongchucvu=0; $tongphone=0; $tongngoaikhoa=0; $tongcom=0; $tongbh=0; $tongbhnv=0; $tongdoanhthu=0; $tongloinhuan=0; $tongluong=0; $tongthuclinh=0;
    foreach ($staffs as $salary) : ?>
    <?php

        $chucvu = isset($arr_position_salary[$salary->staff_id])?$arr_position_salary[$salary->staff_id]:0;
        $tongchucvu += $chucvu;

        $phone = isset($arr_phone[$salary->staff_id])?$arr_phone[$salary->staff_id]:0;
        $tongphone += $phone;

        $ngoaikhoa = isset($arr_curricular[$salary->staff_id])?$arr_curricular[$salary->staff_id]:0;
        $tongngoaikhoa += $ngoaikhoa;

        $com = isset($arr_eating_allowance[$salary->staff_id])?$arr_eating_allowance[$salary->staff_id]:0;
        $tongcom += $com;

        $tienbh = isset($arr_insurrance[$salary->staff_id]['congty'])?$arr_insurrance[$salary->staff_id]['congty']:0;
        $tienbhnv = isset($arr_insurrance[$salary->staff_id]['nhanvien'])?$arr_insurrance[$salary->staff_id]['nhanvien']:0;
        $tongbh += $tienbh; 
        $tongbhnv += $tienbhnv;

        $doanhthu = isset($luong_doanhthu[$salary->staff_id])?$luong_doanhthu[$salary->staff_id]:0;
        $tongdoanhthu += $doanhthu;

        $loinhuan = isset($luong_loinhuan[$salary->staff_id])?$luong_loinhuan[$salary->staff_id]:0;
        $tongloinhuan += $loinhuan;

        $congluong = $chucvu+$phone+$ngoaikhoa+$com-$tienbhnv+$doanhthu+$loinhuan;
        $tongluong += $congluong;

        $heso_thoigian = isset($arr_attend[$salary->staff_id])?round($arr_attend[$salary->staff_id]/24,2):"";

        $heso_danhgia = isset($position_evaluate[$salary->staff_id])?round((100+$position_evaluate[$salary->staff_id])/100,2):"";

        $heso_hieuqua = isset($position_work[$salary->staff_id])?round((100+$position_work[$salary->staff_id])/100,2):"";

        $heso_kyluat = isset($position_rule[$salary->staff_id])?round((100-$position_rule[$salary->staff_id])/100,2):"";

        $thuclinh = $congluong*$heso_thoigian*$heso_danhgia*$heso_hieuqua*$heso_kyluat;
        if ($heso_thoigian=="" && $heso_danhgia=="" && $heso_hieuqua=="" && $heso_kyluat=="") {
            $thuclinh = $congluong;
        }
        $tongthuclinh += $thuclinh;
    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $salary->staff_id ?>"  class="edit_tr">
        	
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="staff_name_<?php echo $salary->staff_id; ?>"><?php echo $salary->staff_name; ?></td>
            <td class="fix" id="position_<?php echo $salary->staff_id; ?>"><?php echo $salary->position; ?></td>
            <td class="fix"><?php echo $lib->formatMoney($chucvu) ?></td>
            <td class="fix"><a href="<?php echo $this->url('positionsalaryview/revenue/'.$salary->staff_id.'/'.strtotime('01-'.$ngaytao)) ?>" ><?php echo $lib->formatMoney($doanhthu) ?></a></td>
            <td class="fix"><a href="<?php echo $this->url('positionsalaryview/profit/'.$salary->staff_id.'/'.strtotime('01-'.$ngaytao)) ?>" ><?php echo $lib->formatMoney($loinhuan) ?></a></td>
            <td class="fix editable" data="<?php echo $salary->staff_id; ?>" id="ngoaikhoa_<?php echo $salary->staff_id; ?>"><?php echo $lib->formatMoney($ngoaikhoa) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($phone) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($com) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tienbh) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tienbhnv) ?></td>
            <td class="fix"><b><?php echo $lib->formatMoney($congluong) ?></b></td>
            <td class="fix"><a href="<?php echo $this->url('positionstaffevaluate/index/-1/'.$salary->staff_id.'/'.strtotime('01-'.$ngaytao)) ?>" ><?php echo $lib->formatMoney($heso_danhgia) ?></a></td>
            <td class="fix"><a href="<?php echo $this->url('positionstaffwork/index/-1/'.$salary->staff_id.'/'.strtotime('01-'.$ngaytao)) ?>" ><?php echo $lib->formatMoney($heso_hieuqua) ?></a></td>
            <td class="fix"><a href="attendance/index/<?php echo strtotime('01-'.$ngaytao).'/'.$salary->staff_id ?>"><?php echo $lib->formatMoney($heso_thoigian) ?></a></td>
            <td class="fix"><a href="<?php echo $this->url('positionruleapply/index/-1/'.$salary->staff_id.'/'.strtotime('01-'.$ngaytao)) ?>" ><?php echo $lib->formatMoney($heso_kyluat) ?></a></td>
            <td class="fix"><b><?php echo $lib->formatMoney($thuclinh) ?></b></td>
            
        </tr>
        <?php 
        ?>
    <?php endforeach; ?>
   </tbody>
   <tfoot>
       <tr style="font-weight:bold"> 
           <td colspan="3">Tổng cộng</td>
           <td class="fix"><?php echo $lib->formatMoney($tongchucvu) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongdoanhthu) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongloinhuan) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongngoaikhoa) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongphone) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongcom) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongbh) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongbhnv) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongluong) ?></td>
            <td class="fix"></td>
            <td class="fix"></td>
            <td class="fix"></td>
            <td class="fix"></td>
            <td class="fix"><?php echo $lib->formatMoney($tongthuclinh) ?></td>
       </tr>
       
   </tfoot>
</table>
<?php
$this->helper('slidePaginator');
?>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<script type="text/javascript">

$(".table_data a").click(function(){
    $("#winpopup").dialog({
        draggable:true,
        modal: true,
        autoOpen: false,
        maxHeight:500,
        width:"80%",
        resizable: false,
        title:'Chi tiết',
        position: ['center',20],
        
    });
    $("#winpopup").load($(this).attr('href'));
    $("#winpopup").dialog("open");
     
    return false;
});

$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Bảng lương",
    hide: 'fold',
    show: 'blind'
});

$('.approve').click(function(){
    var id = $(this).attr("data");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/positionsalaryview/approveall", {data: id},
           function(data){
            

            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});

$('.editButton').click(function(){
    var id = $(this).attr("data");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/newsalary/approve", {data: id},
           function(data){

            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});

$('.number').keyup(function(){
    // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
});


$('.editable').dblclick(function(e){  
        var i=0;
        var id=$(this).attr('id');
        e.stopPropagation();      //<-------stop the bubbling of the event here
        var value = $('#'+id).html();
        var data=$(this).attr('data');

        updateVal('#'+id, value, data);
        
    });
    function updateVal(currentEle, value, id) {
        var id = id;
        $(currentEle).html('<input class="thVal" style="width:50px"  type="text" value="'+value+'" />');
        $(".thVal").focus();
        $(".thVal").keyup(function (event) {
            if (event.keyCode == 13) {
                var keyword = $(".thVal").val().trim();
                var thang = $('#chonngaytao').val();
                $.ajax({
                    url: '<?php echo BASE_URL ?>/totalsalary/ngoaikhoa',
                    type: 'POST',
                    data: {data:id,keyword:keyword,thang:thang},
                    success:function(data){
                        $(currentEle).html(keyword);
                        setTimeout(function() {
                                        searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 100);
                    }
                });

            }
        });
        
        $(".thVal").focusout(function () { // you can use $('html')
            var keyword = $(".thVal").val().trim();
            var thang = $('#chonngaytao').val();
                $.ajax({
                    url: '<?php echo BASE_URL ?>/totalsalary/ngoaikhoa',
                    type: 'POST',
                    data: {data:id,keyword:keyword,thang:thang},
                    success:function(data){
                        $(currentEle).html(keyword);
                        setTimeout(function() {
                                        searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 100);
                    }
                });
        });
    }

$('.editable2').dblclick(function(e){  
        var i=0;
        var id=$(this).attr('id');
        e.stopPropagation();      //<-------stop the bubbling of the event here
        var value = $('#'+id).html();
        var data=$(this).attr('data');

        updateVal2('#'+id, value, data);
        
    });
    function updateVal2(currentEle, value, id) {
        var id = id;
        $(currentEle).html('<input class="thVal2" style="width:50px"  type="text" value="'+value+'" />');
        $(".thVal2").focus();
        $(".thVal2").keyup(function (event) {
            if (event.keyCode == 13) {
                var keyword = $(".thVal2").val().trim();
                var thang = $('#chonngaytao').val();
                $.ajax({
                    url: '<?php echo BASE_URL ?>/totalsalary/chucvu',
                    type: 'POST',
                    data: {data:id,keyword:keyword,thang:thang},
                    success:function(data){
                        $(currentEle).html(keyword);
                        setTimeout(function() {
                                        searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 100);
                    }
                });

            }
        });
        
        $(".thVal2").focusout(function () { // you can use $('html')
            var keyword = $(".thVal2").val().trim();
            var thang = $('#chonngaytao').val();
                $.ajax({
                    url: '<?php echo BASE_URL ?>/totalsalary/chucvu',
                    type: 'POST',
                    data: {data:id,keyword:keyword,thang:thang},
                    success:function(data){
                        $(currentEle).html(keyword);
                        setTimeout(function() {
                                        searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 100);
                    }
                });
        });
    }

/*$('.editable3').dblclick(function(e){  
        var i=0;
        var id=$(this).attr('id');
        e.stopPropagation();      //<-------stop the bubbling of the event here
        var value = $('#'+id).html();
        var data=$(this).attr('data');

        updateVal3('#'+id, value, data);
        
    });
    function updateVal3(currentEle, value, id) {
        var id = id;
        $(currentEle).html('<input class="thVal3" style="width:50px" type="text" value="'+value+'" />');
        $(".thVal3").focus();
        $(".thVal3").keyup(function (event) {
            if (event.keyCode == 13) {
                var keyword = $(".thVal3").val().trim();
                var thang = $('#chonngaytao').val();
                $.ajax({
                    url: '<?php echo BASE_URL ?>/totalsalary/baohiem',
                    type: 'POST',
                    data: {data:id,keyword:keyword,thang:thang},
                    success:function(data){
                        $(currentEle).html(keyword);
                    }
                });

            }
        });
        
        $(".thVal3").focusout(function () { // you can use $('html')
            var keyword = $(".thVal3").val().trim();
            var thang = $('#chonngaytao').val();
                $.ajax({
                    url: '<?php echo BASE_URL ?>/totalsalary/baohiem',
                    type: 'POST',
                    data: {data:id,keyword:keyword,thang:thang},
                    success:function(data){
                        $(currentEle).html(keyword);
                    }
                });
        });
    }*/
</script>