<?php $l=1 ; $tong=0; ?>
<table class="table_data" id="or">
<thead>
    <tr>
        <th class="fix">
            <a class="sort">STT</a>
        </th>
        <th  class="fix">
            <a class="sort " >Thương hiệu </a>
        </th>
        <th  class="fix">
            <a class="sort " >Kích cỡ </a>
        </th>
        <th  class="fix">
            <a class="sort " >Mã gai </a>
        </th>
        <th  class="fix">
            <a class="sort " >Số lượng </a>
        </th>
        <th  class="fix">
            <a class="sort " >Giá </a>
        </th>
           
        <th  class="fix">&nbsp;</th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($tire_desireds as $tire_desired) : 
        $tong += $tire_desired->tire_number;
    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $tire_desired->tire_desired_id ?>" class="edit_tr" >
            <td class="fix"><?php echo $l++; ?></td>
            <td class="fix" data="<?php echo $tire_desired->tire_brand_code; ?>"  id="tire_brand_<?php echo $tire_desired->tire_desired_id; ?>"><?php echo $tire_desired->tire_brand_name; ?></td>
            <td class="fix" data="<?php echo $tire_desired->tire_size; ?>" id="tire_size_<?php echo $tire_desired->tire_desired_id; ?>"><?php echo $tire_desired->tire_size_number; ?></td>
            <td class="fix" data="<?php echo $tire_desired->tire_pattern_code; ?>" id="tire_pattern_code_<?php echo $tire_desired->tire_desired_id; ?>">
                <?php echo $tire_desired->tire_pattern_name; ?>
            </td>
            <td class="fix"  id="tire_number_<?php echo $tire_desired->tire_desired_id; ?>"><?php echo $tire_desired->tire_number; ?></td>
            <td class="fix"  id="tire_price_<?php echo $tire_desired->tire_desired_id; ?>"><?php echo $lib->formatMoney($tire_desired->tire_price); ?></td>
            <td>
                <button class="del" data="<?php echo $tire_desired->tire_desired_id ?>" style="display:block">Xóa</button>
            </td>
        </tr>
    <?php endforeach; ?>
    <tr style="text-align:center; font-weight: bold; color: red;">
        <td class="fix" colspan="4" >Tổng cộng</td>
        <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
        <td class="fix" ></td>
    </tr>
   </tbody>
</table>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Thông tin đặt hàng </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_customer" method="post" action="">
                      <table style="margin:0 auto;width:100%">
                        <tr>
                            <td>
                              <span class="add-on"><i class="icon-company" ></i></span>
                              <span>Thương hiệu: </span>
                            </td>
                            <td><input type="text" id="tire_brand" name="tire_brand" value="" disabled required="required" /></td>
                          </tr>
                          <tr>
                            <td>
                              <span class="add-on"><i class="icon-resize-full" ></i></span>
                              <span>Kích cỡ: </span>
                            </td>
                            <td><input type="text" id="tire_size" name="tire_size" value="" disabled required="required" /></td>
                          </tr>
                          <tr>
                            <td>
                              <span class="add-on"><i class="icon-barcode" ></i></span>
                              <span>Mã gai: </span>
                            </td>
                            <td><input type="text" id="tire_pattern" name="tire_pattern" value="" disabled required="required" /></td>
                          </tr>
                          <tr>
                            <td>
                              <span class="add-on"><i class="icon-th-list" ></i></span>
                              <span>Số lượng: </span>
                            </td>
                            <td><input type="text" id="tire_number" name="tire_number" value="" class="number" required="required" /></td>
                          </tr>
                          <tr>
                            <td>
                              <span class="add-on"><i class="icon-th-list" ></i></span>
                              <span>Giá: </span>
                            </td>
                            <td><input type="text" id="tire_price" name="tire_price" value="" class="numbers" required="required" /></td>
                          </tr>
                        
                        <tr>
                            <td><input type="hidden" readonly id="max_number" name="max_number" required="required" value="0" ></td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td><input type="submit" name="submit" value="Hoàn tất" tabindex="1"></td>
                            <td ><input type="reset" name="reset" value="Nhập lại" tabindex="2"></td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>
<script type="text/javascript">

$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }
   
});
    $('.edit_tr').click(function(e){
            if(!$('.checkbox').is(':checked') && e.target == '[object HTMLButtonElement]'){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            var tire_brand_name = $(this).find("#tire_brand_"+$(this).attr('id')).text();
            var tire_brand = $(this).find("#tire_brand_"+$(this).attr('id')).attr('data');
            var tire_size_name = $(this).find("#tire_size_"+$(this).attr('id')).text();
            var tire_size = $(this).find("#tire_size_"+$(this).attr('id')).attr('data');
            var tire_pattern_name = $(this).find("#tire_pattern_code_"+$(this).attr('id')).text();
            var tire_pattern = $(this).find("#tire_pattern_code_"+$(this).attr('id')).attr('data');
            var tire_number = $(this).find("#tire_number_"+$(this).attr('id')).text();
            var tire_price = $(this).find("#tire_price_"+$(this).attr('id')).text();
            
            //alert(customer_code);
            $('#yes').val($(this).attr('id'));
            
            
            
            $('#tire_brand').val(tire_brand_name);
            $('#tire_brand').attr('data',tire_brand);
            $('#tire_size').val(tire_size_name);
            $('#tire_size').attr('data',tire_size);
            $('#tire_pattern').val(tire_pattern_name);
            $('#tire_pattern').attr('data',tire_pattern);
            $('#tire_number').val(tire_number);
            $('#tire_price').val(tire_price);

          var customer = "";
        
          $.ajax({
                url: '<?php echo BASE_URL ?>/ordertire/getoldprice',
                type: 'POST',
                data: {brand:tire_brand, size:tire_size, pattern:tire_pattern, customer:customer},
                success:function(data){
                    var data = jQuery.parseJSON(data);
                    $('#max_number').val(data.max);
                    
                }
            });

    });


</script>
<script type="text/javascript">


$(document).ready(function(){
            // Validate form
            $("#add_customer").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var tire_brand = $('#tire_brand').attr('data');
                    var tire_size = $('#tire_size').attr('data');
                    var tire_pattern = $('#tire_pattern').attr('data');
                    var tire_number = $('#tire_number').attr('value');
                    var tire_price = $('#tire_price').attr('value');

                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/ordertirewaiting/editorder", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            tire_brand: tire_brand,
                            tire_size: tire_size,
                            tire_pattern: tire_pattern,
                            tire_number: tire_number,
                            tire_price: tire_price,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                $('#tire_number_'+yes).text(tire_number);
                                $('#tire_price_'+yes).text(tire_price);
                            }
                            else{
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
   
   

   $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
        ;
      });
    });

   $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

         $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}

</script>
</div>

<script type="text/javascript">
$('.del').click(function(){
    var id = $(this).attr('data');
    var r = confirm("Bạn có chắc chắn muốn xóa không?");
      if (r == true){
        $('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/ordertirewaiting/deleteorder", {data: id},
           function(data){
            //alert(data);
            if (data.trim() != 'Bạn không có quyền thực hiện thao tác này') {
              $('#or tr#'+id).remove(); 
              $('#loading').fadeOut(500); 
            };
            $('#loading').fadeOut(500);
           
           }); 
      }
});
</script>