<div class="slide-content" id="hang-giao-chuyen-nha-may">
			<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_native_toolbox"></div>
        <div class="item-page">
            <p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: justify; line-height: 27pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><b><span style="font-size:18.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#333333">Hàng giao / chuyển nhà máy (Ex-work)<o:p></o:p></span></b></p>

<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: justify; line-height: 27pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><b><span style="font-size:18.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#333333">&nbsp;</span></b></p>

<p class="MsoListParagraphCxSpFirst" style="margin-bottom: 0.0001pt; text-align: justify; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Trong&nbsp;</span><a href="http://vi.wikipedia.org/wiki/Th%C6%B0%C6%A1ng_m%E1%BA%A1i" title="Thương mại"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;;color:windowtext;
text-decoration:none;text-underline:none">thương mại</span></a><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;quốc tế,&nbsp;Giá xuất
xưởng&nbsp;được gọi là&nbsp;EX&nbsp;Works (viết tắtEXW). Đây là một điều kiện
của </span><a href="http://vi.wikipedia.org/wiki/Incoterm" title="Incoterm"><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:windowtext;text-decoration:
none;text-underline:none">Incoterm</span></a><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">.
Tất nhiên, tùy theo địa điểm giao hàng mà người ta có thể gọi điều kiện này là
"giá giao tại nhà máy" (Ex Factory), "giá giao tại mỏ" (Ex
Mine), "giá giao tại đồn điền" (ex plantation), "giá giao tại
kho" (Ex Warehouse) nhưng tên gọi tiêu biểu là "giá xuất xưởng"
hay "giá giao tại xưởng" (Ex Works).<o:p></o:p></span></p>

<p><center><img src="public/images/ex.jpg"></center></p>
<p class="MsoListParagraphCxSpLast" style="margin-bottom: 0.0001pt; text-align: justify; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Theo điều kiện EXW này, bên bán
phải: đặt hàng hoá dưới quyền định đoạt của bên mua trong thời hạn và tại địa
điểm do hợp đồng quy định, để bên mua có thể xếp hàng lên phương tiện vận tải
của mình. Còn bên mua phải nhận hàng tại địa điểm (xưởng, mỏ, kho, đồn điền
v.v) của bên bán, chịu mọi rủi ro và phí tổn để lo liệu việc chuyên chở về địa
điểm đích. Đối với các giao dịch&nbsp;</span><a href="http://vi.wikipedia.org/wiki/Th%C6%B0%C6%A1ng_m%E1%BA%A1i_qu%E1%BB%91c_t%E1%BA%BF" title="Thương mại quốc tế"><span style="font-size:10.0pt;line-height:150%;
font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;;
color:windowtext;text-decoration:none;text-underline:none">ngoại thương</span></a><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;theo điều kiện này thì bên mua
phải có khả năng hoàn thành các thủ tục&nbsp;</span><a href="http://vi.wikipedia.org/wiki/H%E1%BA%A3i_quan" title="Hải quan"><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:windowtext;text-decoration:
none;text-underline:none">hải quan</span></a><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;tại
quốc gia cung cấp hàng hóa, một điều mà ngày nay gần như không thể thực hiện
được. Do vậy, trong phần lớn các trường hợp mà thuật ngữ được đề cập tới như là
EXW thì trên thực tế có nghĩa là bên bán phải thực hiện các thủ tục xuất khẩu
và đúng ra nó phải là điều kiện&nbsp;</span><a href="http://vi.wikipedia.org/wiki/FCA_(Incoterm)" title="FCA (Incoterm)"><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:windowtext;text-decoration:
none;text-underline:none">FCA</span></a><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;(Giao
cho người vận tải).<o:p></o:p></span></p>

        </div>
    </div>

<script type="text/javascript">
    closeSidepage('#hang-giao-chuyen-nha-may');
   openSidepage('#hang-giao-chuyen-nha-may');
</script>