<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#edit").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
					username: { rangelength: [2,10] }, //Chiều dài chuỗi trong khoảng từ 4 - 10 ký tự
					password: { rangelength: [4,16] },
					confirmpassword: {
            equalTo: "#password" //So sánh với trường cpassword với thành trường có id là password
          },
				}
					 
				 
			});
	
});
</script>
<div class="login_form">
        <div class="goback"><a href="<?php echo $this->url('user') ?>">&larr;</a></div>
        <div class="login_body">
          <h1>CẬP NHẬT TÀI KHOẢN</h1>
              <form id="edit" method="post" action="">
                  <table style="margin-top:20px;">
                    
                    <tr>
                        <td>Mật khẩu mới</td>
                        <td><input type="password" id="password" name="password" tabindex="1" autofocus ></td>
                        
                    </tr>
                    <tr>
                        <td>Nhập lại mật khẩu mới</td>
                        <td><input type="password" id="confirmpassword" name="confirmpassword" tabindex="2" ></td>
                    </tr>
                    <tr>
                        <td>Họ tên </td>
                        <td>
                          <select name="staff" id="staff" tabindex="3" >
                            <option value="<?php echo isset($user_staff)?$user_staff->staff_id : null; ?>"><?php echo isset($user_staff)?$user_staff->staff_name : null; ?></option>
                            <?php
                            foreach ($staff as $staff) {
                              echo '<option value="'.$staff->staff_id.'">'.$staff->staff_name.'</option>';
                            }
                            ?>
                          </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Quyền </td>
                        <td>
                          <select name="role" id="role" tabindex="4" required="required">
                            <option value="<?php echo $user_role->role_id; ?>"><?php echo $user_role->role_name; ?></option>
                            <?php
                            foreach ($role as $role) {
                              echo '<option value="'.$role->role_id.'">'.$role->role_name.'</option>';
                            }
                            ?>
                          </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Group </td>
                        <td>
                          <select name="user_group" id="user_group" tabindex="5" >
                            <?php for ($i=1; $i <=10 ; $i++) {  ?>
                              <option <?php echo $user_data->user_group==$i?'selected="selected"':null; ?> value="<?php echo $i ?>">Group <?php echo $i ?></option>
                            <?php } ?>
                            
                          </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Phòng </td>
                        <td>
                          <select name="user_dept" id="user_dept" tabindex="6" >
                              <option <?php echo $user_data->user_dept==1?'selected="selected"':null; ?> value="1">Ban GD</option>
                              <option <?php echo $user_data->user_dept==2?'selected="selected"':null; ?> value="2">Phòng CSKH</option>
                              <option <?php echo $user_data->user_dept==3?'selected="selected"':null; ?> value="3">Phòng Sale</option>
                          </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Trạng thái</td>
                        <td>
                          <input type="radio" name="userlock" tabindex="7" value="1" <?php echo $user_data->user_lock==1?'checked':null; ?>> Khóa
                          <input type="radio" name="userlock" tabindex="8" value="0" <?php echo $user_data->user_lock==0?'checked':null; ?>> Mở
                        </td>
                    </tr>
                    
                     <tr>
                        <td ><input type="reset" name="reset" value="Nhập lại" tabindex="10"></td>
                         <td><input type="submit" name="submit" value="Hoàn tất" tabindex="9"></td>
                         
                    </tr>
                </table> 
            </form>
        </div>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
        </div>

