<script type="text/javascript">
$(document).ready(function(){
	
			// Validate form
			$("#loginForm").validate({
				errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
				rules: {
					password: { rangelength: [4,16] },
					confirmpassword: {
            equalTo: "#password" //So sánh với trường cpassword với thành trường có id là password
          },
				}
					 
				 
			});
	
});
</script>
<div class="top-detail">
    <div class="panel panel-info login_form">
        <div class="panel-heading">
            <div class="panel-title">CẬP NHẬT TÀI KHOẢN</div>
        </div> 
        <div class="panel-body">
            <form id="loginForm" method="post" action="">
            <div class="row omb_row-sm-offset-3">
                <div class="col-xs-12 col-sm-6">    
                    
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-clock-o"></i> Mật khẩu cũ</span>
                            <input type="password" class="form-control" id="oldpassword" name="oldpassword" placeholder="Mật khẩu cũ" tabindex="1" autofocus required="required">
                        </div>
                        <span class="help-block"></span>
                                            
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-lock"></i> Mật khẩu mới</span>
                            <input type="password" class="form-control" placeholder="Mật khẩu mới" id="password" name="password" tabindex="2" required="required">
                        </div>
                        <span class="help-block"></span>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-history"></i> Nhập lại mật khẩu</span>
                            <input type="password" class="form-control" placeholder="Nhập lại mật khẩu" id="confirmpassword" name="confirmpassword" tabindex="3" required="required">
                        </div>
                        <span class="help-block"></span>

                        <input class="btn btn-lg btn-primary btn-block" type="submit" name="submit" value="Cập nhật">
                    
                </div>
            </div>   
            <div class="row omb_row-sm-offset-3">
                <div class="col-xs-12 col-sm-6" style="color:#a94442">  
                    <?php echo isset($error) ? $error : null; ?>
                </div>
            </div>
            </form>
        </div>
        
    </div>
</div>