<div class="main-content-box">
    <span class="label label-danger"><i class="fa fa-dollar"></i> Giá rẻ nhất Việt Nam</span>
    <span class="label label-danger"><i class="fa fa-truck"></i> 100% hàng nhập khẩu trực tiếp từ nhà máy ở Thái Lan</span>
    <span class="label label-danger"><i class="fa fa-check-square-o"></i> 100% hàng đã qua kiểm tra đạt tiêu chuẩn Châu Âu</span>
    <div class="offer offer-radius offer-primary">
        <div class="shape">
            <div class="shape-text">
                Made in <br> <span>Thailand</span>
            </div>
        </div>
        <div class="offer-content">                    
            <?php $filedir = BASE_URL."/public/images/upload/"; ?>
            <div class="col-md-3 col-xs-6 col-xs-12">
                <div class="box box-success">
                    <a href="<?php echo BASE_URL ?>/vn/brand/ling-long" title="Lốp xe Ling long Thailand">
                        <img src="<?php echo $filedir.'ling-long.jpg' ?>" width="100%" height="100%">
                    </a>
                </div>
            </div>
            <div class="col-md-3 col-xs-6 col-xs-12">
                <div class="box box-success">
                    <a href="<?php echo BASE_URL ?>/vn/brand/infinity" title="Lốp xe Infinity Thailand">
                        <img src="<?php echo $filedir.'infinity.jpg' ?>" width="100%" height="100%">
                    </a>
                </div>
            </div>
            <div class="col-md-3 col-xs-6 col-xs-12">
                <div class="box box-success">
                    <a href="<?php echo BASE_URL ?>/vn/brand/leao" title="Lốp xe Leao Thailand">
                        <img src="<?php echo $filedir.'leao.jpg' ?>" width="100%" height="100%">
                    </a>
                </div>
            </div>
            <div style="clear:both"></div>
            <div class="col-md-3 col-xs-6 col-xs-12">
                <div class="box box-success">
                    <a href="<?php echo BASE_URL ?>/vn/brand/zhongce" title="Lốp xe Zhongce Thailand">
                        <img src="<?php echo $filedir.'zhongce.jpg' ?>" width="100%" height="100%">
                    </a>
                </div>
            </div>
            <div class="col-md-3 col-xs-6 col-xs-12">
                <div class="box box-success">
                    <a href="<?php echo BASE_URL ?>/vn/brand/westlake" title="Lốp xe Westlake Thailand">
                        <img src="<?php echo $filedir.'westlake.jpg' ?>" width="100%" height="100%">
                    </a>
                </div>
            </div>
            <div class="col-md-3 col-xs-6 col-xs-12">
                <div class="box box-success">
                    <a href="<?php echo BASE_URL ?>/vn/brand/goodride" title="Lốp xe Goodride Thailand">
                        <img src="<?php echo $filedir.'goodride.jpg' ?>" width="100%" height="100%">
                    </a>
                </div>
            </div>
            <div class="col-md-3 col-xs-6 col-xs-12">
                <div class="box box-success">
                    <a href="<?php echo BASE_URL ?>/vn/brand/chaoyang" title="Lốp xe Chaoyang Thailand">
                        <img src="<?php echo $filedir.'chaoyang.jpg' ?>" width="100%" height="100%">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="main-content-box">
    <hr class="style18">
    <div class="row">
        <?php foreach ($tire_producers as $tire_producer) { ?>
            <div class="col-md-2 col-xs-6 col-xs-12">
                <div class="box box-success">
                    <?php
                    $filename = "public/images/upload/".strtolower(str_replace(' ', '-', $tire_producer->tire_producer_name)).".jpg";
                    if (@getimagesize($filename)) {
                    ?>
                    
                    <a href="<?php echo BASE_URL ?>/vn/brand/<?php echo strtolower(str_replace(' ', '-', $tire_producer->tire_producer_name)) ?>" title="Lốp xe <?php echo $tire_producer->tire_producer_name ?>">
                        <img src="<?php echo $filename ?>" width="100%" height="100%">
                    </a>
                    <?php
                    }
                    else{
                    ?>
                        <div class="items-list-prod">
                            <div class="view_all">
                                <a class="view_all_link" href="<?php echo BASE_URL ?>/vn/brand/<?php echo strtolower(str_replace(' ', '-', $tire_producer->tire_producer_name)) ?>" title="Lốp xe <?php echo $tire_producer->tire_producer_name ?>">
                                    <?php echo $tire_producer->tire_producer_name ?> <i class="fa fa-caret-right"></i>
                                </a>
                            </div>
                        </div>
                    <?php
                    }
                    ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<style type="text/css">
.box {
    position: relative;
    border-radius: 3px;
    background: #000;
    border-top: 3px solid #d2d6de;
    margin-bottom: 20px;
    width: 100%;
    box-shadow: 1px 2px 2px 2px rgba(0, 0, 0, 0.3);
}
.box.box-success {
    border-top-color: #48b66e;
}
.box:hover{
    -webkit-box-shadow: 2px 4px 28px 0px rgba(32,191,64,1);
    -moz-box-shadow: 2px 4px 28px 0px rgba(32,191,64,1);
    box-shadow: 2px 4px 28px 0px rgba(32,191,64,1);
}
@media (min-width: 768px){
    .box {
        height: 100%;
    }
}
@media (min-width: 992px){
    .box {
        height: 50px;
    }
}

.label{
    font-size: 100%;
}

.shape{ 
    border-style: solid; border-width: 0 120px 70px 0; float:right; height: 0px; width: 0px;
    -ms-transform:rotate(360deg); /* IE 9 */
    -o-transform: rotate(360deg);  /* Opera 10.5 */
    -webkit-transform:rotate(360deg); /* Safari and Chrome */
    transform:rotate(360deg);
}
.offer{
    background:#fff; border:1px solid #ddd; box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2); margin-bottom: 20px; overflow:hidden;
}
.offer-radius{
    border-radius:7px;
}
.offer-danger { border-color: #d9534f; }
.offer-danger .shape{
    border-color: transparent #d9534f transparent transparent;
    border-color: rgba(255,255,255,0) #d9534f rgba(255,255,255,0) rgba(255,255,255,0);
}
.offer-success {    border-color: #5cb85c; }
.offer-success .shape{
    border-color: transparent #5cb85c transparent transparent;
    border-color: rgba(255,255,255,0) #5cb85c rgba(255,255,255,0) rgba(255,255,255,0);
}
.offer-default {    border-color: #999999; }
.offer-default .shape{
    border-color: transparent #999999 transparent transparent;
    border-color: rgba(255,255,255,0) #999999 rgba(255,255,255,0) rgba(255,255,255,0);
}
.offer-primary {    border-color: #428bca; }
.offer-primary .shape{
    border-color: transparent #428bca transparent transparent;
    border-color: rgba(255,255,255,0) #428bca rgba(255,255,255,0) rgba(255,255,255,0);
}
.offer-info {   border-color: #5bc0de; }
.offer-info .shape{
    border-color: transparent #5bc0de transparent transparent;
    border-color: rgba(255,255,255,0) #5bc0de rgba(255,255,255,0) rgba(255,255,255,0);
}
.offer-warning {    border-color: #f0ad4e; }
.offer-warning .shape{
    border-color: transparent #f0ad4e transparent transparent;
    border-color: rgba(255,255,255,0) #f0ad4e rgba(255,255,255,0) rgba(255,255,255,0);
}

.shape-text{
    color:#fff; font-size:13px; font-weight:bold; position:relative; right:-72px; top:-7px; white-space: nowrap;
    -ms-transform:rotate(30deg); /* IE 9 */
    -o-transform: rotate(360deg);  /* Opera 10.5 */
    -webkit-transform:rotate(30deg); /* Safari and Chrome */
    transform:rotate(30deg);
}   
.shape-text span{
    font-size: 20px;
    margin-left: -28px;
}
.offer-content{
    padding: 20px;
}

hr{
    margin: 0;
}
hr.style18 { 
  height: 30px; 
  border-style: solid; 
  border-color: #428bca; 
  border-width: 1px 0 0 0; 
  border-radius: 20px; 
} 
hr.style18:before { 
  display: block; 
  content: ""; 
  height: 30px; 
  margin-top: -31px; 
  border-style: solid; 
  border-color: #428bca; 
  border-width: 0 0 1px 0; 
  border-radius: 20px; 
}

</style>