<div class="slide-content" id="cung-ung-thuc-pham">
			<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_native_toolbox"></div>
        <div class="item-page">

            <h2>Cung ứng thực phẩm      </h2>

        <p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--> Cung cấp các loại lương thực, thực phẩm tươi sống hoặc đông lạnh theo yêu cầu. Tất cả đều có giấy tờ chứng nhận an toàn vệ sinh thực phẩm.</p>
        <p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--> Cung cấp nước ngọt, bia rượu.</p> 
        </div>
    </div>

<script type="text/javascript">
    closeSidepage('#cung-ung-thuc-pham');
   openSidepage('#cung-ung-thuc-pham');
</script>