<div class="slide-content" id="moi-gioi-tau">
        <div class="item-page">

            <h2>Môi giới tàu        </h2>

<p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Phòng môi giới tàu biển của chúng
tôi có chức năng cung cấp dịch vụ môi giới tàu &amp; hàng hoá cho các nhà xuất
- nhập khẩu và các Chủ tàu không chỉ ở việt Nam mà còn tại nhiều nước khác
trong khu vực và trên toàn thế giới như: Trung Quốc, Nhật Bản, Hàn Quốc, Hồng
Kông, các nước Đông Nam Á, Nga, Ấn Độ, Trung Đông, kể cả Châu Phi và Châu Âu
với các hợp đồng tàu chuyến, tàu định hạn và tàu chạy chuyến cố định.<o:p></o:p></span><br></p><p><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span><br></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Chúng tôi gồm các chuyên gia trong
lĩnh vực môi giới Hàng hải, có nhiều năm kinh nghiệm thực tế, chuyên cung cấp
các loại tàu, hàng với nhiều kích cỡ và chủng loại khác nhau, các tàu có trọng
tải từ 2,000DWT đến trên 35,000DWT, hàng hoá các loại từ 2,000 tấn đến trên
35,000 tấn.<o:p></o:p></span><br></p><p><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span><br></p><p><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span><br></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Thêm vào đó, chúng tôi luôn duy trì
các mối quan hệ gần gũi, chia sẻ thông tin và hợp tác cùng với rất nhiều các
hãng tàu lớn, các nhà phân phối hàng hoá, các công ty thương mại, các khu chế
xuất, khu công nghiệp, các công ty cung ứng xăng dầu, sửa chữa tàu biển… liên
lạc thường xuyên, trao đổi và nắm bắt thông tin thị trường từ hơn 1,000 nhà môi
giới uy tín khác nhau trên toàn thế giới. Nhờ đó chúng tôi luôn có thể đảm bảo
về chất lượng của dịch vụ vận chuyển cũng như số lượng các loại hàng hoá mà
chúng tôi cung cấp đến cho các chủ tàu.<o:p></o:p></span><br></p><p><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span><br></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Phòng môi giới của chúng tôi thường
xuyên tham gia đàm phán, thương thảo, tư vấn và chuẩn bị tốt nhất các điều kiện
để các bên tham gia tiến hành ký kết các Hợp đồng vận chuyển cho các loại hàng
hoá như: hàng nông sản, phân hoá học, hoá chất, khoáng sản, quặng, than đá,
hàng dự án, hàng siêu trường, siêu trọng và nhiều loại hàng hoá khác.<o:p></o:p></span><br></p><p><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span><br></p><p><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span><br></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Bên cạnh việc đảm bảo cung cấp lượng
hàng hoá dồi dào theo năng lực vận tải của tàu, Phòng môi giới Hàng hải của
chúng tôi còn có thể lập trình đánh giá chi tiết các yêu cầu cụ thể của khách
hàng và đưa ra các giải pháp vận chuyển phù hợp. Với mục tiêu cuối cùng của
chúng tôi là tìm ra giải pháp vận chuyển tối ưu nhất cho các chuyến hàng, đáp
ứng các yêu cầu vận chuyển khắt khe của khách hàng với mức giá thoả thuận tốt
nhất.<o:p></o:p></span><br></p><p><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span><br></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Song song với việc Môi giới hàng
hoá, chúng tôi còn thường xuyên cập nhật danh sách các tàu có nhu cầu được bán
hoặc thanh lý cũng như địa chỉ của những nhà tài chính tiềm năng. Chính vì thế
chúng tôi luôn có thể đáp ứng và phục vụ tốt mọi nhu cầu mua bán tàu với mức
giá cạnh tranh nhất trong từng thời điểm cụ thể của thị trường Hàng hải.<o:p></o:p></span><br></p><p><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span><br></p><p><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span><br></p><p><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:Wingdings;mso-fareast-font-family:
Wingdings;mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Vậy nên, khi bạn cần tham khảo về
những vấn đề pháp lý liên quan hoặc sự tư vấn của những người có kinh nghiệm
trong lĩnh vực Môi giới - Thuê tàu về giá cước vận chuyển trên thị trường trong
thời điểm hiện tại, cũng như khi bạn cần thuê một chiếc tàu hay muốn tìm một
vài lô hàng vận chuyển thích hợp, bạn cần được tham vấn bởi những nhà môi giới
chuyên nghiệp và uy tín<o:p></o:p></span><br></p>
        </div>
    </div>

<script type="text/javascript">
    closeSidepage('#moi-gioi-tau');
   openSidepage('#moi-gioi-tau');
</script>