<style type="text/css">
/* calendar */
table.calendar      { border-left:1px solid #999; }
tr.calendar-row {  }
td.calendar-day { min-height:80px; font-size:11px; position:relative; } * html div.calendar-day { height:80px; }
td.calendar-day:hover   { background:#eceff5; }
td.calendar-day-np  { background:#eee; min-height:80px; } * html div.calendar-day-np { height:80px; }
td.calendar-day-head { background:#ccc; font-weight:bold; text-align:center; width:120px; padding:5px; border-bottom:1px solid #999; border-top:1px solid #999; border-right:1px solid #999; }
div.day-number      { background:#999; padding:5px; color:#fff; font-weight:bold; float:right; margin:-5px -5px 0 0; width:20px; text-align:center; }
/* shared */
td.calendar-day, td.calendar-day-np { width:120px; padding:5px; border-bottom:1px solid #999; border-right:1px solid #999; }

.add{ display: none;}
td.calendar-day:hover .add{ display: block;}
p.number{
    text-align: center;
    color: red;
    font-weight: bold;
}
p.number:hover{ cursor: pointer; text-decoration: underline;}
</style>

<?php
/* draws a calendar */
function draw_calendar($month,$year,$checkeat){

    /* draw table */
    $calendar = '<table cellpadding="0" cellspacing="0" class="calendar">';

    /* table headings */
    $headings = array('Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7','Chủ nhật');
    $calendar.= '<tr class="calendar-row"><td class="calendar-day-head">'.implode('</td><td class="calendar-day-head">',$headings).'</td></tr>';

    /* days and weeks vars now ... */
    $running_day = date('w',mktime(0,0,0,$month,1,$year))-1;
    $days_in_month = date('t',mktime(0,0,0,$month,1,$year));
    $days_in_this_week = 1;
    $day_counter = 0;
    $dates_array = array();

    /* row for week one */
    $calendar.= '<tr class="calendar-row">';

    /* print "blank" days until the first of the current week */
    for($x = 0; $x < $running_day; $x++):
        $calendar.= '<td class="calendar-day-np"> </td>';
        $days_in_this_week++;
    endfor;

    /* keep going with days.... */
    for($list_day = 1; $list_day <= $days_in_month; $list_day++):
        $calendar.= '<td class="calendar-day">';
            /* add in the day number */
            $calendar.= '<div class="day-number">'.$list_day.'</div>';

            $name = strtotime($list_day.'-'.$month.'-'.$year.' 09:00:00') >= strtotime(date('d-m-Y H:i:s')) ? 1:0;
            
            if (isset($checkeat[$list_day.$month.$year])) {
                $calendar.= '<p name="'.$name.'" class="number" data="'.$list_day.'-'.$month.'-'.$year.'">'.$checkeat[$list_day.$month.$year].'</p>';
            }
            else if ($name == 1 && !isset($checkeat[$list_day.$month.$year])) {
                $calendar.= '<button name="'.$name.'" class="add" data="'.$list_day.'-'.$month.'-'.$year.'">Đăng ký</button>';
            }
            /** QUERY THE DATABASE FOR AN ENTRY FOR THIS DAY !!  IF MATCHES FOUND, PRINT THEM !! **/
            //$calendar.= str_repeat('<p> </p>',2);
            
        $calendar.= '</td>';
        if($running_day == 6):
            $calendar.= '</tr>';
            if(($day_counter+1) != $days_in_month):
                $calendar.= '<tr class="calendar-row">';
            endif;
            $running_day = -1;
            $days_in_this_week = 0;
        endif;
        $days_in_this_week++; $running_day++; $day_counter++;
    endfor;

    /* finish the rest of the days in the week */
    if($days_in_this_week < 8):
        for($x = 1; $x <= (8 - $days_in_this_week); $x++):
            $calendar.= '<td class="calendar-day-np"> </td>';
        endfor;
    endif;

    /* final row */
    $calendar.= '</tr>';

    /* end the table */
    $calendar.= '</table>';
    
    /* all done, return result */
    return $calendar;
}

?>
<center>
<?php
$month = date('m');
$year = date('Y');
echo "<h2>Tháng $month $year</h2>";
echo draw_calendar($month,$year,$checkeat);
?>
<table style="width:300px; font-size:14px">
    <tr>
        <td>Tổng ngày ăn: <strong><?php echo $tongngay ?></strong></td>
        <td>Tổng phần ăn: <strong><?php echo array_sum($checkeat) ?></strong></td>
    </tr>
</table>

</center>


<div id="dialogContent" title="Đăng ký cơm">
    
    
    <form action="#" method="post" id="editForm">
        
        
        <label>
            <span class="add-on"><i class="icon-retweet" ></i></span>
            <span>Số phần: </span>
            <input type="text" id="i_number" name="i_number" required="required" />
            <input type="hidden" id="i_date" name="i_date" required="required" />
        </label>
        
    </form>
</div>
<script type="text/javascript">
$('.number')
    .click(function() {
        if ($(this).attr('name') == 1) {
            $('#i_date').val($(this).attr('data'));
            $('#i_number').val($(this).text());
            $( "#dialogContent" ).dialog( "open" );
        }
    });

$('.add')
    .button({ icons: { primary: "ui-icon-document" }})
    .click(function() {
        if ($(this).attr('name') == 1) {
            $('#i_date').val($(this).attr('data'));

            $( "#dialogContent" ).dialog( "open" );
        }
    });


//set up the dialog box.
$( "#dialogContent" ).dialog({
    autoOpen: false,
    modal: true,
    buttons: {
        OK: function() {
            var date = $('#i_date').val();
            var number = $('#i_number').val();
                
                $.post("<?php echo BASE_URL ?>/checkeat/add", {date: date, number: number},
                   function(data){
                    setTimeout(function() {
                        sapxep();
                      }, 200);
                   
                   }); 
              
            $( this ).dialog( "close" );
        },        
        Cancel: function() {
            $( this ).dialog( "close" );
        }
    }
});
</script>