
<?php
$url_order = 'ASC';
if ($order_by == 'customer_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> CÔNG NỢ ĐƠN HÀNG </h1></center>
<div class="add-box">
    <a class="add_button" id="btnExport" >Export Excel</a>
    
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">       
        <div class="add-box">
            <select id="sl_nv" name="sl_nv" style="width:150px">
                <option value="">Nhân viên</option>
                <?php foreach ($staffs as $staff) { ?>
                    <option value="<?php echo $staff->staff_id ?>"><?php echo $staff->staff_name ?></option>
                <?php } ?>
            </select>
            <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        </div>
        <div class="alignleft actions">
            <input autocomplete="off" type="text" name="customer" id="customer" placeholder="Tên khách hàng" <?php echo isset($customer->customer_name)?'value="'.$customer->customer_name.'"':null ?> />
            <ul id="customer_list_id"></ul>
            <input type="hidden" name="sl_status" id="sl_status" <?php echo isset($trangthai)?'value="'.$trangthai.'"':null ?> >
            <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        </div>
        <div class="alignleft actions">
            <select id="sl_tha" name="sl_tha" >
                <option value="0">Còn nợ</option>
                <option value="1">Đã thanh toán</option>
            </select>
            <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        </div>

        

      </div>
    

</div>

<table id="tblExport" class="table_data tablesaw" data-tablesaw-mode="columntoggle" data-tablesaw-mode-switch data-tablesaw-minimap>
<thead>
    <tr>
    	<th  class="fix" scope="col" data-tablesaw-sortable-col data-tablesaw-priority="7"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix" scope="col" data-tablesaw-sortable-col data-tablesaw-priority="6">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'customer_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th  class="fix" scope="col" data-tablesaw-sortable-col data-tablesaw-priority="persist">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix" scope="col" data-tablesaw-sortable-col data-tablesaw-priority="5">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','order_tire_number','<?php echo $url_order ?>')">Sản lượng <?php if ($order_by == 'order_tire_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th class="fix" scope="col" data-tablesaw-sortable-col data-tablesaw-priority="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','total','<?php echo $url_order ?>')">KH phải trả <?php if ($order_by == 'total'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix" scope="col" data-tablesaw-sortable-col data-tablesaw-priority="3">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','pay_money','<?php echo $url_order ?>')">Đã trả <?php if ($order_by == 'pay_money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix" scope="col" data-tablesaw-sortable-col data-tablesaw-priority="1">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','total','<?php echo $url_order ?>')">Còn lại <?php if ($order_by == 'total'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th class="fix" scope="col" data-tablesaw-sortable-col data-tablesaw-priority="4">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','username','<?php echo $url_order ?>')">Sale <?php if ($order_by == 'username'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        
    </tr>
    
   </thead>
   <tbody>
    <?php $tongsl=0; $tongkhtra=0; $tongdatra=0; $tongcon=0; ?>
    <?php foreach ($customers as $order_tire) : 
    if ($tha == 0) {
        if (isset($data_customer['money'][$order_tire->customer_id]) && ( ($data_customer['money'][$order_tire->customer_id]-$data_customer['pay_money'][$order_tire->customer_id]>0) || ($data_customer['pay_money'][$order_tire->customer_id]-$data_customer['money'][$order_tire->customer_id]>0)) ) {
        $tongsl += $data_customer['number'][$order_tire->customer_id];
        $tongkhtra += $data_customer['money'][$order_tire->customer_id];
        $tongdatra += $data_customer['pay_money'][$order_tire->customer_id];
        $tongcon += $data_customer['money'][$order_tire->customer_id]-$data_customer['pay_money'][$order_tire->customer_id];
    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $order_tire->customer_id ?>" class="edit_tr" data="<?php echo ($order_tire->sale==$_SESSION['userid_logined'] || $_SESSION['role_logined']==1)?1:0 ?>">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $order_tire->customer_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            
            <td class="fix title" data="<?php echo $order_tire->customer; ?>"  id="customer_<?php echo $order_tire->customer_id; ?>"><a style="text-decoration:underline" class="customer" href="<?php echo $this->url('tiredebit/customer/'.$order_tire->customer_id); ?>"><?php echo $order_tire->customer_name; ?></a></td>
            <td class="fix"  id="order_tire_number_<?php echo $order_tire->customer_id; ?>"><a style="text-decoration:underline" class="customer" href="<?php echo $this->url('tiredebit/customer/'.$order_tire->customer_id); ?>"><?php echo $data_customer['number'][$order_tire->customer_id]; ?></a></td>
            
            <td style="text-align: right;" class="fix"  id="total_<?php echo $order_tire->customer_id; ?>"><a style="text-decoration:underline" class="customer" href="<?php echo $this->url('tiredebit/customer/'.$order_tire->customer_id); ?>"><?php echo $lib->formatMoney($data_customer['money'][$order_tire->customer_id]); ?></a></td>
            <td style="text-align: right;" class="fix"  id="pay_money_<?php echo $order_tire->customer_id; ?>"><a style="text-decoration:underline" class="pay_money" href="<?php echo $this->url('tiredebit/cuspay/'.$order_tire->customer_id); ?>"><?php echo $lib->formatMoney($data_customer['pay_money'][$order_tire->customer_id]); ?></a></td>
            <td style="text-align: right;" class="fix error"  id="con_<?php echo $order_tire->customer_id; ?>"><a style="font-weight:bold;text-decoration:underline;" class="error customer" href="<?php echo $this->url('tiredebit/cus/'.$order_tire->customer_id); ?>"><?php echo $lib->formatMoney($data_customer['money'][$order_tire->customer_id]-$data_customer['pay_money'][$order_tire->customer_id]); ?></a></td>
            
            <td class="fix" id="sale_<?php echo $order_tire->customer_id; ?>"><?php echo $data_customer['sale'][$order_tire->customer_id]; ?></td> 
             
        </tr>
    <?php } 
    }
    else{
        if (isset($data_customer['money'][$order_tire->customer_id]) && ($data_customer['money'][$order_tire->customer_id]-$data_customer['pay_money'][$order_tire->customer_id]==0)) {
        $tongsl += $data_customer['number'][$order_tire->customer_id];
        $tongkhtra += $data_customer['money'][$order_tire->customer_id];
        $tongdatra += $data_customer['pay_money'][$order_tire->customer_id];
        $tongcon += $data_customer['money'][$order_tire->customer_id]-$data_customer['pay_money'][$order_tire->customer_id];
    ?>
    <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $order_tire->customer_id ?>" class="edit_tr" data="<?php echo ($order_tire->sale==$_SESSION['userid_logined'] || $_SESSION['role_logined']==1)?1:0 ?>">
            <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $order_tire->customer_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            
            <td class="fix" data="<?php echo $order_tire->customer; ?>"  id="customer_<?php echo $order_tire->customer_id; ?>"><a style="text-decoration:underline" class="customer" href="<?php echo $this->url('tiredebit/customer/'.$order_tire->customer_id); ?>"><?php echo $order_tire->customer_name; ?></a></td>
            <td class="fix"  id="order_tire_number_<?php echo $order_tire->customer_id; ?>"><a style="text-decoration:underline" class="customer" href="<?php echo $this->url('tiredebit/customer/'.$order_tire->customer_id); ?>"><?php echo $data_customer['number'][$order_tire->customer_id]; ?></a></td>
            
            <td style="text-align: right;" class="fix"  id="total_<?php echo $order_tire->customer_id; ?>"><a style="text-decoration:underline" class="customer" href="<?php echo $this->url('tiredebit/customer/'.$order_tire->customer_id); ?>"><?php echo $lib->formatMoney($data_customer['money'][$order_tire->customer_id]); ?></a></td>
            <td style="text-align: right;" class="fix"  id="pay_money_<?php echo $order_tire->customer_id; ?>"><a style="text-decoration:underline" class="pay_money" href="<?php echo $this->url('tiredebit/cuspay/'.$order_tire->customer_id); ?>"><?php echo $lib->formatMoney($data_customer['pay_money'][$order_tire->customer_id]); ?></a></td>
            <td style="text-align: right;" class="fix error"  id="con_<?php echo $order_tire->customer_id; ?>"><a style="font-weight:bold;text-decoration:underline;" class="error customer" href="<?php echo $this->url('tiredebit/cus/'.$order_tire->customer_id); ?>"><?php echo $lib->formatMoney($data_customer['money'][$order_tire->customer_id]-$data_customer['pay_money'][$order_tire->customer_id]); ?></a></td>
            
            <td class="fix" id="sale_<?php echo $order_tire->customer_id; ?>"><?php echo $data_customer['sale'][$order_tire->customer_id]; ?></td> 
             
        </tr>
    <?php    }
    }
    endforeach; ?>
    <tr style=" color:rgb(211, 11, 57); text-align: center; font-weight:bold;">
            <td class="fix" colspan="3">Tổng cộng</td>
            <td class="fix"><?php echo $lib->formatMoney($tongsl) ?></td>
            <td style="text-align: right;" class="fix"><?php echo $lib->formatMoney($tongkhtra) ?></td>
            <td style="text-align: right;" class="fix"><?php echo $lib->formatMoney($tongdatra) ?></td>
            <td style="text-align: right;" class="fix"><?php echo $lib->formatMoney($tongcon) ?></td>
            <td class="fix"></td>
        </tr>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('tiredebit') ?>">&larr;</a></div>


<script type="text/javascript">
var c = "<?php echo $tha ?>";
$('#sl_tha option[value='+c+']').attr('selected','selected');
var n = "<?php echo $nv ?>";
$('#sl_nv option[value='+n+']').attr('selected','selected');

$(".customer").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:500,
            width:"90%",
            resizable: false,
            title:'Danh sách đơn hàng',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });
$(".order_cost").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:500,
            width:600,
            resizable: false,
            title:'Chi phí',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });
$(".order_list").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:500,
            width:600,
            resizable: false,
            title:'Thông tin',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });
$(".pay_money").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:500,
            width:600,
            resizable: false,
            title:'Đã thanh toán',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });


function set_item(item,value,company,phone,address,email,ngay,mst,type) {
    // change input value
    $('#customer').val(item);
    $("#customer").attr("data",value);
    $('#sl_status').val(value);
    $('#customer_list_id').hide();
    $('#customer').focus();

}

$('#customer').keyup(function(){
      
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/ordertire/getcustomer',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                $('#customer_list_id').slideDown(200);
                $('#customer_list_id').html(data);
            }
        });
        if ($('#customer').val() == "" || $('#customer').attr('data') == "") {
            
            $('#customer').attr('data',"");
            $('#sl_status').val("");
        }
      
      
   });  
$('#customer').on('keydown', function() {
        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('#customer').attr('data',"");
            $('#sl_status').val("");
        }
            
      });  
$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        //$('.add-field').slideUp(500);      
    }
    $('#customer_list_id').slideUp(200); 
    
});
</script>