<?php
    $today = strtotime($ngay);
    $k=1;
?>
<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;"><h1> HÀNG QUÁ HẠN</h1></center>

</div>
<div style="width:90%;">
    <form id="inven" method="post" action="">
    <div style="text-align:left">
            Ngày: <input style="width:90px" type="text"  id="date" name="date" value="<?php echo $ngay ?>"><input type="submit" id="check" value="Kiểm tra">     
    </div>
    <div class="add-box">
        <select id="thuonghieu" name="thuonghieu" style="width:120px">
            <option value="0">Thương hiệu</option>
            <?php foreach ($tire_brands as $tire_brand) { ?>
                <option value="<?php echo $tire_brand->tire_brand_id ?>"><?php echo $tire_brand->tire_brand_name ?></option>
            <?php } ?>
        </select>
        <select id="kichco" name="kichco" style="width:100px">
            <option value="0">Kích cỡ</option>
            <?php foreach ($tire_sizes as $tire_size) { ?>
                <option value="<?php echo $tire_size->tire_size_id ?>"><?php echo $tire_size->tire_size_number ?></option>
            <?php } ?>
        </select>
        <select id="magai" name="magai" style="width:80px">
            <option value="0">Mã gai</option>
            <?php foreach ($tire_patterns as $tire_pattern) { ?>
                <option value="<?php echo $tire_pattern->tire_pattern_id ?>"><?php echo $tire_pattern->tire_pattern_name ?></option>
            <?php } ?>
        </select>
        <input type="submit" id="check2" value="Chọn">
    </div>
    </form>
</div>
<div class="add-box">
    <a class="add_button" id="btnExport" >Export Excel</a>
    
</div>
<div style="clear:both"></div>



<div >
    <table id="tblExport" class="table_data">
<thead>
    <tr>
        <th  class="fix" >
            <a class="sort" >STT </a>
        </th>
        <th  class="fix" >
            Hình ảnh
        </th>
        <th  class="fix">
            <a class="sort" >Thương hiệu </a>
        </th>
        <th  class="fix">
            <a class="sort" >Size </a>
        </th>
        <th  class="fix">
            <a class="sort " >Mã gai </a>
        </th>
        
        <th  class="fix">
            <a class="sort" >Tồn kho </a>
        </th>
        <th  class="fix">
            <a class="sort" >Ngày SX </a>
        </th>
        <th  class="fix">
            <a class="sort" >Lô hàng </a>
        </th>
        <th  class="fix">
            <a class="sort" >Ngày nhập </a>
        </th>
        <th  class="fix">
            <a class="sort" >Quá hạn </a>
        </th>
        
    </tr>
    
   </thead>
   <tbody>
    <?php $doanhthu=0; $chiphi=0; $loinhuan=0; $soluong = 0; $daban=0; $tonkho=0; ?>
    <?php foreach ($tire_buys as $tire_buy) : ?>
    
    <?php 
        
        $ton = $tire_buy->soluong - (isset($sell[$tire_buy->tire_buy_id]['number'])?$sell[$tire_buy->tire_buy_id]['number']:0);

        $timeDiff = $today - $tire_buy->date_manufacture;

        $numberDays = $timeDiff/86400;  // 86400 seconds in one day

        // and you might want to convert to integer
        $numberDays = intval($numberDays); 

        if($ton > 0 && $numberDays > 180){

        $doanhthu += (isset($tire_buy_data[$tire_buy->tire_buy_id]['revenue'])?$tire_buy_data[$tire_buy->tire_buy_id]['revenue']:0);
        $chiphi += (isset($tire_buy_data[$tire_buy->tire_buy_id]['cost'])?$tire_buy_data[$tire_buy->tire_buy_id]['cost']:0);
        $soluong += $tire_buy->soluong;
        $daban += (isset($sell[$tire_buy->tire_buy_id]['number'])?$sell[$tire_buy->tire_buy_id]['number']:0); 

    ?>
        
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $tire_buy->tire_buy_id ?>" class="edit_tr" >
            
            
            <td  class="fix"><?php echo $k++; ?></td>
            <td  class="fix"><img src="<?php echo BASE_URL ?>/public/images/upload/<?php echo $link_picture[$tire_buy->tire_buy_id]['image']; ?>" width="50" height="50" /></td>
            <td class="fix" data="<?php echo $tire_buy->tire_buy_brand; ?>" id="tire_buy_brand_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $tire_buy->tire_brand_name; ?></td>
            <td class="fix" data="<?php echo $tire_buy->tire_buy_size; ?>" id="tire_buy_size_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $tire_buy->tire_size_number; ?></td>
            <td class="fix" data="<?php echo $tire_buy->tire_buy_pattern; ?>" id="tire_buy_pattern_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $tire_buy->tire_pattern_name; ?></td>
            
            <td class="fix" id="conlai_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $lib->formatMoney($ton ); ?></td>
            <td class="fix" id="date_manufacture_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $tire_buy->date_manufacture>0?date('m/Y',$tire_buy->date_manufacture):null; ?></td>
            <td class="fix" id="code_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $tire_buy->code; ?></td>
            <td class="fix" id="tire_buy_date_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $lib->hien_thi_ngay_thang($tire_buy->tire_buy_date); ?></td>
            <td class="fix error" id="expired_<?php echo $tire_buy->tire_buy_id; ?>"><i class="fa fa-clock-o"></i> <?php echo str_replace('ago', '', $lib->time_elapsed_string(date('d-m-Y',$tire_buy->date_manufacture),2)); ?></td>
            
        </tr>

    <?php } ?>
    <?php endforeach; ?>

    <tr style="text-align:center; font-weight: bold; color: red;">
        <td class="fix" colspan="5" >Tổng cộng</td>
        <td class="fix"><?php echo $soluong-$daban; ?></td>
        <td class="fix" colspan="4" ></td>
    </tr>
     
   </tbody>
</table>
</div>


<script type="text/javascript">
    
var ngay = "<?php echo $ngay ?>";
var t = "<?php echo $thuonghieu ?>";
$('#thuonghieu option[value='+t+']').attr('selected','selected');
var s = "<?php echo $kichco ?>";
$('#kichco option[value='+s+']').attr('selected','selected');
var p = "<?php echo $magai ?>";
$('#magai option[value='+p+']').attr('selected','selected');


var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $("#date").datepicker(pickerOpay2);

</script> 