<link rel="stylesheet" href="<?php BASE_URL ?>/public/js/chosen/chosen.css">
<script src="<?php echo BASE_URL ?>/public/js/chosen/chosen.jquery.js" type="text/javascript"></script>
<?php
$url_order = 'ASC';
if ($order_by == 'work_plan_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'work_plan_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'work_plan_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'end_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
  elseif ($order_by == 'work_plan_comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
  elseif ($order_by == 'work_plan_complete')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
  elseif ($order_by == 'work_plan_owner')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
  elseif ($order_by == 'work_plan_point')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
  elseif ($order_by == 'work_plan_code_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-2">
          <a onClick="add_click();" class="btn btn-primary btn-block margin-bottom"><i class="fa  fa-pencil-square-o"></i> Thêm công việc</a>
          <a target="_blank" href="<?php echo $this->url('workplancode') ?>" class="btn btn-default btn-block"><i class="fa  fa-bars"></i> Danh mục đầu việc</a>

          <div class="box box-solid collapsed-box">
            <div class="box-header with-border">
              <h3 class="box-title">Hôm nay</h3>

              <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                </button>
              </div>
            </div>
            <div class="box-body no-padding">
              <ul class="nav nav-pills nav-stacked">
                <li><a href="<?php echo $this->url('weeklyplan/todayworking') ?>"><i class="fa fa-calendar-minus-o"></i> Đang thực hiện
                  <span class="label label-warning pull-right"><?php echo $todayworking ?></span></a>
                </li>
                <li><a href="<?php echo $this->url('weeklyplan/todayworkcomplete') ?>"><i class="fa fa-calendar-check-o"></i> Đã hoàn thành
                  <span class="label label-success pull-right"><?php echo $todaycomplete ?></span></a>
                </li>
                <li><a href="<?php echo $this->url('weeklyplan/todaydeadline') ?>"><i class="fa fa-calendar-times-o"></i> Trễ Deadline
                  <span class="label label-danger pull-right"><?php echo $todaydeadline ?></span></a>
                </li>
              </ul>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /. box -->
          <div class="box box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">Tuần này</h3>

              <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="box-body no-padding">
              <ul class="nav nav-pills nav-stacked">
                <li><a href="<?php echo $this->url('weeklyplan/total') ?>"><i class="fa fa-calendar-o"></i> Tổng cộng
                  <span class="label label-primary pull-right"><?php echo $worktotal ?></span></a>
                </li>
                <li><a href="<?php echo $this->url('weeklyplan/working') ?>"><i class="fa fa-calendar-minus-o"></i> Đang thực hiện
                  <span class="label label-warning pull-right"><?php echo $working ?></span></a>
                </li>
                <li><a href="<?php echo $this->url('weeklyplan/workcomplete') ?>"><i class="fa fa-calendar-check-o"></i> Đã hoàn thành
                  <span class="label label-success pull-right"><?php echo $complete ?></span></a>
                </li>
                <li><a href="<?php echo $this->url('weeklyplan/deadline') ?>"><i class="fa fa-calendar-times-o"></i> Trễ Deadline
                  <span class="label label-danger pull-right"><?php echo $deadline ?></span></a>
                </li>
              </ul>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /. box -->
          <div class="box box-solid collapsed-box">
            <div class="box-header with-border">
              <h3 class="box-title">Tổng hợp</h3>

              <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                </button>
              </div>
            </div>
            <div class="box-body no-padding">
              <ul class="nav nav-pills nav-stacked">
                <li><a href="<?php echo $this->url('weeklyplan/weekcomplete') ?>"><i class="fa fa-circle-o text-red"></i> Hoàn thành trong tuần</a></li>
                <li><a href="<?php echo $this->url('weeklyplan/monthcomplete') ?>"><i class="fa fa-circle-o text-yellow"></i> Hoàn thành trong tháng</a></li>
                <li><a href="<?php echo $this->url('weeklyplan/totalcomplete') ?>"><i class="fa fa-circle-o text-light-blue"></i> Tổng số công việc</a></li>
              </ul>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-10">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"><?php echo $title ?></h3>

              <div class="box-tools pull-right">
                <div class="has-feedback">
                    <div class="input-group">
                      <input type="text" class="pull-right" id="reservation" value="<?php echo date('d/m/Y',strtotime($batdau)).' - '.date('d/m/Y',strtotime($ketthuc)) ?>">
                      <div class="form-control-feedback">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <input type="hidden" name="batdau" id="batdau" value="<?php echo $batdau ?>">
                      <input type="hidden" name="ketthuc" id="ketthuc" value="<?php echo $ketthuc ?>">
                    </div>
                  
                </div>
              </div>
              <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <div class="search-box">
        
                  <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
                  <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">

              </div>
              
              <div class="tablenav top">
                <div class="alignleft actions">
                    <select name="action" id="action">
                        <option value="-1" selected="selected">Chọn</option>
                        
                        <option value="delete">Xóa</option>
                    </select>
                    <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
                </div>
                <div class="alignleft actions">
                  <select name="m" id="chonloc">
                    <option  value="18446744073709">Hiển thị tất cả</option>
                    <option value="50">Hiển thị 50 giá trị</option>
                    <option value="100">Hiển thị 100 giá trị</option>
                    <option value="150">Hiển thị 150 giá trị</option>
                    <option selected="selected" value="200">Hiển thị 200 giá trị</option>
                  </select>
                  <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
                </div>
                <div class="alignleft actions">
                  <select id="sl_nv" name="sl_nv" style="width:150px">
                        <option value="0">Nhân viên</option>
                        <?php foreach ($staffs as $staff) { 
                          $randomcolor[$staff->staff_id] = '#' . $lib->rand_color();
                        ?>
                          <option value="<?php echo $staff->staff_id ?>"><?php echo $staff->staff_name ?></option>
                        <?php } ?>
                    </select>
                    <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
                </div>
                <div class="alignleft actions">
                  <select id="sl_status" name="sl_status" style="width:150px">
                        <option value="0">Công việc</option>
                        <?php foreach ($work_codes as $code) { ?>
                          <option value="<?php echo $code->work_plan_code_id ?>"><?php echo $code->work_plan_code_name ?></option>
                        <?php } ?>
                    </select>
                    <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
                </div>
                
              </div>
              <div class="add-box">
                    <a class="add_button" href="<?php echo $this->url('weeklyplan/export/'.strtotime($batdau).'/'.strtotime($ketthuc).'/'.$nv.'/'.$trangthai.'/'.$comp) ?>" >Export Excel</a>
                </div>
              <div style="clear:both"></div>
              <div class="table-responsive mailbox-messages">
                <table class="table_data" id="tblExport">
                  <thead>
                      <tr>
                          <th rowspan="2" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
                          <th rowspan="2" class="fix" >
                              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_plan_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'work_plan_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                          </th>
                          <th rowspan="2" class="fix">
                              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_plan_code_name','<?php echo $url_order ?>')">Mã CV <?php if ($order_by == 'work_plan_code_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                          </th>
                          <th rowspan="2" class="fix">
                              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_plan_name','<?php echo $url_order ?>')">Nội dung công việc <?php if ($order_by == 'work_plan_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                          </th>
                          <th rowspan="2" class="fix">
                              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_plan_number','<?php echo $url_order ?>')">SL <?php if ($order_by == 'work_plan_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                          </th>
                          <th rowspan="2" class="fix">
                              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_plan_unit','<?php echo $url_order ?>')">ĐVT <?php if ($order_by == 'work_plan_unit'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                          </th>
                          <th colspan="6" class="fix">
                              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','end_date','<?php echo $url_order ?>')">Ngày thực hiện <?php if ($order_by == 'end_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                          </th>
                          <th rowspan="2" class="fix">
                              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_plan_owner','<?php echo $url_order ?>')">PIC <?php if ($order_by == 'work_plan_owner'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                          </th>
                          <th rowspan="2" class="fix">
                              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_plan_comment','<?php echo $url_order ?>')">Ghi chú <?php if ($order_by == 'work_plan_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                          </th>
                          <th rowspan="2" class="fix">
                              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_plan_point','<?php echo $url_order ?>')">Thời gian <?php if ($order_by == 'work_plan_point'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                          </th>
                          <th rowspan="2" class="fix">
                              <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_plan_complete','<?php echo $url_order ?>')">OK <?php if ($order_by == 'work_plan_complete'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                          </th>
                          <th rowspan="2" class="fix"></th>
                      </tr>
                      <tr>
                        <th class="fix">T2</th>
                        <th class="fix">T3</th>
                        <th class="fix">T4</th>
                        <th class="fix">T5</th>
                        <th class="fix">T6</th>
                        <th class="fix">T7</th>
                      </tr>
                      
                     </thead>
                     <tbody>
                      <?php
                      $tong = 0;
                      $day = array();
                      for ($k = strtotime('last Sunday', strtotime($ketthuc)); $k <= strtotime($ketthuc); $k = strtotime('+1 day', $k)) {
                        $day[] = $k;
                      }
                      ?>
                      <?php foreach ($works as $work_plan) : 
                      $timeDiff = abs($work_plan->end_date - $work_plan->start_date);
                      $numberDays = $timeDiff/86400;
                      $numberDays = intval($numberDays+1);

                      $day_color = isset($randomcolor[$work_plan->work_plan_owner])?$randomcolor[$work_plan->work_plan_owner]:'rgba(255, 1, 60, 0.61)';
                      $tong += round($work_plan->work_plan_point/1,2);
                      ?>
                      
                          
                          <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $work_plan->work_plan_id ?>" class="edit_tr" <?php echo ($work_plan->work_plan_complete!=1 && $work_plan->end_date < strtotime(date('d-m-Y')) || ($work_plan->work_plan_complete==1 && $work_plan->work_plan_complete_date > $work_plan->end_date) )?'style="color:red"':null ?> >
                              
                              <td>
                                <?php if(($_SESSION['userid_logined'] == 1 || $_SESSION['userid_logined'] == $work_plan->create_user) && ($work_plan->end_date >= strtotime(date('d-m-Y')) )){ ?>
                                  <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $work_plan->work_plan_id ?>">
                                <?php } ?>
                              </td>
                              
                              <td  class="fix"><?php echo $i++; ?></td>
                              <td class="fix" data="<?php echo $work_plan->work_plan_code; ?>" id="work_plan_code_name_<?php echo $work_plan->work_plan_id; ?>"><?php echo $work_plan->work_plan_code_name; ?></td>
                              <td class="fix" id="work_plan_name_<?php echo $work_plan->work_plan_id; ?>"><?php echo $work_plan->work_plan_name; ?></td>
                              <td class="fix" id="work_plan_number_<?php echo $work_plan->work_plan_id; ?>"><?php echo $work_plan->work_plan_number; ?></td>
                              <td class="fix" id="work_plan_unit_<?php echo $work_plan->work_plan_id; ?>"><?php echo $work_plan->work_plan_unit; ?></td>
                              <td  class="fix" <?php echo ($day[1]>=$work_plan->start_date && $day[1]<=$work_plan->end_date)?'style="background:'.$day_color.'"':null ?> ></td>
                              <td  class="fix" <?php echo ($day[2]>=$work_plan->start_date && $day[2]<=$work_plan->end_date)?'style="background:'.$day_color.'"':null ?> ></td>
                              <td  class="fix" <?php echo ($day[3]>=$work_plan->start_date && $day[3]<=$work_plan->end_date)?'style="background:'.$day_color.'"':null ?> ></td>
                              <td  class="fix" <?php echo ($day[4]>=$work_plan->start_date && $day[4]<=$work_plan->end_date)?'style="background:'.$day_color.'"':null ?> ></td>
                              <td  class="fix" <?php echo ($day[5]>=$work_plan->start_date && $day[5]<=$work_plan->end_date)?'style="background:'.$day_color.'"':null ?> ></td>
                              <td  class="fix" <?php echo ($day[6]>=$work_plan->start_date && $day[6]<=$work_plan->end_date)?'style="background:'.$day_color.'"':null ?> ></td>
                              <td style="display:none" class="fix" id="work_plan_time_<?php echo $work_plan->work_plan_id; ?>"><?php echo date('d/m/Y',$work_plan->start_date).' - '.date('d/m/Y',$work_plan->end_date); ?></td>
                              <td class="fix" data="<?php echo $work_plan->work_plan_owner; ?>" id="work_plan_owner_<?php echo $work_plan->work_plan_id; ?>">
                                  <?php 
                                  $str = "";
                                      if($work_plan->work_plan_owner != ""){
                                          $contributors = explode(',', $work_plan->work_plan_owner);
                                          foreach ($contributors as $key) {
                                            $pieces = explode(' ', $staff_data['name'][$key]);
                                            $last_word = array_pop($pieces);
                                            if ($str == "") {
                                              $str = $last_word;
                                            }
                                            else{
                                              $str .= ",".$last_word;
                                            }
                                          }
                                        echo $str;
                                      }
                                      ?>
                              </td>
                              <td class="fix" id="work_plan_comment_<?php echo $work_plan->work_plan_id; ?>"><?php echo $work_plan->work_plan_comment; ?></td>
                              <td class="fix" id="work_plan_point_<?php echo $work_plan->work_plan_id; ?>"><?php echo $work_plan->work_plan_point; ?></td>
                              <td class="fix" id="work_plan_complete_<?php echo $work_plan->work_plan_id; ?>" data="<?php echo $work_plan->work_plan_complete; ?>"><input data="<?php echo $work_plan->work_plan_id; ?>" class="checkbox2" type="checkbox" <?php echo $work_plan->work_plan_complete==1?'checked disabled':null; ?> ></td>
                              <td style="display:none" class="fix" id="work_plan_complete_date_<?php echo $work_plan->work_plan_id; ?>"><?php echo $lib->hien_thi_ngay_thang($work_plan->work_plan_complete_date); ?></td>
                              <td style="display:none" class="fix" id="work_plan_result_<?php echo $work_plan->work_plan_id; ?>"><?php echo $work_plan->work_plan_result; ?></td>
                              <td style="display:none" class="fix" id="end_date_<?php echo $work_plan->work_plan_id; ?>"><?php echo $work_plan->end_date; ?></td>
                              <td style="display:none" class="fix" data="<?php echo $work_plan->work_plan_attachment; ?>" id="work_plan_attachment_<?php echo $work_plan->work_plan_id; ?>">
                                  <?php 
                                  $str = "";
                                      if($work_plan->work_plan_attachment != ""){
                                          $contributors = explode(',', $work_plan->work_plan_attachment);
                                          foreach ($contributors as $key) {
                                            $pieces = explode(' ', $attachment_data['name'][$key]);
                                            $last_word = array_pop($pieces);
                                            if ($str == "") {
                                              $str = $last_word;
                                            }
                                            else{
                                              $str .= ",".$last_word;
                                            }
                                          }
                                        echo $str;
                                      }
                                      ?>
                              </td>
                              <td class="pull-right">
                                <?php if($_SESSION['userid_logined'] == 1 || ($_SESSION['userid_logined'] == $work_plan->create_user && $work_plan->end_date >= strtotime(date('d-m-Y')) ) ){ ?>
                                  <button class="btn btn-sm btn-flat btn-danger" onclick="del(<?php echo $work_plan->work_plan_id ?>)" ><i class="fa fa-remove"></i></button>
                                <?php } ?>
                              </td>
                          </tr>


                      <?php endforeach; ?>
                      <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
                          <th colspan="3" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                              Tổng thời gian làm việc
                          </th>
                          <td class="fix" colspan="11" ></td>
                          <td class="fix" ><?php echo $lib->formatMoney($tong) ?></td>
                          <td class="fix" ></td>
                          <td class="fix" ></td>
                      </tr>
                     </tbody>
                  </table>
                </div>
                
              <!-- /.mail-box-messages -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer no-padding">
              <div class="mailbox-controls">
                <?php
                $this->helper('slidePaginator');
                ?>
                <!-- /.pull-right -->
              </div>
            </div>
          </div>
          <!-- /. box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->

<div class="add-field">
  <form id="add_work" method="post" action="" enctype="multipart/form-data">
    <div class="box box-info">
      <div class="box-body">
        <div class="col-md-6">
          <div class="input-group">
            <label>Mã CV</label>
            <select style="width:200px" name="work_plan_code_name" id="work_plan_code_name" tabindex="1" required="required">
              <?php foreach ($work_codes as $work_code) { ?>
                <option value="<?php echo $work_code->work_plan_code_id ?>" ><?php echo $work_code->work_plan_code_name ?></option>
              <?php } ?>
            </select>
          </div>
          <div class="input-group">
            <label>Nội dung công việc</label>
            <input type="text" name="work_plan_name" id="work_plan_name" tabindex="2" required="required" maxlength="35">
          </div>
          <div class="input-group">
            <div style="padding-left:0" class="col-md-6">
              <label>Số lượng</label>
              <input style="width:50px" type="text" name="work_plan_number" id="work_plan_number" tabindex="3" value="1" required="required">
            </div>
            <div class="col-md-6">
              <label>ĐVT</label>
              <input style="width:80px" type="text" name="work_plan_unit" id="work_plan_unit" tabindex="3" required="required">
            </div>
          </div>
          <div class="input-group">
            <label>Ngày thực hiện</label>
            <input type="text" name="work_plan_time" id="work_plan_time" tabindex="4" required="required" >
          </div>
          <div class="input-group">
            <label>Người thực hiện</label>
            <select style="width:200px" class="form-control select2" multiple="multiple" name="work_plan_owner" id="work_plan_owner" tabindex="5" required="required">
              <?php foreach ($staffs as $staff) { ?>
                <option <?php echo $staff->staff_id==$staff_info->staff_id?'selected':null ?> value="<?php echo $staff->staff_id ?>" ><?php echo $staff->staff_name ?></option>
              <?php } ?>
            </select>
          </div>
          
          
        </div>
        <div class="col-md-6">
          <div class="input-group">
            <label>Ghi chú</label>
            <textarea name="work_plan_comment" id="work_plan_comment" tabindex="6" maxlength="30"></textarea>
          </div>
          
          <div class="input-group">
            <label>Thời gian (Giờ:phút)</label>
            <input style="width:50px" type="text" name="work_plan_point" id="work_plan_point" tabindex="7" required="required" placeholder="Giờ" >
            <input style="width:50px" type="text" name="work_plan_point2" id="work_plan_point2" tabindex="8" placeholder="Phút" >
          </div>
          <div class="input-group">
            <input type="checkbox" name="work_plan_complete" id="work_plan_complete" value="1" tabindex="9"> Đã hoàn thành
            <input class="ngay" style="width:80px" type="text" name="work_plan_complete_date" id="work_plan_complete_date" tabindex="10" disabled >
          </div>
          <div class="input-group">
            <label>Kết quả</label>
            <textarea name="work_plan_result" id="work_plan_result" tabindex="11" maxlength="50" disabled></textarea>
          </div>
          <div class="input-group">
              <label><i class="fa fa-paperclip"></i> Đính kèm </label>
              <input type="file" name="attachment[]" id="attachment" multiple>
              <div id="show-attach">
                
              </div>
          </div>
        </div>
        <div class="col-md-12">
            <div class="box-footer">
            <input type="hidden" readonly id="yes" name="yes" required="required" >
            <button type="submit" class="btn btn-primary" tabindex="12">Hoàn tất</button>
            <button type="reset" class="btn" tabindex="13">Nhập lại</button>
          </div>
          <div class="box-footer">
            <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>

<div id="hoanthanh"></div><!-- /.modal -->

<div id="dialogContent" title="Hoàn thành">
    
    
    <form action="#" method="post" id="editForm">
        
        <label>
            <span>Ngày hoàn thành: </span>
            <input class="ngay" type="text" id="i_work_plan_complete_date" name="i_work_plan_complete_date" value="" required="required" />
        </label>
        <label>
            <span>Kết quả: </span><br>
            <input type="text" id="i_work_plan_result" name="i_work_plan_result" value="" required="required" />
            <input type="hidden" id="i_work_plan" name="i_work_plan" value="" required="required" />
            <input type="hidden" id="i_work_plan_complete" name="i_work_plan_complete" value="" required="required" />
        </label>
        
    </form>
</div>

<script type="text/javascript">
$('html').click(function(e) {

    $('#customer_list_id').slideUp(200);

});
function add_click(){
  $('#yes').val("");
  $('.add-field').slideDown(500);
  $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   

  $('#work_plan_code_name').val("");
  $('#work_plan_code_name').attr("data","");
  $('#work_plan_name').val("");
  var staff = ["<?php echo $staff_info->staff_id ?>"];
  $('#work_plan_owner option[value='+staff+']').attr("selected",'selected');
  $('#work_plan_owner').val(staff).trigger("change");
  $('#work_plan_comment').val("");
  $('#work_plan_point').val("");
  $('#work_plan_complete').prop("checked",false);
  $('#work_plan_complete_date').val("");
  $('#work_plan_number').val(1);
  $('#work_plan_unit').val("");
  $('#work_plan_result').val("");
  $('#work_plan_result').attr('disabled',true);
  $('#work_plan_result').attr('required',false);
  $('#show-attach').html("");
  //$('.detail').hide();
  $('.add-field input').attr('disabled',false);
  $('.add-field button').attr('disabled',false);

  $( ".add-field" ).dialog( "open" );
}

$('.edit_tr').click(function(e){
  if(!$('.checkbox').is(':focus') && e.target.nodeName != "I" && e.target.nodeName != "BUTTON" && e.target.nodeName != "A" && !$('.checkbox2').is(':focus') && e.target.nodeName != "INPUT"){
      if(!$('.checkbox').is(':focus') && !$('.checkbox2').is(':focus')){
          $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
      }

      var work_plan_code_name = $(this).find("#work_plan_code_name_"+$(this).attr('id')).text();
      var work_plan_code_id = $(this).find("#work_plan_code_name_"+$(this).attr('id')).attr('data');
      var work_plan_name = $(this).find("#work_plan_name_"+$(this).attr('id')).text();
      var work_plan_owner = $(this).find("#work_plan_owner_"+$(this).attr('id')).attr('data');
      var work_plan_time = $(this).find("#work_plan_time_"+$(this).attr('id')).text();
      var work_plan_comment = $(this).find("#work_plan_comment_"+$(this).attr('id')).text();
      var work_plan_complete = $(this).find("#work_plan_complete_"+$(this).attr('id')).attr('data');
      var work_plan_point = $(this).find("#work_plan_point_"+$(this).attr('id')).text();
      var end_date = $(this).find("#end_date_"+$(this).attr('id')).text();
      var today = "<?php echo strtotime(date('d-m-Y')) ?>";
      var work_plan_complete_date = $(this).find("#work_plan_complete_date_"+$(this).attr('id')).text();
      var work_plan_attachment = $(this).find("#work_plan_attachment_"+$(this).attr('id')).text();
      var work_plan_number = $(this).find("#work_plan_number_"+$(this).attr('id')).text();
      var work_plan_unit = $(this).find("#work_plan_unit_"+$(this).attr('id')).text();
      var work_plan_result = $(this).find("#work_plan_result_"+$(this).attr('id')).text();


      $('#yes').val($(this).attr('id'));

      $('#work_plan_code_name option[value='+work_plan_code_id+']').attr('selected','selected');
      //$('#work_plan_code_name').attr('data',work_plan_code_id);
      $('#work_plan_code_name').trigger("chosen:updated");

      $('#work_plan_name').val(work_plan_name);
      $('#work_plan_number').val(work_plan_number);
      $('#work_plan_time').val(work_plan_time);
      $('#work_plan_unit').val(work_plan_unit);
      $('#work_plan_result').val(work_plan_result);

      var entry = work_plan_owner.split(",");
      $('#work_plan_owner').val(entry).trigger("change");

      work_plan_point = work_plan_point.split('.');
      
      $('#work_plan_point').val(work_plan_point[0]);
      $('#work_plan_point2').val(Math.round(parseFloat('0.'+work_plan_point[1])*60) || null);

      $('#show-attach').empty();
      var attach = work_plan_attachment.split(",");
      for (var s = 0; s < attach.length; s++) {
        $('#show-attach').append('<p class="help-block '+attach[s].trim().replace('.','-')+'"><a target="_blank" href="<?php echo BASE_URL ?>/public/files/'+attach[s].trim()+'" >'+attach[s]+'</a> <i class="fa fa-trash remove-attach" data="'+attach[s].trim()+'" ></i></p>');
      };
      $('.remove-attach').click(function(){
        var data = $('#yes').val();
        var val = $(this).attr('data');
        $.ajax({
              url: '<?php echo BASE_URL ?>/weeklyplan/deleteattach',
              type: 'POST',
              data: {data:data, val:val},
              success:function(data){
                  $('.'+val.replace('.','-')).remove();
                  console.log(val);
              }
          });
      });

      $('#work_plan_comment').val(work_plan_comment);
      
      if (work_plan_complete == 1) {
        $('#work_plan_complete').prop("checked",true);
      }
      else{
        $('#work_plan_complete').prop("checked",false);
      }

      <?php if ($_SESSION['role_logined'] != 1) { ?>
      if (work_plan_complete == 1) {
        $('#work_plan_complete').prop("checked",true);
        $('.add-field input').attr('disabled',true);
        $('.add-field button').attr('disabled',true);
        $('#work_plan_result').attr('disabled',false);
        $('#work_plan_result').attr('required',true);
      }
      else{
        $('#work_plan_complete').prop("checked",false);
        $('.add-field input').attr('disabled',false);
        $('.add-field button').attr('disabled',false);
        $('#work_plan_result').attr('disabled',true);
        $('#work_plan_result').attr('required',false);
      }
      <?php } ?>

      $('#work_plan_complete_date').val(work_plan_complete_date);

      if (end_date <  today) {
        $('#work_plan_time').attr('disabled',true);
      }

      /*if (work_plan_number>0) {
        $('.detail').show();
      }
      else{
        $('.detail').hide();
      }*/
      


      $( ".add-field" ).dialog( "open" );
  }
});

$('.checkbox2').click(function(){
  var work_plan_id = $(this).attr('data');
  if ($(this).is(':checked')) {
    var work_plan_complete = 1;
    $('#i_work_plan').val(work_plan_id);
    $( "#dialogContent" ).dialog( "open" )
  }
  else{
    var id = work_plan_id;
    var work_plan_result = "";
    var work_plan_complete = 0;
    var work_plan_complete_date = "";

    $.ajax({
        url: '<?php echo BASE_URL ?>/weeklyplan/complete',
        type: 'POST',
        data: {data: id, work_plan_result: work_plan_result, work_plan_complete: work_plan_complete, work_plan_complete_date:work_plan_complete_date},
        success:function(data){
            setTimeout(function() {
          sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
        }, 200);
            
        }
    });
  }
   

      
});
//set up the dialog box.
$( "#dialogContent" ).dialog({
    autoOpen: false,
    modal: true,
    buttons: {
        OK: function() {
            var id = $('#i_work_plan').val();
            var work_plan_result = $('#i_work_plan_result').val();
            var work_plan_complete = 1;
            var work_plan_complete_date = $('#i_work_plan_complete_date').val();
                
                $.post("<?php echo BASE_URL ?>/weeklyplan/complete", {data: id, work_plan_result: work_plan_result, work_plan_complete: work_plan_complete, work_plan_complete_date:work_plan_complete_date},
                   function(data){
                    $("html, body").animate({ scrollTop: 0 }, 100);
                    setTimeout(function() {
                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                      }, 200);
                   
                   }); 
              
            $( this ).dialog( "close" );
        },        
        Cancel: function() {
            $( this ).dialog( "close" );
        }
    }
});

$('#work_plan_complete').click(function(){
  if ($(this).is(':checked')) {
    $('#work_plan_complete_date').attr("disabled",false);
    $('#work_plan_complete_date').val("<?php echo date('d/m/Y') ?>");
    $('#work_plan_result').attr('disabled',false);
    $('#work_plan_result').attr('required',true);
  }
  else{
    $('#work_plan_complete_date').attr("disabled",true);
    $('#work_plan_complete_date').val("");
    $('#work_plan_result').val("");
    $('#work_plan_result').attr('disabled',true);
    $('#work_plan_result').attr('required',false);
  }
  
    
});

$('#work_plan_name').keyup(function(){
  $(this).val(ucfirst($(this).val()));
});

$('#work_plan_code_name').keyup(function(){

      

  var keyword = $(this).val();

  $.ajax({

      url: '<?php echo BASE_URL ?>/weeklyplan/getworkname',

      type: 'POST',

      data: {keyword:keyword},

      success:function(data){

          $('#customer_list_id').slideDown(200);

          $('#customer_list_id').html(data);

      }

  });

  if ($('#work_plan_code_name').val() == "" || $('#work_plan_code_name').attr('data') == "") {

      //$('#loc_from').val("");

      $('#work_plan_code_name').attr('data',"");

      $('#work_plan_code_name').attr('code',false);

  }



});

$('#work_plan_code_name').on('keydown', function() {

  var key = event.keyCode || event.charCode;



  if( key == 8 || key == 46 ){

      $('#work_plan_code_name').attr('data',"");

  }

      

}); 

$(document).ready(function(){
  // Validate form
  $("#add_work").validate({
      errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
      rules: {
          
      },
      submitHandler: function(form) {
      
          var work_plan_code_name = $('#work_plan_code_name').attr('value');
          var work_plan_code_id = $('#work_plan_code_name').attr('data');
          var work_plan_name = $('#work_plan_name').attr('value');
          var work_plan_owner = $('#work_plan_owner').val();
          var work_plan_time = $('#work_plan_time').attr('value');
          var work_plan_comment = $('#work_plan_comment').attr('value');
          var work_plan_point = $('#work_plan_point').attr('value');
          var work_plan_point2 = $('#work_plan_point2').attr('value');
          var work_plan_complete_date = $('#work_plan_complete_date').attr('value');
          var work_plan_number = $('#work_plan_number').attr('value');
          var work_plan_unit = $('#work_plan_unit').attr('value');
          var work_plan_result = $('#work_plan_result').attr('value');
          
          if ($('#work_plan_complete').is(':checked')) {
            var work_plan_complete = 1;
          }
          else{
            var work_plan_complete = 0;
          }

          
          
          var yes = $('#yes').attr('value');
          
          var action      = "them";

          var formData = new FormData();
          formData.append('work_plan_code_name',work_plan_code_name);
          formData.append('work_plan_code_id',work_plan_code_id);
          formData.append('work_plan_name',work_plan_name);
          formData.append('work_plan_number',work_plan_number);
          formData.append('work_plan_unit',work_plan_unit);
          formData.append('work_plan_owner',work_plan_owner);
          formData.append('work_plan_time',work_plan_time);
          formData.append('work_plan_comment',work_plan_comment);
          formData.append('work_plan_point',work_plan_point);
          formData.append('work_plan_point2',work_plan_point2);
          formData.append('work_plan_complete',work_plan_complete);
          formData.append('work_plan_complete_date',work_plan_complete_date);
          formData.append('work_plan_result',work_plan_result);
          formData.append('yes',yes);
          var ins = document.getElementById('attachment').files.length;
          for (var x = 0; x < ins; x++) {
              formData.append("myfile[]", document.getElementById('attachment').files[x]);
          }
       
          $.ajax({
              type: "POST", // phương thức gởi đi
              url: "<?php echo BASE_URL ?>/weeklyplan/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
              data: formData, // giá trị post
              contentType: false,
              processData: false,
              success: function(answer){ // if everything goes well
                  //alert(answer);
                  $('#error').hide();
                  $('#error').slideToggle(100); // hiển thị thẻ div success
                  $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                  $('#error').fadeOut(10000);

                  if (yes != "") {
                      if (answer.trim() != "Thông tin này đã tồn tại" ) {
                        $('#hoanthanh').dialog('open');
                      
                      }
                  }
                  else{
                      if (answer.trim() != "Thông tin này đã tồn tại") {
                        $('#hoanthanh').dialog('open');
                      }
                  }
              }
          });
          return false;
           
       }
  });
});

var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');
var nv = "<?php echo $nv ?>";
$('#sl_nv option[value='+nv+']').attr('selected','selected');
var t = "<?php echo $trangthai ?>";
$('#sl_status option[value='+t+']').attr('selected','selected');

$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Công việc",
    hide: 'fold',
    show: 'blind'
});
$( "#hoanthanh" ).dialog({

    autoOpen: false,

    modal: true,

    width: "auto",

    maxHeight: $(window).height()-50,

    title: "Thông báo",

    hide: 'fold',

    show: 'blind',

    buttons: {

        'Thêm công việc': function() {

          $( this ).dialog( "close" );

          add_click();

        },
        'Kết thúc': function(){

          setTimeout(function() {
            searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
          }, 100);

          $( this ).dialog( "close" );

        } ,       


    }

});
$('.number').keyup(function(event) {

        // skip for arrow keys
    if(event.which >= 37 && event.which <= 40) return;

    // format number
    $(this).val(function(index, value) {
      return value
        .replace(/[^0-9-.]/g, "")
      ;
    });
  });



function set_item_work(value,name) {

    // change input value

    $('#work_plan_code_name').val(name);

    $("#work_plan_code_name").attr("data",value);

    $("#work_plan_code_name").attr("code",'true');



    // hide proposition list

    $('#customer_list_id').hide();

    $('#work_plan_code_name').focus();

     
}

function del(id)
{
  if($('.add-field') != null)
  {
    $('.add-field').slideUp();
  }
  var r = confirm("Bạn có chắc chắn muốn xóa không?");
  if (r == true){
    //$('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
    $.post("<?php echo $this->url('workplan') ?>/delete", {data: id},
       function(data){
        //alert(data);
        if (data.trim() != 'Bạn không có quyền thực hiện thao tác này') {
          $('tr#'+id).remove(); 
          //$('#loading').fadeOut(500); 
        };
        //$('#loading').fadeOut(500);
        $("html, body").animate({ scrollTop: 0 }, 100);
       
       }); 
  }
}
function action(){
  
    var action       = $('#action').attr('value');
    if(action != -1)
    {
      if($('.add-field') !== null)
        {
          $('.add-field').fadeOut();
        }
      var del = [];
      ids = $('input:checkbox.checkbox:checked').map(function() { return del.push(this.value); });
      
       if(action=='delete'){
         var r = confirm("Bạn có chắc chắn muốn xóa không?");
        if (r == true){
          //$('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
           $.ajax({
            url: "<?php echo $this->url('workplan') ?>/delete",   
            type: 'POST',   
            data: "xoa="+del,   
            success:function(answer){ 
              for(var i=0; i<del.length; i++)
                 $('tr#'+del[i]).remove();
              //$('#loading').fadeOut(500); 
              $("html, body").animate({ scrollTop: 0 }, 100);
            }
          });
        }
       }
       
    }
  
}
</script>
<!-- Select2 -->
<link rel="stylesheet" href="<?php echo BASE_URL ?>/public/js/plugins/select2/select2.min.css">
<script src="<?php echo BASE_URL ?>/public/js/plugins/select2/select2.full.min.js"></script>
<!-- daterange picker -->
<link rel="stylesheet" href="<?php echo BASE_URL ?>/public/js/plugins/daterangepicker/daterangepicker.css">
<script src="<?php echo BASE_URL ?>/public/js/plugins/daterangepicker/moment.min.js"></script>
<script src="<?php echo BASE_URL ?>/public/js/plugins/daterangepicker/daterangepicker.js"></script>
<script type="text/javascript">
$(function () {
  $('body').addClass('sidebar-collapse');

  $("#work_plan_code_name").chosen();
  $("#work_plan_code_name_chosen").css({'width':'150px'});

  $(".select2").select2();
    //Date range picker
    $('#reservation').daterangepicker({
      locale: {
        format: 'DD/MM/YYYY'
      },
    });

    $('#reservation').on('apply.daterangepicker', function(ev, picker) {
      $('#batdau').val(picker.startDate.format('DD-MM-YYYY'));
      $('#ketthuc').val(picker.endDate.format('DD-MM-YYYY'));
        searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
    });

    $('#work_plan_time').daterangepicker({
      locale: {
        format: 'DD/MM/YYYY'
      },
      minDate: '<?php echo date("d/m/Y",strtotime("monday this week")) ?>',
      maxDate: '<?php echo date("d/m/Y",strtotime($ketthuc)+604800) ?>',
    });
});

var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd/mm/yy',
        firstDay: 1,
        isRTL: false,
        showWeek: true,
        weekHeader: 'Tuần',
        showButtonPanel: true,
        maxDate: "+1d",
        minDate: "-5d",
         
    };  
    $(".ngay").datepicker(pickerOpts4);
</script>
<style type="text/css">
.daterangepicker_input{
  width: 50%;
}
.daterangepicker.dropdown-menu, .select2-container{
  z-index: 9999999;
}
#customer_list_id, .modal {
  z-index: 99999999;
}
.remove-attach{
  cursor: pointer;
}
</style>