<?php
$url_order = 'ASC';
if ($order_by == 'tire_price_discount_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_brand_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_size_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_pattern_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> BẢNG GIÁ LỐP</h1></center>
<div class="add-box">
    <?php if($_SESSION['role_logined']==1){ ?>
    <a class="add_button" onClick="add_click();">Nhập mới</a>
    <a class="add_button" id="import_excel" href="<?= $this->url('tirepricediscount/import')?>">Import Excel</a>
    <?php } ?>
    <a class="add_button" id="btnExport" >Export Excel</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Search">
        <input type="button" name="" id="search-submit" class="button-search" value="Search" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
       
    </div>
    <div class="tablenav top">

    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Select</option>
                
                <option value="delete">Delete</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Apply" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">All</option>
			<option value="15">15 items</option>
            <option value="20">20 items</option>
            <option value="50">50 items</option>
            <option selected="selected" value="100">100 items</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Apply" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

        
      </div>

</div>

<table class="table_data" id="tblExport">
<thead>
    <tr>
        <th rowspan="2" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th rowspan="2" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_price_discount_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'tire_price_discount_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_brand_name','<?php echo $url_order ?>')">Thương hiệu <?php if ($order_by == 'tire_brand_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_size_number','<?php echo $url_order ?>')">Kích cỡ <?php if ($order_by == 'tire_size_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_pattern_name','<?php echo $url_order ?>')">Mã gai <?php if ($order_by == 'tire_pattern_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_price','<?php echo $url_order ?>')">Giá công khai <?php if ($order_by == 'tire_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th colspan="10" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_retail','<?php echo $url_order ?>')">Chiết khấu theo sản lượng <?php if ($order_by == 'tire_retail'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','start_date','<?php echo $url_order ?>')">Từ ngày <?php if ($order_by == 'start_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','end_date','<?php echo $url_order ?>')">Đến ngày <?php if ($order_by == 'end_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th rowspan="2" class="fix"></th>
    </tr>
    <tr>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_retail','<?php echo $url_order ?>')">10 <?php if ($order_by == 'tire_retail'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_20','<?php echo $url_order ?>')">20 <?php if ($order_by == 'tire_20'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_40','<?php echo $url_order ?>')">40 <?php if ($order_by == 'tire_40'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_60','<?php echo $url_order ?>')">60 <?php if ($order_by == 'tire_60'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_80','<?php echo $url_order ?>')">80 <?php if ($order_by == 'tire_80'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_100','<?php echo $url_order ?>')">100 <?php if ($order_by == 'tire_100'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_120','<?php echo $url_order ?>')">120 <?php if ($order_by == 'tire_120'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_150','<?php echo $url_order ?>')">150 <?php if ($order_by == 'tire_150'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_180','<?php echo $url_order ?>')">180 <?php if ($order_by == 'tire_180'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_cont','<?php echo $url_order ?>')">Nguyên cont <?php if ($order_by == 'tire_cont'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($tires as $tire) : ?>
    
        
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $tire->tire_price_discount_id ?>" class="edit_tr">
            
            <td>
                <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $tire->tire_price_discount_id ?>">
            </td>
            
            <td  class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="tire_brand_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $tire->tire_brand_name; ?></td>
            <td class="fix" id="tire_size_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $tire->tire_size_number; ?></td>
            <td class="fix" id="tire_pattern_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $tire->tire_pattern_name; ?></td>
            <td class="fix" id="tire_price_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_price); ?></td>
            <td class="fix" id="tire_retail_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_retail); ?></td>
            <td class="fix" id="tire_20_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_20); ?></td>
            <td class="fix" id="tire_40_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_40); ?></td>
            <td class="fix" id="tire_60_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_60); ?></td>
            <td class="fix" id="tire_80_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_80); ?></td>
            <td class="fix" id="tire_100_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_100); ?></td>
            <td class="fix" id="tire_120_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_120); ?></td>
            <td class="fix" id="tire_150_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_150); ?></td>
            <td class="fix" id="tire_180_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_180); ?></td>
            <td class="fix" id="tire_cont_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->formatMoney($tire->tire_cont); ?></td>
            <td class="fix" id="start_date_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->hien_thi_ngay_thang($tire->start_date); ?></td>
            <td class="fix" id="end_date_<?php echo $tire->tire_price_discount_id; ?>"><?php echo $lib->hien_thi_ngay_thang($tire->end_date); ?></td>
            <td>
                <?php if($_SESSION['role_logined']==1){ ?>
                <button class="error" onclick="del(<?php echo $tire->tire_price_discount_id ?>)" >Xóa</button>
                <?php } ?>
               
            </td>
        </tr>


    <?php endforeach; ?>
     
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div style="display:none" id="lasted"></div>
<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Bảng giá </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_tire" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            
                            <td>Thương hiệu</td>
                            <td>
                                <select name="tire_brand" id="tire_brand" tabindex="1"  required="required">
                                    <?php foreach ($tire_brands as $tire_brand) { ?>
                                    <option value="<?php echo $tire_brand->tire_brand_id ?>"><?php echo $tire_brand->tire_brand_name ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>Kích cỡ</td>
                            <td>
                                <select name="tire_size" id="tire_size" tabindex="2"  required="required">
                                    <?php foreach ($tire_sizes as $tire_size) { ?>
                                    <option value="<?php echo $tire_size->tire_size_id ?>"><?php echo $tire_size->tire_size_number ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>Mã gai</td>
                            <td>
                                <select name="tire_pattern" id="tire_pattern" tabindex="3"  required="required">
                                    <?php foreach ($tire_patterns as $tire_pattern) { ?>
                                    <option value="<?php echo $tire_pattern->tire_pattern_id ?>"><?php echo $tire_pattern->tire_pattern_name ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>Giá công khai</td>
                            <td><input  type="text" class="numbers" id="tire_price"  name="tire_price" tabindex="6"  required="required" ></td>
                            <td>Giá bán lẻ</td>
                            <td><input  type="text" class="numbers" id="tire_retail"  name="tire_retail" tabindex="7"  required="required" ></td>
                            <td>Sản lượng 20</td>
                            <td><input  type="text" class="numbers" id="tire_20"  name="tire_20" tabindex="8"  required="required" ></td>
                            
                        </tr>
                        <tr>
                            
                            <td>Sản lượng 40</td>
                            <td><input  type="text" class="numbers" id="tire_40"  name="tire_40" tabindex="9"  required="required" ></td>
                            <td>Sản lượng 60</td>
                            <td><input  type="text" class="numbers" id="tire_60"  name="tire_60" tabindex="10"  required="required" ></td>
                            <td>Sản lượng 80</td>
                            <td><input  type="text" class="numbers" id="tire_80"  name="tire_80" tabindex="11"  required="required" ></td>
                            
                            
                        </tr>
                        <tr>
                            <td>Sản lượng 100</td>
                            <td><input  type="text" class="numbers" id="tire_100"  name="tire_100" tabindex="12"  required="required" ></td>
                            <td>Sản lượng 120</td>
                            <td><input  type="text" class="numbers" id="tire_120"  name="tire_120" tabindex="13"  required="required" ></td>
                            <td>Sản lượng 150</td>
                            <td><input  type="text" class="numbers" id="tire_150"  name="tire_150" tabindex="14"  required="required" ></td>
                            
                        </tr>
                        <tr>
                            <td>Sản lượng 180</td>
                            <td><input  type="text" class="numbers" id="tire_180"  name="tire_180" tabindex="15"  required="required" ></td>
                            <td>Giá nguyên cont</td>
                            <td><input  type="text" class="numbers" id="tire_cont"  name="tire_cont" tabindex="16"  required="required" ></td>
                        </tr>
                        <tr>
                            <td>Từ ngày</td>
                            <td>
                                <input  type="text" class="ngay" id="start_date"  name="start_date" tabindex="17"  required="required" >
                            </td>
                            <td>Đến ngày</td>
                            <td>
                                <input  type="text" class="ngay" id="end_date"  name="end_date" tabindex="18"  required="required" >
                            </td>
                        </tr>
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>
                                <input type="submit" name="submit" value="Submit" tabindex="19" <?php echo $_SESSION['role_logined']!=1?'disabled':null ?> >
                                
                            </td>
                            <td>
                                <input type="reset" name="reset" value="Reset" tabindex="20">
                            </td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>


<script type="text/javascript">


  
$('.add-field').hide();  


$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);   
    }
    
});



    $('.edit_tr').click(function(e){
        if(e.target != '[object HTMLButtonElement]' && e.target != '[object HTMLSpanElement]' && !$('.checkbox').is(':focus')) { 
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            
            var tire_brand = $(this).find("#tire_brand_"+$(this).attr('id')).text();
            var tire_size = $(this).find("#tire_size_"+$(this).attr('id')).text();
            var tire_pattern = $(this).find("#tire_pattern_"+$(this).attr('id')).text();
            var tire_price = $(this).find("#tire_price_"+$(this).attr('id')).text();
            var tire_retail = $(this).find("#tire_retail_"+$(this).attr('id')).text();
            var tire_20 = $(this).find("#tire_20_"+$(this).attr('id')).text();
            var tire_40 = $(this).find("#tire_40_"+$(this).attr('id')).text();
            var tire_60 = $(this).find("#tire_60_"+$(this).attr('id')).text();
            var tire_80 = $(this).find("#tire_80_"+$(this).attr('id')).text();
            var tire_100 = $(this).find("#tire_100_"+$(this).attr('id')).text();
            var tire_120 = $(this).find("#tire_120_"+$(this).attr('id')).text();
            var tire_150 = $(this).find("#tire_150_"+$(this).attr('id')).text();
            var tire_180 = $(this).find("#tire_180_"+$(this).attr('id')).text();
            var tire_cont = $(this).find("#tire_cont_"+$(this).attr('id')).text();
            var start = $(this).find("#start_date_"+$(this).attr('id')).text();
            var end = $(this).find("#end_date_"+$(this).attr('id')).text();
            //alert(cost_code);
            $('#yes').val($(this).attr('id'));
            
            $('#tire_brand option:contains('+tire_brand+')').attr('selected','selected');
            $('#tire_size option:contains('+tire_size+')').attr('selected','selected');
            $('#tire_pattern option:contains('+tire_pattern+')').attr('selected','selected');
            $('#tire_price').val(tire_price);
            $('#tire_retail').val(tire_retail);
            $('#tire_20').val(tire_20);
            $('#tire_40').val(tire_40);
            $('#tire_60').val(tire_60);
            $('#tire_80').val(tire_80);
            $('#tire_100').val(tire_100);
            $('#tire_120').val(tire_120);
            $('#tire_150').val(tire_150);
            $('#tire_180').val(tire_180);
            $('#tire_cont').val(tire_cont);
            $('#start_date').val(start.replace(/\//g,"-"));
            $('#end_date').val(end.replace(/\//g,"-"));
            

            $( ".add-field" ).dialog( "open" );
        }

        
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
     
        $('#tire_price').val(0);
        $('#tire_retail').val(0);
        $('#tire_20').val(0);
        $('#tire_40').val(0);
        $('#tire_60').val(0);
        $('#tire_80').val(0);
        $('#tire_100').val(0);
        $('#tire_120').val(0);
        $('#tire_150').val(0);
        $('#tire_180').val(0);
        $('#tire_cont').val(0);
        $('#start_date').val("");
        $('#end_date').val("");
                
        $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

    $( ".add-field" ).dialog( "open" );
}


$(document).ready(function(){
            // Validate form
            $("#add_tire").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var tire_brand = $('#tire_brand').attr('value');
                    var tire_size = $('#tire_size').attr('value');
                    var tire_pattern = $('#tire_pattern').attr('value');
                    var tire_price = $('#tire_price').attr('value');
                    var tire_retail = $('#tire_retail').attr('value');
                    var tire_20 = $('#tire_20').attr('value');
                    var tire_40 = $('#tire_40').attr('value');
                    var tire_60 = $('#tire_60').attr('value');
                    var tire_80 = $('#tire_80').attr('value');
                    var tire_100 = $('#tire_100').attr('value');
                    var tire_120 = $('#tire_120').attr('value');
                    var tire_150 = $('#tire_150').attr('value');
                    var tire_180 = $('#tire_180').attr('value');
                    var tire_cont = $('#tire_cont').attr('value');
                    var start_date = $('#start_date').attr('value');
                    var end_date = $('#end_date').attr('value');

                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/tirepricediscount/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            
                            tire_brand: tire_brand,
                            tire_size: tire_size,
                            tire_pattern: tire_pattern,
                            tire_price: tire_price,
                            tire_retail: tire_retail,
                            tire_20: tire_20,
                            tire_40: tire_40,
                            tire_60: tire_60,
                            tire_80: tire_80,
                            tire_100: tire_100,
                            tire_120: tire_120,
                            tire_150: tire_150,
                            tire_180: tire_180,
                            tire_cont: tire_cont,
                            start_date: start_date,
                            end_date: end_date,
                            yes: yes,

                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

                            }
                            else{
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                
                            }
                        }
                    });
                    return false;
                     
                 }
            });


});

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });


 
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');


</script>
</div>

<script type="text/javascript">


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Bảng giá",
    hide: 'fold',
    show: 'blind'
});


var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onSelect: function(dateStr) {
          if ($('#end_date').val()=="") {
            var d = $.datepicker.parseDate('dd-mm-yy', dateStr);
            //var years = parseInt(10, 10);

            //d.setFullYear(d.getFullYear() + years);

            $('#end_date').datepicker('setDate', d);
          }
            
        },
        onClose: function(selectedDate) {
                
                $( "#end_date" ).datepicker( "option", "minDate", selectedDate );

         },
    }; 
    $("#start_date").datepicker(pickerOpts);

    var pickerOpts2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#start_date" ).datepicker( "option", "maxDate", selectedDate );

         },
    }; 
    $("#end_date").datepicker(pickerOpts2);

$('.numbers').keyup(function(event) {

      // skip for arrow keys
  if(event.which >= 37 && event.which <= 40) return;

  // format number
  $(this).val(function(index, value) {
    return value
      .replace(/\D/g, "")
      .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
    ;
  });
});
</script>

