
<?php
$url_order = 'ASC';
if ($order_by == 'payable_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'expect_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'week')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'money')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bank_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'vendor')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'cost_type')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> DỰ CHI </h1></center>

	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <div class="add-box">
             
        
            <select style="width: 120px;" name="sl_status" id="sl_status">
                <option selected="selected" value="0">Chưa duyệt</option>
                <option  value="1">Đã duyệt</option>
            </select>

            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');"> 
            
        </div>
    </div>
    <div class="tablenav top">
        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Duyệt</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action_approve();">
        </div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="5">Hiển thị 5 giá trị</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="15">Hiển thị 15 giá trị</option>
            <option selected="selected" value="20">Hiển thị 20 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

        <div class="add-box">
            <a class="add_button" id="btnExport" >Export Excel</a>
        </div>


      </div>

</div>

<table id="tblExport" class="table_data">
    <thead>
    <tr>
        <th style="width:20px" rowspan="2" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th style="width:35px" rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','payable_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'payable_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','type','<?php echo $url_order ?>')">Mảng <?php if ($order_by == 'type'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','code','<?php echo $url_order ?>')">Code <?php if ($order_by == 'code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th  rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','cost_type','<?php echo $url_order ?>')">Loại chi phí <?php if ($order_by == 'cost_type'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix" colspan="2">
            <a class="sort">Phải trả </a>
        </th>  
        <th  class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money','<?php echo $url_order ?>')">Nợ <?php if ($order_by == 'money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>   
          
        <th  class="fix" colspan="2" >
            <a class="sort" >Dự kiến trả </a>
        </th> 
        
        <th class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bank','<?php echo $url_order ?>')">Tài khoản đi <?php if ($order_by == 'bank'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        
        <th  class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Nội dung<?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Ghi chú<?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix" rowspan="2" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','username','<?php echo $url_order ?>')">Sale <?php if ($order_by == 'username'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix" rowspan="2" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','username','<?php echo $url_order ?>')">Kế toán <?php if ($order_by == 'username'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix" rowspan="2" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','username','<?php echo $url_order ?>')">Duyệt <?php if ($order_by == 'username'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix" rowspan="2" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','pending','<?php echo $url_order ?>')">Pending <?php if ($order_by == 'pending'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        
    </tr>
    <tr>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','vendor','<?php echo $url_order ?>')">Vendor <?php if ($order_by == 'vendor'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','expect_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'expect_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','week','<?php echo $url_order ?>')">Tuần <?php if ($order_by == 'week'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
    </tr>
    
   </thead>
    <tbody>
    <?php $tong = 0; $tongcon = 0; $tongtt = 0; ?>
    <?php foreach ($payables as $payable) : ?>
    <?php $tong += $payable->money; ?>
    <?php $tongtt += $payable->pay_money; ?>
    <?php $tongcon += ($payable->money-$payable->pay_money); ?>
    <?php
        if ($payable->sale_report > 0) {
            $link = 'salereport/index/'.$payable->code;
        }
        else if ($payable->agent > 0) {
            $link = 'agent/index/'.$payable->code;
        }
        else if ($payable->agent_manifest > 0) {
            $link = 'agentmanifest/index/'.$payable->code;
        }
        else if ($payable->trading > 0) {
            $link = 'trading/index/'.$payable->code;
        }
        else if ($payable->invoice > 0) {
            $link = 'invoice/index/'.$payable->invoice;
        }
    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $payable->payable_id ?>" class="edit_tr">
            <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $payable->payable_id ?>"></td>
            <td  class="fix"><?php echo $i++; ?></td>
            <td  class="fix" data="<?php echo $payable->type ?>" id="type_<?php echo $payable->payable_id; ?>"><?php echo $payable->type==1?"Sale":($payable->type==2?"Agent":($payable->type==3?"TCMT":"Trading")); ?></td>
            <td  class="fix" id="code_<?php echo $payable->payable_id; ?>"><a style="text-decoration: underline;" href="<?php echo $this->url($link) ?>"><?php echo $payable->code; ?></a></td>
            <td  class="fix" data="<?php echo $payable->cost_type; ?>" id="cost_type_<?php echo $payable->payable_id; ?>"><?php echo $payable->cost_type==1?'Trucking':($payable->cost_type==2?'Barging':($payable->cost_type==3?'Feeder':($payable->cost_type==4?'Thu hộ':($payable->cost_type==5?'Hoa hồng':($payable->cost_type==6?'TTHQ':($payable->cost_type==7?'Khác':null)))))); ?></td>
            
            <td  class="fix" data="<?php echo $payable->vendor; ?>" id="vendor_<?php echo $payable->payable_id; ?>"><?php echo isset($vendors['name'][$payable->vendor])?$vendors['name'][$payable->vendor]:null; ?></td>
            <td  class="fix" data="<?php echo $payable->customer; ?>" id="customer_<?php echo $payable->payable_id; ?>"><?php echo isset($customers['name'][$payable->customer])?$customers['name'][$payable->customer]:null; ?></td>
            
            
            <td  class="fix" id="money_<?php echo $payable->payable_id; ?>"><?php echo $lib->formatMoney($payable->money); ?></td>
            <td class="fix"  id="expect_date_<?php echo $payable->payable_id; ?>"><?php echo $lib->hien_thi_ngay_thang($payable->expect_date) ?></td>
            <td  class="fix" id="week_<?php echo $payable->payable_id; ?>"><?php echo $payable->week; ?></td>
            
            <td class="fix" id="source_<?php echo $payable->payable_id; ?>"><?php echo $payable->bank_name; ?></td>
            <td class="fix" id="comment_<?php echo $payable->payable_id; ?>"><?php echo $payable->comment; ?></td>  
            <td class="fix" id="comment_box_<?php echo $payable->payable_id; ?>"><a id="chat_<?php echo $payable->payable_id; ?>" class="add_button" href="<?= $this->url('comment/getcomment/1/'.$payable->payable_id.'/payable')?>">Chat</a></td>   
            
            <td class="fix" style="display:none" id="type_<?php echo $payable->payable_id; ?>"><?php echo $payable->type; ?></td>         
            <td class="fix" style="display:none" id="invoice_number_<?php echo $payable->payable_id; ?>"><?php echo $payable->invoice_number; ?></td> 
            <td class="fix" id="approve3_<?php echo $payable->payable_id; ?>"><?php echo isset($users['name'][$payable->approve3])?$users['name'][$payable->approve3]:(($_SESSION['role_logined']==3)?'<button data="'.$payable->payable_id.'" class="approve3">Duyệt</button>':null); ?></td>  
            <td class="fix" id="approve2_<?php echo $payable->payable_id; ?>"><?php echo isset($users['name'][$payable->approve2])?$users['name'][$payable->approve2]:(($_SESSION['role_logined']==8 || $_SESSION['role_logined']==9)?'<button data="'.$payable->payable_id.'" class="approve2">Duyệt</button>':null); ?></td>  
            <td class="fix" id="approve_<?php echo $payable->payable_id; ?>"><?php echo isset($users['name'][$payable->approve])?$users['name'][$payable->approve]:(($_SESSION['role_logined']==1 || $_SESSION['role_logined']==7 || $_SESSION['role_logined']==9)?'<button data="'.$payable->payable_id.'" class="approve">Duyệt</button>':null); ?></td>  
            <td class="fix" id="pending_<?php echo $payable->payable_id; ?>">
                <?php if($_SESSION['role_logined']==1 || $_SESSION['role_logined']==9){ ?>
                <button data="<?php echo $payable->payable_id ?>" value="<?php echo $payable->pending ?>" class="pending">
                    <?php echo $payable->pending==1?"Impending":"Pending" ?>
                </button>
                <?php }else{ echo $payable->pending==1?"Pending":null; } ?>
            </td>        
            
        </tr>
        
    <?php endforeach; ?>
    <tr style="text-align:center; font-weight: bold; color: red;">
        <td class="fix" colspan="7" >Tổng cộng</td>
        <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
        <td class="fix" colspan="7" ></td>
        <td class="fix" ></td>
        <td class="fix" ></td>
        
    </tr>
   </tbody>
</table>


<?php
$this->helper('slidePaginator');
?>

<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('pending/payable') ?>">&larr;</a></div>
<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');

$('.pending').click(function(){
    var id = $(this).attr("data");
    var val = $(this).attr("value");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        //$('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/payable/pending", {data: id, val: val},
           function(data){
            
            if (val==1) {
                $("html, body").animate({ scrollTop: 0 }, 100);
                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 100);
            }
            else
                $('#chat_'+id).click();
           
           }); 
      }

});

$('.approve').click(function(){
    var id = $(this).attr("data");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/payable/approve", {data: id},
           function(data){
            

            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});

$('.approve2').click(function(){
    var id = $(this).attr("data");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/payable/approve2", {data: id},
           function(data){
            

            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});

$('.approve3').click(function(){
    var id = $(this).attr("data");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/payable/approve3", {data: id},
           function(data){
            

            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});

$('.pay').click(function(){
    var id = $(this).attr("value");
    var source = $(this).attr("data");
    var money = $(this).attr("name");
    var pay_date = $(this).attr("alt");
    var invoice_number = $(this).attr("title");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/payable/pay", {data: id, source: source, money: money, pay_date: pay_date, invoice_number: invoice_number},
           function(data){
            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});
$('.source').change(function(){
    var val = $(this).val();
    $('.pay').attr('data',val);
    $(".source option[value="+val+"]").attr('selected', 'selected');
});
$('.money').keyup(function(event) {
        var val = $(this).val();
        $('.pay').attr('name',val);
    });
$('.pay_date').change(function(){
    var val = $(this).val();
    $('.pay').attr('alt',val);
    $('.pay_date').val(val);
});
$('.invoice_number').keyup(function(){
    var val = $(this).val();
    $('.pay').attr('title',val);
    $('.invoice_number').val(val);
});

var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".pay_date").datepicker(pickerOpay2);


var ch = "<?php echo $trangthai ?>";
$('#sl_status option[value='+ch+']').attr('selected','selected');

</script>
</div>

<style type="text/css">

.wrap {
    width: 100%;
    font-size: 12px;
}

.wrap table {
    width: 100%;
    table-layout: fixed;
}

.wrap td, .wrap th {
    width: 100px;
    word-wrap: break-word;
}

table.head tr td {
    background: #eee;
}

.inner_table {
    width: 100%;
    height: 300px;
    overflow-y: auto;
    
}

</style>

<script type="text/javascript">

$('.editButton')
    .button({ icons: { primary: "ui-icon-document" }})
    .click(function() {
        
        $('#i_payable').val($(this).attr('value'));
        $('#i_pay_date').val($(this).attr('alt'));
        $('#i_source option[value='+$(this).attr('data')+']').attr('selected','selected');
        $('#i_pay_money').val($(this).attr('name'));
        $('#i_invoice_number').val($(this).attr('title'));
        $('#i_pay_money').focus();

        var comment = $("#comment_"+$('#i_payable').val()).text();
        $('#i_comment').val(comment);

        $( "#dialogContent" ).dialog( "open" )
    });


//set up the dialog box.
$( "#dialogContent" ).dialog({
    autoOpen: false,
    modal: true,
    buttons: {
        OK: function() {
            var id = $('#i_payable').val();
            var source = $('#i_source').val();
            var money = $('#i_pay_money').val();
            var pay_date = $('#i_pay_date').val();
            var invoice_number = $('#i_invoice_number').val();
            var comment = $('#i_comment').val();
                
                $.post("<?php echo BASE_URL ?>/payable/pay", {data: id, source: source, money: money, pay_date: pay_date, invoice_number: invoice_number, comment: comment},
                   function(data){
                    //alert(data);
                    $("html, body").animate({ scrollTop: 0 }, 100);
                    setTimeout(function() {
                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                      }, 200);
                   
                   }); 
              
            $( this ).dialog( "close" );
        },        
        Cancel: function() {
            $( this ).dialog( "close" );
        }
    }
});

$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Dự chi",
    hide: 'fold',
    show: 'blind'
});

function action_approve(){
    var del = [];
      ids = $('input:checkbox.checkbox:checked').map(function() { return del.push(this.value); });
      
       if(action=='delete'){
         var r = confirm("Bạn có chắc chắn không?");
        if (r == true){
          $('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
           $.ajax({
            url: "<?php echo BASE_URL ?>/pending/approvepayable",   
            type: 'POST',   
            data: "xoa="+del,   
            success:function(answer){ 
              for(var i=0; i<del.length; i++)
                 $('tr#'+del[i]).remove();
              $('#loading').fadeOut(500); 
              $("html, body").animate({ scrollTop: 0 }, 100);
            }
          });
        }
       }
}

$(".add_button").click(function(){
    
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:500,
            width:400,
            resizable: false,
            title:'Chatting...',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        

        return false;
    });

$('#winpopup').on('dialogclose', function(event) {
     

            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 100);

 });
</script>