

<?php

$url_order = 'ASC';

if ($order_by == 'pending_payable_id')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'pending_payable_date')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'comment')

    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';



    $i = $sonews*$page-($sonews-1);



?>



<div id="loading"></div>

<div id="winpopup"></div>



<div id="content" style="padding:5px;">

    <center style="clear:both;margin-bottom: -30px;"><h1> CHI PHÍ LÔ HÀNG </h1></center>



	<div class="search-box">

        

        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">

        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">

        <div class="add-box">

             

        

            <select style="width: 120px;" name="sl_status" id="sl_status">

                <option selected="selected" value="0">Chưa duyệt</option>

                <option  value="1">Đã duyệt</option>

            </select>



            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');"> 

            

        </div>

    </div>

    <div class="tablenav top">

    	<div class="alignleft actions">

            <select name="action" id="action">

                <option value="-1" selected="selected">Chọn</option>

                

                <option value="delete">Duyệt</option>

            </select>

            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action_approve();">

        </div>

		<div class="alignleft actions">

		<select name="m" id="chonloc">

			<option  value="18446744073709">Hiển thị tất cả</option>

			<option value="5">Hiển thị 5 giá trị</option>

            <option value="10">Hiển thị 10 giá trị</option>

            <option value="15">Hiển thị 15 giá trị</option>

            <option selected="selected" value="20">Hiển thị 20 giá trị</option>

		</select>

		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		

        </div>



        <div class="add-box">

            <a class="add_button" id="btnExport" >Export Excel</a>

        </div>

      </div>



</div>



<table id="tblExport" class="table_data">

    <thead>

    <tr>

        <th style="width:20px" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>

        <th style="width:35px" class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','pending_payable_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'pending_payable_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','code','<?php echo $url_order ?>')">Code <?php if ($order_by == 'code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix" >

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money','<?php echo $url_order ?>')">Số tiền <?php if ($order_by == 'money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>  

        

          

        

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','revenue','<?php echo $url_order ?>')">Doanh thu<?php if ($order_by == 'revenue'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','cost','<?php echo $url_order ?>')">Chi phí<?php if ($order_by == 'cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','revenue','<?php echo $url_order ?>')">Lợi nhuận<?php if ($order_by == 'revenue'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Nội dung<?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Ghi chú<?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','approve3','<?php echo $url_order ?>')">Sale<?php if ($order_by == 'approve3'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','approve2','<?php echo $url_order ?>')">Kế toán<?php if ($order_by == 'approve2'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','approve','<?php echo $url_order ?>')">Duyệt<?php if ($order_by == 'approve'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        <th  class="fix">

            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','approve','<?php echo $url_order ?>')">Pending<?php if ($order_by == 'approve'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>

        </th>

        

    </tr>

    

   </thead>

        <tbody>

    

    <?php foreach ($costs as $cost) : ?>

    <?php

        if ($cost->sale_report > 0) {

            $link = 'salereport/index/'.$cost->code;

        }

        else if ($cost->agent > 0) {

            $link = 'agent/index/'.$cost->code;

        }

        else if ($cost->agent_manifest > 0) {

            $link = 'agentmanifest/index/'.$cost->code;

        }

        else if ($cost->trading > 0) {

            $link = 'trading/index/'.$cost->code;

        }

        else if ($cost->invoice > 0) {

            $link = 'invoice/index/'.$cost->invoice;

        }

    ?>

        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $cost->pending_payable_id ?>" class="edit_tr" >

            <td ><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $cost->pending_payable_id ?>"></td>

            <td  class="fix"><?php echo $i++; ?></td>

             <td  class="fix"  id="code_<?php echo $cost->pending_payable_id; ?>"><a style="text-decoration: underline;" href="<?php echo $this->url($link) ?>"><?php echo $cost->code ?></a></td>

            

            <td  class="fix" id="pending_payable_money_<?php echo $cost->pending_payable_id; ?>"><a style="text-decoration: underline;" href="<?php echo $this->url('pending/payable/'.$cost->code) ?>"><?php echo $lib->formatMoney($cost->money); ?></a></td>

               

             <td  class="fix" id="revenue_<?php echo $cost->pending_payable_id; ?>"><?php echo $lib->formatMoney($cost->revenue); ?></td>

             <td  class="fix" id="cost_<?php echo $cost->pending_payable_id; ?>"><?php echo $lib->formatMoney($cost->cost); ?></td>

             <td  class="fix" id="profit_<?php echo $cost->pending_payable_id; ?>"><?php echo $lib->formatMoney($cost->revenue-$cost->cost); ?></td>

             <td  class="fix" id="comment_<?php echo $cost->pending_payable_id; ?>"><?php echo $cost->comment; ?></td> 

             <td class="fix" id="comment_box_<?php echo $cost->pending_payable_id; ?>"><a id="chat_<?php echo $cost->pending_payable_id; ?>" class="add_button" href="<?= $this->url('comment/getcomment/1/'.$cost->pending_payable_id.'/pending_payable')?>">Chat</a></td> 

            <td class="fix" id="approve3_<?php echo $cost->pending_payable_id; ?>"><?php echo isset($users['name'][$cost->approve3])?$users['name'][$cost->approve3]:(($_SESSION['role_logined']==3)?'<button data="'.$cost->pending_payable_id.'" class="approve3">Duyệt</button>':null); ?></td>  

             <td class="fix" id="approve2_<?php echo $cost->pending_payable_id; ?>"><?php echo isset($users['name'][$cost->approve2])?$users['name'][$cost->approve2]:(($_SESSION['role_logined']==8 )?'<button data="'.$cost->pending_payable_id.'" class="approve2">Duyệt</button>':null); ?></td>  

             <td class="fix" id="approve_<?php echo $cost->pending_payable_id; ?>"><?php echo isset($users['name'][$cost->approve])?$users['name'][$cost->approve]:(($_SESSION['role_logined']==1 || $_SESSION['role_logined']==7 || $_SESSION['role_logined']==9)?'<button data="'.$cost->pending_payable_id.'" class="approve">Duyệt</button>':null); ?></td>     

             <td class="fix" id="pending_<?php echo $cost->pending_payable_id; ?>">

                <?php if($_SESSION['role_logined']==1 || $_SESSION['role_logined']==9){ ?>

                <button data="<?php echo $cost->pending_payable_id ?>" value="<?php echo $cost->pending ?>" class="pending">

                    <?php echo $cost->pending==1?"Impending":"Pending" ?>

                </button>

                <?php }else{ echo $cost->pending==1?"Pending":null; } ?>

            </td>  

             

        </tr>

    <?php endforeach; ?>

    

   </tbody>

    </table>







<?php

$this->helper('slidePaginator');

?>



<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>





<div style="display:none" id="lasted"></div>

<script type="text/javascript">

    var count = parseInt(<?php echo $lastID ?>);

    $('#lasted').html(count);



$("#import_excel").click(function(){

        $("#winpopup").dialog({

            draggable:true,

            modal: true,

            autoOpen: false,

            height:300,

            width:400,

            resizable: false,

            title:'Import Excel',

            

        });

        $("#winpopup").load($(this).attr('href'));

        $("#winpopup").dialog("open");

         

        return false;

    });



var x = "<?php echo $limit ?>";

$('#chonloc option[value='+x+']').attr('selected','selected');





$('.approve').click(function(){

    var id = $(this).attr("data");

    var r = confirm("Bạn có chắc chắn không?");

      if (r == true){

        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);

        $.post("<?php echo BASE_URL ?>/pending/approvesaleall", {data: id},

           function(data){

            



            $("html, body").animate({ scrollTop: 0 }, 100);

            setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);



            $('#loading').fadeOut(500);

           

           }); 

      }



});

$('.approve2').click(function(){

    var id = $(this).attr("data");

    var r = confirm("Bạn có chắc chắn không?");

      if (r == true){

        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);

        $.post("<?php echo BASE_URL ?>/pending/approvesale", {data: id},

           function(data){

            



            $("html, body").animate({ scrollTop: 0 }, 100);

            setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);



            $('#loading').fadeOut(500);

           

           }); 

      }



});

$('.approve3').click(function(){

    var id = $(this).attr("data");

    var r = confirm("Bạn có chắc chắn không?");

      if (r == true){

        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);

        $.post("<?php echo BASE_URL ?>/pending/approvesalefirst", {data: id},

           function(data){

            



            $("html, body").animate({ scrollTop: 0 }, 100);

            setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);



            $('#loading').fadeOut(500);

           

           }); 

      }



});



$('.pay').click(function(){

    var id = $(this).attr("value");

    var source = $(this).attr("data");

    var source_in = $(this).attr("tabindex");

    var money = $(this).attr("name");

    var pay_date = $(this).attr("alt");

    var money_in = $(this).attr("title");

    var r = confirm("Bạn có chắc chắn không?");

      if (r == true){

        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);

        $.post("<?php echo BASE_URL ?>/pending_payable/pay", {data: id, source: source, source_in: source_in,money: money, pay_date: pay_date, money_in: money_in},

           function(data){

            $("html, body").animate({ scrollTop: 0 }, 100);

            setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 200);



            $('#loading').fadeOut(500);

           

           }); 

      }



});

$('.source').change(function(){

    var val = $(this).val();

    $('.pay').attr('data',val);

    $(".source option[value="+val+"]").attr('selected', 'selected');

});

$('.money').keyup(function(event) {

        var val = $(this).val();

        $('.pay').attr('name',val);

    });

$('.pay_date').change(function(){

    var val = $(this).val();

    $('.pay').attr('alt',val);

    $('.pay_date').val(val);

});



var pickerOpay2 = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],

        dateFormat: 'dd-mm-yy',

        changeMonth: true,

        changeYear: true,

        yearRange: "-100:+0",

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true

    }; 

    $(".pay_date").datepicker(pickerOpay2);



    var pickerOpay3 = {

        closeText: "Đóng",

        currentText: "Hiện tại",

        nextText: "Tiếp",

        prevText: "Quay lại",

        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],

        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],

        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],

        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],

        dateFormat: 'dd-mm-yy',

        changeMonth: true,

        changeYear: true,

        yearRange: "-100:+0",

        firstDay: 1,

        isRTL: false,

        showButtonPanel: true

    }; 

    $("#pay_date").datepicker(pickerOpay3);



var ch = "<?php echo $trangthai ?>";

$('#sl_status option[value='+ch+']').attr('selected','selected');



    



</script>

</div>

<style type="text/css">



.wrap {

    width: 100%;

    font-size: 12px;

}



.wrap table {

    width: 100%;

    table-layout: fixed;

}



.wrap td, .wrap th {

    width: 100px;

    word-wrap: break-word;

}



table.head tr td {

    background: #eee;

}



.inner_table {

    width: 100%;

    height: 300px;

    overflow-y: auto;

    

}



</style>



<script type="text/javascript">



$('.editButton')

    .button({ icons: { primary: "ui-icon-document" }})

    .click(function() {

        

        $('#i_pending_payable').val($(this).attr('value'));

        $('#i_pay_date').val($(this).attr('alt'));

        $('#i_source option[value='+$(this).attr('data')+']').attr('selected','selected');

        $('#i_pay_money').val($(this).attr('name'));

        $('#i_source_in option[value='+$(this).attr('tabindex')+']').attr('selected','selected');

        $('#i_money_in').val($(this).attr('title'));

        $('#i_pay_money').focus();



        $( "#dialogContent" ).dialog( "open" )

    });





//set up the dialog box.

$( "#dialogContent" ).dialog({

    autoOpen: false,

    modal: true,

    buttons: {

        OK: function() {

            var id = $('#i_pending_payable').val();

            var source = $('#i_source').val();

            var source_in = $('#i_source_in').val();

            var money = $('#i_pay_money').val();

            var pay_date = $('#i_pay_date').val();

            var money_in = $('#i_money_in').val();

                

                $.post("<?php echo BASE_URL ?>/pending_payable/pay", {data: id, source: source, source_in: source_in,money: money, pay_date: pay_date, money_in: money_in},

                   function(data){

                    $("html, body").animate({ scrollTop: 0 }, 100);

                    setTimeout(function() {

                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                      }, 200);

                   

                   }); 

              

            $( this ).dialog( "close" );

        },        

        Cancel: function() {

            $( this ).dialog( "close" );

        }

    }

});





$( ".add-field" ).dialog({

    autoOpen: false,

    modal: true,

    width: "auto",

    title: "Thu chi",

    hide: 'fold',

    show: 'blind'

});



$(':checkbox').bind('click',function(){

    var th = $(this), name = th.prop('name'); 

     if(th.is(':checked')){

       $(':checkbox').not($(this)).prop('checked',false);

       

     }



    if ($('.sale').is(':checked')) {

        $('.check_sale').slideDown(300);

        $('input[name="check_sale"]').prop('checked', true);

    }

    else{

        $('.check_sale').slideUp(300);

        $('input[name="check_sale"]').prop('checked', false);

    }

});



function action_approve(){

    var del = [];

      ids = $('input:checkbox.checkbox:checked').map(function() { return del.push(this.value); });

      

       if(action=='delete'){

         var r = confirm("Bạn có chắc chắn không?");

        if (r == true){

          $('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);

           $.ajax({

            url: "<?php echo BASE_URL ?>/pending/approvependingpayable",   

            type: 'POST',   

            data: "xoa="+del,   

            success:function(answer){ 

              for(var i=0; i<del.length; i++)

                 $('tr#'+del[i]).remove();

              $('#loading').fadeOut(500); 

              $("html, body").animate({ scrollTop: 0 }, 100);

            }

          });

        }

       }

}



$('.pending').click(function(){

    var id = $(this).attr("data");

    var val = $(this).attr("value");

    var r = confirm("Bạn có chắc chắn không?");

      if (r == true){

        //$('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);

        $.post("<?php echo BASE_URL ?>/pending/pendingpayable", {data: id, val: val},

           function(data){

            

            if (val==1) {

                $("html, body").animate({ scrollTop: 0 }, 100);

                setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 100);

            }

            else

                $('#chat_'+id).click();

           

           }); 

      }



});

$(".add_button").click(function(){

    

        $("#winpopup").dialog({

            draggable:true,

            modal: true,

            autoOpen: false,

            height:500,

            width:400,

            resizable: false,

            title:'Chatting...',

            

        });

        $("#winpopup").load($(this).attr('href'));

        $("#winpopup").dialog("open");

         

        



        return false;

    });



$('#winpopup').on('dialogclose', function(event) {

     



            $("html, body").animate({ scrollTop: 0 }, 100);

            setTimeout(function() {

                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');

                                      }, 100);



 });

</script>