<div class="slide-content" id="hang-giao-chuyen-door">
			<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_native_toolbox"></div>
        <div class="item-page">

            <p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: justify; line-height: 27pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><b><span style="font-size:18.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#333333">Hàng giao / chuyển cửa (Door to Door)<o:p></o:p></span></b></p>

<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: justify; line-height: 27pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><b><span style="font-size:18.0pt;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;;color:#333333">&nbsp;</span></b></p>

<p class="MsoListParagraphCxSpFirst" style="margin-bottom: 6.75pt; text-align: justify; text-indent: -0.25in; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;
font-family:Wingdings;mso-fareast-font-family:Wingdings;mso-bidi-font-family:
Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;
</span></span><!--[endif]--><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Chúng tôi đặc biệt tập trung dịch vụ
giao nhận hàng tận nơi (<i>Door to Door</i>)
từ cảng Hải phòng, cảng Qui Nhơn, cảng Đà Nẵng, cảng Hồ Chí Minh đến tất cả các
cảng trên thế giới và ngược lại. Hàng hóa của khách hàng được chúng tôi theo
sát từ điểm nhận đến điểm giao.<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-bottom: 6.75pt; text-align: justify; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;">&nbsp;</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-bottom: 6.75pt; text-align: justify; text-indent: -0.25in; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;
font-family:Wingdings;mso-fareast-font-family:Wingdings;mso-bidi-font-family:
Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;
</span></span><!--[endif]--><i><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;">Door to door</span></i><span style="font-size:10.0pt;
font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">
dịch kiểu thô sơ là từ cửa đến cửa. Trong vận chuyển hiểu rộng ra là đến tận
nơi người gửi để nhận hàng và đến tận nơi người nhận để trả hàng. Khi bạn đến
với chúng tôi bạn không phải lo bất cứ vấn đề gì mà vẫn có thể nhận hàng ở hai
nơi khác nhau.<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle"><span style="font-size:10.0pt;line-height:
107%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;">&nbsp;</span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-bottom: 6.75pt; text-align: justify; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;">&nbsp;</span></p>

<p class="MsoListParagraphCxSpLast" style="margin-bottom: 6.75pt; text-align: justify; text-indent: -0.25in; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;
font-family:Wingdings;mso-fareast-font-family:Wingdings;mso-bidi-font-family:
Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;
</span></span><!--[endif]--><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Khi đến với chúng tôi bạn sẽ yên tâm
đối với hàng hóa của mình vì chúng tôi có những điểm mạnh sau:<o:p></o:p></span></p>

<p class="MsoNormal" style="margin: 0in 0in 6.75pt 0.5in; text-align: justify; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;">+ Đội xe pick up hàng 24/24 chuyên nghiệp với các thiết bị
hiện đại không làm hàng của bạn bị vỡ hay hư hỏng hay chậm tiến độ.<o:p></o:p></span></p>

<p><center><img src="public/images/door1.jpg"></center></p>

<p class="MsoNormal" style="margin: 0in 0in 6.75pt 0.5in; text-align: justify; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;">+ Dịch vụ đóng gói, sắp xếp hàng chuyên nghiệp giúp bạn tiết
kiêm chi phí và an toàn trong quá trình vận chuyển<o:p></o:p></span></p>

<p><center><img src="public/images/door2.jpg"></center></p>

<p class="MsoNormal" style="margin: 0in 0in 6.75pt 0.5in; text-align: justify; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;">+ Hệ thống khai quan chuyên nghiệp, có hợp đồng đại lý Hải
quan. Khi hàng hóa của bạn được công ty tôi xuất đi thì hàng của bạn có xác suất
miễn kiểm rất cao, và thường được ưu tiên vì chúng tôi có lịch sử sạch cũng như
mối quan hệ tốt với Hải quan.<o:p></o:p></span></p>

<p><center><img src="public/images/door3.jpg"></center></p>

<p class="MsoNormal" style="margin: 0in 0in 6.75pt 0.5in; text-align: justify; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;">+ Đội ngũ nhân viên nhiều kinh nghiệm đối với hàng giao
door. Họ sẽ tư vấn cho bạn nên dùng kết hợp các phương tiện như thế nào cho tối
ưu nhất, cần những chứng từ gì cho hàng của bạn để hàng vào nước nhập một cách
dễ dàng, và làm thế nào để bạn được miễn thuế nhập khẩu...<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpFirst" style="margin-bottom: 6.75pt; text-align: justify; text-indent: -0.25in; line-height: 13.5pt; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;
font-family:Wingdings;mso-fareast-font-family:Wingdings;mso-bidi-font-family:
Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;
</span></span><!--[endif]--><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Đối với hàng giao <i>door to door</i>, bạn sẽ mất nhiều công sức
cho từng khâu, tiêu tốn chi phí, thời gian, sức khỏe, tiền bạc nếu đây không
phải là chuyên môn của bạn. Đến với chúng tôi bạn sẽ nhận được sự tiết kiệm
từng khâu, hàng hóa sẽ được giao tận nơi một cách an toàn với các giải pháp tối
ưu.<o:p></o:p></span></p>


            
        </div>
    </div>   

<script type="text/javascript">
    closeSidepage('#hang-giao-chuyen-door');
   openSidepage('#hang-giao-chuyen-door');
</script>