<div class="slide-content" id="tapioca-chips">
            <!-- Go to www.addthis.com/dashboard to customize your tools -->
        <div class="addthis_native_toolbox"></div>
        <div class="item-page">
			<h2>
			TAPIOCA CHIPS/POWDER
            International export 
			</h2>
			Tapioca Chips and Powder are our main products for exporting to all over the world. We originally purchase these high quality products from the countries of Middle of Vietnam as Binh Dinh, Central Highlands and Southeast areas. Dried Tapioca Chips is used as ingredient in producing animal feed, axit, ethanol, etc. 

            <center>
            	<img src="public/images/tapioca.jpg">
            </center>
        
        </div>
    </div>
<script type="text/javascript">
    closeSidepage('#tapioca-chips');
   openSidepage('#tapioca-chips');
</script>