
<?php
$url_order = 'ASC';
if ($order_by == 'office_cost_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'office_cost_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'recipient')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'approver')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'source')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'office_cost')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> CHI PHÍ HÀNH CHÍNH </h1></center>
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm chi phí</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <div class="add-box">
                  
            Từ  <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:100px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
    </div>
    <div class="tablenav top">
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="5">Hiển thị 5 giá trị</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="15">Hiển thị 15 giá trị</option>
            <option selected="selected" value="20">Hiển thị 20 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>

</div>

<table class="table_data">
<thead>
    <tr>
    	<th rowspan="2" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','office_cost_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'office_cost_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','office_cost_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'office_cost_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','office_cost','<?php echo $url_order ?>')">Chi phí <?php if ($order_by == 'office_cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>   
          
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','recipient','<?php echo $url_order ?>')">Chi cho <?php if ($order_by == 'recipient'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','approver','<?php echo $url_order ?>')">Người duyệt <?php if ($order_by == 'approver'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','source','<?php echo $url_order ?>')">Nguồn <?php if ($order_by == 'source'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
           
        <th  class="fix">&nbsp;</th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($costs as $cost) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $cost->office_cost_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $cost->office_cost_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="office_cost_date_<?php echo $cost->office_cost_id; ?>"><?php echo $lib->hien_thi_ngay_thang($cost->office_cost_date) ?></td>
            <td class="fix" id="comment_<?php echo $cost->office_cost_id; ?>"><?php echo $cost->comment; ?></td>
            <td class="fix" id="office_cost_<?php echo $cost->office_cost_id; ?>"><?php echo $lib->formatMoney($cost->office_cost); ?></td>
            
            <td class="fix" id="recipient_<?php echo $cost->office_cost_id; ?>"><?php echo $cost->recipient; ?></td>
            <td class="fix" id="approver_<?php echo $cost->office_cost_id; ?>"><?php echo $cost->approver; ?></td>
            <td class="fix" id="source_<?php echo $cost->office_cost_id; ?>"><?php echo $cost->bank_name; ?></td>
            <td class="fix" id="person_<?php echo $cost->office_cost_id; ?>"><?php echo $cost->person==1?"Nhân viên":"Khác"; ?></td>
            
            <td>
                <a class="error" href="#">Sửa</a>
                | 
                <a class="error" onclick="del(<?php echo $cost->office_cost_id ?>)" >Xóa</a>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Thông tin chi phí </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_cost" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>

                            <td><div class="add-box"><a class="add_button" onClick="add_click();">Thêm chi phí</a></div></td>
                            
                        </tr>
                        <tr>
                            <td></td>
                            <td>Ngày </td>
                            <td>
                                <input style="width:90px" type="text" id="office_cost_date"  name="office_cost_date" tabindex="1" required="required" >
                            </td>
                            <td>Chi phí </td>
                            <td><input type="text" class="number"  id="office_cost"  name="office_cost" tabindex="3" required="required" ></td>
                            
                            <td>Chi cho </td>
                            <td>
                                <select id="person" name="person" style="width:100px">
                                    <option value="1">Nhân viên</option>
                                    <option value="2">Lương</option>
                                    <option value="3">Thưởng doanh số</option>
                                    <option value="0">Khác</option>
                                </select>
                                <input style="width:150px" type="text"  id="recipient"  name="recipient" tabindex="5" required="required" >
                            </td>
                            

                        </tr>
                        <tr>
                            <td></td>
                            <td>Nội dung</td>
                            <td><textarea id="comment" name="comment" tabindex="2" required="required"></textarea></td>
                            <td>Nguồn </td>
                            <td>
                                <select  style="width:120px" id="source"  name="source" tabindex="4" required="required">
                                    <?php foreach($banks as $bank){ ?>
                                    <option value="<?php echo $bank->bank_id ?>"><?php echo $bank->bank_name ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>Người duyệt</td>
                            <td>
                                <input type="text"  id="approver" name="approver" tabindex="6" >
                            </td>
                            
                        </tr>
                        
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><input type="submit" name="submit" value="Hoàn tất" tabindex="7"></td>
                            <td ><input type="reset" name="reset" value="Nhập lại" tabindex="8"></td>
                            <td></td>
                            <td></td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>
<script type="text/javascript">

var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $("#office_cost_date").datepicker(pickerOpts);

    var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts3);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);


$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }
   

});


    $('.edit_tr').click(function(){
        if(!$('.checkbox').is(':checked')){
            $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
        }
        var office_cost_date = $(this).find("#office_cost_date_"+$(this).attr('id')).text();
        var comment = $(this).find("#comment_"+$(this).attr('id')).text();
        var office_cost = $(this).find("#office_cost_"+$(this).attr('id')).text();
        var recipient = $(this).find("#recipient_"+$(this).attr('id')).text();
        var approver = $(this).find("#approver_"+$(this).attr('id')).text();
        var source = $(this).find("#source_"+$(this).attr('id')).text();
        var person = $(this).find("#person_"+$(this).attr('id')).text();


        //alert(cost_code);
        $('#yes').val($(this).attr('id'));
        
        
        $('#office_cost_date').val(office_cost_date);
        $('#comment').val(comment);
        $('#office_cost').val(office_cost);
        $('#recipient').val(recipient);
        $('#approver').val(approver);
        $("#source option:contains(" + source + ")").attr('selected', 'selected');
        $("#person option:contains(" + person + ")").attr('selected', 'selected');
        
    });
</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
     
        $('#office_cost_date').val();
        $('#comment').val();
        $("#source option[value=1]").attr('selected', 'selected');
        $("#person option[value=1]").attr('selected', 'selected');
        $('#office_cost').val();
        $('#recipient').val();
        $('#approver').val();
        
        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });


}


$(document).ready(function(){
            // Validate form
            $("#add_cost").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var office_cost_date = $('#office_cost_date').attr('value');
                    
                    var office_cost = $('#office_cost').attr('value');
                    var comment = $('#comment').attr('value');
                    var recipient = $('#recipient').attr('value');
                    var approver = $('#approver').attr('value');
                    var source = $('#source').attr('value');
                    var person = $('#person').attr('value');

                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/officecost/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            office_cost_date: office_cost_date,
                            office_cost: office_cost,
                            comment: comment,
                            recipient: recipient,
                            approver: approver,
                            source: source,
                            person: person,
                            yes: yes,

                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                
                                    $('#office_cost_date_'+yes).text(office_cost_date);
                                    $('#comment_'+yes).text(comment);
                                    $('#recipient_'+yes).text(recipient);
                                    $('#approver_'+yes).text(approver);
                                    $('#office_cost_'+yes).text(office_cost);
                                    $('#source_'+yes).text($("#source option:selected").text());
                                    $('#person_'+yes).text($("#person option:selected").text());
                                
                            }
                            else{
                                
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="office_cost_date_'+parseInt(lastID+1)+'">'+office_cost_date+'</td><td class="fix" id="comment_'+parseInt(lastID+1)+'">'+comment+'</td><td class="fix" id="office_cost_'+parseInt(lastID+1)+'">'+office_cost+'</td><td class="fix" id="recipient_'+parseInt(lastID+1)+'">'+recipient+'</td><td class="fix" id="approver_'+parseInt(lastID+1)+'">'+approver+'</td><td class="fix" id="source_'+parseInt(lastID+1)+'">'+$("#source option:selected").text()+'</td><td style="display:none" class="fix" id="person_'+parseInt(lastID+1)+'">'+$("#person option:selected").text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   


   $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
    

});

function get_number(id){
    return $(id).val().replace(/\,/g,'');
}

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');

</script>
</div>