
<?php
$url_order = 'ASC';
if ($order_by == 'receivable_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'expect_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'money')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'week')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'staff')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bank_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'vendor')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> ĐÃ THU </h1></center>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <div class="add-box">
                  
            Từ  <input style="width:90px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            đến  <input style="width:90px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >
            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
        </div>
    </div>
    <div class="tablenav top">
        <div style="clear:both"></div>
        <div class="add-box">
             
        
            <select style="width: 100px;" name="sl_status" id="sl_status">
                <option selected="selected" value="0">Chưa thu</option>
                <option  value="1">Đã thu</option>
            </select>

            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');"> 
            
        </div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="10">Hiển thị 10 giá trị</option>
            <option value="20">Hiển thị 20 giá trị</option>
            <option value="50">Hiển thị 50 giá trị</option>
            <option selected="selected" value="100">Hiển thị 100 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>



      </div>

</div>

<div class="tabs">
    <ul class="tab-links">
        <li class="active" ><a href="#tab1">Lô hàng</a></li>
        <li ><a href="#tab2">Hành chính</a></li>
        <li ><a href="#tab3">Nhân viên</a></li>
        <li ><a href="#tab4">Vay vốn</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab active" id="tab1" >
            <div class="add-box">
                <a class="add_button" id="btnExport">Export Excel</a>
            </div>
            <table id="tblExport" class="table_data">
            <thead>
                <tr>
                    <th style="width:20px" rowspan="2" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
                    <th style="width:40px" rowspan="2" class="fix">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','receivable_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'receivable_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    <th class="fix" rowspan="2">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','receive_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'receive_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    <th style="width:60px" class="fix" rowspan="2">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','code','<?php echo $url_order ?>')">Code <?php if ($order_by == 'code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th> 
                    <th class="fix" colspan="2">
                        <a class="sort" >Phải thu </a>
                    </th> 
                    <th style="width:90px" class="fix" rowspan="2">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money','<?php echo $url_order ?>')">Số tiền <?php if ($order_by == 'money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>   
                      
                    
                    <th class="fix" rowspan="2">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bank_name','<?php echo $url_order ?>')">Tài khoản <?php if ($order_by == 'bank_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th> 
                    <th style="width:200px" class="fix" rowspan="2">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','receive_comment','<?php echo $url_order ?>')">Ghi chú<?php if ($order_by == 'receive_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>

                </tr>
                <tr>
                    <th  class="fix">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    <th class="fix">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','vendor','<?php echo $url_order ?>')">Vendor <?php if ($order_by == 'vendor'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    
                </tr>
                
               </thead>
               <tbody>
                <?php $tong = 0; $tongcon = 0; $tongtt = 0; ?>
                <?php foreach ($receivables as $receivable) : ?>
                <?php $tong += $receivable->money; ?>
                <?php $tongcon += ($receivable->money-$receivable->pay_money); ?>
                <?php $tongtt += $receivable->pay_money; ?>
                <?php 
                    $timeDiff = strtotime(date('d-m-Y')) - $receivable->expect_date;

                    $numberDays = $timeDiff/86400;  // 86400 seconds in one day

                    // and you might want to convert to integer
                    $numberDays = intval($numberDays); 
                ?>
                <?php
                    if ($receivable->sale_report > 0) {
                        $link = 'salereport/index/'.$receivable->code;
                    }
                    else if ($receivable->agent > 0) {
                        $link = 'agent/index/'.$receivable->code;
                    }
                    else if ($receivable->agent_manifest > 0) {
                        $link = 'agentmanifest/index/'.$receivable->code;
                    }
                    else if ($receivable->trading > 0) {
                        $link = 'trading/index/'.$receivable->code;
                    }
                    else if ($receivable->invoice > 0) {
                        $link = 'invoice/index/'.$receivable->invoice;
                    }
                    else if ($receivable->order_tire > 0) {
                        $link = 'tiresale/sale/'.$receivable->code;
                    }
                ?>
                <?php if($_SESSION['role_logined'] == 10){ $link = "#"; } ?>
                    <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $receivable->receivable_id ?>" class="edit_tr masterTooltip" <?php echo $numberDays>90?'title="Vui lòng cập nhật ngày dự kiến thu"':null ?>>
                        <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $receivable->receivable_id ?>"></td>
                        <td class="fix"><?php echo $i++; ?></td>
                        <td class="fix"  style="color:<?php echo $numberDays>90?'red':null; ?>"  id="receive_date_<?php echo $receivable->receivable_id; ?>"><?php echo $lib->hien_thi_ngay_thang($receivable->receive_date) ?></td>
                        <td class="fix" id="code_<?php echo $receivable->receivable_id; ?>"><a style="text-decoration: underline;" href="<?php echo $this->url($link) ?>"><?php echo $receivable->code; ?></a></td>
                        <td class="fix" data="<?php echo $receivable->customer; ?>" id="customer_<?php echo $receivable->receivable_id; ?>"><a style="text-decoration: underline;" href="<?php echo $_SESSION['role_logined'] != 10?$this->url('cusdebts/index/'.$receivable->customer):"#" ?>"><?php echo isset($customers['name'][$receivable->customer])?$customers['name'][$receivable->customer]:null; ?></a></td>
                        <td class="fix" data="<?php echo $receivable->vendor; ?>" id="vendor_<?php echo $receivable->receivable_id; ?>"><?php echo isset($vendors['name'][$receivable->vendor])?$vendors['name'][$receivable->vendor]:null; ?></td>
                        
                        <td class="fix" id="money_<?php echo $receivable->receivable_id; ?>"><?php echo $lib->formatMoney($receivable->money); ?></td>
                        
                        <td class="fix" id="source_<?php echo $receivable->receivable_id; ?>"><?php echo $receivable->bank_name; ?></td>
                        <td class="fix" id="receive_comment_<?php echo $receivable->receivable_id; ?>"><?php echo $receivable->receive_comment; ?></td>
                        
                        
                    </tr>
                    
                <?php endforeach; ?>
                <?php foreach ($deposits as $cost) : ?>
                <?php $tong += $cost->money_in;  ?>
                    <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $cost->costs_id ?>" class="edit_tr" >
                        <td ><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $cost->costs_id ?>"></td>
                        <td  class="fix"><?php echo $i++; ?></td>
                        <td class="fix"  id="pay_date_<?php echo $cost->costs_id; ?>"><?php echo $lib->hien_thi_ngay_thang($cost->pay_date) ?></td>
                        <td  class="fix" id="code_<?php echo $cost->costs_id; ?>"><?php echo $cost->code; ?></td> 
                        <td class="fix" data="<?php echo $cost->customer; ?>" id="customer_<?php echo $cost->costs_id; ?>"><a style="text-decoration: underline;" href="<?php echo $_SESSION['role_logined'] != 10?$this->url('cusdebts/index/'.$cost->customer):"#" ?>"><?php echo isset($customers['name'][$cost->customer])?$customers['name'][$cost->customer]:null; ?></a></td>
                        <td class="fix" ></td>
                        <td  class="fix" id="money_in_<?php echo $cost->costs_id; ?>"><?php echo $lib->formatMoney($cost->money_in); ?></td>
                        
                        
                        <td class="fix" id="source_in_<?php echo $cost->costs_id; ?>"><?php echo $cost->bank_name; ?></td>
                        <td  class="fix" id="comment_<?php echo $cost->costs_id; ?>"><?php echo $cost->comment; ?></td> 
                        
                    </tr>
                <?php endforeach; ?>
                <tr style="text-align:center; font-weight: bold; color: red;">
                    <td class="fix" colspan="6" >Tổng cộng</td>
                    <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
                    <td class="fix" colspan="2" ></td>
                </tr>
               </tbody>
            </table>
        </div>
        <div class="tab" id="tab2" >
            <div class="add-box">
                <a class="add_button" id="btnExport2">Export Excel</a>
            </div>
            <table id="tblExport2" class="table_data">
                <thead>
                <tr>
                    <th style="width:20px"  class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
                    <th style="width:40px" class="fix">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','costs_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'costs_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    <th style="width:75px" class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','pay_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'pay_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th> 
                    <th  class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money_in','<?php echo $url_order ?>')">Số tiền <?php if ($order_by == 'money_in'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th> 
                      
                    <th class="fix">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Nội dung<?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    
                    <th class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','source_in','<?php echo $url_order ?>')">Tài khoản <?php if ($order_by == 'source_in'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th> 
                </tr>
                
               </thead>
                    <tbody>
                <?php $tong = 0;  ?>
                <?php foreach ($costs as $cost) : ?>
                <?php $tong += $cost->money_in;  ?>
                    <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $cost->costs_id ?>" class="edit_tr" >
                        <td ><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $cost->costs_id ?>"></td>
                        <td  class="fix"><?php echo $i++; ?></td>
                        <td class="fix"  id="pay_date_<?php echo $cost->costs_id; ?>"><?php echo $lib->hien_thi_ngay_thang($cost->pay_date) ?></td>
                        <td  class="fix" id="money_in_<?php echo $cost->costs_id; ?>"><?php echo $lib->formatMoney($cost->money_in); ?></td>
                        <td  class="fix" id="comment_<?php echo $cost->costs_id; ?>"><?php echo $cost->comment; ?></td> 
                        
                        <td class="fix" id="source_in_<?php echo $cost->costs_id; ?>"><?php echo $cost->bank_name; ?></td>
                        
                    </tr>
                <?php endforeach; ?>
                <tr style="text-align:center; font-weight: bold; color: red;">
                    <td class="fix" colspan="3" >Tổng cộng</td>
                    <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
                    <td class="fix" colspan="2" ></td>
                </tr>
               </tbody>
            </table>
        </div>
        <div class="tab" id="tab3" >
            <div class="add-box">
                <a class="add_button" id="btnExport3">Export Excel</a>
            </div>
            <table id="tblExport3" class="table_data">
            <thead>
                <tr>
                    <th style="width:20px" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
                    <th style="width:40px"  class="fix">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','receivable_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'receivable_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    <th class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','receive_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'receive_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    <th class="fix">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','staff','<?php echo $url_order ?>')">Nhân viên <?php if ($order_by == 'staff'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    <th style="width:90px" class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money','<?php echo $url_order ?>')">Số tiền <?php if ($order_by == 'money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>   
                      
                    
                    <th class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bank_name','<?php echo $url_order ?>')">Tài khoản <?php if ($order_by == 'bank_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th> 
                    <th style="width:200px" class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','receive_comment','<?php echo $url_order ?>')">Ghi chú<?php if ($order_by == 'receive_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>

                </tr>
                
               </thead>
               <tbody>
                <?php $tong = 0; $tongcon = 0; $tongtt = 0; ?>
                <?php foreach ($staffs as $receivable) : ?>
                <?php $tong += $receivable->money; ?>
                <?php $tongcon += ($receivable->money-$receivable->pay_money); ?>
                <?php $tongtt += $receivable->pay_money; ?>
                <?php 
                    $timeDiff = strtotime(date('d-m-Y')) - $receivable->expect_date;

                    $numberDays = $timeDiff/86400;  // 86400 seconds in one day

                    // and you might want to convert to integer
                    $numberDays = intval($numberDays); 
                ?>
                <?php if($_SESSION['role_logined'] == 10){ $link = "#"; } ?>
                    <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $receivable->receivable_id ?>" class="edit_tr masterTooltip" <?php echo $numberDays>90?'title="Vui lòng cập nhật ngày dự kiến thu"':null ?>>
                        <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $receivable->receivable_id ?>"></td>
                        <td class="fix"><?php echo $i++; ?></td>
                        <td class="fix"  style="color:<?php echo $numberDays>90?'red':null; ?>"  id="receive_date_<?php echo $receivable->receivable_id; ?>"><?php echo $lib->hien_thi_ngay_thang($receivable->receive_date) ?></td>
                        <td class="fix" data="<?php echo $receivable->staff; ?>" id="staff_<?php echo $receivable->receivable_id; ?>"><a style="text-decoration: underline;" href="<?php echo $this->url('staffdebts/index/'.$receivable->staff) ?>"><?php echo $receivable->staff_name; ?></a></td>
                        <td class="fix" id="money_<?php echo $receivable->receivable_id; ?>"><?php echo $lib->formatMoney($receivable->money); ?></td>
                        
                        <td class="fix" id="source_<?php echo $receivable->receivable_id; ?>"><?php echo $receivable->bank_name; ?></td>
                        <td class="fix" id="receive_comment_<?php echo $receivable->receivable_id; ?>"><?php echo $receivable->receive_comment; ?></td>
                        
                        
                    </tr>
                    
                <?php endforeach; ?>
                <tr style="text-align:center; font-weight: bold; color: red;">
                    <td class="fix" colspan="4" >Tổng cộng</td>
                    <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
                    <td class="fix" colspan="2" ></td>
                </tr>
               </tbody>
            </table>
        </div>

        <div class="tab" id="tab4" >
            <div class="add-box">
                <a class="add_button" id="btnExport4">Export Excel</a>
            </div>
            <table id="tblExport4" class="table_data">
            <thead>
                <tr>
                    <th style="width:20px" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
                    <th style="width:40px"  class="fix">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','lender_cost_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'lender_cost_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    <th class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','lender_cost_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'lender_cost_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    <th class="fix">
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','lender_name','<?php echo $url_order ?>')">Người vay <?php if ($order_by == 'lender_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>
                    <th style="width:90px" class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money','<?php echo $url_order ?>')">Số tiền <?php if ($order_by == 'money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>   
                      
                    
                    <th class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','bank_name','<?php echo $url_order ?>')">Tài khoản <?php if ($order_by == 'bank_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th> 
                    <th style="width:200px" class="fix" >
                        <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Ghi chú<?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
                    </th>

                </tr>
                
               </thead>
               <tbody>
                <?php $tong = 0; ?>
                <?php foreach ($lendercosts as $receivable) : ?>
                <?php $tong += $receivable->money; ?>
                
                <?php if($_SESSION['role_logined'] == 10){ $link = "#"; } ?>
                    <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $receivable->lender_cost_id ?>" class="edit_tr masterTooltip" >
                        <td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $receivable->lender_cost_id ?>"></td>
                        <td class="fix"><?php echo $i++; ?></td>
                        <td class="fix" id="lender_cost_date_<?php echo $receivable->lender_cost_id; ?>"><?php echo $lib->hien_thi_ngay_thang($receivable->lender_cost_date) ?></td>
                        <td class="fix" data="<?php echo $receivable->lender; ?>" id="lender_<?php echo $receivable->lender_cost_id; ?>"><?php echo $receivable->lender_name; ?></td>
                        <td class="fix" id="money_<?php echo $receivable->lender_cost_id; ?>"><?php echo $lib->formatMoney($receivable->money); ?></td>
                        
                        <td class="fix" id="source_<?php echo $receivable->lender_cost_id; ?>"><?php echo $receivable->bank_name; ?></td>
                        <td class="fix" id="comment_<?php echo $receivable->lender_cost_id; ?>"><?php echo $receivable->comment; ?></td>
                        
                        
                    </tr>
                    
                <?php endforeach; ?>
                <tr style="text-align:center; font-weight: bold; color: red;">
                    <td class="fix" colspan="4" >Tổng cộng</td>
                    <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
                    <td class="fix" colspan="2" ></td>
                </tr>
               </tbody>
            </table>
        </div>
    </div>
</div>
<?php
$this->helper('slidePaginator');
?>
<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('expectrevenue') ?>">&larr;</a></div>
<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


<script type="text/javascript">
   var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts3);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);

var tt = "<?php echo $trangthai ?>";
$('#sl_status option[value='+tt+']').attr('selected','selected');
var lm = "<?php echo $limit ?>";
$('#chonloc option[value='+lm+']').attr('selected','selected');

   jQuery(document).ready(function() {
    jQuery('.tabs .tab-links a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });

    jQuery('.tabs .tab-left a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');
 
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });
});

   $(document).ready(function () {
        $("#btnExport2").click(function () {
            $("#tblExport2").battatech_excelexport({
                containerid: "tblExport2"
               , datatype: 'table'
            });
        });
        $("#btnExport3").click(function () {
            $("#tblExport3").battatech_excelexport({
                containerid: "tblExport3"
               , datatype: 'table'
            });
        });
        $("#btnExport4").click(function () {
            $("#tblExport4").battatech_excelexport({
                containerid: "tblExport4"
               , datatype: 'table'
            });
        });
    });
</script>