
<?php
$url_order = 'ASC';
if ($order_by == 'order_tire_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'delivery_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'total')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'order_tire_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $j = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>HẠCH TOÁN ĐƠN HÀNG</h1>
</section>
<div id="content" style="padding:5px;">
<div class="add-box">
    <a class="add_button" id="btnExport" >Export Excel</a>
    
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
        <div >
            <select id="sl_tha" name="sl_tha" style="width:90px; margin-left:5px;">
             <?php 
                for ($i=1; $i < 13; $i++) { 
                    echo '<option value="'.$i.'">Tháng '.$i.'</option>';
                }
             ?>
            </select>
            <select id="sl_na" name="sl_na" style="width:100px">
             <?php 
                $nam = date('Y');
                for ($i=($nam-5); $i < ($nam+5); $i++) { 
                    echo '<option value="'.$i.'">Năm '.$i.'</option>';
                }
             ?>
            </select>
            <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        </div>
        <div >
    
            Từ  <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:100px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');"> 
                                    
        </div>
        
        <div class="add-box">
            <select id="sl_nv" name="sl_nv" style="width:150px">
                <option value="">Trạng thái</option>
                <option value="0">Chưa hạch toán</option>
                <option value="1">Đã hạch toán</option>
            </select>
            <input type="button" name="" id="search" class="button-search" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        </div>
    	
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
            <option selected="selected" value="10">Hiển thị 10 giá trị</option>
			<option value="20">Hiển thị 20 giá trị</option>
            <option value="30">Hiển thị 30 giá trị</option>
            <option value="50">Hiển thị 50 giá trị</option>
            
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>
    

</div>

<table id="tblExport" class="table_data">
<thead>
    <tr>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','order_tire_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'order_tire_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','delivery_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'delivery_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','order_number','<?php echo $url_order ?>')">Số ĐH <?php if ($order_by == 'order_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','order_tire_number','<?php echo $url_order ?>')">Sản lượng <?php if ($order_by == 'order_tire_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','total','<?php echo $url_order ?>')">Thu <?php if ($order_by == 'total'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','vat','<?php echo $url_order ?>')">Thuế GTGT <?php if ($order_by == 'vat'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','discount','<?php echo $url_order ?>')">Trừ giảm <?php if ($order_by == 'discount'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','total','<?php echo $url_order ?>')">KH phải trả <?php if ($order_by == 'total'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','order_cost','<?php echo $url_order ?>')">Chi phí <?php if ($order_by == 'order_cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','order_cost','<?php echo $url_order ?>')">Giá vốn <?php if ($order_by == 'order_cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','username','<?php echo $url_order ?>')">Sale <?php if ($order_by == 'username'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        
        <th class="fix">
            
        </th> 
    </tr>
    
   </thead>
   <tbody>
    <?php $tongthu=0; $tongsl=0; $tongthue=0; $tongtru=0; $tongkhtra=0; $tongcpban=0; $tongcpnhap=0; $tongloinhuan=0; ?>
    <?php foreach ($order_tires as $order_tire) : 
    $tongthu += $order_tire->total-$order_tire->vat+$order_tire->discount+$order_tire->reduce;
    $tongsl += $order_tire->order_tire_number;
    $tongthue += $order_tire->vat;
    $tongtru += $order_tire->discount+$order_tire->reduce;
    $tongkhtra += $order_tire->total;
    $tongcpban += $order_tire->order_cost;
    $tongcpnhap += $costs[$order_tire->order_tire_id];
    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $order_tire->order_tire_id ?>" class="edit_tr" data="<?php echo ($order_tire->sale==$_SESSION['userid_logined'] || $_SESSION['role_logined']==1)?1:0 ?>">
            <td class="fix"><?php echo $j++; ?></td>
            <td class="fix"  id="delivery_date_<?php echo $order_tire->order_tire_id; ?>"><?php echo $order_tire->delivery_date>0?$lib->hien_thi_ngay_thang($order_tire->delivery_date):"Chưa giao"; ?></td>
            <td class="fix"  id="order_number_<?php echo $order_tire->order_tire_id; ?>">
                <?php 
                    echo $order_tire->order_number;
                ?>
            </td>
            
            <td class="fix" data="<?php echo $order_tire->customer; ?>"  id="customer_<?php echo $order_tire->order_tire_id; ?>"><?php echo $order_tire->customer_name; ?></td>
            <td class="fix"  id="order_tire_number_<?php echo $order_tire->order_tire_id; ?>"><a style="font-weight:bold;text-decoration:underline" class="order_list" href="<?php echo $this->url('ordertire/listtire/'.$order_tire->order_tire_id); ?>"><?php echo $order_tire->order_tire_number; ?></a></td>
            <td class="fix text-right" id="thu_<?php echo $order_tire->order_tire_id; ?>"><?php echo $lib->formatMoney($order_tire->total-$order_tire->vat+$order_tire->discount+$order_tire->reduce); ?></td> 
            <td class="fix text-right"  id="vat_<?php echo $order_tire->order_tire_id; ?>"><?php echo $lib->formatMoney($order_tire->vat); ?></td>
            <td class="fix text-right"  id="discount_<?php echo $order_tire->order_tire_id; ?>"><?php echo $lib->formatMoney($order_tire->discount+$order_tire->reduce); ?></td>
            <td class="fix text-right"  id="total_<?php echo $order_tire->order_tire_id; ?>"><?php echo $lib->formatMoney($order_tire->total); ?></td>
            <td class="fix text-right"  id="order_cost_<?php echo $order_tire->order_tire_id; ?>">
                <a style="font-weight:bold;text-decoration:underline" class="order_cost" data="<?php echo $order_tire->order_tire_id; ?>" href="<?php echo $this->url('ordertire/listcost/'.$order_tire->order_tire_id); ?>">
                    <?php echo $lib->formatMoney($order_tire->order_cost); ?>
                </a>
            </td>
            <td class="fix text-right"  id="cost_<?php echo $order_tire->order_tire_id; ?>"><?php echo $lib->formatMoney($costs[$order_tire->order_tire_id]); ?></td>
            <td class="fix" id="sale_<?php echo $order_tire->order_tire_id; ?>"><?php echo $order_tire->username; ?></td> 
             
            
            <td class="fix" id="approve_<?php echo $order_tire->order_tire_id; ?>">
                <button class="btn add_additional" data="<?php echo $order_tire->order_tire_id; ?>" alt="1">Hạch toán</button>
            </td> 
        </tr>
    <?php endforeach; ?>
    <?php foreach ($sales as $tire_sale) : 
    $tongsl += $tire_sale->volume;
    $tongcpnhap += $costs2[$tire_sale->tire_sale_id];
    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $tire_sale->tire_sale_id ?>" class="edit_tr" >
            <td class="fix"><?php echo $j++; ?></td>
            <td class="fix"  id="delivery_date_<?php echo $tire_sale->tire_sale_id; ?>"><?php echo $lib->hien_thi_ngay_thang($tire_sale->tire_sale_date); ?></td>
            <td class="fix"  id="order_number_<?php echo $tire_sale->tire_sale_id; ?>">
                
            </td>
            
            <td class="fix" data="<?php echo $tire_sale->customer; ?>"  id="customer_<?php echo $tire_sale->tire_sale_id; ?>"><?php echo $tire_sale->customer_name; ?></td>
            <td class="fix"  id="tire_sale_number_<?php echo $tire_sale->tire_sale_id; ?>"><a style="font-weight:bold;text-decoration:underline" class="order_list" href="<?php echo $this->url('ordertire/listtire/'.$tire_sale->tire_sale_id); ?>"><?php echo $tire_sale->volume; ?></a></td>
            <td class="fix text-right" id="thu_<?php echo $tire_sale->tire_sale_id; ?>"></td> 
            <td class="fix text-right"  id="vat_<?php echo $tire_sale->tire_sale_id; ?>"></td>
            <td class="fix text-right"  id="discount_<?php echo $tire_sale->tire_sale_id; ?>"></td>
            <td class="fix text-right"  id="total_<?php echo $tire_sale->tire_sale_id; ?>"></td>
            <td class="fix text-right"  id="order_cost_<?php echo $tire_sale->tire_sale_id; ?>">
            </td>
            <td class="fix text-right"  id="cost_<?php echo $tire_sale->tire_sale_id; ?>"><?php echo $lib->formatMoney($costs2[$tire_sale->tire_sale_id]); ?></td>
            <td class="fix" id="sale_<?php echo $tire_sale->tire_sale_id; ?>"><?php echo $tire_sale->username; ?></td> 
             
            
            <td class="fix" id="approve_<?php echo $tire_sale->tire_sale_id; ?>">
                <button class="btn add_additional" data="<?php echo $tire_sale->tire_sale_id; ?>" alt="2">Hạch toán</button>
            </td>
        </tr>
    <?php endforeach; ?>
    <tr style=" color:rgb(211, 11, 57); text-align: center; font-weight:bold;">
            <td class="fix" colspan="4">Tổng cộng</td>
            <td class="fix"><?php echo $lib->formatMoney($tongsl) ?></td>
            <td class="fix  text-right"><?php echo $lib->formatMoney($tongthu) ?></td>
            <td class="fix  text-right"><?php echo $lib->formatMoney($tongthue) ?></td>
            <td class="fix  text-right"><?php echo $lib->formatMoney($tongtru) ?></td>
            <td class="fix  text-right"><?php echo $lib->formatMoney($tongkhtra) ?></td>
            <td class="fix text-right"><?php echo $lib->formatMoney($tongcpban) ?></td>
            <td class="fix text-right"><?php echo $lib->formatMoney($tongcpnhap) ?></td>
            <td class="fix"></td>
            <td class="fix"></td>
        </tr>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('ordertire/report') ?>">&larr;</a></div>
<div class="add-field">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            <form id="add_daily" role="form" method="post" action="" enctype="multipart/form-data">
              
              <div class="col-md-12 nopadding">
                <input type="text" name="additional_date" id="additional_date" class="date_mask" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask>
                <span id="company"></span>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item active">
                    <a class="nav-link active" data-toggle="tab" href="#item" role="tab">Thu: <b><span id="thu"></span></b></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link active" data-toggle="tab" href="#item" role="tab">Thuế: <b><span id="thue"></span></b></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link active" data-toggle="tab" href="#item" role="tab">Trừ giảm: <b><span id="trugiam"></span></b></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link active" data-toggle="tab" href="#item" role="tab">Tổng cộng: <b><span id="tong"></span></b></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link active" data-toggle="tab" href="#item" role="tab">Giá vốn: <b><span id="von"></span></b></a>
                  </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                  <div class="tab-pane active" id="item" role="tabpanel">
                    <div class="table-container">
                      <table id="dataTable0" class="dataTable">
                        <thead>
                          <tr>
                            <th class="width-3">STT</th>
                            <th class="width-10">TK nợ</th>
                            <th class="width-10">TK có</th>
                            <th class="width-10">Số tiền</th>
                            <th>Nội dung</th>
                            <th class="width-10">Code</th>
                            <th style="width:8px"></th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td class="width-3">1</td>
                            <td class="width-10">
                              <select name="additional_debit[]" class="additional_debit dropchosen" required="required">
                                  <option value="">Tài khoản</option>
                                  <?php foreach ($account_parents as $account_parent) { ?>
                                      <option value="<?php echo $account_parent->account_id ?>"><?php echo $account_parent->account_number.' - '.$account_parent->account_name ?></option>
                                  <?php } ?>
                              </select>
                            </td>
                            <td class="width-10">
                              <select name="additional_credit[]" class="additional_credit" required="required">
                                  <option value="">Tài khoản</option>
                                  <?php foreach ($account_parents as $account_parent) { ?>
                                      <option value="<?php echo $account_parent->account_id ?>"><?php echo $account_parent->account_number.' - '.$account_parent->account_name ?></option>
                                  <?php } ?>
                              </select>
                            </td>
                            <td class="width-10"><input type="text" name="additional_money[]" class="additional_money numbers text-right" autocomplete="off" required="required"></td>
                            <td><input type="text" name="additional_comment[]" class="additional_comment keep-val" autocomplete="off" required="required"></td>
                            
                            <td class="width-10"><input type="text" name="additional_code[]" class="additional_code keep-val" autocomplete="off"></td>
                          </tr>
                          <tr>
                            <td class="width-3">1</td>
                            <td class="width-10">
                              <select name="additional_debit[]" class="additional_debit" required="required">
                                  <option value="">Tài khoản</option>
                                  <?php foreach ($account_parents as $account_parent) { ?>
                                      <option value="<?php echo $account_parent->account_id ?>"><?php echo $account_parent->account_number.' - '.$account_parent->account_name ?></option>
                                  <?php } ?>
                              </select>
                            </td>
                            <td class="width-10">
                              <select name="additional_credit[]" class="additional_credit" required="required">
                                  <option value="">Tài khoản</option>
                                  <?php foreach ($account_parents as $account_parent) { ?>
                                      <option value="<?php echo $account_parent->account_id ?>"><?php echo $account_parent->account_number.' - '.$account_parent->account_name ?></option>
                                  <?php } ?>
                              </select>
                            </td>
                            <td class="width-10"><input type="text" name="additional_money[]" class="additional_money numbers text-right" autocomplete="off" required="required"></td>
                            <td><input type="text" name="additional_comment[]" class="additional_comment keep-val" autocomplete="off" required="required"></td>
                            
                            <td class="width-10"><input type="text" name="additional_code[]" class="additional_code keep-val" autocomplete="off"></td>
                          </tr>
                          <tr>
                            <td class="width-3">1</td>
                            <td class="width-10">
                              <select name="additional_debit[]" class="additional_debit" required="required">
                                  <option value="">Tài khoản</option>
                                  <?php foreach ($account_parents as $account_parent) { ?>
                                      <option value="<?php echo $account_parent->account_id ?>"><?php echo $account_parent->account_number.' - '.$account_parent->account_name ?></option>
                                  <?php } ?>
                              </select>
                            </td>
                            <td class="width-10">
                              <select name="additional_credit[]" class="additional_credit" required="required">
                                  <option value="">Tài khoản</option>
                                  <?php foreach ($account_parents as $account_parent) { ?>
                                      <option value="<?php echo $account_parent->account_id ?>"><?php echo $account_parent->account_number.' - '.$account_parent->account_name ?></option>
                                  <?php } ?>
                              </select>
                            </td>
                            <td class="width-10"><input type="text" name="additional_money[]" class="additional_money numbers text-right" autocomplete="off" required="required"></td>
                            <td><input type="text" name="additional_comment[]" class="additional_comment keep-val" autocomplete="off" required="required"></td>
                            
                            <td class="width-10"><input type="text" name="additional_code[]" class="additional_code keep-val" autocomplete="off"></td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    <i class="fa fa-plus" title="Thêm dòng mới"></i> F2: Thêm dòng
                    <i class="fa fa-minus" title="Xóa dòng cuối cùng"></i> F3: Xóa dòng
                    
                  </div>
                  
                  
                </div>
              </div>
              
              <?php if(!isset($disable_control)){ ?>
              <div class="row">
                <div class="col-md-12">
                  <div class="box-footer">
                    <input type="hidden" readonly id="yes" name="yes" required="required" >
                    <input type="hidden" readonly id="type_order" name="type_order" required="required" >
                    <button type="submit" class="btn btn-primary" tabindex="16"><i class="fa fa-save"></i> Hoàn thành</button>
                    <button type="reset" class="btn" tabindex="17"><i class="fa fa-undo"></i>  Nhập lại</button>
                  </div>
                  <div class="box-footer">
                    <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
                  </div>
                </div>
              </div>
              <?php } ?>
            </form>
          </div>
          <!-- /.box -->

        </div>
        <!--/.col (left) -->
        
      </div>
      <!-- /.row -->
       
</div>

<script type="text/javascript">
var i_index=0;
    $(".date_mask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
    $('.add-field').hide(); 

    $('.add_additional').click(function(){
        var id = $(this).attr('data');
        var type = $(this).attr('alt');
        
        $('#thu').html($('#thu_'+id).text());
        $('#thue').html($('#vat_'+id).text());
        $('#trugiam').html($('#discount_'+id).text());
        $('#tong').html($('#total_'+id).text());
        $('#von').html($('#cost_'+id).text());
        $('#company').html($('#order_number_'+id).text()+" - "+$('#customer_'+id).text());

        

        $('.add-field').slideDown(500);
         $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
         
            $('.add-field input').val("");
            $('.add-field input').attr("data","");
            $('.add-field input').attr("alt","");

            $('#yes').val(id);
            $('#type_order').val(type);
            
            $('#additional_date').val($('#delivery_date_'+id).text());

            $('#dataTable0 tbody tr').remove();
            $.ajax({
              url: '<?php echo BASE_URL ?>/daily/getitemaddorder',
              type: 'POST',
              data: {yes:id,type_order:type},
              success:function(answer){
                  //alert(answer);
                  //var data = JSON.parse(answer);
                  var data = JSON.parse(answer);
                  $('#dataTable0 tbody').append(data.hang);
                  $('.dropchosen').chosen();
                  

                  $('input').keyup(function (e) {
                      if (e.which == 39) { // right arrow
                        $(this).closest('td').next().find('input').focus();

                      } else if (e.which == 37) { // left arrow
                        $(this).closest('td').prev().find('input').focus();

                      } else if (e.which == 40) { // down arrow
                        $(this).closest('tr').next().find('td:eq(' + $(this).closest('td').index() + ')').find('input').focus();

                      } else if (e.which == 38) { // up arrow
                        $(this).closest('tr').prev().find('td:eq(' + $(this).closest('td').index() + ')').find('input').focus();
                      }
                    });

                  
                  $( ".additional_money" ).focusin(function() {
                      i_index = $( this ).closest('tr').index();
                    });

                  $('.nav span').click(function(){
                    $('.additional_money:eq('+i_index+')').val($(this).text());
                  });

                  $('.additional_code').each(function(){
                    var val = $(this).val().trim();
                    if (val == "") {
                        $(this).val($('#order_number_'+id).text());
                    }
                  });
                  $('.additional_money').keyup(function(){
                    var tong = parseFloat($('#tong').text().replace(/\,/g,'')) || 0;
                    tong += parseFloat($('#von').text().replace(/\,/g,'')) || 0;

                    var giam = parseFloat($('#trugiam').text().replace(/\,/g,'')) || 0;

                    if(giam>0){
                        tong += giam+giam;
                    }

                    var total = 0;
                    $('.additional_money').each(function(){
                      total += parseFloat(get_number($(this))) || 0;
                    });

                    if (total > tong) {
                      $(this).val("");
                    }
                  });

                  $('.numbers').keyup(function(event) {
                      // skip for arrow keys
                    if(event.which >= 37 && event.which <= 40) return;
                    // format number
                    $(this).val(function(index, value) {
                      return value
                        .replace(/[^0-9-.]/g, "")
                        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
                      ;
                    });
                  });
                  
                $('.numbers').focus(function(){
                    if ( $(this).val() == '0') {
                       $(this).val(""); 
                    };
                    
                });
                $('.numbers').blur(function(){
                    if ( $(this).val() == "") {
                        $(this).val(0);
                    };
                    
                });

                  
                }
            });

            

        $( ".add-field" ).dialog( "open" );
    });

$(document).ready(function(){
  // Validate form
  $("#add_daily").validate({
      errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
      rules: {

      },
      submitHandler: function(form) {
                
        var additional_date = $('#additional_date').attr('value');

        var yes = $('#yes').attr('value');
        var type_order = $('#type_order').attr('value');

        var total = 0;
        var tong = parseFloat($('#tong').text().replace(/\,/g,'')) || 0;
        tong += parseFloat($('#von').text().replace(/\,/g,'')) || 0;

        var giam = parseFloat($('#trugiam').text().replace(/\,/g,'')) || 0;

        if(giam>0){
            tong += giam+giam;
        }
        

        $('.additional_money').each(function(){
          total += parseFloat(get_number($(this))) || 0;
        });


        if (total != tong) {
          alert("Vui lòng hạch toán đúng số tiền!");
          return false;
        }
        

        var additional = [];
        var additional_id = [];
        var additional_debit = [];
        var additional_credit = [];
        var additional_money = [];
        var additional_comment = [];
        var additional_code = [];

        $('select.additional_debit').each(function(){
          additional_debit.push($(this).val());
        });
        $('select.additional_credit').each(function(){
          additional_credit.push($(this).val());
        });
        $('.additional_money').each(function(){
          additional_money.push($(this).val());
          additional_id.push($(this).attr('data') || "");
        });
        $('.additional_comment').each(function(){
          additional_comment.push($(this).val());
        });
        $('.additional_code').each(function(){
          additional_code.push($(this).val());
        });

        for (var i = 0; i < additional_money.length; i++) {
          additional.push({'additional_id':additional_id[i], 'additional_debit':additional_debit[i],'additional_credit':additional_credit[i], 'additional_money':additional_money[i], 'additional_comment':additional_comment[i], 'additional_code':additional_code[i]});
                
        };

        $.ajax({
            type: "POST", // phương thức gởi đi
            url: "<?php echo BASE_URL ?>/daily/addorder", // nơi mà dữ liệu sẽ chuyển đến khi submit
            data: {
                
                additional_date: additional_date,
                additional: additional,
                yes: yes,
                type_order: type_order,

                }, // giá trị post
            success: function(answer){ // if everything goes well
                //alert(answer);
                $('#error').hide();
                $('#error').slideToggle(100); // hiển thị thẻ div success
                $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                $('#error').fadeOut(10000);

                if (yes != "") {
                    if (answer.trim() == "Cập nhật thành công") {
                        setTimeout(function() {
                                searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                              }, 200);
                    }
                }
                else{
                    if (answer.trim() == "Thêm thành công") {
                        setTimeout(function() {
                            searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                          }, 200);
                    }
                    
                }
            }
        });
        return false;
         
     }
        
  });
});
</script>
<script type="text/javascript">
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');

var c = "<?php echo $trangthai ?>";
$('#sl_status option[value='+c+']').attr('selected','selected');

var s = "<?php echo $nv ?>";
$('#sl_nv option[value='+s+']').attr('selected','selected');

var th = "<?php echo $thang ?>";
$('#sl_tha option[value='+th+']').attr('selected','selected');

var n = "<?php echo $nam ?>";
$('#sl_na option[value='+n+']').attr('selected','selected');



$(".order_cost").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:500,
            width:600,
            resizable: false,
            title:'Chi phí',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });
$(".order_list").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:500,
            width:600,
            resizable: false,
            title:'Thông tin',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });




var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".ngay").datepicker(pickerOpay2);



</script>
<script type="text/javascript">
    
    $('#sl_tha').change(function(){
        var m = $(this).val();
        var y = $('#sl_na').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

    $('#sl_na').change(function(){
        var y = $(this).val();
        var m = $('#sl_tha').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });


    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showWeek: true,
        weekHeader: 'Tuần',
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showWeek: true,
        weekHeader: 'Tuần',
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
  
  $( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "90%",
    title: "Hạch toán",
    hide: 'fold',
    show: 'blind',
    position: ['center',5],
});

  function get_number(id){
  return $(id).val().replace(/\,/g,'');
}
</script>
<script type="text/javascript">
    $(document).ready(function () {
 
      $('input').keyup(function (e) {
        if (e.which == 39) { // right arrow
          $(this).closest('td').next().find('input').focus();
    
        } else if (e.which == 37) { // left arrow
          $(this).closest('td').prev().find('input').focus();
 
        } else if (e.which == 40) { // down arrow
          $(this).closest('tr').next().find('td:eq(' + $(this).closest('td').index() + ')').find('input').focus();
 
        } else if (e.which == 38) { // up arrow
          $(this).closest('tr').prev().find('td:eq(' + $(this).closest('td').index() + ')').find('input').focus();
        }
      });
 
    // un-comment to display key code
    // $("input").keydown(function (e) {
    //   console.log(e.which);
    // });
    });


document.addEventListener("keydown", function(event) {
  var index = 0;
  var rowIndex=$('#dataTable'+index+' input:focus').closest('tr').index();
  if ($('#dataTable'+index+' input').is(':focus')) {
    if (event.keyCode == 113) { //F8
      //addRow('dataTable'+index);
      $('.dataTable').each(function(){
        addRow($(this).attr('id'));
      });
    }
    if (event.keyCode == 114) { //F9
      //delRow('dataTable'+index);
      $('.dataTable').each(function(){
        delRow($(this).attr('id'),rowIndex);
      });
    }
    if (event.keyCode == 13) {
        
        event.preventDefault();
        return false;
    }
  }
});

function addRow(id){
  var table=document.getElementById(id);
  var rowCount=table.rows.length;
  var row=table.insertRow(rowCount);
  var colCount=table.rows[1].cells.length;
  for(var i=0;i<colCount;i++){
      var newcell=row.insertCell(i);
      newcell.innerHTML=table.rows[1].cells[i].innerHTML;
      newcell.className=table.rows[1].cells[i].className;
      /*switch(newcell.childNodes[0].type){
          case"text":newcell.childNodes[0].value="";
          break;
          case"checkbox":newcell.childNodes[0].checked=false;
          break;
          case"select-one":newcell.childNodes[0].selectedIndex=0;
          break;
      }*/
  }
  $('#'+id+' tr:last td input').val("");
  $('#'+id+' tr:last td input.keep-val').each(function(){
    $(this).val($(this).closest('tr').prev().find('td:eq(' + $(this).closest('td').index() + ')').find('input').val());
  });
  $('#'+id+' tr:last td input').attr("data","");
  $('#'+id+' tr:last td input').attr("alt","");
  $('#'+id+' tr:last td input:first').focus();
  var i=1;
  $('#'+id+' tbody tr td:first-child').each(function() {
    $(this).text(i);
    i++;
  });
  $('input').keyup(function (e) {
      if (e.which == 39) { // right arrow
        $(this).closest('td').next().find('input').focus();

      } else if (e.which == 37) { // left arrow
        $(this).closest('td').prev().find('input').focus();

      } else if (e.which == 40) { // down arrow
        $(this).closest('tr').next().find('td:eq(' + $(this).closest('td').index() + ')').find('input').focus();

      } else if (e.which == 38) { // up arrow
        $(this).closest('tr').prev().find('td:eq(' + $(this).closest('td').index() + ')').find('input').focus();
      }
    });
  
  $('#'+id+' tr:last td div.chosen-container').remove();
  $('#'+id+' tr:last td select.dropchosen').show();
  $('#'+id+' tr:last td select.dropchosen').chosen();
  //$(".dropchosen").trigger("chosen:updated");

  
  $( ".additional_money" ).focusin(function() {
      i_index = $( this ).closest('tr').index();
    });

  $('.nav span').click(function(){
    $('.additional_money:eq('+i_index+')').val($(this).text());
  });
  $('.additional_money').keyup(function(){
    var tong = parseFloat($('#tong').text().replace(/\,/g,'')) || 0;
    tong += parseFloat($('#von').text().replace(/\,/g,'')) || 0;

    var total = 0;
    $('.additional_money').each(function(){
      total += parseFloat(get_number($(this))) || 0;
    });

    if (total > tong) {
      $(this).val("");
    }
  });

  $('.numbers').keyup(function(event) {
      // skip for arrow keys
    if(event.which >= 37 && event.which <= 40) return;
    // format number
    $(this).val(function(index, value) {
      return value
        .replace(/[^0-9-.]/g, "")
        .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });
  });

  
}
function delRow(id,rowIndex){
  try{
      var table=document.getElementById(id);
      var rowCount=table.rows.length;
      if(rowCount<=2){
        alert("Cannot delete all the rows.");
      }
      else{
        table.deleteRow(rowIndex+1);
      }
      
      //$('#'+id+' tr:last td input:first').focus();
      var i=1;
      $('#'+id+' tbody tr td:first-child').each(function() {
        $(this).text(i);
        i++;
      });

      $('.numbers').val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
      
  }
  catch(e){
      alert(e);
  }
}
</script>
<style type="text/css">
.table-container {
    height: 30em;
    font-size: 11px;
}
.table-container table {
    display: flex;
    flex-flow: column;
    height: 100%;
    width: 100%;
}
.table-container table thead {
    /* head takes the height it requires, 
    and it's not scaled when table is resized */
    flex: 0 0 auto;
    width: calc(100% - 0.9em);
}
.table-container table tbody {
    /* body takes all the remaining available space */
    flex: 1 1 auto;
    display: block;
    overflow-y: scroll;
}
.table-container table tbody tr {
    width: 100%;
}
.table-container table thead,
.table-container table tbody tr {
    display: table;
    table-layout: fixed;
}
/* decorations */

.table-container table {
    border: 1px solid lightgrey;
}
.table-container table td, .table-container table th {
    text-align: center;
    padding: 0;
    border: 1px solid lightgrey;
}
.table-container table th {
    border: 1px solid grey;
}
.width-3 {
    width: 3%;
}
.width-5 {
    width: 5%;
}
.width-7 {
    width: 7%;
}
.width-10 {
    width: 10%;
}
.table-container table td input{
  width: 90%;
  margin: 0;
}

.right {
    margin-left: -50px;
    height: auto;
    width: auto;
    background: rgba(0, 0, 0, 0.08);
    border: 0;
}
.bootstrap-select>.btn {
  width: 120px;
    padding-right: 25px;
}
.bootstrap-select:not([class*=col-]):not([class*=form-control]):not(.input-group-btn) {
    width: 100%;
}
span:hover{
    cursor: pointer;
    text-decoration: underline;
}
</style>