<?php
$url_order = 'ASC';
if ($order_by == 'daily_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'document_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'document_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'daily_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'debit')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'credit')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'money')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> BÁO CÁO THU CHI</h1></center>
<div class="add-box">
    <a class="add_button" id="btnExport" >Export excel</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Search">
        <input type="button" name="" id="search-submit" class="button-search" value="Search" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
       
    </div>
    <div class="tablenav top">
        <div class="add-box">
            Từ tháng <input class="monthPicker" style="width:90px" type="search" name="chonngaytao" id="chonngaytao" placeholder="Chọn tháng" <?php if(isset($ngaytao)) echo "value='$ngaytao'"; ?> >    
            Đến tháng <input class="monthPicker" style="width:90px" type="search" name="chonngaytaobatdau" id="chonngaytaobatdau" placeholder="Chọn tháng" <?php if(isset($ngaytaobatdau)) echo "value='$ngaytaobatdau'"; ?> >  

            <input type="button" name="chon" id="chon" class="button" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">        
                                        
        </div>
        <div class="add-box">
                  
            Từ  <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:100px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
        <div class="add-box">
             
        
            <select style="width: 150px;" name="sl_status" id="sl_status">
                <option selected="selected" value="0">Chưa duyệt</option>
                <option  value="1">Đã duyệt</option>
            </select>

        </div>

    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Select</option>
                
                <option value="delete">Delete</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Apply" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">All</option>
			<option value="15">15 items</option>
            <option value="20">20 items</option>
            <option value="50">50 items</option>
            <option value="100">100 items</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Apply" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

        <div class="add-box">
            <a class="add_button" id="approve_all" >Duyệt tất cả</a>
        </div>

      </div>

</div>

<table class="table_data" id="tblExport">
<thead>
    <tr>
        <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','daily_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'daily_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','daily_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'daily_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','code','<?php echo $url_order ?>')">Code <?php if ($order_by == 'code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money_in','<?php echo $url_order ?>')">Thu <?php if ($order_by == 'money_in'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money_out','<?php echo $url_order ?>')">Chi <?php if ($order_by == 'money_out'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','service','<?php echo $url_order ?>')">Tên dịch vụ <?php if ($order_by == 'service'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','owner','<?php echo $url_order ?>')">Người nhận <?php if ($order_by == 'owner'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','note','<?php echo $url_order ?>')">Ghi chú <?php if ($order_by == 'note'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','account','<?php echo $url_order ?>')">Tài khoản <?php if ($order_by == 'account'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th class="fix">Duyệt</th>
    </tr>
    
   </thead>
   <tbody>
    <?php 
    $tongthu=0; $tongchi=0;
    foreach ($dailys as $daily) : 
        $tongthu += $daily->money_in;
        $tongchi += $daily->money_out;
    ?>
    
        
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $daily->daily_id ?>" class="edit_tr">
            
            <td>
                <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $daily->daily_id ?>">
            </td>
            
            <td  class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="daily_date_<?php echo $daily->daily_id; ?>"><?php echo $lib->hien_thi_ngay_thang($daily->daily_date); ?></td>
            <td class="fix" id="code_<?php echo $daily->daily_id; ?>"><?php echo $daily->code; ?></td>
            <td class="fix" id="comment_<?php echo $daily->daily_id; ?>"><?php echo $daily->comment; ?></td>
            <td class="fix" id="money_in_<?php echo $daily->daily_id; ?>"><?php echo $lib->formatMoney($daily->money_in); ?></td>
            <td class="fix" id="money_out_<?php echo $daily->daily_id; ?>"><?php echo $lib->formatMoney($daily->money_out); ?></td>
            <td class="fix" id="service_<?php echo $daily->daily_id; ?>"><?php echo $daily->service==1?"Hành chính":($daily->service==2?"Lốp xe":"Logistics"); ?></td>
            <td class="fix" id="owner_<?php echo $daily->daily_id; ?>"><?php echo $daily->owner; ?></td>
            <td class="fix" id="note_<?php echo $daily->daily_id; ?>"><?php echo $daily->note; ?></td>
            <td class="fix" id="account_<?php echo $daily->daily_id; ?>"><?php echo $daily->account; ?></td>
            <td class="fix" style="display:none" data="<?php echo $daily->debit ?>" id="debit_<?php echo $daily->daily_id; ?>"><?php echo isset($account_data[$daily->debit])?$account_data[$daily->debit]:null; ?></td>
            <td class="fix" style="display:none" data="<?php echo $daily->credit ?>" id="credit_<?php echo $daily->daily_id; ?>"><?php echo isset($account_data[$daily->credit])?$account_data[$daily->credit]:null; ?></td>
            
            <td class="fix" id="approve_<?php echo $daily->daily_id; ?>"><?php echo isset($users['name'][$daily->approve])?$users['name'][$daily->approve]:(($_SESSION['role_logined']==1 || $_SESSION['role_logined']==9)?'<button data="'.$daily->daily_id.'" class="approve">Duyệt</button>':null); ?></td> 
            
        </tr>


    <?php endforeach; ?>
        <tr style="font-weight:bold; color:red" >
                <td class="fix" colspan="3">Tổng cộng</td>
                <td class="fix"></td>
                <td class="fix"></td>
                <td class="fix"><?php echo $lib->formatMoney($tongthu) ?></td>
                <td class="fix"><?php echo $lib->formatMoney($tongchi) ?></td>
                <td class="fix"></td>
                <td class="fix"></td>
                <td class="fix"></td>
                <td class="fix"></td>
                <td class="fix"></td>
            </tr>
     
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div style="display:none" id="lasted"></div>
<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });


 
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');

var t = "<?php echo $trangthai ?>";
$('#sl_status option[value='+t+']').attr('selected','selected');


</script>
</div>

<script type="text/javascript">


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Báo cáo thu chi",
    hide: 'fold',
    show: 'blind'
});



$(".show").click(function(){
    $("#winpopup").dialog({
        draggable:true,
        modal: true,
        autoOpen: false,
        width: "90%",
        resizable: false,
        position: "top",
        title:'Chi tiết',
        buttons: {
            OK: function() {
                $( this ).dialog( "close" );
            },
            Cancel: function() {
                $( this ).dialog( "close" );
            }
        }
    });
    $("#winpopup").load($(this).attr('href'));
    $("#winpopup").dialog("open");
    return false;
});

var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".ngay").datepicker(pickerOpay2);

var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts3);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);

    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        changeMonth: true,
        changeYear: true,
        dateFormat: 'mm/yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function() {
                $("#chonngaytao").change();
         },
         
    };  
    $("#chonngaytao").datepicker(pickerOpts);

    $("#chonngaytao").change(function(){
        var month = parseInt($("#ui-datepicker-div .ui-datepicker-month :selected").val());
        var year = parseInt($("#ui-datepicker-div .ui-datepicker-year :selected").val());
        $(this).datepicker('setDate', new Date(year, month, 1));

        var firstDay = new Date(year, month, 1);

        $('#batdau').datepicker("setDate", firstDay );
    });

    var pickerOpts5 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        changeMonth: true,
        changeYear: true,
        dateFormat: 'mm/yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function() {
                $("#chonngaytaobatdau").change();
         },
         
    };  
    $("#chonngaytaobatdau").datepicker(pickerOpts5);

    $("#chonngaytaobatdau").change(function(){
        var month = parseInt($("#ui-datepicker-div .ui-datepicker-month :selected").val());
        var year = parseInt($("#ui-datepicker-div .ui-datepicker-year :selected").val());
        $(this).datepicker('setDate', new Date(year, month, 1));

        var lastDay = new Date(year, month+1, 0);
        $('#ketthuc').datepicker("setDate", lastDay );
    });

    $(".monthPicker").focus(function () {
        $(".ui-datepicker-calendar").hide();
        $("#ui-datepicker-div").position({
            my: "center top",
            at: "center bottom",
            of: $(this)
        });    
    });

$('.approve').click(function(){
    var id = $(this).attr("data");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/daily/approve", {data: id},
           function(data){
            
            $("#approve_"+id).text("<?php echo $_SESSION['user_logined'] ?>");

            $('#loading').fadeOut(200);
           
           }); 
      }

});
$('#approve_all').click(function(){
    var id = 1;
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/daily/approveall", {data: id},
           function(data){
            
            searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
            $('#loading').fadeOut(200);
           
           }); 
      }

});

$('#sl_status').change(function(){
    searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
});
</script>

