<?php
$url_order = 'ASC';
if ($order_by == 'tire_order_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_brand_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_size_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_order_tire_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> ĐƠN ĐẶT HÀNG</h1></center>
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm đơn đặt hàng</a>
</div>
    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Search">
        <input type="button" name="" id="search-submit" class="button-search" value="Search" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
       
    </div>
    <div class="tablenav top">

        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Select</option>
                
                <option value="delete">Delete</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Apply" onclick="action();">
        </div>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
            <option  value="18446744073709">All</option>
            <option value="15">15 items</option>
            <option value="20">20 items</option>
            <option value="50">50 items</option>
            <option selected="selected" value="100">100 items</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Apply" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                              
        </div>

        
      </div>

</div>

<table class="table_data">
<thead>
    <tr>
        <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_order_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'tire_order_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_order_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'tire_order_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_brand_name','<?php echo $url_order ?>')">Thương hiệu <?php if ($order_by == 'tire_brand_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_size_number','<?php echo $url_order ?>')">Size <?php if ($order_by == 'tire_size_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_pattern','<?php echo $url_order ?>')">Mã gai <?php if ($order_by == 'tire_pattern'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_number','<?php echo $url_order ?>')">Số lượng <?php if ($order_by == 'tire_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_price','<?php echo $url_order ?>')">Giá bán <?php if ($order_by == 'tire_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_receive_date','<?php echo $url_order ?>')">Ngày giao hàng <?php if ($order_by == 'tire_receive_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_price','<?php echo $url_order ?>')">Tổng cộng <?php if ($order_by == 'tire_price'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        
        <th class="fix"></th>
    </tr>
    
   </thead>
   <tbody>
    <?php $tongtt=0; $tong=0; ?>
    <?php foreach ($tire_orders as $tire_order) : ?>
    
        <?php $tong += $tire_order->tire_number; $tongtt += $tire_order->tire_number*$tire_order->tire_price; ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $tire_order->tire_order_id ?>" class="edit_tr">
            
            <td>
                <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $tire_order->tire_order_id ?>">
            </td>
            
            <td  class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="tire_order_date_<?php echo $tire_order->tire_order_id; ?>"><?php echo $lib->hien_thi_ngay_thang($tire_order->tire_order_date); ?></td>
            <td class="fix" data="<?php echo $tire_order->customer ?>" id="customer_<?php echo $tire_order->tire_order_id; ?>"><?php echo $tire_order->customer_name; ?></td>
            <td class="fix" id="tire_brand_<?php echo $tire_order->tire_order_id; ?>"><?php echo $tire_order->tire_brand_name; ?></td>
            <td class="fix" id="tire_size_<?php echo $tire_order->tire_order_id; ?>"><?php echo $tire_order->tire_size_number; ?></td>
            <td class="fix" data="<?php echo $tire_order->tire_pattern; ?>" id="tire_pattern_<?php echo $tire_order->tire_order_id; ?>"><?php echo $tire_order->tire_pattern_name; ?></td>
            <td class="fix" id="tire_number_<?php echo $tire_order->tire_order_id; ?>"><?php echo $tire_order->tire_number; ?></td>
            <td class="fix" id="tire_price_<?php echo $tire_order->tire_order_id; ?>"><?php echo $lib->formatMoney($tire_order->tire_price); ?></td>
            <td class="fix" id="tire_receive_date_<?php echo $tire_order->tire_order_id; ?>"><?php echo $tire_order->tire_receive_date>0?$lib->hien_thi_ngay_thang($tire_order->tire_receive_date):null; ?></td>
            <td class="fix" id="profit_<?php echo $tire_order->tire_order_id; ?>"><?php echo $lib->formatMoney($tire_order->tire_number*$tire_order->tire_price); ?></td>
            
            <td>
                <button data="<?php echo $tire_order->customer ?>"  class="editButton">Xuất hợp đồng</button>

                <button class="error" onclick="del(<?php echo $tire_order->tire_order_id; ?>)" >Xóa</button>
                <?php
                    if ($tire_order->status != 1) {
                ?>
                        <button class="approve receive" data="<?php echo $tire_order->tire_order_id; ?>" >Đã giao hàng</button>
                <?php  
                    }
                ?>
               
            </td>
        </tr>


    <?php endforeach; ?>
    <tr style="text-align:center; font-weight: bold; color: red;">
        <td class="fix" colspan="7" >Tổng cộng</td>
        <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
        <td class="fix" ></td>
        <td class="fix" ></td>
        <td class="fix"><?php echo $lib->formatMoney($tongtt); ?></td>
        <td class="fix" ></td>
    </tr>
     
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('tiresale') ?>">&larr;</a></div>
<div style="display:none" id="lasted"></div>
<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Đơn hàng </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_tire" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            <td>Ngày GD</td>
                            <td>
                                <input  class="ngay" type="text" id="tire_order_date"  name="tire_order_date" tabindex="1"  required="required" >
                                
                            </td>
                            <td>Khách hàng </td>
                            <td><input type="text"  id="customer" name="customer" tabindex="2"  autocomplete="off" required="required" placeholder="Nhập tên hoặc * để chọn" > <a style="font-size: 24px; font-weight: bold; color:red" title="Thêm mới" target="_blank" href="<?php echo $this->url('customer') ?>"> + </a>
                                <ul id="customer_list_id"></ul>
                            </td>
                            
                            
                            
                        </tr>
                        <tr>
                            <td>Thương hiệu</td>
                            <td>
                                <select name="tire_brand" id="tire_brand" tabindex="3"  required="required">
                                    <?php foreach ($tire_brands as $tire_brand) { ?>
                                        <option value="<?php echo $tire_brand->tire_brand_id ?>"><?php echo $tire_brand->tire_brand_name ?></option>
                                    <?php } ?>
                                    
                                </select>
                                
                            </td>
                            <td>Size</td>
                            <td>
                                <select name="tire_size" id="tire_size" tabindex="4"  required="required">
                                    <?php foreach ($tire_sizes as $tire_size) { ?>
                                        <option value="<?php echo $tire_size->tire_size_id ?>"><?php echo $tire_size->tire_size_number ?></option>
                                    <?php } ?>
                                    
                                </select>
                                
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Mã gai
                            </td>
                            <td>
                                <input type="text" class="tire_pattern" id="tire_pattern" name="tire_pattern" required="required" autocomplete="false" placeholder="Nhập mã hoặc * để chọn" tabindex="5"> 
                                <ul class="tire_list_id"></ul>
                            </td>
                            <td>Số lượng</td>
                            <td>
                                <input style="width:50px" class="number" type="text" id="tire_number"  name="tire_number" tabindex="6"  required="required" >
                                
                            </td>
                            
                            
                        </tr>
                        <tr>
                            <td>Giá bán</td>
                            <td>
                                <input style="width:80px" class="numbers" type="text" id="tire_price"  name="tire_price" tabindex="7"  required="required" >
                                
                            </td>
                            <td>Ngày giao hàng</td>
                            <td>
                                <input style="width:80px" class="ngay" type="text" id="tire_receive_date"  name="tire_receive_date" tabindex="8"  >
                                
                            </td>
                        </tr>
                                  
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td></td>
                            

                            <td>
                                <input type="submit" name="submit" value="Submit" tabindex="9">
                                
                            </td>
                            <td></td>
                            <td>
                                <input type="reset" name="reset" value="Reset" tabindex="10">
                            </td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>

<div id="dialogContent" title="Hợp đồng">
    
    
    <form action="#" method="post" id="editForm">
        <label>
            <input type="hidden" id="contract_customer" name="contract_customer" value="" />
            <span class="add-on"><i class="icon-calendar" ></i></span>
            <span>Ngày: </span>
            <input type="text" id="contract_date" name="contract_date" value="" class="pay_date" required="required" />
        </label>
        <label>
            <span class="add-on"><i class="icon-ok-circle" ></i></span>
            <span>Số hợp đồng: </span>
            <input type="text" id="contract_number" name="contract_number" value="" required="required" />
        </label>
        
        <label>
            <span class="add-on"><i class="icon-retweet" ></i></span>
            <span>Phương thức thanh toán (%): </span>
            Đợt 1: <input type="text" id="contract_pay" name="contract_pay" value="" required="required" />
            Đợt 2: <input type="text" id="contract_pay2" name="contract_pay2" value="" required="required" />
        </label>
        <label>
            <span class="add-on"><i class="icon-calendar" ></i></span>
            <span>Hiệu lực: </span>
            <input type="text" id="contract_valid" name="contract_valid" value="" class="pay_date" required="required" />
        </label>
        
    </form>
</div>


<script type="text/javascript">


  
$('.add-field').hide();  


$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);      
    }
    $('#customer_list_id').slideUp(200);
    $('.tire_list_id').slideUp(200);  

    if ($('#customer').attr('data') == "") {
        $('#customer').val("");
        $('#customer').focus();
    };

    
});



    $('.edit_tr').click(function(e){
        if(e.target != '[object HTMLButtonElement]' && e.target != '[object HTMLSpanElement]' && !$('.checkbox').is(':focus')) { 
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            
            var tire_brand = $(this).find("#tire_brand_"+$(this).attr('id')).text();
            var tire_size = $(this).find("#tire_size_"+$(this).attr('id')).text();
            var tire_number = $(this).find("#tire_number_"+$(this).attr('id')).text();
            var tire_price = $(this).find("#tire_price_"+$(this).attr('id')).text();
            var tire_order_date = $(this).find("#tire_order_date_"+$(this).attr('id')).text();
            var tire_receive_date = $(this).find("#tire_receive_date_"+$(this).attr('id')).text();
            var customer_name = $(this).find("#customer_"+$(this).attr('id')).text();
            var customer = $(this).find("#customer_"+$(this).attr('id')).attr('data');
            var tire_pattern_name = $(this).find("#tire_pattern_"+$(this).attr('id')).text();
            var tire_pattern = $(this).find("#tire_pattern_"+$(this).attr('id')).attr('data');

            //alert(cost_code);
            $('#yes').val($(this).attr('id'));
            
            $('#tire_receive_date').val(tire_receive_date.replace(/\//g,"-"));
            $("#tire_brand option:contains(" + tire_brand + ")").attr('selected', 'selected');
            $("#tire_size option:contains(" + tire_size + ")").attr('selected', 'selected');
            $('#tire_number').val(tire_number);
            $('#tire_price').val(tire_price);
            $('#tire_order_date').val(tire_order_date.replace(/\//g,"-"));
            $('#customer').val(customer_name);
            $('#customer').attr('data',customer);
            $('#tire_pattern').val(tire_pattern_name);
            $('#tire_pattern').attr('data',tire_pattern);

            $( ".add-field" ).dialog( "open" );
        }

        
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
     
        $('#tire_number').val("");
        $('#tire_price').val("");
        $('#tire_order_date').val("");
        $('#customer').val("");
        $('#customer').attr('data',"");
        $('#tire_pattern').val("");
        $('#tire_pattern').attr('data',"");
                
        $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

    $( ".add-field" ).dialog( "open" );
}


$(document).ready(function(){
            // Validate form
            $("#add_tire").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var tire_receive_date = $('#tire_receive_date').attr('value');
                    var tire_brand = $('#tire_brand').attr('value');
                    var tire_size = $('#tire_size').attr('value');
                    var tire_number = $('#tire_number').attr('value');
                    var tire_price = $('#tire_price').attr('value');
                    var tire_order_date = $('#tire_order_date').attr('value');
                    var customer = $('#customer').attr('data');
                    var tire_pattern = $('#tire_pattern').attr('data');
                    var tire_pattern_name = $('#tire_pattern').attr('value');
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/tireorder/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            tire_receive_date: tire_receive_date,
                            tire_brand: tire_brand,
                            tire_size: tire_size,
                            tire_number: tire_number,
                            tire_price: tire_price,
                            tire_order_date: tire_order_date,
                            customer: customer,
                            tire_pattern_name: tire_pattern_name,
                            tire_pattern: tire_pattern,

                            yes: yes,

                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

                                    $('#expect_date_'+yes).text(expect_date);
                                    $('#comment_'+yes).text(comment);
                                    $('#money_'+yes).text(money);
                                    $('#source_'+yes).text($("#source option:selected").text());
                                    $('#source_in_'+yes).text($("#source_in option:selected").text());
                            }
                            else{
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="vendor_'+parseInt(lastID+1)+'">'+vendor+'</td><td class="fix" id="money_'+parseInt(lastID+1)+'">'+money+'</td><td class="fix" id="expect_date_'+parseInt(lastID+1)+'">'+expect_date+'</td><td class="fix" id="week_'+parseInt(lastID+1)+'"></td><td class="fix" id="code_'+parseInt(lastID+1)+'">'+code+'</td><td class="fix" id="source_'+parseInt(lastID+1)+'">'+$("#source option:selected").text()+'</td><td class="fix" id="comment_'+parseInt(lastID+1)+'">'+comment+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                
                            }
                        }
                    });
                    return false;
                     
                 }
            });

$('.tire_pattern').keyup(function(){
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/tireprice/getpattern',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                $('.tire_list_id').slideDown(200);
                $('.tire_list_id').html(data);
            }
        });
        if ($('.tire_pattern').val() == "" || $('.tire_pattern').attr('data') == "") {
            
            $('.tire_pattern').attr('data',"");
        }

        
    });

$('#customer').keyup(function(){
      
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/salereport/getcustomer',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                $('#customer_list_id').slideDown(200);
                $('#customer_list_id').html(data);
            }
        });
        if ($('#customer').val() == "" || $('#customer').attr('data') == "") {
            
            $('#customer').attr('data',"");
        }
      
      
   });  
$('#customer').on('keydown', function() {
        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('#customer').attr('data',"");
        }
            
      });  


   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-]/g, "")
        ;
      });
    });
    

});

function get_number(id){
    return $(id).val().replace(/\,/g,'');
}
function set_item(item,value,phone,address,email,ngay) {
    // change input value
    $('#customer').val(item);
    $("#customer").attr("data",value);
    $('#customer_list_id').hide();
    $('#customer').focus();

}
function set_item_tire(item,name) {
    // change input value
    $('.tire_pattern').val(item);
    $(".tire_pattern").attr("data",name);
    
    $('.tire_list_id').hide();
    $('.tire_pattern').focus();
}
</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });


 
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');


</script>
</div>

<script type="text/javascript">


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Lô hàng",
    hide: 'fold',
    show: 'blind'
});


var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".ngay").datepicker(pickerOpay2);

$('.receive').click(function(){
    var id = $(this).attr("data");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/tireorder/receive", {data: id},
           function(data){
            

            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }
});
</script>

<script type="text/javascript">

$('.editButton')
    .button({ icons: { primary: "ui-icon-document" }})
    .click(function() {
        
        $('#contract_customer').val($(this).attr('data'));

        $( "#dialogContent" ).dialog( "open" )
    });


//set up the dialog box.
$( "#dialogContent" ).dialog({
    autoOpen: false,
    modal: true,
    buttons: {
        OK: function() {
            var customer = $('#contract_customer').val();
            var date = $('#contract_date').val();
            var number = $('#contract_number').val();
            var pay = $('#contract_pay').val();
            var pay2 = $('#contract_pay2').val();
            var valid = $('#contract_valid').val();
            
            
            number = number.replace(/ /g,"$");

            $("#winpopup").dialog({
                draggable:true,
                modal: true,
                autoOpen: false,
                width: "90%",
                height: 600,
                resizable: false,
                title:'Chi tiết',
                buttons: {
                    OK: function() {
                        window.location.href = "<?php echo BASE_URL ?>/tireorder/contract/"+customer+"/0/0/0/"+date+"@"+number+"@"+pay+"@"+pay2+"@"+valid;
                    },
                    Cancel: function() {
                        $( this ).dialog( "close" );
                    }
                }
            });
            $("#winpopup").load("<?php echo BASE_URL ?>/tireorder/contract/"+customer+"/0/0/0/"+date+"@"+number+"@"+pay+"@"+pay2+"@"+valid);
            $("#winpopup").dialog("open");
            
            //     $.post("<?php echo BASE_URL ?>/marketing/contract", {customer: customer, from: from, to: to,date: date, number: number, pay: pay, valid: valid},
            //       function(data){
                        
            //        });  
              
            // $( this ).dialog( "close" );
        },        
        Cancel: function() {
            $( this ).dialog( "close" );
        }
    }
});



var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".pay_date").datepicker(pickerOpay2);
</script>