<style type="text/css">
    .ui-datepicker-calendar {
        display: none;
    }​
</style>
<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        changeMonth: true,
        changeYear: true,
        dateFormat: 'MM yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function() {
                $("#chonngaytao").change();
         },
         
    };  
    $("#chonngaytao").datepicker(pickerOpts);
              
            
    $("#chonngaytao").change(function(){
        var month = parseInt($("#ui-datepicker-div .ui-datepicker-month :selected").val());
        var year = parseInt($("#ui-datepicker-div .ui-datepicker-year :selected").val());
        if (month<9) {
            var ngay = "0"+(month+1)+"-"+year;
        }
        else
            var ngay = (month+1)+"-"+year;

        var page = "<?php echo $page; ?>";
        var cot = "<?php echo $order_by; ?>";
        var sapxep = "<?php echo $order; ?>";
        var keyword = "<?php echo $keyword; ?>";
        var loc =    $('#chonloc').val();
        
        
        var dataString = 'keyword='+ keyword+"&limit="+loc+"&ngaytao="+ngay+"&page="+ page +"&order_by="+ cot +"&order="+ sapxep;  
        
        $('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
        
            $.ajax({
                type: "POST",                            // Phương thức gọi là GET
                url: "#",                 // File xử lý
                data: dataString,                       // Dữ liệu truyền vào
                beforeSend:  function() {               // add class "loading" cho khung nhập
                    $('input#search-input').addClass('loading');
                },
                success: function(server_response)      // Khi xử lý thành công sẽ chạy hàm này
                {
                    $('body').html(server_response);    // Hiển thị dữ liệu vào thẻ div #searchresultdata
                    
                     
                    if ($('input#search-input').hasClass("loading")) {      // Kiểm tra class "loading"
                        $("input#search-input").removeClass("loading");     // Remove class "loading"
                    }
                    $('#loading').fadeOut(500); 
                }
            });
        
        
    });
});
</script>
<?php
$url_order = 'ASC';
if ($order_by == 'check_salary_percent_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'order_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'order_new')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'order_old')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'create_time')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);
    

$tongthanhtien = 0;

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> PHẦN TRĂM TÍNH LƯƠNG </h1></center>
    <?php if($_SESSION['role_logined'] != 10){ ?>
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm bảng tính lương</a>
    
    <a class="add_button" id="btnExport"> Export Excel</a>
     

</div>
<?php } ?>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
        <div class="add-box">
        	<input type="search" name="chonngaytao" id="chonngaytao" placeholder="Chọn ngày" <?php if(isset($thang)) echo 'value="'.date('m-Y',$thang).'"'; else if(isset($ngaytao)) echo "value='$ngaytao'"; ?>>  
                                        
        </div>
    	<div class="alignleft actions">
            <?php if($_SESSION['role_logined'] != 10){ ?>
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
        <?php } ?>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="5">Hiển thị 5 giá trị</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="15">Hiển thị 15 giá trị</option>
            <option selected="selected" value="20">Hiển thị 20 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">

        </div>
        
      </div>


</div>

<table class="table_data" id="tblExport">
<thead>
    <tr>
    	<th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','check_salary_percent_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'check_salary_percent_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','order_percent','<?php echo $url_order ?>')">Lương sản phẩm (%) <?php if ($order_by == 'order_percent'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>  
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','order_number','<?php echo $url_order ?>')">Lương sản lượng <?php if ($order_by == 'order_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','order_new','<?php echo $url_order ?>')">Khách hàng mới <?php if ($order_by == 'order_new'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','order_old','<?php echo $url_order ?>')">Khách hàng cũ <?php if ($order_by == 'order_old'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','create_time','<?php echo $url_order ?>')">Tháng <?php if ($order_by == 'create_time'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>  
        
        <th class="fix">&nbsp;</th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($checksalarypercents as $salary) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $salary->check_salary_percent_id ?>" class="edit_tr">
        	<td>
                <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $salary->check_salary_percent_id ?>">
                
            </td>
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="order_percent_<?php echo $salary->check_salary_percent_id; ?>"><?php echo $salary->order_percent; ?></td>
            <td class="fix" id="order_number_<?php echo $salary->check_salary_percent_id; ?>"><?php echo $lib->formatMoney($salary->order_number); ?></td>
            <td class="fix" id="order_new_<?php echo $salary->check_salary_percent_id; ?>"><?php echo $lib->formatMoney($salary->order_new); ?></td>
            <td class="fix" id="order_old_<?php echo $salary->check_salary_percent_id; ?>"><?php echo $lib->formatMoney($salary->order_old); ?></td>
            <td class="fix" id="create_time_<?php echo $salary->check_salary_percent_id; ?>"><?php echo date('m-Y',$salary->create_time); ?></td>
            
            <td>
                <button onclick="del(<?php echo $salary->check_salary_percent_id ?>)" >Xóa</button>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('checksalarypercent') ?>">&larr;</a></div>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Thông tin</h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_salary" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td style="float:right;padding:10px">Tháng</td>
                            <td><input readonly type="text" id="create_time" name="create_time" tabindex="1" required="required"></td>
                            
                        </tr>
                        <tr>
                            <td>Lương sản phẩm (%) </td>
                            <td><input type="text" id="order_percent" name="order_percent" tabindex="1"  required="required"></td>
                            <td>Lương sản lượng </td>
                            <td><input type="text" id="order_number" class="number" name="order_number" tabindex="2"  required="required"></td>
    
                        </tr>
                        <tr>
                            <td>Khách hàng mới </td>
                            <td><input type="text" id="order_new" class="number" name="order_new" tabindex="3"  ></td>
                            <td>Khách hàng cũ </td>
                            <td><input type="text" id="order_old" class="number" name="order_old" tabindex="4"  ></td>
    
                        </tr>
                        
                         <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td><input type="submit" name="submit" value="Hoàn tất" tabindex="5"></td>
                            <td ><input type="reset" name="reset" value="Nhập lại" tabindex="6"></td>
                            
                             
                        </tr>
                        
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>
<script type="text/javascript">
$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }
   $('#staff_list_id').slideUp(200);
});
    $('.edit_tr').click(function(e){

        if(e.target != '[object HTMLButtonElement]' && !$('.checkbox').is(':focus')){
            if(!$('.checkbox').is(':checked')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            var order_number = $(this).find("#order_number_"+$(this).attr('id')).text();
            var order_percent = $(this).find("#order_percent_"+$(this).attr('id')).text();
            var order_new = $(this).find("#order_new_"+$(this).attr('id')).text();
            var order_old = $(this).find("#order_old_"+$(this).attr('id')).text();
            var create_time = $(this).find("#create_time_"+$(this).attr('id')).text();
            //alert(staff_name);
            $('#yes').val($(this).attr('id'));
            $('#order_number').val(order_number);
            $('#order_percent').val(order_percent);
            $('#order_new').val(order_new);
            $('#order_old').val(order_old);
            $('#create_time').val(create_time);


            $( ".add-field" ).dialog( "open" );
        }

    });
</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
    $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
    
     
        $('#order_number').val("");
        $('#order_new').val("");
        $('#order_old').val("");
        $('#create_time').prop('readonly',false);
        $('#create_time').val("<?php echo date('m-Y',strtotime('-1 month')) ?>");

        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

        var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        changeMonth: true,
        changeYear: true,
        dateFormat: 'MM yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function() {
            var month = parseInt($("#ui-datepicker-div .ui-datepicker-month :selected").val());
            var year = parseInt($("#ui-datepicker-div .ui-datepicker-year :selected").val());
            if (month<9) {
                var ngay = "0"+(month+1)+"-"+year;
            }
            else
                var ngay = (month+1)+"-"+year;
               $("#create_time").val(ngay);
         },
         
    };  
    $("#create_time").datepicker(pickerOpts);

    $( ".add-field" ).dialog( "open" );


}


$(document).ready(function(){
            // Validate form
            $("#add_salary").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                    
                    var order_number = $('#order_number').attr('value');
                    var order_percent = $('#order_percent').attr('value');
                    var order_new = $('#order_new').attr('value');
                    var order_old = $('#order_old').attr('value');
                    var create_time = $('#create_time').attr('value');
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/checksalarypercent/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            order_number: order_number,
                            order_percent: order_percent,
                            order_new: order_new,
                            order_old: order_old,
                            create_time: create_time,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes == "") {
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                
                            }
                            else{
                                if (answer.trim() != "Bảng lương này đã tồn tại") {

                                    setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);


                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   

$('.number').keyup(function(){
    // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
});



});
  
function get_number(id){
    return $(id).val().replace(/[^0-9\.-]+/g,"");
}
function set_item(item,value,code,birth,gender) {
    // change input value
    $('#staff_name').val(item);
    $("#staff_name").attr("data",value);
    $('#staff_list_id').hide();
    $('#staff_name').focus();
    $('#staff_name').attr('code','true');
}
</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');
</script>
</div>

<script type="text/javascript">


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Bảng tính lương",
    hide: 'fold',
    show: 'blind'
});



</script>