<?php
    $today = strtotime($ngay);
    $max = $max < strtotime(date('d-m-Y')) ? strtotime(date('d-m-Y')) : $max;
    $total = $total;
    $now = $total;

    $k=1;
?>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;"><h1> TỒN KHO</h1></center>

</div>
<div style="width:90%;">
    <div style="text-align:left">
        <form id="inven" method="post" action="">
            Ngày: <input style="width:90px" type="text"  id="date" name="date" value="<?php echo $ngay ?>"><input type="submit" id="check" value="Kiểm tra">
        </form>
        
    </div>
</div>
<div class="add-box">
    <a class="add_button" id="btnExport">Export Excel</a>
    
</div>
<div style="clear:both"></div>

<div style="width:30%;float:left">
    <table class="table_data">
        <thead>
            <tr>
                <th class="fix">Ngày</th>
                <th class="fix">Sản lượng nhập</th>
                <th class="fix">Sản lượng bán</th>
                <th class="fix">Tồn kho</th>
            </tr>
        </thead>
        <tbody>
            <?php for ( $i = $today; $i <= ($max+86400); $i = $i + 86400 ) { 
                $buy = isset($tire[date('d-m-Y',$i)]['buy'])?$tire[date('d-m-Y',$i)]['buy']:null;
                $sale = isset($tire[date('d-m-Y',$i)]['sale'])?$tire[date('d-m-Y',$i)]['sale']:null;
                $now += ($buy-$sale); 
            ?>
            <tr>
                  <td class="fix"><?php echo date('d/m/Y',$i) ?></td>
                  <td class="fix"><a target="_blank" href="<?php echo BASE_URL ?>/tiresale/index/<?php echo strtotime(date('d-m-Y',$i)) ?>"><?php echo $buy ?></a></td>
                  <td class="fix"><a target="_blank" href="<?php echo BASE_URL ?>/tiresale/sale/<?php echo strtotime(date('d-m-Y',$i)) ?>"><?php echo $sale ?></a></td>
                  <td class="fix <?php echo $total != $now?'error':null; ?>"><?php echo $total += ($buy-$sale) ?></td>
            </tr>
            <?php  }  ?>
        </tbody>
            
    </table>
</div>
<div style="width:68%;float:right">
    <table id="tblExport" class="table_data">
<thead>
    <tr>
        <th  class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_buy_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'tire_buy_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_brand_name','<?php echo $url_order ?>')">Thương hiệu <?php if ($order_by == 'tire_brand_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_size_number','<?php echo $url_order ?>')">Size <?php if ($order_by == 'tire_size_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_buy_pattern','<?php echo $url_order ?>')">Mã gai <?php if ($order_by == 'tire_buy_pattern'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_buy_volume','<?php echo $url_order ?>')">Tồn kho <?php if ($order_by == 'tire_buy_volume'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_buy_volume','<?php echo $url_order ?>')">Giá vốn <?php if ($order_by == 'tire_buy_volume'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_buy_volume','<?php echo $url_order ?>')">Tổng cộng <?php if ($order_by == 'tire_buy_volume'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
    </tr>
    
   </thead>
   <tbody>
    <?php $doanhthu=0; $chiphi=0; $loinhuan=0; $soluong = 0; $daban=0; $tonkho=0; $tonggiatri=0;?>
    <?php foreach ($tire_buys as $tire_buy) : ?>
    
    <?php 
        $doanhthu += (isset($tire_buy_data[$tire_buy->tire_buy_id]['revenue'])?$tire_buy_data[$tire_buy->tire_buy_id]['revenue']:0);
        $chiphi += (isset($tire_buy_data[$tire_buy->tire_buy_id]['cost'])?$tire_buy_data[$tire_buy->tire_buy_id]['cost']:0);
        $soluong += $tire_buy->soluong;
        $daban += (isset($sell[$tire_buy->tire_buy_id]['number'])?$sell[$tire_buy->tire_buy_id]['number']:0);

        $ton = $tire_buy->soluong - (isset($sell[$tire_buy->tire_buy_id]['number'])?$sell[$tire_buy->tire_buy_id]['number']:0);

        if($ton != 0){
            $giatri = $tire_prices[$tire_buy->tire_buy_brand][$tire_buy->tire_buy_size][$tire_buy->tire_buy_pattern];
            $thanhtien = $ton*$giatri;
            $tonggiatri += $thanhtien;
    ?>
        
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $tire_buy->tire_buy_id ?>" class="edit_tr">
            
            
            <td  class="fix"><?php echo $k++; ?></td>
            <td class="fix" id="tire_buy_brand_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $tire_buy->tire_brand_name; ?></td>
            <td class="fix" id="tire_buy_size_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $tire_buy->tire_size_number; ?></td>
            <td class="fix" data="<?php echo $tire_buy->tire_buy_pattern; ?>" id="tire_buy_pattern_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $tire_buy->tire_pattern_name; ?></td>
            
            <td class="fix" id="conlai_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $lib->formatMoney($ton ); ?></td>
            <td class="fix" id="giatri_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $lib->formatMoney($giatri ); ?></td>
            <td class="fix" id="thanhtien_<?php echo $tire_buy->tire_buy_id; ?>"><?php echo $lib->formatMoney($thanhtien ); ?></td>
            
        </tr>

    <?php } ?>
    <?php endforeach; ?>

    <tr style="text-align:center; font-weight: bold; color: red;">
        <td class="fix" colspan="4" >Tổng cộng</td>
        <td class="fix"><?php echo $soluong-$daban; ?></td>
        <td class="fix" ></td>
        <td class="fix" ><?php echo $lib->formatMoney($tonggiatri ); ?></td>
    </tr>
     
   </tbody>
</table>
</div>

<script type="text/javascript">
  

var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $("#date").datepicker(pickerOpay2);

</script> 