<div class="slide-content" id="tam-nhin-va-huong-phat-trien">
			<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_native_toolbox"></div>
        <div class="item-page">
            <body spellcheck="false"><p class="MsoNormal"><b><span style="font-size:18.0pt;line-height:107%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">TẦM
NHÌN VÀ SỨ MỆNH<o:p></o:p></span></b></p>

<p class="MsoNormal"><b><span style="font-size:10.0pt;line-height:107%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></b></p>

<p class="MsoListParagraphCxSpFirst" style="margin-bottom:0in;margin-bottom:.0001pt;
mso-add-space:auto;text-align:justify;text-indent:-.25in;line-height:150%;
mso-list:l0 level1 lfo1"><!--[if !supportLists]--><span style="font-size:10.0pt;
line-height:150%;font-family:Wingdings;mso-fareast-font-family:Wingdings;
mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--> 
<img src="public/images/tamnhin.jpg" align="right">
<span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;&nbsp;Bằng
nỗ lực lao động, sáng tạo, và áp dụng khoa học vào quản lý, Công ty CMG mong muốn
trở thành Công ty hàng đầu trong lĩnh vực cung cấp dịch vụ Logistics tại Việt
Nam, khu vực Đông Nam Á và hướng tới Châu Á, Quốc tế. Đồng thời, mong muốn góp
phần đưa thương hiệu Logistics Việt Nam lên bản đồ Logistics Thế giới.<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin-bottom:0in;margin-bottom:
.0001pt;mso-add-space:auto;text-align:justify;line-height:150%"><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p>

<p class="MsoListParagraphCxSpLast" style="margin-bottom:0in;margin-bottom:.0001pt;
mso-add-space:auto;text-align:justify;text-indent:-.25in;line-height:150%;
mso-list:l0 level1 lfo1"><!--[if !supportLists]--><span style="font-size:10.0pt;
line-height:150%;font-family:Wingdings;mso-fareast-font-family:Wingdings;
mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;&nbsp;Công
ty CMG hướng đến mục tiêu cung cấp các giải pháp Logistics và chuỗi cung ứng tối
ưu cho khách hàng với trách nhiệm cao nhất, đem lại hiệu quả vượt trội so với sự
mong đợi của khách hàng, từng bước đưa thương hiệu CMG đạt tiêu chuẩn là thương
hiệu của uy tín và chất lượng.<o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;text-align:
justify;line-height:150%"><span style="font-size:10.0pt;line-height:150%;
font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p>

<p class="MsoNormal" style="text-align:justify"><b><span style="font-size:18.0pt;line-height:107%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">GIÁ
TRỊ CỐT LÕI<o:p></o:p></span></b></p>

<p class="MsoNormal" style="text-align:justify"><b><span style="font-size:10.0pt;line-height:107%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sự
hài lòng của Khách hàng:<o:p></o:p></span></b></p>

<p class="MsoListParagraph" style="text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;
line-height:107%;font-family:Wingdings;mso-fareast-font-family:Wingdings;
mso-bidi-font-family:Wingdings">v<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:107%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;&nbsp;Sự
hài lòng của Khách hàng không chỉ đối với các chất lượng dịch vụ chúng tôi cung
cấp, mà còn là sự tín nhiệm và trung thành, luôn chọn chúng tôi là nhà cung cấp
dịch vụ đầu tiên bất cứ khi nào Khách hàng cần.<o:p></o:p></span></p>
<p><center><img src="public/images/hailongkhachhang.jpg" ></center></p>


        </div>
    </div>


<script type="text/javascript">
    closeSidepage('#tam-nhin-va-huong-phat-trien');
   openSidepage('#tam-nhin-va-huong-phat-trien');
</script>