
<?php
$url_order = 'ASC';
if ($order_by == 'customer_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_address')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_phone')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_email')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'company_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'mst')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_address')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';



    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> DANH SÁCH KHÁCH HÀNG </h1></center>
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm khách hàng mới</a>
    <a class="add_button" id="import_excel" href="<?= $this->url('customer/import')?>">Import Excel</a>
    <a class="add_button" id="btnExport" >Export Excel</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
            <option selected="selected" value="10">Hiển thị 10 giá trị</option>
			<option value="20">Hiển thị 20 giá trị</option>
            <option value="30">Hiển thị 30 giá trị</option>
            <option value="50">Hiển thị 50 giá trị</option>
            
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>

</div>

<table id="tblExport" class="table_data">
<thead>
    <tr>
    	<th rowspan="2" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'customer_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_code','<?php echo $url_order ?>')">Mã KH <?php if ($order_by == 'customer_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Tên khách hàng <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','company_name','<?php echo $url_order ?>')">Công ty <?php if ($order_by == 'company_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','mst','<?php echo $url_order ?>')">MST <?php if ($order_by == 'mst'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_address','<?php echo $url_order ?>')">Địa chỉ <?php if ($order_by == 'customer_address'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_phone','<?php echo $url_order ?>')">Số điện thoại <?php if ($order_by == 'customer_phone'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_email','<?php echo $url_order ?>')">Email <?php if ($order_by == 'customer_email'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>   
        
           
        <th  class="fix">&nbsp;</th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($customers as $customer) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $customer->customer_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $customer->customer_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="customer_code_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_code ?></td>
            <td class="fix"  id="customer_name_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_name ?></td>
            <td class="fix"  id="company_name_<?php echo $customer->customer_id; ?>"><?php echo $customer->company_name; ?></td>
            
            <td class="fix"  id="mst_<?php echo $customer->customer_id; ?>"><?php echo $customer->mst; ?></td>
            <td class="fix" id="customer_address_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_address; ?></td>
            <td class="fix" id="customer_phone_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_phone; ?></td>
            <td class="fix" id="customer_email_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_email; ?></td>
            <td class="fix" style="display:none" id="customer_fax_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_fax; ?></td>
            <td class="fix" style="display:none" id="co_name_<?php echo $customer->customer_id; ?>"><?php echo $customer->co_name; ?></td>
            <td class="fix" style="display:none" id="director_<?php echo $customer->customer_id; ?>"><?php echo $customer->director; ?></td>
            <td class="fix" style="display:none" id="customer_bank_name_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_bank_name; ?></td>
            <td class="fix" style="display:none" id="account_number_<?php echo $customer->customer_id; ?>"><?php echo $customer->account_number; ?></td>
            <td class="fix" style="display:none" id="cmg_bank_<?php echo $customer->customer_id; ?>"><?php echo $customer->cmg_bank; ?></td>
            <td class="fix" style="display:none" id="customer_expect_date_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_expect_date; ?></td>
            <td class="fix" style="display:none" id="customer_after_date_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_after_date; ?></td>
            <td class="fix" style="display:none" id="customer_street_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_street; ?></td>
            <td class="fix" style="display:none" id="customer_ward_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_ward; ?></td>
            <td class="fix" style="display:none" id="customer_district_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_district; ?></td>
            <td class="fix" style="display:none" id="customer_city_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_city; ?></td>
            <td class="fix" style="display:none" id="customer_province_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_province; ?></td>

            <td>
                <a class="error" href="#">Sửa</a>
                | 
                <a class="error" onclick="del(<?php echo $customer->customer_id ?>)" >Xóa</a>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('customer') ?>">&larr;</a></div>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Thông tin khách hàng </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_customer" method="post" action="">
                      <table style="margin:0 auto;width:100%">
                        <tr>
                            
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><div class="add-box"><a class="add_button" onClick="add_click();">Thêm khách hàng mới</a></div></td>
                            
                        </tr>
                        <tr>
                            <td>Mã khách hàng</td>
                            <td>
                                <input type="text" id="customer_code"  name="customer_code" tabindex="1" required="required" >
                            </td>
                        </tr>
                        <tr>
                            
                            <td>Tên KH</td>
                            <td>
                                <input type="text" id="customer_name"  name="customer_name" tabindex="1" required="required" >
                            </td>
                            <td>Tên công ty</td>
                            <td>
                                <input type="text" id="company_name"  name="company_name" tabindex="2" required="required" >
                            </td>
                            <td>Mã số thuế </td>
                            <td><input type="text" id="mst"  name="mst" tabindex="3" ></td>
                            <td>Tên rút gọn </td>
                            <td><input type="text" id="co_name"  name="co_name" tabindex="4" ></td>

                        </tr>
                        <tr>
                            
                            <td>Địa chỉ </td>
                            <td><textarea id="customer_address"  name="customer_address" tabindex="5" ></textarea></td>
                            <td>Email </td>
                            <td><input type="email"  id="customer_email" name="customer_email" tabindex="6" ></td>
                            <td>Số điện thoại </td>
                            <td>
                                <input type="text" class="numbers" id="customer_phone" name="customer_phone" tabindex="7" >
                            </td>
                            <td>Số fax </td>
                            <td>
                                <input type="text" class="numbers" id="customer_fax" name="customer_fax" tabindex="8" >
                            </td>
                            
                        </tr>
                        <tr>
                            
                            <td>Giám đốc </td>
                            <td><input type="text" id="director"  name="director" tabindex="9" ></td>
                            <td>Tài khoản ngân hàng </td>
                            <td>
                                <input type="text" style="width:90px" id="customer_bank_name"  name="customer_bank_name" tabindex="10" >
                                <input type="text" style="width:150px" id="account_number"  name="account_number" tabindex="11" >
                            </td>
                            <td>Tài khoản ngân hàng CMG </td>
                            <td>
                                
                                <select  style="width:100px" class="source" id="cmg_bank"  name="cmg_bank">
                                    <option value="null">Tài khoản</option>
                                    <?php foreach($banks as $bank){ ?>
                                    <option value="<?php echo $bank->bank_id ?>"><?php echo $bank->bank_name ?></option>
                                    <?php } ?>
                                </select> 
                            </td>
                            <td>Công nợ </td>
                            <td>
                                
                                <input type="text" style="width:30px" class="number" id="customer_expect_date" name="customer_expect_date" tabindex="12" placeholder="Ngày" > hàng tháng <br>
                                <input type="text" style="width:30px" class="number" id="customer_after_date" name="customer_after_date" tabindex="13" placeholder="Số" > ngày sau xuất HĐ
                            </td>
                        </tr>
                        <tr>
                            
                            <td>Đường </td>
                            <td><textarea id="customer_street"  name="customer_street" tabindex="14" ></textarea></td>
                            <td>Phường/Xã </td>
                            <td><textarea id="customer_ward"  name="customer_ward" tabindex="15" ></textarea></td>
                            <td>Quận/Huyện</td>
                            <td><textarea id="customer_district"  name="customer_district" tabindex="16" ></textarea></td>
                            <td>Thành phố</td>
                            <td><textarea id="customer_city"  name="customer_city" tabindex="17" ></textarea></td>
                            
                        </tr>
                        <tr>
                            <td>Tỉnh</td>
                            <td>
                                <select  style="width:100px"  id="customer_province"  name="customer_province" tabindex="18">
                                    <?php foreach($districts as $district){ ?>
                                    <option value="<?php echo $district->district_id ?>"><?php echo $district->district_name ?></option>
                                    <?php } ?>
                                </select> 
                            </td>
                        </tr>
                        
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><input type="submit" name="submit" value="Hoàn tất" tabindex="19"></td>
                            <td ><input type="reset" name="reset" value="Nhập lại" tabindex="20"></td>
                            <td></td>
                            <td></td>
                            <td></td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>
<script type="text/javascript">

$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }
   
});
    $('.edit_tr').click(function(){
        if(!$('.checkbox').is(':checked')){
            $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
        }
        var customer_name = $(this).find("#customer_name_"+$(this).attr('id')).text();
        var customer_code = $(this).find("#customer_code_"+$(this).attr('id')).text();
        
        var customer_address = $(this).find("#customer_address_"+$(this).attr('id')).text();
        var customer_phone = $(this).find("#customer_phone_"+$(this).attr('id')).text();
        var customer_fax = $(this).find("#customer_fax_"+$(this).attr('id')).text();
        var customer_email = $(this).find("#customer_email_"+$(this).attr('id')).text();

        var company_name = $(this).find("#company_name_"+$(this).attr('id')).text();
        var co_name = $(this).find("#co_name_"+$(this).attr('id')).text();
        var director = $(this).find("#director_"+$(this).attr('id')).text();
        var mst = $(this).find("#mst_"+$(this).attr('id')).text();
        var customer_bank_name = $(this).find("#customer_bank_name_"+$(this).attr('id')).text();
        var account_number = $(this).find("#account_number_"+$(this).attr('id')).text();
        var cmg_bank = $(this).find("#cmg_bank_"+$(this).attr('id')).text();
        var customer_expect_date = $(this).find("#customer_expect_date_"+$(this).attr('id')).text();
        var customer_after_date = $(this).find("#customer_after_date_"+$(this).attr('id')).text();

        var customer_street = $(this).find("#customer_street_"+$(this).attr('id')).text();
        var customer_ward = $(this).find("#customer_ward_"+$(this).attr('id')).text();
        var customer_district = $(this).find("#customer_district_"+$(this).attr('id')).text();
        var customer_city = $(this).find("#customer_city_"+$(this).attr('id')).text();
        var customer_province = $(this).find("#customer_province_"+$(this).attr('id')).text();
        
        //alert(customer_code);
        $('#yes').val($(this).attr('id'));
        
        
        $('#customer_code').val(customer_code);
        $('#customer_name').val(customer_name);
        $('#customer_address').val(customer_address);
        $('#customer_phone').val(customer_phone);
        $('#customer_fax').val(customer_fax);
        $('#customer_email').val(customer_email);
       
       $('#company_name').val(company_name);
       $('#co_name').val(co_name);
       $('#director').val(director);
       $('#mst').val(mst);
       $('#customer_bank_name').val(customer_bank_name);
       $('#account_number').val(account_number);
       $('#customer_expect_date').val(customer_expect_date);
       $('#customer_after_date').val(customer_after_date);
       $("#cmg_bank option[value=" + cmg_bank + "]").attr('selected', 'selected');
       
       $('#customer_street').val(customer_street);
       $('#customer_ward').val(customer_ward);
       $('#customer_district').val(customer_district);
       $('#customer_city').val(customer_city);
       $("#customer_province option[value=" + customer_province + "]").attr('selected', 'selected');

        $('#customer_name').focus();
        $('#customer_name').attr('data',"true");
    });
</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
    $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
    
        $('#customer_code').val("");
        $('#customer_name').val("");
        $('#customer_address').val("");
        $('#customer_phone').val("");
        $('#customer_email').val("");
        $('#customer_fax').val("");
        
        $('#company_name').val("");
       $('#co_name').val("");
       $('#director').val("");
       $('#mst').val("");
       $('#customer_bank_name').val("");
       $('#account_number').val("");
       $('#customer_expect_date').val("");
       $('#customer_after_date').val("");
       $("#cmg_bank option[value=null]").attr('selected', 'selected');

       $('#customer_street').val("");
       $('#customer_ward').val("");
       $('#customer_district').val("");
       $('#customer_city').val("");

   $('#customer_name').focus();
   $('#customer_name').attr('data',"false");

}


$(document).ready(function(){
            // Validate form
            $("#add_customer").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                    var customer_code = $('#customer_code').attr('value');
                    var customer_name = $('#customer_name').attr('value');
                    var customer_address = $('#customer_address').attr('value');
                    var customer_phone = $('#customer_phone').attr('value');
                    var customer_fax = $('#customer_fax').attr('value');
                    var customer_email = $('#customer_email').attr('value');

                    var company_name = $('#company_name').attr('value');
                    var co_name = $('#co_name').attr('value');
                    var director = $('#director').attr('value');
                    var mst = $('#mst').attr('value');
                    var customer_bank_name = $('#customer_bank_name').attr('value');
                    var account_number = $('#account_number').attr('value');
                    var cmg_bank = $('#cmg_bank').attr('value');
                    var customer_expect_date = $('#customer_expect_date').attr('value');
                    var customer_after_date = $('#customer_after_date').attr('value');

                    var customer_street = $('#customer_street').attr('value');
                    var customer_ward = $('#customer_ward').attr('value');
                    var customer_district = $('#customer_district').attr('value');
                    var customer_city = $('#customer_city').attr('value');
                    var customer_province = $('#customer_province').attr('value');
                    

                    var yes = $('#yes').attr('value');
                    var check = $('#customer_name').attr('data');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/customer/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            customer_code: customer_code,
                            customer_name: customer_name,
                            customer_address: customer_address,
                            customer_phone: customer_phone,
                            customer_fax: customer_fax,
                            customer_email: customer_email,
                            company_name: company_name,
                            co_name: co_name,
                            director: director,
                            mst: mst,
                            customer_bank_name: customer_bank_name,
                            account_number: account_number,
                            cmg_bank: cmg_bank,
                            customer_expect_date: customer_expect_date,
                            customer_after_date: customer_after_date,
                            customer_street: customer_street,
                            customer_ward: customer_ward,
                            customer_district: customer_district,
                            customer_city: customer_city,
                            customer_province: customer_province,
                            yes: yes,
                            check: check,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (check == "true") {
                                if (answer.trim() != "Thông tin khách hàng đã tồn tại") {
                                    $('#customer_name_'+yes).text(customer_name);
                                    $('#customer_address_'+yes).text(customer_address);
                                    $('#customer_phone_'+yes).text(customer_phone);
                                    $('#customer_email_'+yes).text(customer_email);
                                    $('#company_name_'+yes).text(company_name);
                                    $('#mst_'+yes).text(mst);
                                }
                            }
                            else{
                                if (answer.trim() != "Thông tin khách hàng đã tồn tại") {
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="customer_name_'+parseInt(lastID+1)+'">'+customer_name+'</td><td class="fix" id="company_name_'+parseInt(lastID+1)+'">'+company_name+'</td><td class="fix" id="mst_'+parseInt(lastID+1)+'">'+mst+'</td><td class="fix" id="customer_address_'+parseInt(lastID+1)+'">'+customer_address+'</td><td class="fix" id="customer_phone_'+parseInt(lastID+1)+'">'+customer_phone+'</td><td class="fix" id="customer_email_'+parseInt(lastID+1)+'">'+customer_email+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
   
   

   $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
        ;
      });
    });

   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/(\d{3})(\d{3})(\d{4})/, "$1 $2 $3")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');
</script>
</div>