<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title><?php echo isset($title) ? $title : null ?> - <?php echo ($_SERVER["SERVER_NAME"]=='caimeptrading.com'|| $_SERVER["SERVER_NAME"]=='www.caimeptrading.com')?'Cai Mep Trading':(($_SERVER["SERVER_NAME"]=='viet-trade.org' || $_SERVER["SERVER_NAME"]=='www.viet-trade.org')?'Việt Trade':'Cai Mep Global Logistics' ) ?></title>
  <meta name="keywords" content="Logistics, Xuất Khẩu, Nhập Khẩu, Xuất Nhập Khẩu, Vận Chuyển Hàng Hóa, Vận Chuyển, Hàng Siêu Trọng, Salan, Xà Lan, Sà Lan, Vận Chuyển Sà Lan, Thủ Tục Hải Quan, Hải Quan, Thông Quan, Mở Tờ Khai, Hun Trùng, Đóng Cont, Đóng Hàng, Forwarder, Stufffing, Unstuffing, Export, Import, Terminal, Port, Sea Port, Transhit, Transhipment, OOG, Over Weight, Over Hight, Over Length, Barge, Barging, Barge team, Barge Fleet, Inland Water Way, IWW, Ship, Vessel, Canoe, River, Channal, Pilot, Boarding Agent, Đại lý tàu, Husbanding Agent, Cambudia, Barging Service, Customs, Customs transhipment, Customs Clearance, EDI, Manifest, E-Manifest, chỉnh sửa Manifest, Adjust Manifest, Inbound, Outbound, Cargo, container, 20', 40', Reefer container, Flatrach, Tank, Hàng Quá Khổ, Cấm Tải, Chất lượng,">
  <meta property="og:description" itemprop="description" name="description" content="<?php echo isset($title) ? $title.' - ' : null ?>Logistics - Vận chuyển - Thủ tục hải quan - Manifest - Container">
  <meta name="generator" content="Cai Mep Trading">
  <meta name="alexaVerifyID" content="_9gi6egDJ1Z4jT9va1ez-U0qOno"/>
  <meta name="alexaVerifyID" content="tNObsCQ5mlcxtMgOmpzWfhtjTkc"/>
  <meta http-equiv="content-language" content="vi" />
  <meta property="og:title" itemprop="name" content="<?php echo isset($title) ? $title : null ?> - <?php echo $_SERVER["SERVER_NAME"]=='caimeptrading.com'?'Cai Mep Trading':($_SERVER["SERVER_NAME"]=='www.caimeptrading.com'?'Cai Mep Trading':'Cai Mep Global Logistics') ?>">
  <meta property="og:url" content="<?php echo BASE_URL.$_SERVER['REQUEST_URI'] ?>">
  <meta property="og:type" content="website">
  <meta property="og:image" itemprop="image" name="thumbnail" content="<?php echo BASE_URL ?>/public/img/logo-cmg.png">
  <link rel="alternate" href="<?php echo BASE_URL ?>" hreflang="vi-vn" />
  <link rel="publisher" href="https://plus.google.com/111952529763008010249" title="Cai Mep Global Logistics"/>
  <link href="<?php BASE_URL ?>/public/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Morris chart -->
  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/plugins/morris/morris.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/dist/css/skins/_all-skins.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/style.css">
  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/js/ui/jquery-ui.css">
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery-1.7.2.min.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/ui/jquery-ui.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/html5.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.form.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.validate.min.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/custom.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/localization/messages_vi.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/colResizable-1.5.min.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.stickyheader.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.ba-throttle-debounce.min.js"></script>
  <script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/jquery.battatech.excelexport.js"></script>
  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/component.css" />
  <script src="<?php BASE_URL ?>/public/js/pace.min.js"></script>
  <link rel="stylesheet" href="<?php BASE_URL ?>/public/css/head.css">
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/head.js"></script>
  <!-- InputMask -->
  <script src="<?php BASE_URL ?>/public/js/adminbar/plugins/input-mask/jquery.inputmask.js"></script>
  <script src="<?php BASE_URL ?>/public/js/adminbar/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
  <script src="<?php BASE_URL ?>/public/js/adminbar/plugins/input-mask/jquery.inputmask.extensions.js"></script>

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/css/bootstrap-select.min.css" />
  <script src="<?php BASE_URL ?>/public/js/bootstrap-select.min.js"></script>

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/chosen/chosen.css">
  <script src="<?php echo BASE_URL ?>/public/js/chosen/chosen.jquery.js" type="text/javascript"></script>

  <script type="text/javascript">
    

   var check_lock_user = 0;
    $.ajax({
      type: "POST",
      url: "<?php echo BASE_URL ?>/admin/checklockuser",
      data: "data=<?php echo isset($_SESSION['userid_logined'])?$_SESSION['userid_logined']:0 ?>", // or any data you want to send
      cache: false,
      success: function(html){
        check_lock_user = html;
        if (check_lock_user==1) {
          $.ajax({
            type: "GET",
            url: "<?php echo BASE_URL ?>/user/logout",
            data: "data=1", // or any data you want to send
            cache: false,
            success: function(html){
              window.location.href = "<?php echo BASE_URL ?>";
            }
          });
        };
      }
    });

    
  </script>

      

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="<?php echo BASE_URL ?>" class="logo">
      <?php if($_SERVER["SERVER_NAME"]=='goodtyres.vn' || $_SERVER["SERVER_NAME"]=='www.goodtyres.vn'){ ?>
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>GT</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>GOOD TYRES</b></span>
      <?php }else{ ?>
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>GT</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>GT</b></span>
      <?php } ?>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        
          <!-- Messages: style can be found in dropdown.less-->
          
          <!-- Notifications: style can be found in dropdown.less -->
          
          <!-- Tasks: style can be found in dropdown.less -->
          
          <!-- User Account: style can be found in dropdown.less -->
          <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
          </li>
          <!-- Notifications: style can be found in dropdown.less -->
          <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">10</span>
            </a>
          </li>
          <!-- Tasks: style can be found in dropdown.less -->
          <li class="dropdown tasks-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">9</span>
            </a>
          </li>
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <!-- Kiem tra dang nhap -->
            <?php 
            if ($_SESSION) {
              ?>
              <a class="logined" href="<?php echo $this->url('user/logout') ?>">&nbsp; | Logout</a><a class="logined" href="<?php echo BASE_URL.'/user/info/'.$_SESSION['userid_logined'] ?>"><b><i><?php echo $_SESSION['user_logined']; ?> </i></b></a>
              <?php
            }
            else{
              ?>
              <a class="logined" href="<?php echo $this->url('user/login') ?>">Login</a>
              <?php
            }
            ?>
            <!-- end -->
          </li>
          <!-- Control Sidebar Toggle Button -->
        </ul>
          
          <!-- Control Sidebar Toggle Button -->
          
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <?php if (isset($_SESSION['user_logined'])) { ?>
      <div class="user-panel">
          <button type="button" class="btn btn-block btn-primary" onClick="javascript:window.location.href='<?php echo $this->url('ordertire') ?>'">
            <i class="fa  fa-pencil-square-o"></i> Đặt hàng
          </button>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">QUẢN TRỊ</li>
        <li class="treeview">
          <a data="admin" href="<?php echo $this->url('admin') ?>">
            <i class="fa fa-home"></i> <span>Trang chủ</span>
          </a>
        </li>
        <?php if($_SESSION['role_logined'] == 13){ ?>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-newspaper-o"></i>
            <span>Viết bài</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
              <li><a  data="post" href="<?php echo $this->url('post') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bài đăng</a>
                <ul class="treeview-menu">
                  
                  <li><a  data="post/newpost" href="<?php echo $this->url('post/newpost') ?>"><i class="fa fa-circle-o text-aqua"></i>Thêm bài mới</a></li>
                  <li><a  data="post" href="<?php echo $this->url('post') ?>"><i class="fa fa-circle-o text-aqua"></i>Danh sách bài</a></li>
                </ul>
              </li>
              <li><a  data="photo" href="<?php echo $this->url('photo') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Media</a></li>
              
          </ul>
        </li>
        <li><a data="ordertire" href="<?php echo $this->url('ordertire') ?>">
            <i class="fa fa-caret-right text-aqua"></i>Đặt hàng
            <span class="pull-right-container">
              <small class="label pull-right bg-green">new</small>
            </span>
          </a>
        </li>
        <li><a  data="ordertire/orderlist" href="<?php echo $this->url('ordertire/orderlist') ?>"><i class="fa fa-caret-right text-aqua"></i>Danh sách đơn hàng</a></li>
        <li><a  data="tiresalary" href="<?php echo $this->url('tiresalary') ?>"><i class="fa fa-caret-right text-aqua"></i>Doanh số bán hàng</a></li>
        <li><a data="stock" href="<?php echo $this->url('stock') ?>"><i class="fa fa-circle-o text-aqua"></i>Tồn kho - Dự kiến nhập</a></li>
        <li><a data="inventory" href="<?php echo $this->url('inventory') ?>"><i class="fa fa-circle-o text-aqua"></i>Tồn kho chi tiết</a></li>
        <li><a data="inventory/agent" href="<?php echo $this->url('inventory/agent') ?>"><i class="fa fa-circle-o text-aqua"></i>Tồn kho Việt Trade</a></li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-info-circle"></i>
            <span>Danh mục</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a data="tirepricediscount" href="<?php echo $this->url('tirepricediscount') ?>">
                <i class="fa fa-caret-right text-aqua"></i>Bảng giá chiết khấu
                <span class="pull-right-container">
                  <small class="label pull-right bg-green"><i class="fa fa-dollar"></i></small>
                </span>
              </a>
            </li>
            <li><a data="tirepricediscountevent" href="<?php echo $this->url('tirepricediscountevent') ?>">
                <i class="fa fa-caret-right text-aqua"></i>Thông tin giảm giá
                  <span class="pull-right-container">
                    <small class="label pull-right bg-red"><i class="fa fa-gift"></i></small>
                  </span>
                </a>
            </li> 
            <li><a data="#" href="#"><i class="fa fa-caret-right text-aqua"></i>Thông tin lốp</a>
              <ul class="treeview-menu">
                <li><a data="tirebrandgroup" href="<?php echo $this->url('tirebrandgroup') ?>"><i class="fa fa-circle-o text-aqua"></i>Nhóm thương hiệu</a></li>
                <li><a data="tirebrand" href="<?php echo $this->url('tirebrand') ?>"><i class="fa fa-circle-o text-aqua"></i>Thương hiệu</a></li>
                <li><a data="tiresize" href="<?php echo $this->url('tiresize') ?>"><i class="fa fa-circle-o text-aqua"></i>Kích cỡ</a></li>
                <li><a data="tirepattern" href="<?php echo $this->url('tirepattern') ?>"><i class="fa fa-circle-o text-aqua"></i>Mã gai</a></li>
              </ul>
            </li>
            
            
            
            
          </ul>
        </li>

        <?php } else{ ?>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-newspaper-o"></i>
            <span>Viết bài</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
              <li><a  data="post" href="<?php echo $this->url('post') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bài đăng</a>
                <ul class="treeview-menu">
                  
                  <li><a  data="post/newpost" href="<?php echo $this->url('post/newpost') ?>"><i class="fa fa-circle-o text-aqua"></i>Thêm bài mới</a></li>
                  <li><a  data="post" href="<?php echo $this->url('post') ?>"><i class="fa fa-circle-o text-aqua"></i>Danh sách bài</a></li>
                </ul>
              </li>
              <li><a  data="photo" href="<?php echo $this->url('photo') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Media</a></li>
              <?php if ($_SESSION && ($_SESSION['role_logined'] == 1)) { ?>
              <li><a  data="event" href="<?php echo $this->url('event') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Sự kiện</a>
                <ul class="treeview-menu">
                  
                  <li><a  data="event/addevent" href="<?php echo $this->url('event/addevent') ?>"><i class="fa fa-circle-o text-aqua"></i>Thêm lịch gửi mới</a></li>
                  <li><a  data="event" href="<?php echo $this->url('event') ?>"><i class="fa fa-circle-o text-aqua"></i>Danh sách sự kiện</a></li>
                </ul>
              </li>
              <?php } ?>
          </ul>
        </li>
        <li class="treeview">
          <a data="#" href="#">
            <i class="fa fa-credit-card"></i> <span>Lập phiếu</span>
          </a>
          <ul class="treeview-menu">
            <li><a data="paymentrequest" href="<?php echo $this->url('paymentrequest') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Giấy đề nghị thanh toán</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a data="#" href="#">
            <i class="fa fa-search"></i> <span>Tra cứu</span>
          </a>
          <ul class="treeview-menu">
            <li><a data="receivable" href="<?php echo $this->url('receivable') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Dự thu</a></li>
            <li><a data="payable" href="<?php echo $this->url('payable') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Dự chi</a></li>
            <li><a data="receive" href="<?php echo $this->url('receive') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Đã thu</a></li>
            <li><a data="pay" href="<?php echo $this->url('pay') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Đã chi</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-shopping-cart"></i>
            <span>Bán hàng</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a data="ordertire" href="<?php echo $this->url('ordertire') ?>">
                <i class="fa fa-caret-right text-aqua"></i>Đặt hàng
                <span class="pull-right-container">
                  <small class="label pull-right bg-green">new</small>
                </span>
              </a>
            </li>
            <li><a  data="ordertire/orderlist" href="<?php echo $this->url('ordertire/orderlist') ?>"><i class="fa fa-caret-right text-aqua"></i>Danh sách đơn hàng</a></li>
            <li><a  data="ordertirewaiting" href="<?php echo $this->url('ordertirewaiting') ?>"><i class="fa fa-caret-right text-aqua"></i>Đơn hàng đang chờ</a></li>  
            <li><a  data="ordertire/report" href="<?php echo $this->url('ordertire/report') ?>"><i class="fa fa-caret-right text-aqua"></i>Tổng hợp đơn hàng</a></li>
            <li><a  data="tiresale/sale" href="<?php echo $this->url('tiresale/sale') ?>"><i class="fa fa-caret-right text-aqua"></i>Sản lượng bán</a></li>
            <li><a  data="tiresalary" href="<?php echo $this->url('tiresalary') ?>"><i class="fa fa-caret-right text-aqua"></i>Doanh số bán hàng</a></li>  
            <li><a data="#" href="#"><i class="fa fa-fw fa-caret-right text-aqua"></i>
                  <span>Công nợ</span>
                  <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a  data="tiredebit" href="<?php echo $this->url('tiredebit') ?>"><i class="fa fa-caret-right text-aqua"></i>Khách hàng</a></li> 
                <li><a  data="tiredebitdetail" href="<?php echo $this->url('tiredebitdetail') ?>"><i class="fa fa-caret-right text-aqua"></i>Đơn hàng quá hạn</a></li> 
              </ul>
            </li>
            <li><a  data="ordertirecost" href="<?php echo $this->url('ordertirecost') ?>"><i class="fa fa-caret-right text-aqua"></i>Chi phí đơn hàng</a></li>   
            <li><a  data="invoicetiredetail" href="<?php echo $this->url('invoicetiredetail') ?>"><i class="fa fa-caret-right text-aqua"></i>Hóa đơn</a></li> 
            <li><a  data="customer" href="<?php echo $this->url('customer') ?>"><i class="fa fa-caret-right text-aqua"></i>Danh sách khách hàng</a></li>
          </ul>
        </li>
        <li><a href="#">
            <i class="fa fa-database"></i>
            <span>Kho</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a data="stock" href="<?php echo $this->url('stock') ?>"><i class="fa fa-circle-o text-aqua"></i>Tồn kho - Dự kiến nhập</a></li>
            <li><a data="inventory" href="<?php echo $this->url('inventory') ?>"><i class="fa fa-circle-o text-aqua"></i>Tồn kho chi tiết</a></li>
            <li><a data="inventory/agent" href="<?php echo $this->url('inventory/agent') ?>"><i class="fa fa-circle-o text-aqua"></i>Tồn kho Việt Trade</a></li>
            <li><a data="stock/report" href="<?php echo $this->url('stock/report') ?>"><i class="fa fa-circle-o text-aqua"></i>Giá trị tồn</a></li>
            <li><a data="expired" href="<?php echo $this->url('expired') ?>"><i class="fa fa-circle-o text-aqua"></i>Hàng quá hạn
                  <span class="pull-right-container">
                    <small class="label pull-right bg-red">expired</small>
                  </span>
              </a>
            </li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-archive"></i>
            <span>Mua hàng</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a data="importtireorder" href="<?php echo $this->url('importtireorder') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Nhập khẩu</a></li>
            <li><a data="importtire" href="<?php echo $this->url('importtire') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Lô hàng nhập</a></li>
            <li><a data="tiresale" href="<?php echo $this->url('tiresale') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Hàng nhập</a></li>
            <li><a data="tireimport" href="<?php echo $this->url('tireimport') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Giá vốn</a>
              <ul class="treeview-menu">
                <li><a data="tireimportdetail" href="<?php echo $this->url('tireimportdetail') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Giá vốn lô hàng</a></li>
                <li><a data="tireimport" href="<?php echo $this->url('tireimport') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Giá vốn</a></li>
              </ul>
            </li>
            <li><a  data="shipmentvendor" href="<?php echo $this->url('shipmentvendor') ?>"><i class="fa fa-caret-right text-aqua"></i>Danh sách Vendor/NCC</a></li>
          </ul>
        </li>
        <?php if($_SESSION['role_logined'] == 1 || $_SESSION['role_logined'] == 2 || $_SESSION['role_logined'] == 8 || $_SESSION['role_logined'] == 9){ ?>
        <li><a href="#">
            <i class="fa fa-dollar"></i>
            <span>Tài chính - Kế toán</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a data="daily" href="<?php echo $this->url('daily') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Báo cáo thu chi</a></li>
            <li>
              <a data="invoicetire" href="<?php echo $this->url('invoicetire') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Hóa đơn</a>
              <ul class="treeview-menu">
                <li><a data="vat" href="<?php echo $this->url('vat') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Xuất hóa đơn</a>
                </li><li><a data="vat/view" href="<?php echo $this->url('vat/view') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Xem/Hủy hóa đơn</a>
                </li><li><a data="invoicetiredetail" href="<?php echo $this->url('invoicetiredetail') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi tiết hóa đơn</a></li>
                <li><a data="invoicetire" href="<?php echo $this->url('invoicetire') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Hóa đơn lô hàng</a>
              </li></ul>
            </li>
            <li><a data="daily/deposit" href="<?php echo $this->url('daily/deposit') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Cấn trừ đặt cọc</a></li>
            <li><a data="daily/ordertire" href="<?php echo $this->url('daily/ordertire') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Hạch toán ĐH</a></li>
            
            <li><a data="additional" href="<?php echo $this->url('additional') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phát sinh</a></li>
            <li><a data="forward" href="<?php echo $this->url('forward') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Kết chuyển cuối kỳ</a></li>
            <li><a data="#" href="#"><i class="fa fa-fw fa-caret-right text-aqua"></i>
                  <span>Báo cáo</span>
                  <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="expectrevenued" href="<?php echo $this->url('expectrevenued') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Đã thu</a></li>
                <li><a data="expectpayed" href="<?php echo $this->url('expectpayed') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Đã chi</a></li>
                <li><a data="deposit" href="<?php echo $this->url('deposit') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Đặt cọc</a></li>
                <li><a data="financial" href="<?php echo $this->url('financial') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bảng cân đối</a></li>
                <li><a data="financial/balance" href="<?php echo $this->url('financial/balance') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bảng cân đối tài sản</a></li>

                <li><a data="financial/result" href="<?php echo $this->url('financial/result') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Kết quả hoạt động kinh doanh</a></li>
                <li><a data="financial/asset" href="<?php echo $this->url('financial/asset') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Tài sản</a></li>
                <li><a data="financial/office" href="<?php echo $this->url('financial/office') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi phí hành chính</a></li>
              </ul>
            </li>
            
            
            <li><a data="account" href="<?php echo $this->url('account') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Tài khoản kế toán</a></li>
          </ul>
        </li>
        <li><a href="#">
            <i class="fa fa-group"></i>
            <span>Nhân sự</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a data="checksalarytotal" href="<?php echo $this->url('checksalarytotal') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bảng lương</a></li>
            <li><a data="checksalary" href="<?php echo $this->url('checksalary') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Doanh số tính lương</a></li>
            
            <li><a data="checksalarypercent" href="<?php echo $this->url('checksalarypercent') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>% tính lương</a></li>
            <li><a data="attendance" href="<?php echo $this->url('attendance') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bảng chấm công</a></li>
            <li><a data="eatingallowance" href="<?php echo $this->url('eatingallowance') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phụ cấp cơm</a></li>
            <li><a data="phoneallowance" href="<?php echo $this->url('phoneallowance') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phụ cấp điện thoại</a></li>
            <li><a data="insurrance" href="<?php echo $this->url('insurrance') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bảo hiểm</a></li>
            <li><a data="positionsalary" href="<?php echo $this->url('positionsalary') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Lương chức vụ</a></li>
            <li><a  data="staff" href="<?php echo $this->url('staff') ?>"><i class="fa fa-caret-right text-aqua"></i>Danh sách nhân viên</a></li>
          </ul>
        </li>
        <li><a href="#">
            <i class="fa fa-exclamation-triangle"></i>
            <span>Kiểm tra</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a data="checkdaily" href="<?php echo $this->url('checkdaily') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Tài khoản</a></li>
            <li><a data="checking" href="<?php echo $this->url('checking') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Doanh thu</a></li>
            <li><a data="checking/invoice" href="<?php echo $this->url('checking/invoice') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Thuế GTGT</a></li>
            <li><a data="checking/cost" href="<?php echo $this->url('checking/cost') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi phí</a></li>
            <li><a data="checking/office" href="<?php echo $this->url('checking/office') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Hành chính</a></li>
            <li><a data="checking/result" href="<?php echo $this->url('checking/result') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>KQ HĐKD</a></li>
          </ul>
        </li>
        <li><a href="#">
            <i class="fa fa-pie-chart"></i>
            <span>Báo cáo</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a data="reportsale" href="<?php echo $this->url('reportsale') ?>"><i class="fa fa-caret-right text-aqua"></i>Bán hàng</a></li>
            <li><a data="reportorderrevenue" href="<?php echo $this->url('reportorderrevenue') ?>"><i class="fa fa-caret-right text-aqua"></i>Doanh thu bán hàng</a></li>
            <li><a data="reportordercost" href="<?php echo $this->url('reportordercost') ?>"><i class="fa fa-caret-right text-aqua"></i>Chi phí bán hàng</a></li>
          </ul>
        </li>
        <?php } ?>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-info-circle"></i>
            <span>Danh mục</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a data="tirepricediscount" href="<?php echo $this->url('tirepricediscount') ?>">
                <i class="fa fa-caret-right text-aqua"></i>Bảng giá chiết khấu
                <span class="pull-right-container">
                  <small class="label pull-right bg-green"><i class="fa fa-dollar"></i></small>
                </span>
              </a>
            </li>
            <li><a data="tirepricediscountevent" href="<?php echo $this->url('tirepricediscountevent') ?>">
                <i class="fa fa-caret-right text-aqua"></i>Thông tin giảm giá
                  <span class="pull-right-container">
                    <small class="label pull-right bg-red"><i class="fa fa-gift"></i></small>
                  </span>
                </a>
            </li> 
            <li><a data="#" href="#"><i class="fa fa-caret-right text-aqua"></i>Thông tin lốp</a>
              <ul class="treeview-menu">
                <li><a data="tirebrandgroup" href="<?php echo $this->url('tirebrandgroup') ?>"><i class="fa fa-circle-o text-aqua"></i>Nhóm thương hiệu</a></li>
                <li><a data="tirebrand" href="<?php echo $this->url('tirebrand') ?>"><i class="fa fa-circle-o text-aqua"></i>Thương hiệu</a></li>
                <li><a data="tiresize" href="<?php echo $this->url('tiresize') ?>"><i class="fa fa-circle-o text-aqua"></i>Kích cỡ</a></li>
                <li><a data="tirepattern" href="<?php echo $this->url('tirepattern') ?>"><i class="fa fa-circle-o text-aqua"></i>Mã gai</a></li>
              </ul>
            </li>
            
            
            
            
          </ul>
        </li>
        <?php if($_SESSION['role_logined'] == 1 || $_SESSION['role_logined'] == 9){ ?>
        <li><a href="#">
            <i class="fa fa-cogs"></i>
            <span>Hệ thống</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a data="info" href="<?php echo $this->url('info') ?>"><i class="fa fa-caret-right text-aqua"></i>Thông tin công ty</a></li>
            <li><a data="user" href="<?php echo $this->url('user') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Tài khoản</a></li>
            
          </ul>
        </li>
        <?php } ?>

        <?php } ?>
      </ul>
      <?php } ?>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-md-12">
          <?php echo $content; ?>
        </div>
        <!-- ./col --> 
      </div>
      <!-- /.row -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <!-- <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.0
    </div>
    <span style="font-size:5px">Powered by <a target="_blank" style="color:#fff" href="http://www.tinhoctainha.com">Dịch vụ Tin Học Tại Nhà</a></span>
  </footer> -->

  <!-- Control Sidebar -->
  
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<div id='ajax_loader' style="position: fixed; left: 50%; top: 50%; margin-left : -16px; margin-top : -16px; z-index:999999">
    <img src="<?php echo BASE_URL?>/public/img/loader-gears.gif"></img>
</div>

<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="<?php BASE_URL ?>/public/js/adminbar/bootstrap/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/morris/morris.min.js"></script>
<!-- jQuery Knob Chart -->
<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/knob/jquery.knob.js"></script>
<!-- daterangepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- AdminLTE App -->
<script src="<?php BASE_URL ?>/public/js/adminbar/dist/js/app.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!-- AdminLTE for demo purposes -->
<script src="<?php BASE_URL ?>/public/js/adminbar/dist/js/demo.js"></script>
<script type="text/javascript">
$( document ).ajaxStart(function() {
  $("#ajax_loader").fadeIn(200);
  $('input[type="submit"]').attr('disabled',true);
  $('button[type="submit"]').attr('disabled',true);
});
$( document ).ajaxComplete(function() {
  $("#ajax_loader").fadeOut(200);
  $('input[type="submit"]').attr('disabled',false);
  $('button[type="submit"]').attr('disabled',false);
});
$(window).load(function() { 
  $("#ajax_loader").fadeOut(200);
});
</script>
<!--
<script type="text/javascript">
var persist = 1;
  $('.table_data').addClass('tablesaw');
  $('.table_data').attr('data-tablesaw-mode','columntoggle');
  $('.table_data').attr('data-tablesaw-mode-switch','');
  $('.table_data').attr('data-tablesaw-minimap','');
  $('.table_data th').attr('scope','col');
  $('.table_data th').attr('data-tablesaw-sortable-col','');
  //$('.table_data th.fix').attr('data-tablesaw-priority','persist');
  $('.table_data th').each(function(){
    $(this).attr('data-tablesaw-priority',persist++);
  });
</script>

<link rel="stylesheet" href="<?php echo BASE_URL ?>/public/js/dist/tablesaw.css">
<script src="<?php echo BASE_URL ?>/public/js/dist/tablesaw.jquery.js"></script>
<script src="<?php echo BASE_URL ?>/public/js/dist/tablesaw-init.js"></script>
-->
</body>
</html>