
<?php
$url_order = 'ASC';
if ($order_by == 'spent_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'spent_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'proceeds')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'source')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'vendor')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> BẢNG CHI LÀM HÀNG </h1></center>
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm bảng chi</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <div class="add-box">
                  
            Từ  <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:100px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
    </div>
    <div class="tablenav top">
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="5">Hiển thị 5 giá trị</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="15">Hiển thị 15 giá trị</option>
            <option selected="selected" value="20">Hiển thị 20 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>

</div>

<table class="table_data">
<thead>
    <tr>
    	<th rowspan="2" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','spent_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'spent_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','spent_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'spent_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','proceeds','<?php echo $url_order ?>')">Chi <?php if ($order_by == 'proceeds'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>   
          
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','code','<?php echo $url_order ?>')">CODE <?php if ($order_by == 'code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','vendor','<?php echo $url_order ?>')">Nơi nhận<?php if ($order_by == 'vendor'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','source','<?php echo $url_order ?>')">Nguồn chi<?php if ($order_by == 'source'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
           
        <th  class="fix">&nbsp;</th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($spents as $spent) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $spent->spent_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $spent->spent_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix"  id="spent_date_<?php echo $spent->spent_id; ?>"><?php echo $lib->hien_thi_ngay_thang($spent->spent_date) ?></td>
            <td class="fix" id="comment_<?php echo $spent->spent_id; ?>"><?php echo $spent->comment; ?></td>
            <td class="fix" id="proceeds_<?php echo $spent->spent_id; ?>"><?php echo $lib->formatMoney($spent->proceeds); ?></td>
            
            <td class="fix" id="code_<?php echo $spent->spent_id; ?>"><?php echo $spent->code; ?></td>
            <td class="fix" data="<?php echo $spent->vendor ?>" id="vendor_<?php echo $spent->spent_id; ?>"><?php echo $spent->type==1?$vendors['name'][$spent->vendor]:$spent->name; ?></td>
            <td class="fix" id="source_<?php echo $spent->spent_id; ?>"><?php echo $spent->bank_name; ?></td>
            <td style="display: none" class="fix" id="type_<?php echo $spent->spent_id; ?>"><?php echo $spent->type; ?></td>
            <td style="display: none" class="fix" id="name_<?php echo $spent->spent_id; ?>"><?php echo $spent->name; ?></td>
            
            <td>
                <a class="error" href="#">Sửa</a>
                | 
                <a class="error" onclick="del(<?php echo $spent->spent_id ?>)" >Xóa</a>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Thông tin khoản chi </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_spent" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>

                            <td><div class="add-box"><a class="add_button" onClick="add_click();">Thêm bảng chi</a></div></td>
                            
                        </tr>
                        <tr>
                            <td></td>
                            <td>Ngày </td>
                            <td>
                                <input style="width:90px" type="text" id="spent_date"  name="spent_date" tabindex="1" required="required" >
                            </td>
                            <td>Chi </td>
                            <td><input type="text" class="numbers"  id="proceeds"  name="proceeds" tabindex="3" required="required" ></td>
                            
                            <td>CODE </td>
                            <td>
                                <input type="text" class="number"  id="code"  name="code" tabindex="5"  autocomplete="off" placeholder="Nhập code hoặc * để chọn" >
                                <ul id="code_list_id"></ul>
                            </td>
                            

                        </tr>
                        <tr>
                            <td></td>
                            <td>Nội dung</td>
                            <td><textarea id="comment" name="comment" tabindex="2" required="required"></textarea></td>
                            <td>Nguồn chi</td>
                            <td>
                                <select  style="width:120px" id="source"  name="source" tabindex="4" required="required">
                                    <?php foreach($banks as $bank){ ?>
                                    <option value="<?php echo $bank->bank_id ?>"><?php echo $bank->bank_name ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>
                                <select style="width: 90px" id="type" name="type">
                                    <option value="1">Vendor</option>
                                    <option value="2">Nâng hạ</option>
                                    <option value="3">Hoa hồng</option>
                                    <option value="4">Phí chuyển tiền</option>
                                    <option value="5">Mua hóa đơn</option>
                                    <option value="6">Gửi chứng từ</option>
                                    <option value="7">OPS</option>
                                    <option value="8">Chi phí khác</option>
                                </select>
                            </td>
                            <td>

                                <input type="text"  id="vendor"  name="vendor" tabindex="6"  autocomplete="off" placeholder="Nhập tên hoặc * để chọn" >
                                <ul id="vendor_list_id"></ul>
                            </td>
                            
                            
                        </tr>
                        
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><input type="submit" name="submit" value="Hoàn tất" tabindex="7"></td>
                            <td ><input type="reset" name="reset" value="Nhập lại" tabindex="8"></td>
                            <td></td>
                            <td></td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>
<script type="text/javascript">

var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $("#spent_date").datepicker(pickerOpts);

    var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts3);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);


$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }
   $('#code_list_id').slideUp(200);
   $('#vendor_list_id').slideUp(200);

});


    $('.edit_tr').click(function(){
        if(!$('.checkbox').is(':checked')){
            $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
        }
        var spent_date = $(this).find("#spent_date_"+$(this).attr('id')).text();
        var comment = $(this).find("#comment_"+$(this).attr('id')).text();
        var proceeds = $(this).find("#proceeds_"+$(this).attr('id')).text();
        var code = $(this).find("#code_"+$(this).attr('id')).text();
        var source = $(this).find("#source_"+$(this).attr('id')).text();
        var vendor = $(this).find("#vendor_"+$(this).attr('id')).text();
        var dvendor = $(this).find("#vendor_"+$(this).attr('id')).attr('data');
        var type = $(this).find("#type_"+$(this).attr('id')).text();
        var name = $(this).find("#name_"+$(this).attr('id')).text();

        //alert(spent_code);
        $('#yes').val($(this).attr('id'));
        
        
        $('#spent_date').val(spent_date);
        $('#comment').val(comment);
        $('#proceeds').val(proceeds);
        $('#code').val(code);
        $('#code').attr('data',code);
        $("#source option:contains(" + source + ")").attr('selected', 'selected');
        if(type == 1){
            $('#vendor').val(vendor);
            $('#vendor').attr('data',dvendor);
        }
        else{
            $('#vendor').val(name);
        }
        $("#type option[value="+type+"]").attr('selected', 'selected');
        
    });
</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
     
        $('#spent_date').val();
        $('#comment').val();
        $("#source option[value=1]").attr('selected', 'selected');
        $('#proceeds').val();
        $('#code').val();
        $('#code').attr('data',"");
        $('#vendor').val();
        $('#vendor').attr('data',"");
        $("#type option[value=1]").attr('selected', 'selected');
        
        $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });


}


$(document).ready(function(){
            // Validate form
            $("#add_spent").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    if ($('#code').attr('data') == '') {
                        $('#code').val("");
                        $('#code').focus();
                        return false;
                    };

                    var spent_date = $('#spent_date').attr('value');
                    
                    var proceeds = $('#proceeds').attr('value');
                    var comment = $('#comment').attr('value');
                    var code = $('#code').attr('value');
                    var source = $('#source').attr('value');
                    var vendor = $('#vendor').attr('data');
                    var type = $('#type').attr('value');
                    var name = $('#vendor').attr('value');

                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/spent/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            spent_date: spent_date,
                            proceeds: proceeds,
                            comment: comment,
                            code: code,
                            source: source,
                            vendor: vendor,
                            type: type,
                            name: name,
                            yes: yes,

                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                
                                    $('#spent_date_'+yes).text(spent_date);
                                    $('#comment_'+yes).text(comment);
                                    $('#proceeds_'+yes).text(proceeds);
                                    $('#code_'+yes).text(code);
                                    $('#source_'+yes).text($("#source option:selected").text());
                                    $('#vendor_'+yes).text($("#vendor").val());
                                
                            }
                            else{
                                
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="spent_date_'+parseInt(lastID+1)+'">'+spent_date+'</td><td class="fix" id="comment_'+parseInt(lastID+1)+'">'+comment+'</td><td class="fix" id="proceeds_'+parseInt(lastID+1)+'">'+proceeds+'</td><td class="fix" id="code_'+parseInt(lastID+1)+'">'+code+'</td><td class="fix" id="vendor_'+parseInt(lastID+1)+'">'+$("#vendor").val()+'</td><td class="fix" id="source_'+parseInt(lastID+1)+'">'+$("#source option:selected").text()+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                
                            }
                        }
                    });
                    return false;
                     
                 }
            });

   $('#code').keyup(function(){
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/spent/getcode',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                $('#code_list_id').slideDown(200);
                $('#code_list_id').html(data);
            }
        });
        if ($('#code').val() == "" || $('#code').attr('data') == "") {
            
            $('#code').attr('data',"");
        };
   });
   $('#code').on('keydown', function() {
        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('#code').attr('data',"");
        }
            
      });

    $('#vendor').keyup(function(){
        if($('#type').val()==1){
            var keyword = $(this).val();
            $.ajax({
                url: '<?php echo BASE_URL ?>/spent/getvendor',
                type: 'POST',
                data: {keyword:keyword},
                success:function(data){
                    $('#vendor_list_id').slideDown(200);
                    $('#vendor_list_id').html(data);
                }
            });
            if ($('#vendor').val() == "" || $('#vendor').attr('data') == "") {
                
                $('#vendor').attr('data',"");
            };
        }
        else if($('#type').val()==2){
            var keyword = $(this).val();
            $.ajax({
                url: '<?php echo BASE_URL ?>/spent/getport',
                type: 'POST',
                data: {keyword:keyword},
                success:function(data){
                    $('#vendor_list_id').slideDown(200);
                    $('#vendor_list_id').html(data);
                }
            });
            if ($('#vendor').val() == "" || $('#vendor').attr('data') == "") {
                
                $('#vendor').attr('data',"");
            };
        }
        else if($('#type').val()==3){
            var keyword = $(this).val();
            $.ajax({
                url: '<?php echo BASE_URL ?>/spent/getcommission',
                type: 'POST',
                data: {keyword:keyword},
                success:function(data){
                    $('#vendor_list_id').slideDown(200);
                    $('#vendor_list_id').html(data);
                }
            });
            if ($('#vendor').val() == "" || $('#vendor').attr('data') == "") {
                
                $('#vendor').attr('data',"");
            };
        }
   });
   $('#vendor').on('keydown', function() {
        var key = event.keyCode || event.charCode;

        if( key == 8 || key == 46 ){
            $('#vendor').attr('data',"");
        }
            
      });


   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-]/g, "")
        ;
      });
    });
    

});

function get_number(id){
    return $(id).val().replace(/\,/g,'');
}
function set_item(item) {
    // change input value
    $('#code').val(item);
    $("#code").attr("data",item);
    
    $('#code_list_id').hide();
    $('#code').focus();
}
function set_item_vendor(item,name) {
    // change input value
    $('#vendor').val(name);
    $("#vendor").attr("data",item);
    
    $('#vendor_list_id').hide();
    $('#vendor').focus();
}
function set_item_commission(name) {
    // change input value
    $('#vendor').val(name);
    
    
    $('#vendor_list_id').hide();
    $('#vendor').focus();
}
function set_item_port(name) {
    // change input value
    $('#vendor').val(name);
    
    
    $('#vendor_list_id').hide();
    $('#vendor').focus();
}

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');

</script>
</div>