<div class="slide-content" id="gioi-thieu">
			<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_native_toolbox"></div>
      <div class="item-page">

        <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
150%"><b><span style="font-size:18.0pt;
line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">GIỚI THIỆU<o:p></o:p></span></b></p><p class="MsoListParagraphCxSpFirst" style="margin-bottom:0in;margin-bottom:.0001pt;
mso-add-space:auto;text-indent:-.25in;line-height:150%;mso-list:l1 level1 lfo1"><!--[if !supportLists]--><b><span style="font-size:10.0pt;line-height:
150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:Arial">1.<span style="font-weight: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><!--[endif]--><b><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Thành
lập và phát triển:<o:p></o:p></span></b></p><p class="MsoListParagraphCxSpMiddle" style="margin-bottom:0in;margin-bottom:
.0001pt;mso-add-space:auto;line-height:150%"><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-bottom:0in;margin-bottom:
.0001pt;mso-add-space:auto;text-align:justify;line-height:150%"><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
color:red">Công ty TNHH Cai Mep Global Logistics </span><span style="font-size:
10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">(tên viết tắt là CMG)
được thành lập năm 2012 trên cơ sở kế thừa kinh nghiệm, quan hệ xã hội và uy
tín sẵn có từ các thành viên sáng lập. Công ty CMG chuyên cung cấp các dịch vụ trọn
gói về Logistics như: Giao nhận và Vận chuyển hàng hóa, Dịch vụ Hải Quan, Dịch
vụ kho bãi, và các Dịch vụ liên quan khác. Công ty CMG cam kết mang đến Quý
khách hàng chất lượng dịch vụ uy tín và ổn định cũng như những giải pháp, tư vấn
tối ưu cho các Doanh nghiệp trong và ngoài nước nhằm tiết kiệm chi phí tới mức
tối thiểu nhưng vẫn đạt hiệu quả tối đa.<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-bottom:0in;margin-bottom:
.0001pt;mso-add-space:auto;line-height:150%"><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-bottom:0in;margin-bottom:
.0001pt;mso-add-space:auto;text-indent:-.25in;line-height:150%;mso-list:l1 level1 lfo1"><!--[if !supportLists]--><b><span style="font-size:10.0pt;line-height:
150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:Arial">2.<span style="font-weight: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><!--[endif]--><b><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Sản
phẩm dịch vụ:<o:p></o:p></span></b></p><p class="MsoListParagraphCxSpMiddle" style="margin-bottom:0in;margin-bottom:
.0001pt;mso-add-space:auto;line-height:150%"><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:.75in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l1 level2 lfo1"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">2.1<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ Giao nhận và Vận chuyển:<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ vận chuyển nội địa và quốc tế<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ vận chuyển đa phương thức<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ vận chuyển hàng hóa bằng đường bộ/ đường biển/ đường hàng không/ đường sắt <o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ vận tải hàng hóa<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
line-height:150%"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:.75in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l1 level2 lfo1"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">2.2<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ Hải quan<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ Hải quan<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ Kê khai Hải quan<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ Thông quan<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
line-height:150%"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:.75in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l1 level2 lfo1"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">2.3<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ Kho Bãi<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ cho thuê Kho, Bãi<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ kho Ngoại quan<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ lưu kho hàng hóa và phân phối hàng hóa<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
line-height:150%"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:.75in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l1 level2 lfo1"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">2.4<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ Giám định – Bảo hiểm<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ Giám định tàu <o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ Bảo hiểm tàu<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
line-height:150%"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:.75in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l1 level2 lfo1"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">2.5<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ cung ứng, sửa chữa tàu biển<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
line-height:150%"><span style="font-size:10.0pt;line-height:150%;font-family:
&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:.75in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l1 level2 lfo1"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">2.6<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ khác<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Đại
lý tàu biển<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ Logistics khép kín<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Dịch
vụ xuất nhập khẩu ủy thác<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Mua
bán container hàng khô / lạnh / văn phòng<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Cung
cấp các trang thiết bị, vật tư phục vụ ngành dầu khí, khai khoáng, xây dựng và
các ngành công nghiệp khác.<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
line-height:150%"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-bottom:0in;margin-bottom:
.0001pt;mso-add-space:auto;text-indent:-.25in;line-height:150%;mso-list:l1 level1 lfo1"><!--[if !supportLists]--><b><span style="font-size:10.0pt;line-height:
150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:Arial">3.<span style="font-weight: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><!--[endif]--><b><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Lợi thế
cạnh tranh của Công ty TNHH Cai Mep Global Logistics (CMG):<o:p></o:p></span></b></p><p class="MsoListParagraphCxSpMiddle" style="margin-bottom:0in;margin-bottom:
.0001pt;mso-add-space:auto;text-align:justify;line-height:150%"><b><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></b></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-align:justify;text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;
font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Công ty CMG Chứng tỏ thế mạnh vượt trội ở sự
kết hợp giữa trình độ chuyên môn nghiệp vụ và kinh nghiệm, giữa hiểu biết thực
tiễn thị trường Việt Nam và yêu cầu về chuẩn mực chất lượng dịch vụ của quốc tế.</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"><o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-align:justify;text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;
font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Công ty CMG có mạng lưới kết nối dịch vụ rộng
khắp và đặc biệt có mối quan hệ tốt với chính quyền ở từng địa phương bao gồm
Biên phòng, Hải quan và Cảng vụ.</span><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"><o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
text-align:justify;text-indent:-.25in;line-height:150%;mso-list:l0 level1 lfo2"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Công
ty CMG có đội ngũ nhân viên trên 20 người cùng đối tác có nhiều kinh nghiệm, uy
tín, có kiến thức chuyên sâu, năng động và tận tụy với khách hàng.<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle"><span style="font-size:10.0pt;line-height:
107%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-top:0in;margin-right:0in;
margin-bottom:0in;margin-left:1.0in;margin-bottom:.0001pt;mso-add-space:auto;
line-height:150%"><strong><i><span style="font-size: 9pt; line-height: 150%; font-family: Arial, sans-serif; color: rgb(153, 153, 153); background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;">CMG mong muốn
trở thành đối tác tin cậy với tất cả các khách hàng và sẵn sàng hợp tác, liên
doanh với các đối tác trong và ngoài nước trên cơ sở đảm bảo lợi&nbsp; ích của
các bên.</span></i></strong><span style="font-size:10.0pt;line-height:150%;
font-family:&quot;Arial&quot;,&quot;sans-serif&quot;"><o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle"><span style="font-size:10.0pt;line-height:
107%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-bottom:0in;margin-bottom:
.0001pt;mso-add-space:auto;text-indent:-.25in;line-height:150%;mso-list:l1 level1 lfo1"><!--[if !supportLists]--><b><span style="font-size:10.0pt;line-height:
150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:Arial">4.<span style="font-weight: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><!--[endif]--><b><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Các
đối tác tiêu biểu:<o:p></o:p></span></b></p>
<p><center><img src="public/images/dttb.jpg"></center></p>

      </div>
    </div>
    

<script type="text/javascript">
    closeSidepage('#gioi-thieu');
   openSidepage('#gioi-thieu');
</script>