
<?php
$url_order = 'ASC';
if ($order_by == 'receivable_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'expect_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'money')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'week')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'staff')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bank_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'vendor')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> NỢ PHẢI THU </h1></center>

	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        
    </div>
    <div class="tablenav top">
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="20">Hiển thị 20 giá trị</option>
            <option value="30">Hiển thị 30 giá trị</option>
            <option value="50">Hiển thị 50 giá trị</option>
            <option value="100">Hiển thị 100 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

        
        <div class="add-box">
            <a class="add_button" id="btnExport" >Export Excel</a>
        </div>

      </div>

</div>

<table id="tblExport" class="table_data">
<thead>
    <tr>
    	<th rowspan="2" class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','receivable_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'receivable_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','code','<?php echo $url_order ?>')">Code <?php if ($order_by == 'code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 

        <th class="fix" colspan="3">
            <a class="sort" >Phải thu </a>
        </th> 
        <th class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money','<?php echo $url_order ?>')">Tổng cộng <?php if ($order_by == 'money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>   
          
        <th class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','expect_date','<?php echo $url_order ?>')">Dự kiến thu <?php if ($order_by == 'expect_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','new_expect_date','<?php echo $url_order ?>')">Dự kiến thu (cập nhật)<?php if ($order_by == 'new_expect_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','pay_money','<?php echo $url_order ?>')">Đã thu <?php if ($order_by == 'pay_money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix" rowspan="2">Còn lại</th> 
         <th class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','expect_date','<?php echo $url_order ?>')">Quá hạn <?php if ($order_by == 'expect_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        
        <th style="width:200px" class="fix" rowspan="2">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Ghi chú<?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
    </tr>
    <tr>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','vendor','<?php echo $url_order ?>')">Vendor <?php if ($order_by == 'vendor'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','staff','<?php echo $url_order ?>')">Nhân viên <?php if ($order_by == 'staff'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
    </tr>
    
   </thead>
   <tbody>
    <?php $tong = 0; $tongthu= 0; $tongcon = 0; ?>
    <?php foreach ($receivables as $receivable) : ?>
    <?php $tong += $receivable->money; ?>
    <?php $tongthu += $receivable->pay_money; ?>
    <?php $tongcon += ($receivable->money-$receivable->pay_money); ?>
    <?php 
        $ngay = $receivable->new_expect_date>0?$receivable->new_expect_date:$receivable->expect_date;
        $timeDiff = strtotime(date('d-m-Y')) - $ngay;

        $numberDays = $timeDiff/86400;  // 86400 seconds in one day

        // and you might want to convert to integer
        $numberDays = intval($numberDays); 
    ?>
    <?php
        if ($receivable->sale_report > 0) {
            $link = 'salereport/index/'.$receivable->code;
        }
        else if ($receivable->agent > 0) {
            $link = 'agent/index/'.$receivable->code;
        }
        else if ($receivable->agent_manifest > 0) {
            $link = 'agentmanifest/index/'.$receivable->code;
        }
        else if ($receivable->trading > 0) {
            $link = 'trading/index/'.$receivable->code;
        }
        else if ($receivable->invoice > 0) {
            $link = 'invoice/index/'.$receivable->invoice;
        }
    ?>
    <?php if($_SESSION['role_logined'] == 10){ $link = "#"; } ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $receivable->receivable_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $receivable->receivable_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="code_<?php echo $receivable->receivable_id; ?>"><a href="<?php echo $this->url($link) ?>"><?php echo $receivable->code; ?>&rarr;</a></td>
            <td class="fix" data="<?php echo $receivable->customer; ?>" id="customer_<?php echo $receivable->receivable_id; ?>"><?php echo isset($customers['name'][$receivable->customer])?$customers['name'][$receivable->customer]:null; ?></td>
            <td class="fix" data="<?php echo $receivable->vendor; ?>" id="vendor_<?php echo $receivable->receivable_id; ?>"><?php echo isset($vendors['name'][$receivable->vendor])?$vendors['name'][$receivable->vendor]:null; ?></td>
            <td class="fix" data="<?php echo $receivable->staff; ?>" id="staff_<?php echo $receivable->receivable_id; ?>"><?php echo isset($staffs['name'][$receivable->staff])?$staffs['name'][$receivable->staff]:null; ?></td>
            <td class="fix" id="money_<?php echo $receivable->receivable_id; ?>"><?php echo $lib->formatMoney($receivable->money); ?></td>
            <td class="fix"  id="expect_date_<?php echo $receivable->receivable_id; ?>"><?php echo $lib->hien_thi_ngay_thang($receivable->expect_date) ?></td>
            <td class="fix"  id="new_expect_date_<?php echo $receivable->receivable_id; ?>"><?php echo $receivable->new_expect_date>0?$lib->hien_thi_ngay_thang($receivable->new_expect_date):null ?></td>
            <td class="fix" id="pay_money_<?php echo $receivable->receivable_id; ?>"><?php echo $lib->formatMoney($receivable->pay_money); ?></td>
            <td class="fix" id="conlai_<?php echo $receivable->receivable_id; ?>"><?php echo $lib->formatMoney($receivable->money-$receivable->pay_money); ?></td>
            <td style="color:<?php echo $numberDays>0?'red':($numberDays==0?'rgb(255, 193, 66)':'green'); ?>" class="fix" id="time_<?php echo $receivable->receivable_id; ?>"><?php echo $numberDays>0?$numberDays.' ngày':($numberDays==0?'Ngày cuối':abs($numberDays).' ngày nữa'); ?></td>
            <td class="fix" id="comment_<?php echo $receivable->receivable_id; ?>"><?php echo $receivable->comment; ?></td> 
            
        </tr>
        
    <?php endforeach; ?>
    <tr style="text-align:center; font-weight: bold; color: red;">
        <td class="fix" colspan="6" >Tổng cộng</td>
        <td class="fix"><?php echo $lib->formatMoney($tong); ?></td>
        <td class="fix"></td>
        <td class="fix"></td>
        <td class="fix"><?php echo $lib->formatMoney($tongthu); ?></td>
        <td class="fix"><?php echo $lib->formatMoney($tongcon); ?></td>
        <td class="fix"></td>
        <td class="fix"></td>
    </tr>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<script type="text/javascript">
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');
</script>