<div class="slide-content" id="luu-kho-va-bao-quan-hang-hoa">
            <!-- Go to www.addthis.com/dashboard to customize your tools -->
        <div class="addthis_native_toolbox"></div>
        <div class="item-page">

            <h2>Lưu kho và bảo quản hàng hóa        </h2>


        <p>Kho bãi của chúng tôi cung cấp cho khách hàng khả năng tiếp cận nhanh chóng đến tất cả các cảng và nhà máy. Chúng tôi cung cấp dịch vụ thuê kho cho tất cả các loại hàng hóa thông thường. Các dịch vụ hỗ trợ hiện có như: đóng gói, dán nhãn, đóng kiện và kiểm đếm hàng hóa …</p>
        <p>1. Hệ thống kho CFS:</p>
        <p>2. Kho lạnh:</p>
        <p>&nbsp;&nbsp;a. Đặc tính cao cấp:&nbsp;</p>
        <p>&nbsp;&nbsp;b. Hệ thống kho trữ đông –20°C.</p>
        <p>&nbsp;&nbsp;c. Hệ thống kho bảo ôn 5°C.&nbsp;</p>
        <p>&nbsp;&nbsp;d. Cửa kho mở được 2 phía.</p>
        <p>&nbsp;&nbsp;e. Xếp dở hàng hóa dễ dàng .</p>
        <p>&nbsp;&nbsp;f. Thiết kế và chế tạo theo tiêu chuẩn HACCP/ FDA (Hoa Kỳ).</p>
        <p>&nbsp;&nbsp;g. Thời gian đông lạnh: 1,5 – 2 giờ (đông nhanh); 4 – 5 giờ (đông lạnh tiếp xúc)</p>
        <p>&nbsp;&nbsp;h. Hệ thống thủy lực chất lượng cao</p>
        <p>1. Hệ thống kho:</p>
        <p>&nbsp;&nbsp;- Kho trong nhà:</p>
        <p>&nbsp;&nbsp;- Kho ngoài trời:</p>
        <p>&nbsp;</p>
        <p>2. Thiết bị hỗ trợ:</p>
        <p>&nbsp;&nbsp;- Đầu kéo:</p>
        <p>&nbsp;&nbsp;- Moóc kéo:</p>
        <p>&nbsp;&nbsp;- Xe tải:</p>
        <p>&nbsp;&nbsp;- Xe nâng:</p> 
        <p><center><img src="public/images/kholanh.jpg"></center></p>
        <p><center>Kho lạnh</center></p>
        <p><center><img src="public/images/xenang.jpg"></center></p>
        <p><center>Xe nâng</center></p>
        </div>
    </div>   

<script type="text/javascript">
    closeSidepage('#luu-kho-va-bao-quan-hang-hoa');
   openSidepage('#luu-kho-va-bao-quan-hang-hoa');
</script>