
<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd/mm/yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#chonngaytao" ).datepicker( "option", "minDate", selectedDate );

                var date = $(this).datepicker('getDate'), 
                    month = date.getMonth() + 1,              
                    year =  date.getFullYear();
                    if (month<10) {
                        var ngay = "0"+month+"/"+year;
                    }
                    else
                        var ngay = month+"/"+year;
                $("#chonngaytaobatdau").val(ngay);
                $("#chonngaytao").datepicker("setDate","<?php echo date('d/m/Y') ?>");
                var date = $("#chonngaytao").datepicker('getDate'), 
                    month = date.getMonth() + 1,              
                    year =  date.getFullYear();
                    if (month<10) {
                        var ngay = "0"+month+"/"+year;
                    }
                    else
                        var ngay = month+"/"+year;
                $("#chonngaytao").val(ngay);
         },
         
    };  
    $("#chonngaytaobatdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd/mm/yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                //$( "#chonngaytaobatdau" ).datepicker( "option", "maxDate", selectedDate );
                var date = $(this).datepicker('getDate'), 
                    month = date.getMonth() + 1,              
                    year =  date.getFullYear();
                    if (month<10) {
                        var ngay = "0"+month+"/"+year;
                    }
                    else
                        var ngay = month+"/"+year;
                $("#chonngaytao").val(ngay);
         },
         
    };  
    $("#chonngaytao").datepicker(pickerOpts4);
              
            
    $("#xem").click(function(){
        var ngay = $("#chonngaytao").val();
        var ngaytaobatdau = $("#chonngaytaobatdau").val();

        var page = "<?php echo $page; ?>";
        var cot = "<?php echo $order_by; ?>";
        var sapxep = "<?php echo $order; ?>";
        var keyword = "<?php echo $keyword; ?>";
        var loc =    $('#chonloc').val();
        
        
        var dataString = 'keyword='+ keyword+"&limit="+loc+"&ngaytaobatdau="+ngaytaobatdau+"&ngaytao="+ngay+"&page="+ page +"&order_by="+ cot +"&order="+ sapxep;  
        
        $('#loading').html("<img src='public/images/loading.gif'/>").fadeIn(500);
        
            $.ajax({
                type: "POST",                            // Phương thức gọi là GET
                url: "#",                 // File xử lý
                data: dataString,                       // Dữ liệu truyền vào
                beforeSend:  function() {               // add class "loading" cho khung nhập
                    $('input#search-input').addClass('loading');
                },
                success: function(server_response)      // Khi xử lý thành công sẽ chạy hàm này
                {
                    $('body').html(server_response);    // Hiển thị dữ liệu vào thẻ div #searchresultdata
                    
                     
                    if ($('input#search-input').hasClass("loading")) {      // Kiểm tra class "loading"
                        $("input#search-input").removeClass("loading");     // Remove class "loading"
                    }
                    $('#loading').fadeOut(500); 
                }
            });
        
        
    });
});
</script>
<?php
$url_order = 'ASC';
if ($order_by == 'sales_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'm')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 's')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'c')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'revenue')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'cost')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'profit')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);
$tongdoanhthu = 0;
$tongdoanhthu_ketoan = 0;
$tongchiphi = 0;
$tongchiphi_ketoan = 0;
$tongloinhuan = 0;




/* arr xem M S C nhân viên xuất hiện mấy lần*/
//$arr_msc = array();
$arr_msc = array();
$total_bonus = array();

?>

<div id="loading"></div>
<div id="winpopup"></div>
<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> DOANH SỐ BÁN HÀNG </h1></center>
<div class="add-box">
    <a class="add_button" id="export_excel" href="<?php echo BASE_URL.'/revenue/export/'.$ngaytaobatdau.'/'.$ngaytao ?>">Export Excel</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
        <div class="add-box">
            <input type="button" name="xem" id="xem" value="Xem">
        </div>
        <div class="add-box">
        	Từ  <input style="width:100px" type="search" name="chonngaytaobatdau" id="chonngaytaobatdau" placeholder="Chọn ngày" <?php if(isset($ngaytaobatdau)) echo "value='$ngaytaobatdau'"; ?>>  
            Đến  <input style="width:100px" type="search" name="chonngaytao" id="chonngaytao" placeholder="Chọn ngày" <?php if(isset($ngaytao)) echo "value='$ngaytao'"; ?>>  
                                        
        </div>

    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option selected="selected" value="18446744073709">Hiển thị tất cả</option>
			<option value="2">Hiển thị 2 giá trị</option>
            <option value="5">Hiển thị 5 giá trị</option>
            <option value="8">Hiển thị 8 giá trị</option>
            <option  value="10">Hiển thị 10 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>

</div>

<table class="table_data scrollTable">
<thead>
    <tr>
    	<th rowspan="2" class="fix" ><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th rowspan="2" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sales_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'sales_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','code','<?php echo $url_order ?>')">CODE <?php if ($order_by == 'code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_name','<?php echo $url_order ?>')">Khách hàng <?php if ($order_by == 'customer_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Diễn giải <?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','accounting_payment_date','<?php echo $url_order ?>')">Ngày thanh toán <?php if ($order_by == 'accounting_payment_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th colspan="3" class="fix">MSC</th>
        
        <th colspan="2"  class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','revenue','<?php echo $url_order ?>')">Tổng hợp doanh thu <?php if ($order_by == 'revenue'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th colspan="2" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','cost','<?php echo $url_order ?>')">Tổng hợp chi phí <?php if ($order_by == 'cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','profit','<?php echo $url_order ?>')">Lợi nhuận<?php if ($order_by == 'profit'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','sales_create_time','<?php echo $url_order ?>')">Tháng<?php if ($order_by == 'sales_create_time'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix"  >&nbsp;</th>
    </tr>
    <tr>
        <th id="m_fix" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','m','<?php echo $url_order ?>')">M <?php if ($order_by == 'm'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th id="s_fix" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','s','<?php echo $url_order ?>')">S <?php if ($order_by == 's'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th id="c_fix" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','c','<?php echo $url_order ?>')">C <?php if ($order_by == 'c'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th id="doanhthu_ketoan_fix" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','accounting_amount','<?php echo $url_order ?>')">Kế toán <?php if ($order_by == 'accounting_amount'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th id="doanhthu_sale_fix" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','revenue','<?php echo $url_order ?>')">Sale <?php if ($order_by == 'revenue'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th id="ketoan_fix" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','accounting_cost','<?php echo $url_order ?>')">Kế toán <?php if ($order_by == 'accounting_cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th id="sale_fix" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','cost','<?php echo $url_order ?>')">Sale <?php if ($order_by == 'cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>   
    </tr>
   </thead>
   <tbody>
    
    <?php foreach ($sales as $sale) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $sale->sales_id ?>" class="edit_tr">
        	<td ><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $sale->sales_id ?>"></td>
            <td  class="fix"><?php echo $i++; ?></td>
            <td  class="fix" id="code_<?php echo $sale->sales_id; ?>"><?php echo $sale->code; ?></td>
            <td  class="fix" id="customer_name_<?php echo $sale->sales_id; ?>"><?php echo $sale->customer_name; ?></td>
            
            <td  class="fix" id="comment_<?php echo $sale->sales_id; ?>"><?php echo $sale->comment; ?></td>
            <td  class="fix" id="accounting_payment_date_<?php echo $sale->sales_id; ?>"><?php echo $sale->accounting_payment_date.' - '.$sale->accounting_bank; ?></td>
            
            <td m="<?php echo $sale->m ?>" data="<?php echo isset($staff['basic_salary'][$sale->sales_create_time][$sale->m])?$staff['basic_salary'][$sale->sales_create_time][$sale->m][$sale->sales_id]:null ?>" class="fix"  id="m_<?php echo $sale->sales_id; ?>"><?php echo (isset($staff['staff_id'][$sale->sales_create_time][$sale->m]) && $sale->m==$staff['staff_id'][$sale->sales_create_time][$sale->m])?$staff['staff_name'][$sale->sales_create_time][$sale->m]:null ?></td>
            <td s="<?php echo $sale->s ?>" data="<?php echo isset($staff['basic_salary'][$sale->sales_create_time][$sale->s])?$staff['basic_salary'][$sale->sales_create_time][$sale->s]:null ?>" class="fix"  id="s_<?php echo $sale->sales_id; ?>"><?php echo (isset($staff['staff_id'][$sale->sales_create_time][$sale->s]) && $sale->s==$staff['staff_id'][$sale->sales_create_time][$sale->s])?$staff['staff_name'][$sale->sales_create_time][$sale->s]:null ?></td>
            <td c="<?php echo $sale->c ?>" data="<?php echo isset($staff['basic_salary'][$sale->sales_create_time][$sale->c])?$staff['basic_salary'][$sale->sales_create_time][$sale->c]:null ?>" class="fix"  id="c_<?php echo $sale->sales_id; ?>"><?php echo (isset($staff['staff_id'][$sale->sales_create_time][$sale->c]) && $sale->c==$staff['staff_id'][$sale->sales_create_time][$sale->c])?$staff['staff_name'][$sale->sales_create_time][$sale->c]:null ?></td>
            <td  class="fix <?php echo $sale->accounting_amount!=$sale->revenue?"warning":"" ?>" id="accounting_amount_<?php echo $sale->sales_id; ?>"><?php echo $lib->formatMoney($sale->accounting_amount); ?></td>
            <td  class="fix <?php echo $sale->accounting_amount!=$sale->revenue?"warning":"" ?>" id="revenue_<?php echo $sale->sales_id; ?>"><?php echo $lib->formatMoney($sale->revenue); ?></td>
            <td  class="fix <?php echo $sale->cost!=$sale->accounting_cost?"warning":"" ?>" id="accounting_cost_<?php echo $sale->sales_id; ?>"><?php echo $lib->formatMoney($sale->accounting_cost); ?></td>
            <td  class="fix <?php echo $sale->cost!=$sale->accounting_cost?"warning":"" ?>" id="cost_<?php echo $sale->sales_id; ?>"><?php echo $lib->formatMoney($sale->cost); ?></td>
            <td  class="fix <?php echo ($sale->cost!=$sale->accounting_cost || $sale->accounting_amount!=$sale->revenue)?"error":"" ?>" id="profit_<?php echo $sale->sales_id; ?>"><?php echo $lib->formatMoney($sale->profit); ?></td>
            <td class="fix" id="sales_create_time_<?php echo $sale->sales_id; ?>"><?php echo $sale->sales_create_time; ?></td>
            <td style="display:none;"  id="customer_phone_<?php echo $sale->sales_id; ?>"><?php echo $sale->customer_phone; ?></td>
            <td style="display:none;"  id="customer_address_<?php echo $sale->sales_id; ?>"><?php echo $sale->customer_address; ?></td>
            <td style="display:none;"  id="customer_email_<?php echo $sale->sales_id; ?>"><?php echo $sale->customer_email; ?></td>
            
            
            
            <td style="width:61px">
                <a class="error" href="#">Sửa</a>
                | 
                <a class="error" onclick="#" >Xóa</a>
            </td>
        </tr>
        <?php
        $tongdoanhthu_ketoan += $sale->accounting_amount;
        $tongdoanhthu += $sale->revenue;
        $tongchiphi += $sale->cost;
        $tongchiphi_ketoan += $sale->accounting_cost;
        $tongloinhuan += $sale->profit;


        /*******/
        $arr_msc[$sale->sales_create_time][$sale->m]['m'][$sale->sales_id][] = $sale->profit;
        $arr_msc[$sale->sales_create_time][$sale->s]['s'][$sale->sales_id][] = $sale->profit;
        $arr_msc[$sale->sales_create_time][$sale->c]['c'][$sale->sales_id][] = $sale->profit;
        /*******/
        $staff_msc[$sale->sales_create_time][$sale->m]['m'][$sale->sales_id] = $sale->profit;
        $staff_msc[$sale->sales_create_time][$sale->s]['s'][$sale->sales_id] = $sale->profit;
        $staff_msc[$sale->sales_create_time][$sale->c]['c'][$sale->sales_id] = $sale->profit;

        

         ?>
    <?php endforeach; 

    $array_sum = 0;
    $total_bonus = array();

        $m_sum = array();
        $s_sum = array();
        $c_sum = array();
        $salary_arr = array();

        $thuong_m = 0;
        $thuong_s = 0;
        $thuong_c = 0;

        $arr_thuong_m = array();
        $arr_thuong_s = array();
        $arr_thuong_c = array();

    foreach ($arr_msc as $thang => $mang) {
        
        
        foreach ($mang as $key => $value) {
          //var_dump($value['m']);die();
            $m_sum[$thang][$key] = 0;
            $s_sum[$thang][$key] = 0;
            $c_sum[$thang][$key] = 0;
            $total_bonus[$thang][$key] = 0;

            $arr_thuong_m[$key][$thang] = 0;
            $arr_thuong_s[$key][$thang] = 0;
            $arr_thuong_c[$key][$thang] = 0;

          if (isset($value['m'])) {
            foreach ($value['m'] as $key1 => $value1) {
                $m_sum[$thang][$key] += array_sum($value1);
                
            }
          }
          if (isset($value['s'])) {
            foreach ($value['s'] as $key2 => $value2) {
                $s_sum[$thang][$key] += array_sum($value2);
                
            }
          }
          if (isset($value['c'])) {
            foreach ($value['c'] as $key3 => $value3) {
                $c_sum[$thang][$key] += array_sum($value3);
                
            }
          }
          
          //$total_bonus[$key] = (isset($m_bonus[$key])?(array_sum($m_bonus[$key])>0?array_sum($m_bonus[$key]):0):0)+(isset($s_bonus[$key])?(array_sum($s_bonus[$key])>0?array_sum($s_bonus[$key]):0):0)+(isset($c_bonus[$key])?(array_sum($c_bonus[$key])>0?array_sum($c_bonus[$key]):0):0);
          //$array_sum[] = $total_bonus[$key];

          $thuong_m = isset($staff['basic_salary'][$thang][$key]) ? (($m_sum[$thang][$key]-(3*$staff['basic_salary'][$thang][$key]))*10/100) : 0;
          $thuong_s = isset($staff['basic_salary'][$thang][$key]) ? (($s_sum[$thang][$key]-(3*$staff['basic_salary'][$thang][$key]))*10/100) : 0;
          $thuong_c = isset($staff['basic_salary'][$thang][$key]) ? (($c_sum[$thang][$key]-(3*$staff['basic_salary'][$thang][$key]))*10/100) : 0;


          $arr_thuong_m[$key][$thang] += ($thuong_m > 0 ? $thuong_m : 0);
          $arr_thuong_s[$key][$thang] += ($thuong_s > 0 ? $thuong_s : 0);
          $arr_thuong_c[$key][$thang] += ($thuong_c > 0 ? $thuong_c : 0);


          $total_bonus[$thang][$key] += ($thuong_m > 0 ? $thuong_m : 0) + ($thuong_s > 0 ? $thuong_s : 0) + ($thuong_c > 0 ? $thuong_c : 0);
          
        }
        //$array_sum[] = array_sum($total_bonus);
        //var_dump($total_bonus);
        $array_sum += array_sum($total_bonus[$thang]);
    }
    
    //var_dump($total_bonus['09/2014'][2]);die();
    //var_dump($thuong_m);die();
    

    ?>
    
   </tbody>
   <tfoot>
       <tr>
           <td></td>
           <td></td>
           <td></td>
           <td></td>
           <td></td>
           <td></td>
           <td></td>
           <td colspan="2"><b>Tổng cộng</b></td>
           <td id="total_accounting_amount" class="error"><?php echo $lib->formatMoney($tongdoanhthu_ketoan) ?></td>
           <td id="total_revenue" class="error"><?php echo $lib->formatMoney($tongdoanhthu) ?></td>
           <td id="total_account_cost" class="error"><?php echo $lib->formatMoney($tongchiphi_ketoan) ?></td>
           <td id="total_cost" class="error"><?php echo $lib->formatMoney($tongchiphi) ?></td>
           <td id="total_profit" class="error"><?php echo $lib->formatMoney($tongloinhuan) ?></td>
           <td></td>
           <td></td>

       </tr>
       <tr>
            <td></td>
           <td></td>
           <td></td>
           <td></td>
           <td></td>
           <td></td>
           <td></td>
           <td colspan="2"><b>Thưởng tháng</b></td>
           <td></td>
           <td></td>
           <td><b class="error" id="total_month_bonus"><?php echo $lib->formatMoney($array_sum) ?></b></td>
           <td></td>
           <td></td>
           <td></td>
           <td></td>
           
       </tr>
   </tfoot>
</table>

<?php
$this->helper('slidePaginator');
?>


<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>


<div style="margin-top:20px" class="tabs">
    <ul class="tab-links">
        
        <?php $dem = 1; $count = 1; ?>
        <?php foreach ($staff_all as $info_name) { ?>
            <li><a href="#tab<?php echo $dem++ ?>"><?php echo $info_name->staff_name ?></a></li>
        <?php } ?>
    </ul>
 
    <div class="tab-content">
        
        <?php foreach ($staff_all as $info) { ?>
        <div id="tab<?php echo $count++ ?>" class="tab" style="width:50%">
            
            <table class="table_data">
                <thead>
                    <tr>
                        <th class="fix">STT</th>
                        <th class="fix">Tháng</th>
                        <th class="fix">CODE</th>
                        <th class="fix">M</th>
                        <th class="fix">S</th>
                        <th class="fix">C</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $stt = 1;
                    foreach ($sales as $sale) { 
                    ?>
                    <tr>
                        <td class="fix"><?php echo $stt++ ?></td>
                        <td class="fix"><?php echo $sale->sales_create_time ?></td>
                        <td class="fix"><?php echo $sale->code ?></td>
                        <td class="fix">
                            <?php
                            
                            if (isset($staff_msc[$sale->sales_create_time][$info->staff_id]['m'][$sale->sales_id])) {
                                echo $lib->formatMoney($staff_msc[$sale->sales_create_time][$info->staff_id]['m'][$sale->sales_id]);
                            }
                            ?>
                        </td>
                        <td class="fix">
                            <?php
                            if (isset($staff_msc[$sale->sales_create_time][$info->staff_id]['s'][$sale->sales_id])) {
                                echo $lib->formatMoney($staff_msc[$sale->sales_create_time][$info->staff_id]['s'][$sale->sales_id]);
                            }
                            ?>
                        </td>
                        <td class="fix">
                            <?php
                            if (isset($staff_msc[$sale->sales_create_time][$info->staff_id]['c'][$sale->sales_id])) {
                                echo $lib->formatMoney($staff_msc[$sale->sales_create_time][$info->staff_id]['c'][$sale->sales_id]);
                            }
                            ?>
                        </td>
                    </tr>
                    
                    
                    <?php } ?>
                    <?php $mm = isset($arr_thuong_m[$info->staff_id])?array_sum($arr_thuong_m[$info->staff_id]):0;
                        $ss = isset($arr_thuong_s[$info->staff_id])?array_sum($arr_thuong_s[$info->staff_id]):0;
                        $cc = isset($arr_thuong_c[$info->staff_id])?array_sum($arr_thuong_c[$info->staff_id]):0;
                     ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th><?php echo $lib->formatMoney($mm) ?></th>
                        <th><?php echo $lib->formatMoney($ss) ?></th>
                        <th><?php echo $lib->formatMoney($cc) ?></th>
                    </tr>
                    <tr>
                        <td></td>
                        <td ><b>Thưởng tháng</b></td>
                        <td></td>
                        <td></td>
                        <td style="text-align:center; color:red; font-weight:bold"><?php echo $lib->formatMoney($tongthuong = $mm+$ss+$cc ) ?></td>
                        <td></td>
                        
                    </tr>
                </tfoot>
            </table>
            <div style="clear:both;margin-top:8px"></div>
            <div class="add-box">
                <a class="add_button" id="export_excel" href="<?php echo BASE_URL.'/revenue/export/'.$ngaytaobatdau.'/'.$ngaytao.'/'.$info->staff_id ?>">Export Excel</a>
            </div>
            <div style="clear:both"></div>
        </div>
        <?php } ?>
    </div>
</div>

<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

/*(function($) {
    $.fn.hasScrollBar = function() {
        return this.get(0).scrollHeight > this.height();
    }
})(jQuery);

if ($('#scrollDiv').hasScrollBar()) {
  
  $('.table_data > thead > tr > th:nth-last-child(8)').css({width: "157px"});
  $('.table_data > thead > tr > th:nth-last-child(7)').css({width: "188px"});
  $('.table_data > thead > tr > th:nth-last-child(6)').css({width: "115px"});
  $('.table_data > thead > tr > th:nth-last-child(4)').css({width: "100px"});
  $('.table_data > thead > tr > th:nth-last-child(2)').css({width: "108px"});
  $('.table_data > thead > tr > th:nth-last-child(1)').css({width: "95px"});

  $('#m_fix').css({width: "97px"});
  $('#s_fix').css({width: "94px"});
  $('#c_fix').css({width: "97px"});
  $('.table_data > thead > tr > th:last').css({width: "100px"});
  
}*/
jQuery(document).ready(function() {
    jQuery('.tabs .tab-links a').on('click', function(e)  {
        var currentAttrValue = jQuery(this).attr('href');
 
        // Show/Hide Tabs
        jQuery('.tabs ' + currentAttrValue).slideDown(300).siblings().slideUp(300);
 
        // Change/remove current tab to active
        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
 
        e.preventDefault();
    });
});

</script>
</div>