<link href="<?php echo BASE_URL ?>/public/css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="<?php echo BASE_URL ?>/public/css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
<script src="<?php echo BASE_URL ?>/public/js/tag-it.js" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/editor/ckeditor.js"></script>

<link href="<?php echo BASE_URL ?>/public/js/jquery-file-upload/uploadfile.css" rel="stylesheet">
<script src="<?php echo BASE_URL ?>/public/js/jquery-file-upload/jquery.uploadfile.min.js"></script>

<!-- Main content -->
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Thêm lịch gửi mới</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form id="addevent" role="form" method="post" action="" enctype="multipart/form-data">
              <div class="row">
                <div class="col-md-12">
                  <div class="box-body">
                    <div class="form-group">
                      <label for="event">Sự kiện</label>
                      <select id="event" class="form-control" required="required" tabindex="1">
                        <?php foreach ($events as $event) { ?>
                        <option <?php echo $event_run->event==$event->event_id?"selected":null ?> value="<?php echo $event->event_id ?>"><?php echo $event->event_name ?></option>
                        <?php } ?>
                      </select>
                    </div>
                    
                    <div class="form-group">
                      <label for="event_content">Nội dung</label>
                      <textarea id="event_content" class="form-event_content" rows="3" placeholder="Nội dung ..." tabindex="2" required="required"><?php echo $event_run->event_content ?></textarea>
                    </div>

                    <div class="form-group">
                      <label for="event_frequently">Lặp lại</label>
                      <input type="radio"  name="event_frequently" value="" tabindex="3" <?php echo $event_run->event_frequently==0?"checked":null ?> > Không
                      <input type="radio"  name="event_frequently" value="1" tabindex="3" <?php echo $event_run->event_frequently==1?"checked":null ?> > Hàng ngày
                      <input type="radio"  name="event_frequently" value="2" tabindex="4" <?php echo $event_run->event_frequently==2?"checked":null ?> > Hàng tuần
                      <input type="radio"  name="event_frequently" value="3" tabindex="5" <?php echo $event_run->event_frequently==3?"checked":null ?> > Hàng tháng
                    </div>

                    <div class="form-group">
                      <label for="event_frequently">Bắt đầu</label>
                      <input type="text"  id="start_date" tabindex="6" value="<?php echo $event_run->start_date>0?date('d-m-Y',$event_run->start_date):null ?>">
                    </div>

                    <div class="form-group">
                      <label for="event_frequently">Kết thúc</label>
                      <input type="text"  id="end_date" tabindex="7" value="<?php echo $event_run->end_date>0?date('d-m-Y',$event_run->end_date):null ?>">
                    </div>
                    
                    
                  </div>
                  <!-- /.box-body -->
                  <div class="box-footer">
                    <input type="hidden"  id="yes" value="<?php echo $event_run->event_run_id ?>" >
                    <button type="submit" class="btn btn-primary" tabindex="8">Hoàn thành</button>
                    <button type="reset" class="btn" tabindex="9">Nhập lại</button>
                  </div>
                  <div class="box-footer">
                    <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
                  </div>
                  
                </div>


              </div>
            </form>
            
            
          </div>
          <!-- /.box -->

        </div>
        <!--/.col (left) -->
        
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->

<script type="text/javascript">
  $(document).ready(function() {
      CKEDITOR.replace('event_content');


    $("#addevent").validate({
        errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
        rules: {
            
        },
        submitHandler: function(form) {
            for ( instance in CKEDITOR.instances ){
                CKEDITOR.instances['event_content'].updateElement();
            }

            var event_name = $('#event').attr('value');
            var event_frequently = $('input[name="event_frequently"]:checked').val();
            var start_date = $('#start_date').attr('value');
            var end_date = $('#end_date').attr('value').trim();
            var event_content = $('#event_content').attr('value');

            
            var yes = $('#yes').attr('value');
         
            $.ajax({
                type: "POST", // phương thức gởi đi
                url: "<?php echo BASE_URL ?>/event/addeventlist", // nơi mà dữ liệu sẽ chuyển đến khi submit
                
                data: {
                    event_content: event_content,
                    event_frequently: event_frequently,
                    start_date: start_date,
                    end_date: end_date,
                    event_name: event_name,
                    yes: yes,
                }, // giá trị post
                success: function(answer){ // if everything goes well
                    //alert(answer);
                    var data = JSON.parse(answer);

                    $('#show').html(data.msg);
                    $('#winpopup').show();
                    $('#error').hide();
                    $('#error').slideToggle(100); // hiển thị thẻ div success
                    $('#error').html('<div class="successbox">'+data.msg+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                    $('#error').fadeOut(10000);

                    $('#yes').val(data.id);

                }
            });
            return false;
             
         }
    });
  });

var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#end_date" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#start_date").datepicker(pickerOpts3);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#start_date" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#end_date").datepicker(pickerOpts4);
</script>