<div id="content" style="padding:5px;">
<center style="margin-bottom: 10px;"><h1> TỔNG HỢP DOANH SỐ BÁN HÀNG</h1></center>

<form id="report" name="report" action method="post">
<div style="margin-top: -15px" >
    <div class="add-box">
        <a class="add_button" id="btnExport" >Export Excel</a>
    </div>

    <select id="sl_round" name="sl_round" style="width:90px; margin-left:5px;">
     <?php 
        for ($i=1; $i < 13; $i++) { 
            echo '<option value="'.$i.'">Tháng '.$i.'</option>';
        }
     ?>
    </select>
    <select id="sl_trangthai" name="sl_trangthai" style="width:100px">
     <?php 
        $nam = date('Y');
        for ($i=($nam-5); $i < ($nam+5); $i++) { 
            echo '<option value="'.$i.'">Năm '.$i.'</option>';
        }
     ?>
    </select>
    <input type="submit" name="submit" id="xem" value="Xem">  
</div>
<div >
    
    Từ  <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
    Đến  <input style="width:100px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
     <input type="submit" name="submit" id="xem" value="Xem">  
                            
</div>

</form> 

<?php
$tong = array();
?>

<table class="table_data" id="tblExport">
    <thead>
        <tr>
            <th rowspan="2" class="fix">Sale</th>
            <th colspan="2" class="fix">Khách hàng mới</th>
            <th colspan="2" class="fix">Khách hàng cũ</th>
            <th colspan="2" class="fix">Sản lượng bán</th>
            <th colspan="2" class="fix">Đơn hàng</th>
            <th rowspan="2" class="fix">Lương sản phẩm</th>
            <th rowspan="2" class="fix">Doanh thu</th>
        </tr>
        <tr>
            <th class="fix">Đại lý</th>
            <th class="fix">Trực tiếp</th>
            <th class="fix">Đại lý</th>
            <th class="fix">Trực tiếp</th>
            <th class="fix">Đại lý</th>
            <th class="fix">Trực tiếp</th>
            <th class="fix">Mới</th>
            <th class="fix">Cũ</th>
        </tr>
   </thead>
   <tbody>
        <?php $moi=600000; $cu=200000; $sanluong=7000; $tongdl=0; $tongtt=0; $tongdlmoi=0; $tongdlcu=0; $tongttmoi=0; $tongttcu=0; $tongluongsp=0; $tongluongvuotgia=0; $tongkpi=0; $tongdoanhthu=0; $donmoi=0; $doncu=0; $tongdonmoi=0; $tongdoncu=0; $tongdon=0;
        foreach ($users as $user): 
            $dl = isset($sl_daily[$user->staff_id])?$sl_daily[$user->staff_id]:0;
            $tt = isset($sl_tt[$user->staff_id])?$sl_tt[$user->staff_id]:0; 
            $dlmoi = isset($daily_moi[$user->staff_id])?$daily_moi[$user->staff_id]:0;
            $ttmoi = isset($tt_moi[$user->staff_id])?$tt_moi[$user->staff_id]:0; 
            $dlcu = isset($daily_cu[$user->staff_id])?$daily_cu[$user->staff_id]:0;
            $ttcu = isset($tt_cu[$user->staff_id])?$tt_cu[$user->staff_id]:0;
            $donmoi = isset($don_moi[$user->staff_id])?$don_moi[$user->staff_id]:0;
            $doncu = isset($don_cu[$user->staff_id])?$don_cu[$user->staff_id]:0;
            $tongdl += $dl;
            $tongtt += $tt;
            $tongdlmoi += $dlmoi;
            $tongdlcu += $dlcu;
            $tongttmoi += $ttmoi;
            $tongttcu += $ttcu;
            $tongdonmoi += $donmoi;
            $tongdoncu += $doncu;

            $luongsp = isset($luong_sp[$user->staff_id])?round($luong_sp[$user->staff_id]):0;
            $luongvuotgia = isset($luong_vuotgia[$user->staff_id])?round($luong_vuotgia[$user->staff_id]):0;
            $tongluongsp += $luongsp;
            $tongluongvuotgia += $luongvuotgia;

            $kpi = ($donmoi)*$moi + ($doncu)*$cu + ($dl+$tt)*$sanluong;
            $tongkpi += $kpi;

            $dt = isset($doanhthu[$user->staff_id])?$doanhthu[$user->staff_id]:0;
            $tongdoanhthu += $dt;
        ?>
            <tr style=" color:rgb(0, 32, 96); font-weight:bold;">
                <td class="fix"><?php echo $user->staff_name; ?></td>
                <td class="fix"><a href="<?php echo BASE_URL ?>/ordertire/report/0/<?php echo strtotime($batdau).'/'.$user->user_id ?>"><?php echo $dlmoi; ?></a></td>
                <td class="fix"><a href="<?php echo BASE_URL ?>/ordertire/report/0/<?php echo strtotime($batdau).'/'.$user->user_id ?>"><?php echo $ttmoi; ?></a></td>
                <td class="fix"><a href="<?php echo BASE_URL ?>/ordertire/report/0/<?php echo strtotime($batdau).'/'.$user->user_id ?>"><?php echo $dlcu; ?></a></td>
                <td class="fix"><a href="<?php echo BASE_URL ?>/ordertire/report/0/<?php echo strtotime($batdau).'/'.$user->user_id ?>"><?php echo $ttcu; ?></a></td>
                <td class="fix"><a href="<?php echo BASE_URL ?>/ordertire/report/0/<?php echo strtotime($batdau).'/'.$user->user_id ?>"><?php echo $dl; ?></a></td>
                <td class="fix"><a href="<?php echo BASE_URL ?>/ordertire/report/0/<?php echo strtotime($batdau).'/'.$user->user_id ?>"><?php echo $tt; ?></a></td>
                <td class="fix"><a href="<?php echo BASE_URL ?>/ordertire/report/0/<?php echo strtotime($batdau).'/'.$user->user_id ?>"><?php echo $donmoi; ?></a></td>
                <td class="fix"><a href="<?php echo BASE_URL ?>/ordertire/report/0/<?php echo strtotime($batdau).'/'.$user->user_id ?>"><?php echo $doncu; ?></a></td>
                <td class="fix"><?php echo $lib->formatMoney($luongsp); ?></td>
                <td class="fix"><?php echo $lib->formatMoney($dt); ?></td>
                
            </tr>
        <?php endforeach; ?>
        <tr style=" color:rgb(211, 11, 57); text-align: center; font-weight:bold;">
            <td class="fix">Tổng cộng</td>
            <td class="fix"><?php echo $tongdlmoi ?></td>
            <td class="fix"><?php echo $tongttmoi ?></td>
            <td class="fix"><?php echo $tongdlcu ?></td>
            <td class="fix"><?php echo $tongttcu ?></td>
            <td class="fix"><?php echo $tongdl ?></td>
            <td class="fix"><?php echo $tongtt ?></td>
            <td class="fix"><?php echo $tongdonmoi ?></td>
            <td class="fix"><?php echo $tongdoncu ?></td>
            <td class="fix"></td>
            <td class="fix"></td>
        </tr>
        <tr style=" color:rgb(211, 11, 57); text-align: center; font-weight:bold;">
            <td class="fix">Tổng cộng</td>
            <td class="fix" colspan="2"><?php echo $tongdlmoi+$tongttmoi ?></td>
            <td class="fix" colspan="2"><?php echo $tongdlcu+$tongttcu ?></td>
            <td class="fix" colspan="2"><?php echo $tongdl+$tongtt ?></td>
            <td class="fix" colspan="2"><?php echo $tongdonmoi+$tongdoncu ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongluongsp) ?></td>
            <td class="fix"><?php echo $lib->formatMoney($tongdoanhthu) ?></td>
            
        </tr>
        
   </tbody>
</table>

<script type="text/javascript">
    $(function() {

        var w = $(".report").width();

      $(".report-right-fix").width(w-355);


    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showWeek: true,
        weekHeader: 'Tuần',
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showWeek: true,
        weekHeader: 'Tuần',
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
    
});



</script>
<style type="text/css">
.report{
    width: 100%;
    margin: -5px auto;
}
.report-left{
    float: left;
    width: 150px;
}
.report-right{
    
    overflow: auto;
}
.showtooltip {
        display:none;
        position:absolute;
        border:1px solid #333;
        background-color:#161616;
        border-radius:5px;
        padding:10px;
        color:#fff;
        font-size:12px Arial;
    }
</style>
<script type="text/javascript">
$(document).ready(function() {
// Tooltip only Text
$('.masterTooltip').hover(function(){
        // Hover over code
        var title = $(this).attr('title');
        $(this).data('tipText', title).removeAttr('title');
        $('<p class="showtooltip"></p>')
        .text(title)
        .appendTo('body')
        .fadeIn('slow');
}, function() {
        // Hover out code
        $(this).attr('title', $(this).data('tipText'));
        $('.showtooltip').remove();
}).mousemove(function(e) {
        var mousex = e.pageX + 20; //Get X coordinates
        var mousey = e.pageY + 10; //Get Y coordinates
        $('.showtooltip')
        .css({ top: mousey, left: mousex })
});


});

var w = $("#container").width();

      $(".container").width(w);
      $(".navbar-inner").width(w);
      $(".navbar").width(w);

$(document).ready(function() {
    function fixDiv() {
      
      var $cache = $('.navbar-fixed-top'); 
      if ($(window).scrollTop() > 42) {
        $cache.css({'position': 'fixed', 'top': '0'}); 
        $(".navbar-inner").css({'width':'100%'});
        $(".navbar").css({'width':'100%'});
      }
      else{
        var w = $("#container").width();
        $cache.css({'position': 'relative', 'top': 'auto'});
        $(".navbar-inner").width(w);
        $(".navbar").width(w);
      }
      
    }
  $(window).scroll(fixDiv);
  fixDiv();


});


var v = "<?php echo $vong ?>";
$('#sl_round option[value='+v+']').attr('selected','selected');

var tt = "<?php echo $trangthai ?>";
$('#sl_trangthai option[value='+tt+']').attr('selected','selected');

</script>
</div>

<script type="text/javascript">
    
    $('#sl_round').change(function(){
        var m = $(this).val();
        var y = $('#sl_trangthai').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });

    $('#sl_trangthai').change(function(){
        var y = $(this).val();
        var m = $('#sl_round').val();
        var firstDay = new Date(y, m-1, 1);
        var lastDay = new Date(y, m, 0);

        $('#batdau').datepicker("setDate", firstDay );
        $('#ketthuc').datepicker("setDate", lastDay );

    });


</script>