<div class="slide-content" id="van-tai-duong-bo">
			<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_native_toolbox"></div>
        <div class="item-page">
            <h2>Vận tải đường bộ</h2>
            <p><center><img src="public/images/vtbo.jpg"></center></p>
            <p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: justify; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;">Vận tải đường bộ là phần không thể tách rời khỏi dây chuyền
cung ứng dịch vụ giao nhận kho vận khác. CMG cung ứng các dịch vụ vận tải theo
lịch trình, hàng gom và thuê nguyên chuyến.<o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><b><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;"><o:p>&nbsp;</o:p></span></b></p>

<p class="MsoNormal" style="margin-bottom: 0.0001pt; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><b><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Các dịch vụ của chúng tôi:<o:p></o:p></span></b></p>

<p class="MsoListParagraphCxSpFirst" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Vận tải hàng lẻ<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Vận tải hàng khối lượng lớn<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Các dịch vụ kéo container<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Các dịch vụ vận tải liên hợp<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Vận tải hàng siêu trường, siêu
trọng, hàng rời và hàng đặc biệt.<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Vận chuyển hàng đồ dùng gia đình và
tài sản cá nhân.<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Vận chuyển hàng quá cảnh.<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Vận chuyển hàng tạm nhập-tái xuất và
tạm xuất-tái nhập.<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpLast" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Lưu kho và phân phối hàng hoá<o:p></o:p></span></p>

<p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
150%"><b><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;"><o:p>&nbsp;</o:p></span></b></p>

<p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
150%"><b><span style="font-size:10.0pt;
line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:
&quot;Times New Roman&quot;">Các dịch vụ giá trị gia tăng:<o:p></o:p></span></b></p>

<p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
150%"><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;"><o:p>&nbsp;</o:p></span></p>

<p class="MsoListParagraphCxSpFirst" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Các dịch vụ nhận hàng<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Kiểm soát hàng từ khi nhận hàng đến
khi giao hàng<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Kiểm đếm hàng<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpMiddle" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Báo cáo việc vận chuyển<o:p></o:p></span></p>

<p class="MsoListParagraphCxSpLast" style="margin: 0in 0in 0.0001pt 1in; text-indent: -0.25in; line-height: 150%; background-image: initial; background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial; background-position: initial; background-repeat: initial;"><!--[if !supportLists]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:Arial">-<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-size:10.0pt;line-height:150%;font-family:&quot;Helvetica&quot;,&quot;sans-serif&quot;;
mso-fareast-font-family:&quot;Times New Roman&quot;">Giám sát tại chỗ<o:p></o:p></span></p>
 
        </div>
    </div>

<script type="text/javascript">
    closeSidepage('#van-tai-duong-bo');
   openSidepage('#van-tai-duong-bo');
</script>