<?php
$url_order = 'ASC';
if ($order_by == 'position_revenue_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'position_revenue_percent')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'position_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'position_revenue_type')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> PHẦN TRĂM LƯƠNG DOANH THU</h1></center>
<div class="add-box">
    <a class="add_button" onClick="add_click();">Nhập mới</a>
    <a class="add_button" id="btnExport" >Export Excel</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Search">
        <input type="button" name="" id="search-submit" class="button-search" value="Search" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
       
    </div>
    <div class="tablenav top">

    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Select</option>
                
                <option value="delete">Delete</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Apply" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">All</option>
			<option value="15">15 items</option>
            <option value="20">20 items</option>
            <option value="50">50 items</option>
            <option selected="selected" value="100">100 items</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Apply" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

        
      </div>

</div>

<table class="table_data" id="tblExport">
<thead>
    <tr>
        <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','position_revenue_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'position_revenue_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','position_revenue_percent','<?php echo $url_order ?>')">% doanh thu <?php if ($order_by == 'position_revenue_percent'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','position_name','<?php echo $url_order ?>')">Chức vụ <?php if ($order_by == 'position_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','position_revenue_type','<?php echo $url_order ?>')">Loại <?php if ($order_by == 'position_revenue_type'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','position_revenue_start_date','<?php echo $url_order ?>')">Từ ngày <?php if ($order_by == 'position_revenue_start_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','position_revenue_end_date','<?php echo $url_order ?>')">Đến ngày <?php if ($order_by == 'position_revenue_end_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th class="fix"></th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($positions as $position) : 
        switch ($position->position_revenue_type) {
            case 1:
                $type = "Bán lẻ";
                break;
            case 2:
                $type = "Bán cont";
                break;
            case 3:
                $type = "Vượt giá";
                break;
            case 4:
                $type = "Dưới giá";
                break;
            case 5:
                $type = "Nợ chứng từ";
                break;
            case 6:
                $type = "Nợ k chứng từ";
                break;
            case 7:
                $type = "Bồi thường";
                break;
            default:
                $type = null;
                break;
        }
    ?>
    
        
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $position->position_revenue_id ?>" class="edit_tr">
            
            <td>
                <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $position->position_revenue_id ?>">
            </td>
            
            <td  class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="position_revenue_percent_<?php echo $position->position_revenue_id; ?>"><?php echo $position->position_revenue_percent; ?></td>
            <td class="fix" id="position_name_<?php echo $position->position_revenue_id; ?>"><?php echo $position->position_name; ?></td>
            <td class="fix" id="position_revenue_type_<?php echo $position->position_revenue_id; ?>"><?php echo $type; ?></td>
            <td class="fix" id="position_revenue_start_date_<?php echo $position->position_revenue_id; ?>"><?php echo $lib->hien_thi_ngay_thang($position->position_revenue_start_date); ?></td>
            <td class="fix" id="position_revenue_end_date_<?php echo $position->position_revenue_id; ?>"><?php echo $lib->hien_thi_ngay_thang($position->position_revenue_end_date); ?></td>
            <td>
                <button class="error" onclick="del(<?php echo $position->position_revenue_id ?>)" >Xóa</button>
                
               
            </td>
        </tr>


    <?php endforeach; ?>
     
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div style="display:none" id="lasted"></div>
<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Phần trăm doanh thu </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_tire" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            
                            <td>% doanh thu</td>
                            <td>
                                <input class="number" type="text" id="position_revenue_percent"  name="position_revenue_percent" tabindex="1"  required="required" >
                            </td>
                            <td>Chức vụ</td>
                            <td>
                                <select name="posiition" id="position" tabindex="2"  required="required">
                                    <?php foreach ($position_datas as $pos) { ?>
                                    <option value="<?php echo $pos->position_id ?>"><?php echo $pos->position_name ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>Loại</td>
                            <td>
                                <select name="position_revenue_type" id="position_revenue_type" tabindex="3"  required="required">
                                    <option value="1">Bán lẻ</option>
                                    <option value="2">Bán cont</option>
                                    <option value="3">Vượt giá</option>
                                    <option value="4">Dưới giá</option>
                                    <option value="5">Nợ chứng từ</option>
                                    <option value="6">Nợ k chứng từ</option>
                                    <option value="7">Bồi thường</option>
                                </select>
                            </td>
                            <td>Từ ngày</td>
                            <td>
                                <input  type="text" class="ngay" id="position_revenue_start_date"  name="position_revenue_start_date" tabindex="4"  required="required" >
                            </td>
                            <td>Đến ngày</td>
                            <td>
                                <input  type="text" class="ngay" id="position_revenue_end_date"  name="position_revenue_end_date" tabindex="5"  required="required" >
                            </td>
                        </tr>
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>
                                <input type="submit" name="submit" value="Submit" tabindex="6">
                                
                            </td>
                            <td>
                                <input type="reset" name="reset" value="Reset" tabindex="7">
                            </td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>


<script type="text/javascript">


  
$('.add-field').hide();  


$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);   
    }
    
});



    $('.edit_tr').click(function(e){
        if(e.target != '[object HTMLButtonElement]' && e.target != '[object HTMLSpanElement]' && !$('.checkbox').is(':focus')) { 
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            
            var position_revenue_percent = $(this).find("#position_revenue_percent_"+$(this).attr('id')).text();
            var position = $(this).find("#position_name_"+$(this).attr('id')).text();
            var start = $(this).find("#position_revenue_start_date_"+$(this).attr('id')).text();
            var end = $(this).find("#position_revenue_end_date_"+$(this).attr('id')).text();
            var type = $(this).find("#position_revenue_type_"+$(this).attr('id')).text();
            //alert(cost_code);
            $('#yes').val($(this).attr('id'));
            
            $('#position option:contains('+position+')').attr('selected','selected');
            $('#position_revenue_type option:contains('+type+')').attr('selected','selected');
            $('#position_revenue_percent').val(position_revenue_percent);
            $('#position_revenue_start_date').val(start.replace(/\//g,"-"));
            $('#position_revenue_end_date').val(end.replace(/\//g,"-"));
            

            $( ".add-field" ).dialog( "open" );
        }

        
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
     
        $('#position_revenue_percent').val("");
        $('#position_revenue_start_date').val("");
        $('#position_revenue_end_date').val("");
                
        $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

    $( ".add-field" ).dialog( "open" );
}


$(document).ready(function(){
            // Validate form
            $("#add_tire").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var position = $('#position').attr('value');
                    var position_revenue_percent = $('#position_revenue_percent').attr('value');
                    var position_revenue_start_date = $('#position_revenue_start_date').attr('value');
                    var position_revenue_end_date = $('#position_revenue_end_date').attr('value');
                    var position_revenue_type = $('#position_revenue_type').attr('value');

                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/positionrevenue/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            
                            position: position,
                            position_revenue_percent: position_revenue_percent,
                            position_revenue_start_date: position_revenue_start_date,
                            position_revenue_end_date: position_revenue_end_date,
                            position_revenue_type: position_revenue_type,
                            yes: yes,

                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

                            }
                            else{
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                
                            }
                        }
                    });
                    return false;
                     
                 }
            });


});

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });


 
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');


</script>
</div>

<script type="text/javascript">


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Phần trăm doanh thu",
    hide: 'fold',
    show: 'blind'
});


var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onSelect: function(dateStr) {
          if ($('#position_revenue_end_date').val()=="") {
            var d = $.datepicker.parseDate('dd-mm-yy', dateStr);
            //var years = parseInt(10, 10);

            //d.setFullYear(d.getFullYear() + years);

            $('#position_revenue_end_date').datepicker('setDate', d);
          }
            
        },
        onClose: function(selectedDate) {
                
                $( "#position_revenue_end_date" ).datepicker( "option", "minDate", selectedDate );

         },
    }; 
    $("#position_revenue_start_date").datepicker(pickerOpts);

    var pickerOpts2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#position_revenue_start_date" ).datepicker( "option", "maxDate", selectedDate );

         },
    }; 
    $("#position_revenue_end_date").datepicker(pickerOpts2);

$('.number').keyup(function(event) {

      // skip for arrow keys
  if(event.which >= 37 && event.which <= 40) return;

  // format number
  $(this).val(function(index, value) {
    return value
      .replace(/[^0-9-.]/g, "")
    ;
  });
});
</script>

