
<?php
$url_order = 'ASC';
if ($order_by == 'advance_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'advance_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'expect_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'week')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'money')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'pay_money')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'bank_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'approve')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'approve2')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'approve3')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'staff_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>

<div id="content" style="padding:5px;">
    <center style="clear:both;margin-bottom: -30px;"><h1> TẠM ỨNG </h1></center>
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm bảng tạm ứng</a>
     <a class="add_button" id="import_excel" href="<?= $this->url('advance/import')?>">Import Excel</a>
</div>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <div class="add-box">
                  
            Tuần  <input style="width:50px" type="search" name="batdau" id="batdau" placeholder="Chọn tuần" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
        </div>
    </div>
    <div class="tablenav top">
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="5">Hiển thị 5 giá trị</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="15">Hiển thị 15 giá trị</option>
            <option selected="selected" value="20">Hiển thị 20 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>

</div>

<table class="table_data">
<thead>
    <tr>
    	<th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','advance_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'advance_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','advance_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'advance_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','staff_name','<?php echo $url_order ?>')">Nhân viên <?php if ($order_by == 'staff_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money','<?php echo $url_order ?>')">Số tiền <?php if ($order_by == 'money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','pay_money','<?php echo $url_order ?>')">Đã chi<?php if ($order_by == 'pay_money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>   
          
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','comment','<?php echo $url_order ?>')">Nội dung<?php if ($order_by == 'comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','code','<?php echo $url_order ?>')">Dự kiến trả<?php if ($order_by == 'code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        
        <th class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','approve','<?php echo $url_order ?>')">Duyệt bởi <?php if ($order_by == 'approve'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','approve2','<?php echo $url_order ?>')">Duyệt bởi <?php if ($order_by == 'approve2'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th> 
        <th class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','approve3','<?php echo $url_order ?>')">Duyệt bởi <?php if ($order_by == 'approve3'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
           
        <th  class="fix">Action</th>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($advances as $advance) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $advance->advance_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $advance->advance_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
             <td class="fix"  id="advance_date_<?php echo $advance->advance_id; ?>"><?php echo $lib->hien_thi_ngay_thang($advance->advance_date) ?></td>
            <td class="fix" id="staff_<?php echo $advance->advance_id; ?>"><?php echo $advance->staff_name; ?></td>
            <td class="fix" id="money_<?php echo $advance->advance_id; ?>"><?php echo $lib->formatMoney($advance->money); ?></td>
            <td class="fix" id="pay_money_<?php echo $advance->advanvce_id; ?>"><?php echo $lib->formatMoney($advance->pay_money); ?></td>
             <td class="fix" id="comment_<?php echo $advance->advance_id; ?>"><?php echo $advance->comment; ?></td> 
            <td class="fix"  id="expect_date_<?php echo $advance->advance_id; ?>"><?php echo $lib->hien_thi_ngay_thang($advance->expect_date) ?></td>
             <td class="fix" id="approve_<?php echo $advance->advance_id; ?>"><?php echo isset($users['name'][$advance->approve])?$users['name'][$advance->approve]:($_SESSION['role_logined']==3?'<button data="'.$advance->advance_id.'" class="approve">Duyệt</button>':null); ?></td>  
             <td class="fix" id="approve2_<?php echo $advance->advance_id; ?>"><?php echo isset($users['name'][$advance->approve2])?$users['name'][$advance->approve2]:((isset($users['name'][$advance->approve]) && $_SESSION['role_logined']==8)?'<button data="'.$advance->advance_id.'" class="approve2">Duyệt</button>':null); ?></td>
             <td class="fix" id="approve3_<?php echo $advance->advance_id; ?>"><?php echo isset($users['name'][$advance->approve3])?$users['name'][$advance->approve3]:((isset($users['name'][$advance->approve]) && isset($users['name'][$advance->approve2]) && $_SESSION['role_logined']==7)?'<button data="'.$advance->advance_id.'" class="approve3">Duyệt</button>':null); ?></td>       
            <td>
                <?php if($advance->pay_money != $advance->money || $advance->pay_date == null && isset($users['name'][$advance->approve3]) && ($_SESSION['role_logined'] <= 2 || $_SESSION['role_logined']==7)){ ?>
                
                <button style="white-space: nowrap;" title="" alt="<?php echo date('d-m-Y') ?>"  name="<?php echo $lib->formatMoney($advance->money-$advance->pay_money) ?>" data="<?php echo $advance->source ?>" value="<?php echo $advance->advance_id ?>" class="editButton">Thanh toán</button> 
                 
                <?php } ?>
                <?php if($advance->pay_date == null){ ?>
                <button class="error" onclick="del(<?php echo $advance->advance_id ?>)" >Xóa</button>
                <?php } ?>
            </td>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Tạm ứng</h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_advance" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            
                        </tr>
                        <tr>
                           <td>Số tiền </td>
                            <td>
                                <input type="text" class="numbers"  id="money"  name="money" tabindex="1" required="required"  >
                                
                            </td>
                            <td>Nội dung</td>
                            <td><textarea id="comment" name="comment" tabindex="2" required="required"></textarea></td>
                            <td>Dự kiến trả</td>
                            <td>
                                <input type="text" id="expect_date"  name="expect_date" tabindex="3"  required="required" >
                                
                            </td>
                            
                           
                            

                        </tr>
                        
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><input type="submit" name="submit" value="Hoàn tất" tabindex="4"></td>
                            <td ><input type="reset" name="reset" value="Nhập lại" tabindex="5"></td>
                            <td></td>
                            <td></td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>

<div id="dialogContent" title="Tạm ứng">
    
    
    <form action="#" method="post" id="editForm">
        
        <label>
            <span class="add-on"><i class="icon-ok-circle" ></i></span>
            <span>Tài khoản: </span>
            <select id="i_source" name="i_source" style="width:150px" required="required" >
                <?php foreach($banks as $bank){ ?>
                    <option value="<?php echo $bank->bank_id ?>"><?php echo $bank->bank_name ?></option>
                <?php } ?>
            </select>
        </label>
        <label>
            <span class="add-on"><i class="icon-calendar" ></i></span>
            <span>Ngày: </span>
            <input type="hidden" id="i_advance" name="i_advance" value="" />
            <input type="text" id="i_pay_date" name="i_pay_date" value="" class="pay_date" required="required" />
        </label>
        <label>
            <span class="add-on"><i class="icon-retweet" ></i></span>
            <span>Số tiền: </span>
            <input type="text" id="i_pay_money" name="i_pay_money" value="" class="numbers" required="required" />
        </label>
    </form>
</div>

<script type="text/javascript">

var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $("#expect_date").datepicker(pickerOpts);

  

$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }

});


    $('.edit_tr').click(function(e){
        if(e.target != '[object HTMLButtonElement]' && !$('.checkbox').is(':focus')){
            if(!$('.checkbox').is(':checked')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            var expect_date = $(this).find("#expect_date_"+$(this).attr('id')).text();
            var comment = $(this).find("#comment_"+$(this).attr('id')).text();
            var money = $(this).find("#money_"+$(this).attr('id')).text();
            var pay_money = $(this).find("#pay_money_"+$(this).attr('id')).text();

            //alert(advance_code);
            $('#yes').val($(this).attr('id'));
            
            
            $('#expect_date').val(expect_date.replace(/\//g,"-"));
            $('#comment').val(comment);
            $('#money').val(money);

            $( ".add-field" ).dialog( "open" );
        }
        
    });
</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
     
        $('#expect_date').val();
        $('#comment').val();
        $('#money').val(0);
        $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

        $( ".add-field" ).dialog( "open" );
}


$(document).ready(function(){
            // Validate form
            $("#add_advance").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var expect_date = $('#expect_date').attr('value');
                    
                    var money = $('#money').attr('value');
                    var comment = $('#comment').attr('value');
                    

                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/advance/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            expect_date: expect_date,
                            money: money,
                            comment: comment,
                            
                            yes: yes,

                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

                                    $('#expect_date_'+yes).text(expect_date);
                                    $('#comment_'+yes).text(comment);
                                    $('#money_'+yes).text(money);
                                
                            }
                            else{
                                setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="vendor_'+parseInt(lastID+1)+'">'+vendor+'</td><td class="fix" id="money_'+parseInt(lastID+1)+'">'+money+'</td><td class="fix" id="expect_date_'+parseInt(lastID+1)+'">'+expect_date+'</td><td class="fix" id="week_'+parseInt(lastID+1)+'"></td><td class="fix" id="code_'+parseInt(lastID+1)+'">'+code+'</td><td class="fix" id="source_'+parseInt(lastID+1)+'">'+$("#source option:selected").text()+'</td><td class="fix" id="comment_'+parseInt(lastID+1)+'">'+comment+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                
                            }
                        }
                    });
                    return false;
                     
                 }
            });

   


   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-]/g, "")
        ;
      });
    });
    

});

function get_number(id){
    return $(id).val().replace(/\,/g,'');
}

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');


$('.approve').click(function(){
    var id = $(this).attr("data")
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/advance/approve", {data: id},
           function(data){
            
                $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});
$('.approve2').click(function(){
    var id = $(this).attr("data")
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/advance/approve2", {data: id},
           function(data){
            
            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});
$('.approve3').click(function(){
    var id = $(this).attr("data");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/advance/approve3", {data: id},
           function(data){
            
            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});
$('.pay').click(function(){
    var id = $(this).attr("value");
    var source = $(this).attr("data");
    var money = $(this).attr("name");
    var pay_date = $(this).attr("alt");
    var r = confirm("Bạn có chắc chắn không?");
      if (r == true){
        $('#loading').html("<img src='<?php echo BASE_URL ?>/public/images/loading.gif'/>").fadeIn(500);
        $.post("<?php echo BASE_URL ?>/advance/pay", {data: id, source: source, money: money, pay_date: pay_date},
           function(data){
            
            $("html, body").animate({ scrollTop: 0 }, 100);
            setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);

            $('#loading').fadeOut(500);
           
           }); 
      }

});
$('.source').change(function(){
    var val = $(this).val();
    $('.pay').attr('data',val);
    $(".source option[value="+val+"]").attr('selected', 'selected');
});
$('.money').keyup(function(event) {
        var val = $(this).val();
        $('.pay').attr('name',val);
    });
$('.pay_date').change(function(){
    var val = $(this).val();
    $('.pay').attr('alt',val);
    $('.pay_date').val(val);
});

var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".pay_date").datepicker(pickerOpay2);
</script>
</div>


<script type="text/javascript">

$('.editButton')
    .button({ icons: { primary: "ui-icon-document" }})
    .click(function() {
        
        $('#i_advance').val($(this).attr('value'));
        $('#i_pay_date').val($(this).attr('alt'));
        $('#i_source option[value='+$(this).attr('data')+']').attr('selected','selected');
        $('#i_pay_money').val($(this).attr('name'));
        $('#i_pay_money').focus();

        $( "#dialogContent" ).dialog( "open" )
    });


//set up the dialog box.
$( "#dialogContent" ).dialog({
    autoOpen: false,
    modal: true,
    buttons: {
        OK: function() {
                
            var id = $('#i_advance').val();
            var source = $('#i_source').val();
            var money = $('#i_pay_money').val();
            var pay_date = $('#i_pay_date').val();

                $.post("<?php echo BASE_URL ?>/advance/pay", {data: id, source: source, money: money, pay_date: pay_date},
                   function(data){
                    
                    $("html, body").animate({ scrollTop: 0 }, 100);
                    setTimeout(function() {
                                                sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                              }, 200);

                    $('#loading').fadeOut(500);
                   
                   }); 
              
              
            $( this ).dialog( "close" );
        },        
        Cancel: function() {
            $( this ).dialog( "close" );
        }
    }
});

$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Tạm ứng",
    hide: 'fold',
    show: 'blind'
});
</script>