<html dir="ltr">

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <style type="text/css">

        p{margin: 0}

    </style>

</head>

<body spellcheck="false">

    <h1 style="margin:0in;margin-bottom:.0001pt;tab-stops:center 262.25pt;text-align:center">

    <span style="font-size:12.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:

&quot;Times New Roman&quot;">CỘNG HO&Agrave; X&Atilde; HỘI CHỦ NGHĨA VIỆT NAM</span><o:p></o:p></h1>

<p align="center" class="MsoNormal" style="text-align:center">

    <b><span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><i>Độc lập - Tự do - Hạnh ph&uacute;c</i></span></b><i><o:p></o:p></i></p>

<p align="center" class="MsoNormal" style="text-align:center">

    <b><sup><span style="font-size:13.0pt;mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:

&quot;Times New Roman&quot;">__________________</span></sup></b> <o:p></o:p></p>

<h2 align="center" style="margin-top:24.0pt;margin-right:0in;margin-bottom:0in;

margin-left:0in;margin-bottom:.0001pt;text-align:center">

    <span style="font-size:16.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-fareast-font-family:

&quot;Times New Roman&quot;">HỢP ĐỒNG NGUY&Ecirc;N TẮC </span><o:p></o:p></h2>

<p align="center" class="MsoNormal" style="margin-bottom:12.0pt;text-align:center">

    <b><span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:black">Hợp đồng số</span></b><b><span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">: <span ><?php echo $contract_number ?></span><i>&nbsp;</i></span></b><o:p></o:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:77.95pt;margin-bottom:

3.0pt;margin-left:35.45pt;text-align:justify;text-indent:7.1pt">

    <b><u><span lang="ES" style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;

mso-ansi-language:ES;mso-bidi-font-style:italic">Căn cứ</span></u></b><span lang="ES" style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;

mso-ansi-language:ES;mso-bidi-font-style:italic">:&nbsp; <o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0pt;margin-bottom:

3.0pt;margin-left:35.45pt;text-align:justify;text-indent:7.1pt">

    <i><span lang="ES" style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;

mso-ansi-language:ES">- Bộ luật d&acirc;n sự số: 33/2005/QH11 được Quốc hội nước Cộng ho&agrave; x&atilde; hội chủ nghĩa Việt Nam kho&aacute; XI, kỳ họp thứ 7 th&ocirc;ng qua ng&agrave;y 14/6/2005;</span></i><span style="font-size:13.0pt;mso-bidi-font-family:&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoBodyTextIndent" style="margin-top:3.0pt;margin-right:0pt;

margin-bottom:3.0pt;margin-left:35.45pt;text-indent:7.1pt">

    <i><span lang="ES" style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-ansi-language:

ES">- Luật thương mại số: 36/2005/QH11 được Quốc hội nước Cộng ho&agrave; x&atilde; hội chủ nghĩa Việt Nam kho&aacute; XI, kỳ họp thứ 7 th&ocirc;ng qua ng&agrave;y 14/6/2005;</span></i><span style="font-size:13.0pt;mso-bidi-font-family:&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoBodyTextIndent" style="margin-top:3.0pt;margin-right:77.95pt;

margin-bottom:12.0pt;margin-left:35.45pt;text-indent:7.1pt">

    <i><span lang="ES" style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-ansi-language:

ES">- Nhu cầu v&agrave; khả năng của hai B&ecirc;n.</span></i><span style="font-size:13.0pt;

mso-bidi-font-family:&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoBodyTextIndent" style="margin-top:3.0pt;margin-right:0pt;

margin-bottom:3.0pt;margin-left:14.2pt;text-indent:7.1pt">

    <span lang="ES" style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;mso-ansi-language:

ES;mso-bidi-font-style:italic">Hôm nay, ngày <span ><?php echo $contract_date[0] ?></span> tháng <span ><?php echo $contract_date[1] ?></span> năm <span ><?php echo $contract_date[2] ?></span>, tại trụ sở </span><span lang="DE" style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;

mso-ansi-language:DE"><?php echo $infos->info_company ?> ch&uacute;ng t&ocirc;i gồm:</span><span style="font-size:13.0pt;mso-bidi-font-family:&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;

margin-left:7.1pt;text-align:justify;tab-stops:dotted 462.0pt">

    <b><span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">B&Ecirc;N A (B&ecirc;n b&aacute;n): <?php echo mb_strtoupper($infos->info_company,"UTF-8") ?></b><span style="font-size:13.0pt;mso-bidi-font-family:

&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;tab-stops:1.0in">

    <span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">Địa chỉ:&nbsp; <?php echo $infos->info_address ?>.</span><span style="font-size:13.0pt;mso-bidi-font-family:&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;tab-stops:1.0in">

    <span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">Điện thoại&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : &nbsp;<?php echo $infos->info_phone ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Fax : </span><span style="font-size:13.0pt;mso-bidi-font-family:

&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;tab-stops:1.0in">

    <span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">M&atilde; số thuế&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp;&nbsp; <?php echo $infos->info_mst ?>.</span><span style="font-size:13.0pt;mso-bidi-font-family:&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;tab-stops:1.0in">

    <span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">T&agrave;i khoản&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp; </span><span style="font-size:13.0pt;

mso-bidi-font-family:&quot;Times New Roman&quot;;letter-spacing:-.3pt"> - </span><span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">&nbsp; </span><span style="font-size:13.0pt;mso-bidi-font-family:

&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;tab-stops:1.0in">

    <span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">Đại diện ông/bà&nbsp;&nbsp; :&nbsp;&nbsp; <?php echo $infos->info_director ?>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; Chức vụ: Gi&aacute;m Đốc</span><span style="font-size:13.0pt;mso-bidi-font-family:

&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;

margin-left:7.1pt;text-align:justify;tab-stops:dotted 462.0pt">

    <b><span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">B&Ecirc;N B (B&ecirc;n mua): <?php echo mb_strtoupper($company, "UTF-8") ?></span></b><span style="font-size:13.0pt;

mso-bidi-font-family:&quot;Times New Roman&quot;"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;tab-stops:1.0in">

    <span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">Địa chỉ&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp; <?php echo $address ?><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;tab-stops:1.0in">

    <span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">Điện thoại&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp; <?php echo $phone ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fax:&nbsp;<?php echo $fax ?><span style="color:red">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; </span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-size:13.0pt;mso-bidi-font-family:&quot;Times New Roman&quot;;layout-grid-mode:

line"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;tab-stops:78.0pt 92.15pt">

    <span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">M&atilde; số thuế&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp;&nbsp; <?php echo $mst ?></span><span style="font-size:13.0pt;mso-bidi-font-family:&quot;Times New Roman&quot;;layout-grid-mode:

line"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;tab-stops:78.0pt 92.15pt">

    <span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">T&agrave;i khoản&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp;&nbsp;&nbsp; <?php if($bank_number!=""){  ?> <?php echo $bank_number ?> - <?php echo $bank ?> <?php } ?></span><span style="font-size:13.0pt;mso-bidi-font-family:&quot;Times New Roman&quot;;layout-grid-mode:

line"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span style="font-size:13.0pt;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;layout-grid-mode:

line">Đại diện &ocirc;ng&nbsp;&nbsp;&nbsp; :&nbsp;&nbsp; &nbsp;<?php echo $name ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chức vụ:&nbsp;&nbsp; Gi&aacute;m đốc</span><span style="font-size:13.0pt;mso-bidi-font-family:&quot;Times New Roman&quot;;layout-grid-mode:

line"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:6.0pt;margin-right:0in;margin-bottom:3.0pt;

margin-left:7.1pt;text-align:justify">

    <i><span style="font-size:13.0pt;

layout-grid-mode:line">Hai b&ecirc;n thống nhất thỏa thuận nội dung hợp đồng như sau:</span></i><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:12.0pt;margin-right:0in;margin-bottom:

3.0pt;margin-left:7.1pt;text-align:justify;line-height:130%">

    <b><u><span lang="DE" style="font-size:13.0pt;line-height:130%;mso-ansi-language:DE;

layout-grid-mode:line">ĐIỀU 1:</span></u></b><b><span lang="DE" style="font-size:

13.0pt;line-height:130%;mso-ansi-language:DE;layout-grid-mode:line"> NỘI DUNG HỢP ĐỒNG</span></b><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span style="font-size:13.0pt;layout-grid-mode:line">B&ecirc;n mua đồng &yacute; mua v&agrave; b&ecirc;n b&aacute;n đồng &yacute; b&aacute;n lốp theo c&aacute;c điều khoản như sau:</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Số lượng v&agrave; chủng loại: Theo như th&ocirc;ng b&aacute;o hoặc đơn đặt h&agrave;ng từ b&ecirc;n B.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Đơn gi&aacute;: Được &aacute;p dụng trong bảng k&ecirc; x&aacute;c nhận của hai b&ecirc;n theo từng đợt thỏa thuận.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Thời gian giao h&agrave;ng: Theo như th&ocirc;ng b&aacute;o của b&ecirc;n B.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Địa điểm giao h&agrave;ng: Theo như th&ocirc;ng b&aacute;o của b&ecirc;n B.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Phương thức giao nhận: Khi nhận h&agrave;ng, B&ecirc;n mua c&oacute; tr&aacute;ch nhiệm cử c&aacute;n bộ kiểm nhận phẩm chất, quy c&aacute;ch h&agrave;ng h&oacute;a. Nếu ph&aacute;t hiện h&agrave;ng thiếu hoặc kh&ocirc;ng đ&uacute;ng ti&ecirc;u chuẩn chất lượng th&igrave; lập bi&ecirc;n bản tại chỗ, y&ecirc;u cầu b&ecirc;n b&aacute;n c&oacute; tr&aacute;ch nhiệm đổi h&agrave;ng mới đ&uacute;ng ti&ecirc;u chuẩn cam kết.<o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:PT-BR;layout-grid-mode:line">&nbsp;</span><b><u><span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">ĐIỀU 2:</span></u></b><b><span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:

line"> QUY C&Aacute;CH CHẤT LƯỢNG SẢN PHẨM</span></b><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Đ&uacute;ng y&ecirc;u cầu kỹ thuật theo ti&ecirc;u chuẩn của nh&agrave; sản xuất; đ&uacute;ng k&iacute;ch thước, chủng loại như theo quy định tại điều 1.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; H&agrave;ng mới 100%, chưa qua sử dụng.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Trong trường hợp b&ecirc;n b&aacute;n giao kh&ocirc;ng đ&uacute;ng chủng loại, chất lượng như đ&atilde; cam kết theo hợp đồng, b&ecirc;n mua c&oacute; quyền trả lại v&agrave; B&ecirc;n bán c&oacute; tr&aacute;ch nhiệm đổi h&agrave;ng h&oacute;a thay thế theo đ&uacute;ng như cam kết.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:120%">

    <b><u><span lang="ES-UY" style="font-size:13.0pt;line-height:120%;mso-ansi-language:ES-UY;

layout-grid-mode:line">ĐIỀU 3:</span></u></b><b><span lang="ES-UY" style="font-size:13.0pt;line-height:120%;mso-ansi-language:ES-UY;layout-grid-mode:

line"> PHƯƠNG THỨC THANH TO&Aacute;N HỢP ĐỒNG</span></b><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:130%">

    <b><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;

layout-grid-mode:line">3.1. Thanh to&aacute;n:</span></b><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:130%">

    <span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;

layout-grid-mode:line">- Trường hợp mua lẻ: Khách hàng thanh toán 100% ngay khi xe hàng tới kho.</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:130%">

    <span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;

layout-grid-mode:line">- Đặt hàng nguyên cont: Bên mua đặt cọc 20% số tiền theo đơn hàng và thanh toán toàn bộ số tiền còn lại ngay khi xe hàng tới kho và nhận đủ hoá đơn chứng từ do bên A cung cấp.</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:130%">

    <b><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;

layout-grid-mode:line">3.2. H&igrave;nh thức thanh to&aacute;n:</span></b><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;layout-grid-mode:

line"> Bằng chuyển khoản.</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:130%">

    <b><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;

layout-grid-mode:line">3.3. Đồng tiền thanh to&aacute;n:</span></b><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;layout-grid-mode:

line"> Việt Nam đồng.</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:130%">

    <b><u><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;

layout-grid-mode:line">ĐIỀU 4:</span></u></b><b><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;layout-grid-mode:

line"> QUYỀN V&Agrave; NGHĨA VỤ CỦA C&Aacute;C B&Ecirc;N</span></b><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:130%">

    <b><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;

layout-grid-mode:line">4.1. Quyền v&agrave; nghĩa vụ của B&ecirc;n mua:</span></b><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Tạo mọi điều kiện để B&ecirc;n b&aacute;n giao h&agrave;ng đ&uacute;ng thời hạn của hợp đồng.</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Cử c&aacute;n bộ chuy&ecirc;n tr&aacute;ch kiểm tra quy c&aacute;ch, chất lượng v&agrave; k&yacute; x&aacute;c nhận bi&ecirc;n bản b&agrave;n giao h&agrave;ng h&oacute;a với B&ecirc;n B&aacute;n.</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Bố tr&iacute; nh&acirc;n lực, thiết bị bốc dỡ h&agrave;ng h&oacute;a nhanh ch&oacute;ng để giải ph&oacute;ng phương tiện vận chuyển cho B&ecirc;n B&aacute;n.</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Tạm ứng, thanh to&aacute;n cho B&ecirc;n B&aacute;n theo đ&uacute;ng cam kết của hợp đồng.</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Khách hàng đặt nguyên cont, bên A có trách nhiệm giao hàng sau 24 đến 32 ngày kể từ ngày đặt cọc (Trường hợp phát sinh sự cố ngoài ý muốn khiến việc giao hàng chậm trễ phải thông báo ngay với bên mua hàng).</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; C&aacute;c quyền v&agrave; nghĩa vụ kh&aacute;c theo quy định của ph&aacute;p luật.</span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:130%">

    <b><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;

layout-grid-mode:line">4.2. Quyền v&agrave; nghĩa vụ của B&ecirc;n Bán:</span></b><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Giao h&agrave;ng cho B&ecirc;n Mua theo đ&uacute;ng quy c&aacute;ch, chất lượng, đ&uacute;ng thời gian v&agrave; địa điểm như trong hợp đồng.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Bảo đảm chất lượng v&agrave; bảo h&agrave;nh h&agrave;ng h&oacute;a cung cấp theo đ&uacute;ng ti&ecirc;u chuẩn của nh&agrave; sản xuất.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Xuất h&oacute;a đơn chứng từ hợp lệ của l&ocirc; h&agrave;ng cho B&ecirc;n Mua. <o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; C&aacute;c quyền v&agrave; nghĩa vụ kh&aacute;c theo quy định của Ph&aacute;p luật.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:130%">

    <b><u><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;

layout-grid-mode:line">ĐIỀU 5</span></u></b><b><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;layout-grid-mode:

line">: PHẠT VI PHẠM HỢP ĐỒNG</span></b><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;mso-margin-bottom-alt:auto;

text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;color:black;

mso-ansi-language:ES-UY;layout-grid-mode:line">&nbsp;&nbsp; B&ecirc;n n&agrave;o vi phạm c&aacute;c điều khoản tr&ecirc;n đ&acirc;y sẽ phải chịu tr&aacute;ch nhiệm vật chất theo quy định của c&aacute;c văn bản ph&aacute;p luật c&oacute; hiệu lực hiện. </span><span lang="ES-UY" style="font-size:13.0pt;

mso-ansi-language:ES-UY;layout-grid-mode:line">h&agrave;nh về phạt vi phạm <span style="color:black;mso-themecolor:text1">chịu 0.03% tr&ecirc;n ng&agrave;y </span>do thanh to&aacute;n chậm. Chất lượng, số lượng, thời gian, địa điểm &nbsp;v.v&hellip; mức phạt cụ thể do hai b&ecirc;n thỏa thuận dựa tr&ecirc;n khung phạt Nh&agrave; nước đ&atilde; quy định trong c&aacute;c văn <span style="color:black">bản ph&aacute;p luật về hợp đồng kinh tế.</span></span><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:6.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify;line-height:130%">

    <b><u><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;

layout-grid-mode:line">ĐIỀU 6:</span></u></b><b><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;layout-grid-mode:

line"> ĐIỀU KHOẢN CHUNG</span></b><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Hai b&ecirc;n cam kết thực hiện nghi&ecirc;m t&uacute;c c&aacute;c điều khoản của Hợp đồng. Nếu c&oacute; những kh&oacute; khăn vướng mắc hai b&ecirc;n phải kịp thời th&ocirc;ng b&aacute;o v&agrave; b&agrave;n bạc thống nhất (lập bi&ecirc;n bản ghi to&agrave;n bộ nội dung). B&ecirc;n n&agrave;o vi phạm m&agrave; kh&ocirc;ng c&oacute; sự b&agrave;n bạc thống nhất sẽ phải chịu tr&aacute;ch nhiệm theo quy định của ph&aacute;p luật.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Trong trường hợp phải lập th&ecirc;m c&aacute;c phụ lục hợp đồng th&igrave; c&aacute;c phụ lục n&agrave;y được coi l&agrave; một phần của hợp đồng.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; C&aacute;c điều khoản kh&ocirc;ng ghi trong hợp đồng n&agrave;y sẽ được c&aacute;c b&ecirc;n thực hiện theo quy định hiện h&agrave;nh v&agrave; c&aacute;c văn bản ph&aacute;p luật về hợp đồng.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">-&nbsp; Trong quá trình thực hiện Hợp đồng này nếu xảy ra bất kỳ sự bất đồng nào, Bên nảy sinh bất đồng sẽ thông báo cho bên kia bằng văn bản. Hai bên sẽ thương lượng để giải quyết các bất đồng đó. Trường hợp các bên không tự thương lượng được thì sự việc sẽ được đưa ra giải quyết theo qui định của pháp luật.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:6.0pt;margin-right:0in;margin-bottom:6.0pt;

margin-left:7.1pt;text-align:justify;line-height:130%">

    <b><u><span lang="ES-UY" style="font-size:13.0pt;line-height:130%;mso-ansi-language:ES-UY;layout-grid-mode:

line">ĐIỀU 7:</span></u></b><b><span lang="ES-UY" style="font-size:13.0pt;

line-height:130%;mso-ansi-language:ES-UY;layout-grid-mode:line"> HIỆU LỰC CỦA HỢP ĐỒNG</span></b><o:p></o:p></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">- Hợp đồng n&agrave;y c&oacute; hiệu lực kể từ ng&agrave;y k&yacute;.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">- Hợp đồng qua fax/ scan gửi qua mail có giá trị như bản chính.<o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p class="MsoNormal" style="margin-top:3.0pt;margin-right:0in;margin-bottom:0in;

margin-left:7.1pt;margin-bottom:.0001pt;text-align:justify">

    <span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:line">- Hợp đồng n&agrave;y được lập th&agrave;nh 02 (Hai) bản c&oacute; gi&aacute; trị ph&aacute;p l&yacute; như nhau, mỗi B&ecirc;n giữ 01 (một) bản l&agrave;m cơ sở thực hiện./. <o:p></o:p></span></p>

<p>

    <u1:p></u1:p></p>

<p>

    <span style="font-size:13.0pt">&nbsp;<o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top:.5in;mso-margin-bottom-alt:auto;

text-align:justify;line-height:20.0pt;mso-line-height-rule:exactly">

    <b><span lang="ES-UY" style="font-size:13.0pt;mso-ansi-language:ES-UY;layout-grid-mode:

line">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ĐẠI DIỆN B&Ecirc;N B&Aacute;N&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ĐẠI DIỆN B&Ecirc;N MUA</span></b><u1:p></u1:p><o:p></o:p></p>





</body>

</html>

<?php

header("Content-type: application/x-ms-download");



header("Content-Disposition: attachment; filename=HOP DONG.doc");



header('Cache-Control: public');

?>