<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="<?php echo BASE_URL ?>/public/js/editor/contents.css" type="text/css" rel="stylesheet" _cktemp="true">
    <style type="text/css">
    @media print {
      @page { margin: 0; }
      body { margin: 0.6cm 0.6cm 0cm 0.6cm; height: 100%; -webkit-print-color-adjust: exact;}
      .footer{
       position:fixed;
       bottom:15px;
       right: 15px;
        color: #8e8a8a;
       }
    }
    @page { margin: 0.2cm 0.2cm 0cm 0.2cm; }
    #wrap{
            background: url('/public/img/watermarkA4.png') no-repeat;
        }
    </style>
    <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
       window.print();
    });
    </script>
</head>
<body class="skin-blue sidebar-mini  pace-done">
    <div id="wrap">
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse:
         collapse;width:100%" width="700">
            <colgroup>
                <col style="width: 26pt; text-align: center;" width="35">
                <col span="2" style="width: 95pt; text-align: center;" width="126">
                <col style="width: 26pt; text-align: center;" width="35">
                <col span="3" style="width: 95pt; text-align: center;" width="126">
            </colgroup>
            <tbody>
                <tr height="22" style="height:16.5pt">
                    <td class="xl63" colspan="3" height="22" style="height: 16.5pt; width: 216pt; text-align: center;" width="287">
                        <span style="font-size:14px;"><strong><?php echo mb_strtoupper($infos->info_company, "UTF-8") ?></strong></span></td>
                    <td class="xl63" style="width:26pt" width="35">
                        <span style="font-size:14px;"><strong><br>
                        </strong></span></td>
                    <td class="xl63" colspan="3" style="width: 285pt; text-align: center;" width="378">
                        <span style="font-size:14px;"><strong>CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</strong></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl64" colspan="3" height="22" style="height: 16.5pt; text-align: center;">
                        <span style="font-size:14px;">Số: <?php echo $order_number ?>/BB</span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl73" colspan="3" style="text-align: center;">
                        <span style="font-size:14px;"><u>Độc lập - Tự do - Hạnh phúc</u></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl64" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="30" style="height:22.5pt">
                    <td class="xl74" colspan="7" height="30" style="height: 22.5pt; text-align: center;">
                        <span style="font-size:18px;"><strong>BIÊN BẢN</strong></span></td>
                </tr>
                <tr height="30" style="height:22.5pt">
                    <td class="xl74" colspan="7" height="30" style="height: 22.5pt; text-align: center;">
                        <span style="font-size:18px;"><strong>BÀN GIAO TÀI SẢN và XÁC NHẬN CÔNG NỢ</strong></span></td>
                </tr>
                <tr height="22" style="mso-height-source:userset;height:20.1pt">
                    <td class="xl65" height="22" style="height:20.1pt">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl77" colspan="7" height="22" style="height:16.5pt;width:527pt" width="700">
                        <span style="font-size:14px;">Căn cứ hợp đồng mua bán số <?php echo $orders->contract_number!=""?$orders->contract_number:"............" ?> ngày <?php echo $orders->contract_date>0?$lib->hien_thi_ngay_thang($orders->contract_date):".../.../...." ?> giữa hai Công ty.</span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl77" colspan="7" height="22" style="height:16.5pt;width:527pt" width="700">
                        <span style="font-size:14px;">Hôm nay, ngày <?php echo $ngay ?> tháng <?php echo $thang ?> năm <?php echo $nam ?> tại kho lốp công ty đã tiến hành bàn giao tài sản như sau:</span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl75" colspan="2" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><u><strong>A/ Bên bán:</strong></u></span></td>
                    <td class="xl76" colspan="5">
                        <span style="font-size:14px;"><strong><?php echo mb_strtoupper($infos->info_company, "UTF-8") ?></strong></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl65" colspan="3" height="22" style="height:16.5pt;mso-ignore:colspan">
                        <span style="font-size:14px;">- Mã số thuế: <?php echo $infos->info_mst ?></span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65" colspan="2">
                        <span style="font-size:14px;">Hotline: <?php echo $infos->info_phone ?></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl65" colspan="6" height="22" style="height:16.5pt;mso-ignore:colspan">
                        <span style="font-size:14px;">- Địa chỉ: <?php echo $infos->info_address ?></span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl65" colspan="3" height="22" style="height:16.5pt;mso-ignore:colspan">
                        <span style="font-size:14px;">- Ông/bà: <?php echo $staffs->staff_name ?></span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;">Chức vụ:</span></td>
                    <td class="xl65" colspan="2">
                        <span style="font-size:14px;">SĐT: <?php echo $staffs->staff_phone ?></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl75" colspan="2" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><u><strong>B/ Bên mua:</strong></u></span></td>
                    <td class="xl76" colspan="5">
                        <span style="font-size:14px;"><strong><?php echo mb_strtoupper($customers->company_name, "UTF-8") ?></strong></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl65" colspan="3" height="22" style="height:16.5pt;mso-ignore:colspan">
                        <span style="font-size:14px;">- Mã số thuế: <?php echo $customers->mst ?></span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl77" colspan="7" height="22" style="height:16.5pt;width:527pt" width="700">
                        <span style="font-size:14px;">- Địa chỉ: <?php echo $customers->customer_address ?></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl65" colspan="2" height="22" style="height:16.5pt;mso-ignore:colspan">
                        <span style="font-size:14px;">- Ông/bà: <?php echo $customers->customer_contact ?></span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;">Chức vụ:</span></td>
                    <td class="xl65">
                        <span style="font-size:14px;">SĐT: <?php echo $customers->customer_phone ?></span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl75" colspan="7" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><u><strong>NỘI DUNG BÀN GIAO:</strong></u></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl65" colspan="7" height="22" style="height:16.5pt">
                        <span style="font-size:14px;">Bên A đã tiến hành bàn giao tài sản cho bên B theo bảng thống kê tài sản sau:</span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl63" colspan="7" height="22" style="height: 16.5pt; text-align: center;">
                        <span style="font-size:14px;"><strong>Bảng thống kê tài sản bàn giao</strong></span></td>
                </tr>
                <tr height="34" style="background:#c6f2c8;mso-height-source:userset;height:26.1pt">
                    <td class="xl66" height="34" style="border: 1px solid;height: 26.1pt; text-align: center;">
                        <span style="font-size:14px;"><strong>STT</strong></span></td>
                    <td class="xl66" style="border: 1px solid; none; text-align: center;">
                        <span style="font-size:14px;"><strong>TÊN HÀNG</strong></span></td>
                    <td class="xl66" style="border: 1px solid; none; text-align: center;">
                        <span style="font-size:14px;"><strong>LOẠI HÀNG</strong></span></td>
                    <td class="xl66" style="border: 1px solid; none; text-align: center;">
                        <span style="font-size:14px;"><strong>SL</strong></span></td>
                    <td class="xl66" style="border: 1px solid; text-align: center;">
                        <span style="font-size:14px;"><strong>ĐƠN GIÁ</strong></span></td>
                    <td class="xl66" style="border: 1px solid; text-align: center;">
                        <span style="font-size:14px;"><strong>THÀNH TIỀN</strong></span></td>
                    <td class="xl66" style="border: 1px solid; text-align: center;">
                        <span style="font-size:14px;"><strong>GHI CHÚ</strong></span></td>
                </tr>
                <?php $i=1; $tongnum = 0; $tong = 0;
                 foreach ($order_types as $row) :
                 $tongnum += $row->tire_number;
                 $tong += $row->tire_number*($orders->check_price_vat==1?$row->tire_price_vat:$row->tire_price);
                ?>
                <tr height="22" style="height:16.5pt">
                    <td class="xl67" height="22" style="border: 1px solid;height: 16.5pt; border-top: none; text-align: center;">
                        <span style="font-size:14px;"><?php echo $i++ ?></span></td>
                    <td class="xl67" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><?php echo $row->tire_brand_name ?></span></td>
                    <td class="xl67" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><?php echo $row->tire_size_number.' '.$row->tire_pattern_name ?></span></td>
                    <td class="xl67" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><?php echo $row->tire_number ?></span></td>
                    <td class="xl69" style="border: 1px solid; border-left: none; text-align: right; padding-right: 5px">
                        <span style="font-size:14px;"><?php echo $lib->formatMoney($orders->check_price_vat==1?$row->tire_price_vat:$row->tire_price) ?></span></td>
                    <td class="xl69" style="border: 1px solid; border-left: none; text-align: right; padding-right: 5px">
                        <span style="font-size:14px;"><?php echo $lib->formatMoney($row->tire_number*($orders->check_price_vat==1?$row->tire_price_vat:$row->tire_price)) ?></span></td>
                    <?php if($i==2){ ?>
                    <td class="xl67" rowspan="<?php echo (count($order_types)+1) ?>" style="border: 1px solid; text-align: center;">
                        <span style="font-size:14px;"><?php echo ($orders->check_price_vat==1?'HD('.$orders->vat_percent.')':"") ?></span></td>
                    <?php } ?>
                </tr>
                <?php endforeach; ?>
                <tr height="22" style="height:16.5pt">
                    <td class="xl68" colspan="3" height="22" style="border: 1px solid;height: 16.5pt; text-align: center;">
                        <span style="font-size:14px;"><strong>Cộng</strong></span></td>
                    <td class="xl68" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong><?php echo $tongnum ?></strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong><br>
                        </strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: right; padding-right: 5px">
                        <span style="font-size:14px;"><strong><?php echo $lib->formatMoney($tong) ?></strong></span></td>
                </tr>
                <?php if ($orders->check_price_vat!=1 && $orders->vat>0) { 
                    $tong += $orders->vat;
                ?>
                <tr height="22" style="height:16.5pt">
                    <td class="xl68" colspan="3" height="22" style="border: 1px solid;height: 16.5pt; text-align: center;">
                        <span style="font-size:14px;"><strong>VAT</strong></span></td>
                    <td class="xl68" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong></strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong><br>
                        </strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: right; padding-right: 5px">
                        <span style="font-size:14px;"><strong><?php echo $lib->formatMoney($orders->vat) ?></strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong><br>
                        </strong></span></td>
                </tr>
                <?php } ?>
                <?php if ($orders->discount+$orders->reduce != 0) {
                    $tong -= ($orders->discount+$orders->reduce);
                ?>
                <tr height="22" style="height:16.5pt">
                    <td class="xl68" colspan="3" height="22" style="border: 1px solid;height: 16.5pt; text-align: center;">
                        <span style="font-size:14px;"><strong>Giảm trừ</strong></span></td>
                    <td class="xl68" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong></strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong><br>
                        </strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: right; padding-right: 5px">
                        <span style="font-size:14px;"><strong><?php echo $lib->formatMoney($orders->discount+$orders->reduce) ?></strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong><br>
                        </strong></span></td>
                </tr>
                <?php } ?>
                <?php if (($orders->check_price_vat!=1 && $orders->vat>0) || ($orders->discount+$orders->reduce != 0)) { ?>
                <tr height="22" style="height:16.5pt">
                    <td class="xl68" colspan="3" height="22" style="border: 1px solid;height: 16.5pt; text-align: center;">
                        <span style="font-size:14px;"><strong>Tổng cộng</strong></span></td>
                    <td class="xl68" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong></strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong><br>
                        </strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: right; padding-right: 5px">
                        <span style="font-size:14px;"><strong><?php echo $lib->formatMoney($tong) ?></strong></span></td>
                    <td class="xl70" style="border: 1px solid; border-left: none; text-align: center;">
                        <span style="font-size:14px;"><strong><br>
                        </strong></span></td>
                </tr>
                <?php } ?>
                <tr height="22" style="mso-height-source:userset;height:16.5pt">
                    <td class="xl63" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl63">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl63">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl63">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl71">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl71">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl63">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="23" style="height:16.5pt">
                    <td class="xl65" colspan="2" height="23" style="height:16.5pt;mso-ignore:colspan">
                        <span style="font-size:14px;">Số tiền bằng chữ:</span></td>
                    <td class="xl72" colspan="5">
                        <span style="font-size:14px;"><em><strong><?php echo $lib->convert_number_to_words($tong).' đồng.' ?></strong></em></span></td>
                </tr>
                <tr height="48" style="mso-height-source:userset;height:36.0pt">
                    <td class="xl77" colspan="7" height="48" style="height:36.0pt;width:527pt" width="700">
                        <span style="font-size:14px;">Bên B sẽ thanh toán toàn bộ số tiền trên cho bên A trước khi nhận hàng, bằng tiền mặt (có xác nhận giữa 2 bên) hoặc chuyển khoản theo thông tin sau:</span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl65" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65" colspan="6">
                        <span style="font-size:14px;">TK1: CONG TY TNHH THUONG MAI TONG HOP VINA&nbsp; -&nbsp; 19132409999799&nbsp; Techcombank Quy Nhơn.</span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl65" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65" colspan="6">
                        <span style="font-size:14px;">TK2: CONG TY TNHH THUONG MAI TONG HOP VINA&nbsp; -&nbsp; 58010002759999&nbsp; BIDV CN Bình Định.</span>
                    </td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl78" colspan="7" height="22" style="height:16.5pt;width:527pt" width="700">
                        <span style="font-size:14px;">Hạn thanh toán: <?php echo $lib->hien_thi_ngay_thang($orders->due_date) ?></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl78" colspan="7" height="22" style="height:16.5pt;width:527pt" width="700">
                        <span style="font-size:14px;"><strong>(Khách hàng thanh toán chuyển khoản vui lòng ghi rõ mã số đơn hàng khi thanh toán).</strong></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl65" colspan="6" height="22" style="height:16.5pt;mso-ignore:colspan">
                        <span style="font-size:14px;">Biên bản này lập thành 3 bản có giá trị pháp lý như nhau. Mỗi bên giữ một bản.</span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl65" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl65">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl63" colspan="2" height="22" style="height: 16.5pt; text-align: center;">
                        <span style="font-size:14px;"><strong>BÊN GIAO HÀNG</strong></span></td>
                    <td class="xl63" colspan="3" style="text-align: center;">
                        <span style="font-size:14px;"><strong>BÊN NHẬN HÀNG</strong></span></td>
                    <td class="xl63" colspan="2" style="text-align: center;">
                        <span style="font-size:14px;"><strong>BÊN VẬN CHUYỂN</strong></span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl64" colspan="2" height="22" style="height: 16.5pt; text-align: center;">
                        <span style="font-size:14px;">(Ký, họ tên)</span></td>
                    <td class="xl64" colspan="3" style="text-align: center;">
                        <span style="font-size:14px;">(Ký, đóng dấu &amp; ghi rõ họ tên)</span></td>
                    <td class="xl64" colspan="2" style="text-align: center;">
                        <span style="font-size:14px;">(Ký &amp; ghi rõ họ tên, BS xe, SĐT)</span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl64" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl64" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl64" height="22" style="height:16.5pt">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl64">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
                <tr height="22" style="height:16.5pt">
                    <td class="xl63" colspan="2" height="22" style="height: 16.5pt; text-align: center;">
                        <span style="font-size:14px;"><strong><?php echo $staffs->staff_name ?></strong></span></td>
                    <td class="xl63" colspan="3" height="22" style="height: 16.5pt;">
                        <span style="font-size:14px;">Người nhận:</span><br>
                        <span style="font-size:14px;">SĐT:</span><br>
                        <span style="font-size:14px;">CMND/GPLX:</span><br>
                        <span style="font-size:14px;">Ngày cấp: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nơi cấp:</span><br>
                    </td>
                    <td class="xl63">
                        <span style="font-size:14px;"><br>
                        </span></td>
                    <td class="xl63">
                        <span style="font-size:14px;"><br>
                        </span></td>
                </tr>
            </tbody>
        </table>
        <div class="footer"><i>Please visit our website to view the status of your order. <?php echo BASE_URL ?></i><img height="50" src="<?php echo BASE_URL.'/'.$img ?>" /></div>
    </div>
    </body>
</html>